.github/workflows/appimage.yml, .github/workflows/docker.yml, .github/workflows/license_finder.yml, .github/workflows/main.yml, .github/workflows/pullrequest.yml, .github/workflows/test.yml
Removing extra private-only stuff from RDK.
Note: Will fail tests in current state, due to test@main targets already reverted. Tested in previous push.
=> Remove private-only secret deps from workflows

.github/workflows/appimage.yml, .github/workflows/pullrequest.yml, .github/workflows/pullrequestcomment.yml, .github/workflows/test.yml
This is a workaround to allow code coverage (and appimages) to securely add comments to workflows now that RDK is public.
=> Add secure comments workflow

services/slam/builtin/orbslam_yaml.go
turns out I had two time.Now calls inside of `orbslam_yaml.go`, so I moved some stuff around to have time.Now only call once
=> [DATA-470] fix flaky SLAM timestamp test

services/datamanager/data/fake_robot_with_data_manager.json, services/datamanager/data/fake_robot_with_remote_and_data_manager.json, services/datamanager/data/robot_with_cam_capture.json
Gets rid of logging `"no model given; using default"` in tests
=> Add builtin model to datamanager test configs

.artifact/tree.json, services/slam/builtin/builtin.go, services/slam/builtin/builtin_test.go, services/slam/builtin/orbslam_int_test.go
This PR adds integration tests for orbslam running in online and offline mode, as well as using a saved map. Once this is merged, it will start running on changes to the slam repo. Also, now that app images are being built for orbslam, I'll make the github actions for rdk grab them so that this integration test can run.
=> [DATA-363] Add integration tests for orbslam

components/movementsensor/imuwit/imu.go
If baud_rate wasn't provided it was treated as 0
Logging read strings resulted a log flood (not surprising) and lots of failures to push to cloud due invalid characters.
=> Treat baud_rate as optional in imu-wit and logging

services/slam/builtin/builtin_test.go
It seems like the failure was caused by the switch from `good_camera` to `good_color_camera` in `TestSLAMProcessSuccess`. Removing the unnecessary png decode resolved a timeout reading from the camera in `TestORBSLAMDataProcess`, so I'm giving that a try here.
=> [DATA-496] Remove png decode from mock slam camera

web/server/entrypoint.go, web/server/net_logger.go, web/server/net_logger_test.go
The netLogger was ignoring the level of the logger the rdk configures in the entrypoint file.
Now the netLogger uses the AtomicLevel provided by the log config to determine if a log entry should be passed to the app.
With -debug now only info+ logs will be logged to console and app.
=> RSDK-712 - Fix log level reported to app.

components/sensor/bme280/bme280.go, components/sensor/register/register.go, spatialmath/rotationMatrix.go
Not sure who else should be on this PR?
=> Add support for BME280 temp/humidity/pressure sensor

services/slam/builtin/builtin.go
Implements the RDK side of this ticket: https://viam.atlassian.net/browse/DATA-521
Tested with:
* realsense: mono & rgbd
* webcam: mono
=> SLAM: Process images when they're of YCbCr type

components/camera/videosource/join_pointcloud.go, config/config_test.go, config/frame_test.go, motionplan/collision_test.go, motionplan/constraint_test.go, motionplan/dubinsRRT_test.go, motionplan/motionPlanner_test.go, motionplan/solvableFrameSystem_test.go, pointcloud/point.go, pointcloud/pointcloud_utils.go, pointcloud/pointcloud_utils_test.go, referenceframe/frame_test.go, referenceframe/model_test.go, referenceframe/static_frame_system_test.go, referenceframe/transformable_test.go, services/vision/builtin/helpers_test.go, services/vision/helpers_test.go, spatialmath/box.go, spatialmath/box_test.go, spatialmath/geometry.go, spatialmath/geometry_test.go, spatialmath/orientation.go, spatialmath/point.go, spatialmath/point_test.go, spatialmath/pose.go, spatialmath/sphere.go, spatialmath/sphere_test.go, vision/object_test.go, vision/segmentation/segments_test.go
This commit is the first part of [DATA-498](https://viam.atlassian.net/browse/DATA-498). The next part will focus on the client and server interface. This seemed like a good stopping point since it's pretty large and self-contained.
=> DATA 498 add labels to geometries in RDK

robot/robot.go, robot/robot_test.go, testutils/resource_utils.go
need to do a check on ShortName() instead of Name.
running the example on the ticket still fails with
```
2022-10-07T21:17:07.768-0400    FATAL   client  sample/client.go:36     cannot move: rpc error: code = Unknown desc = arm client does not support inputs directly
```
but thats a different issue
=> RSDK-726 Fix get all resources by name

services/datamanager/builtin/builtin.go
Previously, if:
1. Capture was toggled off when synchronization was toggled on
2. No components had capture configurations
we would return early before initializing the background syncer.
=> Initialize synchronization even if capture is disabled

components/camera/collectors.go
This was updated as part of https://github.com/viamrobotics/rdk/pull/1294/files, but ReadImage seems to do something different from stream.Next(). Reverted back to the call originally added in https://github.com/viamrobotics/rdk/pull/1223.
If this fixes capture, will rename the collector key to "Next" as a follow-up for correctness - but this will all work E2E with "ReadImage" since it's just a key string into this collector.
=> Update ReadImage back to stream.Next

components/camera/transformpipeline/composed.go, components/camera/transformpipeline/composed_test.go, components/camera/transformpipeline/transform.go
The problem that was causing segmentation errors was projecting to an image that was (0,0) size, because the intrinsic parameters were not set. Rather than using the camera's intrinsic parameters, the transform should require its own intrinsic parameters to do the projection.
=> [Data-499] fix overlay transform

services/datamanager/builtin/builtin.go, services/datamanager/builtin/builtin_test.go
We don't need to acquire this lock for the duration of the function, only when accessing the shared variable svc.collectors, which we can copy. 
Also replaces the behavior when a data capture file can't be created to return an err instead of log an error. We can't capture or sync data if that doesn't work, so I think it should fail quickly/completely vs just logging.
=> [DATA] Don't acquire lock  for whole duration of syncDataCaptureFiles.

services/slam/builtin/builtin.go, services/slam/builtin/builtin_test.go
I saw another failure in a PR, and realized there was still this issue in the test.
=> Fix TestORBSLAMDataProcess timeout

components/motor/gpio/basic.go
I was working on something unrelated, and noticed that, when you want to turn off the power to a GPIO motor, if you encounter an error setting EnablePinLow, but no error when setting EnablePinHigh, the error gets suppressed. I've changed it so the errors are propagated no matter what order we do things in. 
I don't see an obvious way to write a test for this, but am willing to do so if someone gives me advice on how to simulate the errors in different places. 
I could have used `multierr.Append`, but went with `multierr.Combine` for consistency with the rest of the function.
=> Don't ignore errors when setting PWMs in GPIO motors

config/resource.go
The logs about services and models are very spammy and are better as debug logs rather than warning.
=> [RSDK-748] change spammy logs to be debug

services/slam/builtin/builtin.go, services/slam/builtin/builtin_test.go, services/slam/builtin/orbslam_yaml.go, services/slam/builtin/orbslam_yaml_test.go
Removing save map loc because it does not fit into the intended user experience of orbslam, and is not in the current tech spec. In addition adding the auto update flag for the orbslam binary call, so the most recent appimage is always used. Lastly changes the RGBflag to inform orbslam a BGR image is in use rather than a RGB, to match a change we made to the orbslam server. 
[DATA-558 remove SaveMapLoc](https://viam.atlassian.net/browse/DATA-558)
[DATA-553 add auto update flag](https://viam.atlassian.net/browse/DATA-553)
=> [DATA-558] remove SaveMapLoc from orbslam_yaml.go

utils/parallel_test.go
Not sure if there's a clean way of removing the timing element from this test. Hopefully this addresses or at least lowers the incidence rate of false positives.
=> RSDK-768: Improve flaky rdk/utils test

services/slam/builtin/builtin.go, services/slam/slamlibraries.go
Together with https://github.com/viamrobotics/slam/pull/77, this lets us run cartographer through rdk.
=> [DATA-567] Support running cartographer through rdk

components/camera/videosource/join_pointcloud.go, components/camera/videosource/join_pointcloud_test.go, pointcloud/merging.go, pointcloud/merging_test.go, pointcloud/pointcloud_utils.go, pointcloud/pointcloud_utils_test.go
The bug was an edge-case when reading the batches of points from a channel into the final point cloud would not read all the points in the channel. 
The loop would continue reading data into the final point cloud if `dataLastTime || atomic.LoadInt32(&activeReaders) > 0`
If there was no data in the channel, then the loop would wait 5 ms and then would set `dataLastTime = false`.
There was a situation where `dataListTime` was false, but `atomic.LoadInt32(&activeReaders)` had become 0 only within those 5 ms when `dataLastTime` was being set to false, meaning there was still some last minute data in the channel. The solution is to do one last read to make sure all of the data is out of the pipeline.
=> [Data-565] Fix for flaky join pointcloud naive test

components/motor/gpio/motor_encoder.go
Still haven't licked the main bug we're working on, but here is some refactoring that I've wanted to do since opening this file. Feel free to say "Alan, this can come after we've found the bug in GoFor, do it later."
Also feel free to say "don't create the `sign` function, do it this other way instead."
=> Refactoring in encoded motors: defer mutex unlocking, better checking of sign bits

go.mod, go.sum, operation/opid.go, operation/opid_test.go, operation/web.go, operation/web_test.go, robot/client/client.go, robot/client/client_test.go, robot/impl/local_robot.go, robot/web/web.go, robot/web/web_test.go, testutils/inject/robot.go
JIRA: https://viam.atlassian.net/browse/RSDK-578
Add client interceptors to pass opids from client to server, and update server interceptors to re-use client-sent opids.
Prerequisites:
=> RSDK-578 Pass op id through to remotes rdk

etc/setup.sh
The current logic expands $PATH and the ruby directory and hardcodes them into .viamdevrc, which then override any PATH changes the user makes afterward.
=> fix variable expansion in .viamdevrc

components/arm/fake/fake.go, robot/impl/local_robot.go, robot/impl/local_robot_test.go, robot/impl/resource_manager.go, utils/errors.go
saves the error to the wrapper, which is returned when we try to access that resource.
Also updated some errors and logging to always return resource name + model if applicable
=> RSDK-474 Save resource error when not started

components/input/gamepad/gamepad_linux.go, components/input/gamepad/gamepad_mappings_linux.go, components/input/input.go
did some minor testing:
* created a bot with this controller
* logs mention detecting it correctly `found known gamepad: 'Logitech G920 Driving Force Racing Wheel' at /dev/input/event0`
* values update (have to refresh the control UI to see the new values, but i think the card is just broken more broadly)
=> add support for logitech G920 steering wheel and pedals

.artifact/tree.json, components/camera/camera_test.go, components/camera/transformpipeline/depth_edges_test.go, components/camera/transformpipeline/mods_test.go, components/camera/transformpipeline/pipeline_test.go, components/camera/transformpipeline/undistort_test.go, components/camera/videosource/server_test.go, pointcloud/voxel_segmentation_test.go, pointcloud/voxel_test.go
Only changes tests, should speed up tests times for some packages by reducing the image/pointcloud size.
=> [Data-504] reduce test image resolutions

components/motor/gpio/motor_encoder.go
Rand and I are struggling with https://viam.atlassian.net/browse/RSDK-694, and although this is not a fix, it is some refactoring which I think makes it easier to reason about this code (splitting the code into smaller, more self-contained single-purpose functions, adding comments, simplifying the control flow). I suggest reviewing commit-by-commit, because everything together gets muddled. For commits where a large section of code has changed indentation amounts, append a `?w=1` to the end of the URL to ignore whitespace changes (e.g., https://github.com/viamrobotics/rdk/commit/b8cf4502dc8caa5af2f66de33fae2a5050017c84?w=1 instead of https://github.com/viamrobotics/rdk/commit/b8cf4502dc8caa5af2f66de33fae2a5050017c84). 
For the most part, changes to behavior are not intended, though the …
=> Simplify some of the RPMMonitor logic

services/slam/builtin/builtin.go, services/slam/builtin/orbslam_yaml_test.go
Implements this ticket: https://viam.atlassian.net/browse/DATA-713
Fixes the issue that `time.RFC3339Nano` saves files with truncated zeros, e.g. `rplidar_data_2022-11-07T19:50:22.334Z.pcd` instead of `rplidar_data_2022-11-07T19:50:22.3340Z.pcd`, which messes up the sorting of files in the slam implementations.
=> [DATA-713] Add zero padding to slamTimeFormat

etc/configs/fake.json, services/baseremotecontrol/builtin/builtin.go, services/baseremotecontrol/builtin/builtin_test.go, services/navigation/builtin/builtin.go, web/frontend/cypress/data/test_robot_config.json
makes it so that the service dependencies is not as much of a breaking change
=> RSDK-863: Add implicit depends_on for services

components/camera/videosource/webcam.go
Hi, you already approved this (https://github.com/viamrobotics/rdk/pull/1551) but merge conflicts got ugly and so here we are
=> [DATA-683] Default webcam selection sent to mediadevices

config/config.go, robot/impl/local_robot.go, robot/impl/resource_manager.go, robot/impl/resource_manager_test.go, web/server/entrypoint.go
For less trusted environments where an untrusted user may update the config and we cannot trust them to run arbitrary code.
Note: This shouldn't be relied upon for completely untrusted environments.
=> APP-955 - Flag `untrusted-env` to disable all processes and shell

services/slam/builtin/cartographer_int_test.go, services/slam/builtin/orbslam_int_test.go
https://viam.atlassian.net/browse/DATA-749
Orbslam is known to hang frequently indefinitely, especially when running it with a mono camera. When orbslam hangs, it will cause a timeout and is the most likely suspect for the observed timeout issues mentioned in the ticket.
This PR updates the integration test to make sure adding an image to orbslam does not exceed 3 minutes. If it does, we assume that orbslam hangs and handle it accordingly.
=> [DATA-749] Fix SLAM integration test timeout

services/slam/builtin/builtin.go, services/slam/builtin/builtin_test.go, web/frontend/cypress/data/test_robot_config.json
Adding Validate function to slam to allow sensors defined by users in config to be automatically added to the depends_on field, thus avoiding requiring users to double write anything
=> DATA-539 Validate SLAM to auto-generate depends_on 

web/server/entrypoint.go
cannot repro the other part, so just fixing this part first
=> RSDK-801: Change default logger to be pretty (ISO formatted)

components/camera/transformpipeline/composed.go, components/camera/transformpipeline/composed_test.go, components/camera/transformpipeline/depth_edges.go, components/camera/transformpipeline/depth_edges_test.go, components/camera/transformpipeline/detector.go, components/camera/transformpipeline/mods.go, components/camera/transformpipeline/mods_test.go, components/camera/transformpipeline/pipeline.go, components/camera/transformpipeline/pipeline_test.go, components/camera/transformpipeline/preprocessing.go, components/camera/transformpipeline/transform.go, components/camera/transformpipeline/undistort.go, components/camera/transformpipeline/undistort_test.go
Removes the stream attribute from transform model, and makes each transform pass its stream type to the next transform.
Hold off merging until coordinate with other teams, since this is a breaking change
=> [Data-758] update transform component

components/input/gpio/gpio_test.go
Refactored the test for 1. split cases into sub-tests and 2. make sub-tests independent via setup/teardown.
There shouldn't be any functional changes to the test other than accounting for the fact that each test starts with a clean state.
Functional changes will be in https://github.com/stevebriskin/rdk/tree/rsdk-702b.
=> RSDK-702: Refactor gpio input test

components/input/gpio/gpio_test.go
Actual changes to lower the odds of flakes.
=> RSDK-702: tweak flakiness in gpio input tests

components/camera/videosource/webcam.go
#1595 closes a camera _with_ a user-specified video path. This PR additionally does it for cameras _without_ a user-specified video path. I tested this the same way as my previous PR except I removed the user-specified video path.
This is necessary for DATA-597 since we only know about cameras discovered on startup. That is, mediadevice's discovery functions are only run in `init` methods. Because of this, if a camera (regardless of if it has a user-specified video path) changes its video path to a path not discovered at startup we will never be able to find it again and re-connect.
=> DATA-597 close cameras with unspecified path on disconnect

robot/web/web.go
Currently, app gets back RawRGBALazy images by default from remote cameras.
This switches all camera streams to request JPEGLazy frames from the cameras if they are using a gRPC GetImage() method.
The alternative could be to change the camera/client.go default request to be empty ( rather than the current default to request RawRGBALazy) such that the server can provide its own default MIME type in the response.
=> Add JPEG hint to app video streams

services/slam/builtin/cartographer_int_test.go
Ticket: https://viam.atlassian.net/browse/DATA-661
This is a fix that's necessary for this PR to go through: https://github.com/viamrobotics/slam/pull/116
=> [DATA-611] Fix cartographer integration test

web/frontend/src/components/base.vue
This PR updates how we process base input events to make sure they are processed in order and to avoid race conditions. Instead of immediately triggering events, we add them to a queue and resolve them one-by-one. The `stop` and `digestInput` functions were refactored to return promises that did not resolve until the callback for their respective `gRPC` calls is invoked. This way if inputs are pressed rapidly, we make sure a set power event is resolved before calling the subsequent stop call. 
Here is my console log after spamming the `d` key:
@micheal-parks @edaniels @stevebriskin If we know how to reproduce this issue it would be great to test out this PR with an actual bot. I am hoping this will be a better solution than having to set a timeout to wait for `stop`s.
=> Base input fix

components/movementsensor/mpu6050/mpu6050.go
This is a breaking change because the MPU code went out earlier this week, but hopefully not many people have started using this yet. The naming standard for these is going to be "i2c_bus", so let's use that. See the scope doc "Communication bus naming convention," which I won't link here because it's an internal document and this PR is public.
Should I create a Jira ticket for this? I'm unsure: it's a breaking change, but it's also a very small change. Steve, what do you think?
Tried locally at my desk: still works great when you update the robot config to match.
=> Rename bus_id -> i2c_bus in MPU6050 accelerometer

components/input/gpio/gpio.go, components/input/gpio/gpio_test.go
Moved defaulting + value validation to a common function.
fly by fix: the original time-based test values were insufficient.
=> RSDK-702: Test for input gpio defaults + errors

components/movementsensor/adxl345/adxl345.go, components/movementsensor/mpu6050/mpu6050.go, components/movementsensor/register/register.go, utils/math.go, utils/math_test.go
(and while I was looking at it, return any errors encountered when querying the MPU6050 accelerometer, too.)
This PR is adapted from https://github.com/viam-labs/adxl345-accelerometer/pull/1, and when this is merged we should probably delete that other repo.
Tried at my desk: results look plausible. I've got two accelerometers at my desk now, and although they both give okay results, the MPU6050 tends to think gravity is a pretty consistent 13.7% stronger than the ADXL345 thinks it is. Is this because I coded one of them up wrong, or because one of the chips is miscalibrated? Part of me suspects the former, but I don't actually know. :grimacing: 
but at the very least, they both give values that are the right order of magnitude, in the right direction.
Sorry the PR is so long; I would …
=> [RSDK-1001] Add support for the ADXL345 accelerometer

components/board/mcp3008.go
Tried at my desk with a Jetson Orin. Without this change, sometimes I read the correct value, and sometimes a value 64,000ish too large. With this change, it's always the correct one, somewhere between 0 and 1023 (both of which I can get by trying to read the ground pin or the hot pin).
=> [RSDK-1015] Ignore garbage bits from MCP3008 ADC chip

config/reader.go, config/reader_ext_test.go, protoutils/messages.go, services/armremotecontrol/builtin/builtin.go, services/baseremotecontrol/builtin/builtin.go, services/datamanager/builtin/builtin.go, services/navigation/builtin/builtin.go, services/slam/builtin/builtin.go, services/vision/builtin/builtin.go
A bug was found where models were not parameters for the RegisterServiceAttributeMapConverter.
=> Service model fix - RegisterServiceAttributeMapConverter models

components/movementsensor/imuwit/imu.go, utils/errors.go
Two issues that were causing this error: 
1. Wrong/invalid baud rate
2. Not closing the port in close function. 
Baud rate validation is done by comparing the given baud rate from config file with the applicable baud rates found in Wit devices. 
Added port closing in close function. Close will error if we loose connection to the serial port.
=> RSDK-730 : RDK fails to shutdown when connected to serial components

robot/client/client.go
When circumventing the `FromRobot(r)` helpers, like one may do if they are new to the RDK, the likely result of trying to address any one of `r.ResourceNames` is going to lead to the `ErrMissingClientRegistration`. If said soul is familiar with Go own flavor of DI package registration it's easy to find the x/register packages (and probably the helpers in the process). However a slight nudge never hurt anyone?
=> Make missing rpc client registration fail with more verbose message

services/datamanager/builtin/builtin.go
Use the standard across RDK of prepending with `.viam` in order to have all Viam-generated files in one place.
Default to this if the user-configured directory is empty.
=> Update default capture directory

config/proto_conversions.go, config/proto_conversions_test.go, resource/model.go
Related to RSDK-1267 but allows for empty model names in the proto conversions. The ultimately will be validated in by the config system and either result in partial or full failures of the robot depending on the config.
=> fix: model name validation during proto conversions

services/slam/builtin/cartographer_int_test.go
followup to https://github.com/viamrobotics/slam/pull/121
removes the lua files being placed into the config folder from the cartographer integration test. 
https://viam.atlassian.net/browse/RSDK-1039
=> [RSDK-1039] remove lua files from cartographer int test

components/motor/dimensionengineering/sabertooth.go, components/motor/dmc4000/dmc.go, components/motor/errors.go, components/motor/fake/motor.go, components/motor/gpio/basic.go, components/motor/gpio/basic_test.go, components/motor/gpio/setup.go, components/motor/gpiostepper/gpiostepper.go, components/motor/gpiostepper/gpiostepper_test.go, components/motor/i2cmotors/ezopmp.go, components/motor/roboclaw/roboclaw.go, components/motor/tmcstepper/stepper_motor_tmc.go
Part one of RSDK-833. 
This part mostly takes care of `NewGoTillStopUnsupportedError `function. 
Added motor name to all the drivers where `NewGoTillStopUnsupportedError` is called.
=> RSDK-833: add motor names to motor errors

.github/workflows/pullrequest-trusted.yml
This adds the `appimage-ignore-tests` label that will still build an image despite test results (basically always) and can be used in conjunction with `appimage` although it's pointless.
This additionally cleans up the logic in our PR workflow such that:
* We only run `test` when we receive the `safe to test` label (this happens per commit) or the `appimage` label (needed for when the label is added after tests run since it's difficult to have a workflow look at a past action run's results; without it, the test job is always skipped)
* We only run `slam_integration_test` when we receive the `safe to test label`
* `appimage` runs conditionally based on test success as expected
* `appimage-ignore-tests` runs conditionally on the same label and does not wait for tests
=> RSDK-577 - allow appimage in PR to ignore test results

Makefile, etc/tag_version.sh, web/server/entrypoint.go
This fixes and cleans up some version reporting info for macos and in general. Also see https://github.com/viamrobotics/homebrew-brews/pull/11
=> RSDK-778 - fixup rdk version in macos and brew

services/datamanager/builtin/capture_test.go, services/datamanager/builtin/sync_test.go, services/datamanager/data/fake_robot_with_infrequent_capture.json, services/datamanager/datasync/upload_data_capture_file.go
Empty sensor readings occur when:
* Syncing more often than capturing
* Restarting/disabling/changing sync or collection before a capture file is written to
This will also delete the local empty file.
=> [RSDK-1616] Do not attempt to sync empty sensor reading files 

cli/cmd/main.go, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/audio-input.vue, web/frontend/src/components/base.vue, web/frontend/src/components/camera.vue
JIRA: https://viam.atlassian.net/browse/RSDK-1019
Uses the wrapper implemented here: https://github.com/viamrobotics/viam-typescript-sdk/pull/9
Tested with directremotecontrol on a live robot.
=> RSDK-1019 use ts wrapper for streaming

module/modmanager/manager_test.go, vision/keypoints/briefdesc_test.go, vision/keypoints/matching_test.go, vision/keypoints/orb_test.go
A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
test.That(t, err, test.ShouldBeNil)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
=> test: use `T.TempDir` to create temporary test directory

data/collector_test.go, services/datamanager/builtin/sync_test.go, services/datamanager/datasync/sync.go
Saw flakiness in these tests in [these](https://github.com/viamrobotics/rdk/actions/runs/3830707034/jobs/6518919924) runs. Was not able to reproduce locally:
```
builtin$ go test -race --count=200 -run TestDataCaptureUpload/If_tabular_uploads_fail_transiently,_they_should_be_retried_until_they_succeed
PASS
ok      go.viam.com/rdk/services/datamanager/builtin    115.741s
data$ go test -race --count=2000 -run TestClose
PASS
ok      go.viam.com/rdk/data    112.579s
```
This makes 3 changes:
- Reduces test collector interval from 15ms -> 5ms. Since the test is essentially checking "after <expected interval> + <leeway>, did we capture stuff?", decreasing the expected interval from 15->5ms and increasing the leeway from 10->20ms should reduce the chances of this happening.
- In the failing …
=> [DATA-fix] Attempt to reduce false negatives in sync/collector tests.

components/generic/server.go, examples/customresources/apis/gizmoapi/gizmoapi.go, examples/customresources/apis/gizmoapi/wrapper.go, examples/customresources/demos/complexmodule/client/client.go, examples/customresources/demos/complexmodule/module_test.go, examples/customresources/models/mybase/mybase.go, examples/customresources/models/mygizmo/mygizmo.go, module/module.go, module/module_test.go
Does what it says on the tin. I somehow overlooked this case (generic interface on regular components) during the main modules project. Thanks to @dannenberg for pointing it out.
=> RSDK-1627 - Add generic DoCommand support for modules

cli/data.go
Tested that works locally and matches the metadata's timeRequested field.
=> [DATA-992] Save exported data filename as RFC3339Nano

motionplan/cBiRRT.go
For more information see http://web.eecs.umich.edu/~imarkov/10rules.pdf
=> Remove recursion from cbirrt, add max iterations to loops.

components/movementsensor/gpsrtk/gpsrtk.go, components/movementsensor/gpsrtk/gpsrtk_test.go
- Migrate go statements to `utils.PanicCapturingGo()`
- Don't start the background goroutine unless the rest of startup succeeds (to prevent leaking goroutines)
- Lock the mutex whenever you read or write any data that is also read/written from a different goroutine (this was the actual cause of the race conditions!)
- Remove the test that sometimes fails due to a bug in third-party code. It sucks that it sometimes fails, but all the problems are down in the bowels of https://github.com/de-bkg/gognss, and not in code we own.
Things I kinda wanted to change but didn't: 
- `RTKMovementSensor.GetStream()` is nearly identical to `ntripCorrectionSource.GetStream()`, and the only times you call the RTK version, you always pass in the same state stored in an ntrip object. …
=> [RSDK-923] Make GPS-RTK code more robust, remove bad test

.github/workflows/main.yml
The slack-side app is all set up to provide the integration hook, and this was just tested and works. Sending to #team-devops for now. Should be pretty simple. We can change the channel or have it spam us with successful runs too if we want. For now, failures only.
=> [RSDK-845] Add Slack Failure Notices to Workflows

components/camera/camera.go, components/camera/camera_test.go, components/camera/videosource/camera_waitgroup.go, components/camera/videosource/webcam.go, go.mod, go.sum
Draft: These gostream changes (https://github.com/edaniels/gostream/pull/16) need to be pushed first.
This PR ensures we can reconnect to a camera found at startup. ~~It keeps one of two goroutines up: one to listen for a disconnection event or another to listen for reconnection events.~~ It uses one goroutine and `goutils.ManagedGo` to ensure that routine is always up, even after panics.
There are two outstanding issues (tested in linux) that will require changes to mediadevices:
1. Cameras plugged into different usb ports from its usb port at start up will not be found. (See [DATA-879](https://viam.atlassian.net/browse/DATA-879))
2. Cameras added after starting up will not be discovered. (see [DATA-880](https://viam.atlassian.net/browse/DATA-880))
I'll create tickets for both with more …
=> DATA-597 Automatically reconnect to a camera

services/slam/builtin/builtin.go, services/slam/builtin/builtin_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-1271)
Check config's first camera component's `distortion_parameters` is not `nil` or a nil pointer. 
Return an error from `rdk.services.slam.builtin.configureCameras`, which will prevent slam initialization if check fails & will output informative log.
=> RSDK-1271 - Check for missing distortion parameters in SLAM service

.github/workflows/appimage.yml, .github/workflows/appimagecleanup.yml, .github/workflows/pullrequestclose.yml, .github/workflows/pullrequestcomment.yml
One fix to correct the always-failing appimage removal on PR close. The rest is/should just be switching to github runners for trivial (non-code) jobs and removing a now-obsolete workaround.
=> Cleanup workflows and fix security for appimage PR removal

robot/web/web.go
This PR removes Warn log for already registered camera/audio streams.
> tested on Pi and Mac
```
$ go run web/cmd/server/main.go -config etc/configs/fake.json
```
Make change to `fake.json` -> no camera/audio "already registered" log :)
=> RSDK-894 - Remove log for already registered camera streams

cli/client.go
We've renamed FindRobots to ListRobots in API to match the naming conventions we want. This PR updates RDK to point to the new ListRobots API with no other changes.
This isn't breaking RDK now. Both APIs exist. I'd like to delete FindRobots as soon as this is released in the RDK and robots are using this RDK version. Its also just a CLI change and not a part of Viam Server.
=> Migrate FindRobots -> ListRobots

robot/web/web.go
JIRA: https://viam.atlassian.net/browse/RSDK-1646
=> RSDK-1646 Configure cors to allow all origins

components/board/commonsysfs/board.go
There have been too many recent frustrating bugs where the eventual cause was traced down to this stuff just not being implemented, and there ought to be an easier way to figure that out.
=> Log that I2C and digital interrupts are not implemented on commonsysfs boards

components/camera/align/extrinsics.go, components/camera/align/homography.go, components/camera/align/join.go, components/camera/camera.go, components/camera/camera_test.go, components/camera/ffmpeg/ffmpeg.go, components/camera/transformpipeline/composed.go, components/camera/transformpipeline/depth_edges.go, components/camera/transformpipeline/detector.go, components/camera/transformpipeline/mods.go, components/camera/transformpipeline/pipeline.go, components/camera/transformpipeline/preprocessing.go, components/camera/transformpipeline/undistort.go, components/camera/videosource/join_pointcloud.go, components/camera/videosource/server.go, components/camera/videosource/static.go, components/camera/videosource/webcam.go, rimage/transform/pinhole_camera_parameters_test.go, services/slam/builtin/builtin.go, services/slam/builtin/orbslam_yaml.go, vision/segmentation/color_objects_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-1271
Fixes issue with original [fix](https://github.com/viamrobotics/rdk/commit/24aaa2572adf385b1739e0a48511b4aa7622757e) which  @edaniels raised to me was only band-aiding over a deeper issue which turned out to occur multiple places in RDK.
The problem is that `transform.PinholeCameraModel`'s `Distortion` field is an interface type, which means that if it is set to a `nil` value it results in the type being `*transform.BrownConrady)(nil)` but the value being `*transform.BrownConrady`, of which `nil` is a valid value. This means that for any users of `transform.PinholeCameraModel.Distortion`, if this was left unaddressed, users would need to write:
```golang
distortion, ok := camaraModel.Distortion.(*transform.BrownConrady)
if !ok {
// 
}
if …
```
=> RSDK-1271 - fix nil distortion interface type propagation

components/board/status.go
This was going to be in https://github.com/viamrobotics/rdk/pull/1759, which is no longer going to be merged. but this line shouldn't be forgotten! Without it, the error contains a `"%s"` in its description and doesn't mention the name of the pin that couldn't be read.
Github suggests I tag Eric, but he's a very busy man and this change isn't worth his time. Instead, I'll get a review from the low guy on the totem pole! (Sorry, Drew :wink:)
=> format error properly

components/board/commonsysfs/board.go
Sorry about this! We want to log when you try using the unimplemented parts, but not when you're just checking their statuses. So, remove half of https://github.com/viamrobotics/rdk/pull/1786. 
This time, we're going to actually try it out on a robot before merging. Thanks to @thegreatco and @dannenberg for pointing out the problem.
=> Don't spam log messages on sysfs boards

components/camera/videosource/webcam.go
change resolutions constraints to be IntExact instead of IntRanged.
=> RSDK-1729 - change resolution constraints to be of type IntExact

.github/workflows/motion-benchmarks.yml, .github/workflows/motion-pull-request-trusted.yml, .github/workflows/pr-labeler.yml
This PR fixes a bug I created earlier today when I pushed the first version of the motion benchmarking Github action. I had overlooked that I will have to be more general in my logic to `go get` the head branch, and this will fix that to make it more robust.
See [this reference PR](https://github.com/viamrobotics/rdk/pull/1797) for a demonstration that this new iteration is functional from PRs within RDK. And [another reference PR](https://github.com/viamrobotics/rdk/pull/1799) to show that it works from other forks, etc.
=> enable other repos to trigger motion benchmarks

.artifact/tree.json, components/camera/fake/camera.go, components/camera/fake/camera_test.go, robot/impl/data/cfgtest1.json, robot/impl/local_robot_test.go
The camera model “fake” is changing, such that a user will have an option of choosing the resolution of the fake image being served. 
- They can leave the attributes blank, which means that the default resolution of 1280 x 720 is used.
- They can specify either “width” or “height”, and the other one will be scaled appropriately with the same ratio of 16:9.
- They can specify both “width” and “height” which will skew the image to whatever they want. 
- Useful for bench marking certain point cloud tests
=> Rsdk-1632 : add attributes to fake camera to change resolution

.github/workflows/motion-benchmarks.yml, .github/workflows/motion-pull-request-trusted.yml, .github/workflows/pr-labeler.yml
#1796 broke CI functionality because the branch names were not updated and was subsequently reverted.  This PR does the correct thing and updates them
=> Fix motion benchmarks after #1796 was reverted

rimage/transform/brown_conrady.go, rimage/transform/brown_conrady_test.go, rimage/transform/distorter.go, services/slam/builtin/builtin.go
[Ticket](https://viam.atlassian.net/browse/RSDK-1271)
Following the advice of @bhaney in response to my question in the ticket:
1.  adds a `CheckValid` method to the Distorter interface
2. adds a test for `BrownConrady{}`
3. implements `CheckValid` on `NoDistortion{}` & `BrownConrady{}`. `BrownConrady{}`'s implementation only verifies its not called on a `nil` pointer (the bug that triggered the ticket in the first place). Please let me know if you would like me to add more validations in this PR (and if so what they should be as I don't know what values are valid), or leave that up to others at a later time.
=> RSDK-1271 - follow up: add BrownConrady CheckValid

cli/auth.go, cli/client.go, cli/cmd/main.go, cli/config.go
This migrates the CLI auth methods to use the built in Auth0 method for device code authorization vs our one implemented in Apps mongodb.
This has the benefit that the access token returned be supported in our RATv2 Auth flow.
The dial options for Robot Commands and Shell are updated to use the RATv2 flow instead of the Location Secret.
The only downside of this is the ~/.viam/cached_cli_config.json access token is only active for 24hrs. This PR handles refreshing with the refresh token and grant. But if someone is expecting to use this access token as is permanently they need to be aware of the refresh logic.
A new Auth0 Native application was created. Its safe to bake the client_id into the RDK as they are meant to be public. Secret is never used or needed. The application has both the …
=> CLI Auth using Web Auth

components/camera/client.go, components/camera/client_test.go, rimage/transform/brown_conrady.go, rimage/transform/distorter.go, rimage/transform/pinhole_camera_parameters.go, rimage/transform/pinhole_camera_parameters_test.go
Bug fix: See script in [RSDK-1035](https://viam.atlassian.net/browse/RSDK-1035) for steps to reproduce.
[RSDK-1035]: https://viam.atlassian.net/browse/RSDK-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RSDK-1035] Camera Properties call fails

web/frontend/src/components/movement-sensor.vue
This bug happens when visiting the remote control tab on app.viam. If webrtc disconnects and reconnects the real time values of a movement sensor update and require a user to refresh the page.
The proposed fix in this Pr has been tested in local and fixes this issue.
In order for this change to go live app will have to use the newest version of RDK when it is released on monday
=> APP-1194 - Sensors stop updating on reconnect

config/diff.go, config/diff_test.go, web/server/entrypoint.go
This PR fixes a problem with the local `rc page` not being able to switch from `grpc` to `webrtc` when a media component is added.
Added a method to `diff.go` called `diffMedia` and an attribute to the `Diff` struct called `MediaEqual`.
WARNING
I had to slightly rearrange the reconfiguring process to first `StopWeb` before `createWebOptions`  and `myRobot.Reconfigure` to avoid race conditions with the `webService` close out.
> tested on RPI
To recreate, start with an empty config and run the server.
```
$ go run ./web/cmd/server/main.go --config ./to/local/config.json
```
```
{}
```
Notice how the rc page on `localhost:8080` is using GRPC.
Then, edit the config by adding a camera component:
```
{
{
"type": "camera",
"model": "webcam",
"name": "cam1"
}
]
}
```
Refresh the …
=> RSDK 889 - Restart web service on media change

.github/workflows/pr-labeler.yml
To help search for PRs by non org members.
=> Label PRs with viam-org for org members

services/slam/builtin/cartographer_int_test.go
This PR fixes a flaky test in the cartographer integration tests where an unexpected map would be generated due to slow close out leading to failures in the offline mode test which was expecting no maps. This has been resolved by changing the map rate on the initial online test and removing the creation of a map at closeout on the SLAM side of things
JIRa Ticket: [RSDK-1732](https://viam.atlassian.net/browse/RSDK-1732)
Associated PR: [#143](https://github.com/viamrobotics/slam/pull/143)
[RSDK-1732]: https://viam.atlassian.net/browse/RSDK-1732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RSDK-1732 Fix for Flaky Cartographer SLAM Test

components/camera/rtsp/rtsp.go
Addresses these two comments:
https://github.com/viamrobotics/rdk/pull/1653#discussion_r1082883572
https://github.com/viamrobotics/rdk/pull/1653#discussion_r1094803685
By doing two select statements, cancellations are respected and the reader never is in a state that could get fully blocked.
=> DATA-751-fix : respect cancellations, never fully block the RTSP model

robot/web/web.go
The app is now always returning two auth handlers. 1 web auth and 1 location secret.
=> APP-1086 - Remove unneeded check for non-web auth handler

components/board/genericlinux/gpio_unsupported.go
This fixes a lint error introduced in https://github.com/viamrobotics/rdk/pull/1822 which results in `make` failing currently.
```
➜  rdk git:(main) ✗ make
... not posting unrelated frontend logs
go build -tags dynamic ./...
GOBIN=`pwd`/bin/gotools/Darwin-arm64 go install google.golang.org/protobuf/cmd/protoc-gen-go \
github.com/bufbuild/buf/cmd/protoc-gen-buf-breaking \
github.com/bufbuild/buf/cmd/protoc-gen-buf-lint \
github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc \
google.golang.org/grpc/cmd/protoc-gen-go-grpc \
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
github.com/edaniels/golinters/cmd/combined \
github.com/golangci/golangci-lint/cmd/golangci-lint \
github.com/AlekSi/gocov-xml \ …
```
=> fix-build-failure-due-to-useless-Errorf

config/config.go, robot/impl/resource_manager.go, services/datamanager/builtin/builtin.go, services/datamanager/builtin/builtin_test.go, web/server/entrypoint.go
This PR adds the `disable-directory-configuration` flag to `viam-server`. When this flag is used, connections to the robot will not be able to change the directory where we store data captured by the data service, and all data will be captured to the default directory, `$HOME/.viam/capture`. This flag can also be able to disable directory configuration for other services such as SLAM, but that work is not included in this PR.
**Manual Testing**
In addition to the automated tests, I tested this manually by running `go run web/cmd/server/main.go -config services/datamanager/data/fake_robot_with_data_manager.json -disable-directory-configuration`, which logged an error. I also tested that when the configuration does not have the capture directory configured at all (empty string), we _do not_ …
=> [DATA-1035] Add option to disable directory configuration

robot/web/web.go, robot/web/web_test.go
RSDK-856
Adds a default context timeout for all inbound gRPC methods of 10 minutes using a new unary interceptor. Tests that the context is modified when no deadline is declared and that the context remains untouched when a deadline is already declared.
=> RSDK-856 Add a default timeout to all inbound gRPC methods

components/arm/yahboom/dofbot.go
Thanks to @biotinker for suggesting this fix!
Without this, I get "nil pointer dereference" errors any time I try to modify the end position of the dofbot arm, and with it I get "zero IK solutions produced, goal positions appears to be physically unreachable" errors instead. Peter suspects this might be because the arm doesn't have enough degrees of freedom to get to any location? but it's at least progress enough to close the original ticket.
I don't like that Go is perfectly happy to leave things uninitialized like this, but that's a complaint with the language, not with our use thereof.
=> [RSDK-1881] Initialize the robot member variable when constructing a dofbot arm

.github/workflows/pr-labeler.yml, .github/workflows/pullrequest-trusted.yml
Ugh, this turned out to be more annoying to debug and correct than I ever expected. Long story short, github fires an event trigger for every label added, even though the .update() action is a single call. When we added the "viam-org" label at the same time as "safe-to-test" it appears to have been doing them in alphabetical order, so the second Test workflow that fired was on a label that wouldn't actually do anything, yet it still cancelled the workflow from the first label (started seconds prior.) And thus, new PRs would just hang and not run their tests. So the labels are now being added one at a time, in the correct order.
Additionally, both the "is-organization-member" and "labeler" actions we were using were out of date and causing warnings. I couldn't find ready/easy replacements, …
=> Fix PR Labeler Workflow

pointcloud/merging_test.go
These flaky tests could potentially be fixed by improvements as explained in RSDK-1200, but until we do the improvements, we should skip these tests.
=> RSDK-1666 remove flaky MergePoints tests for now 

components/arm/yahboom/dofbot.go
doftbot oob rescue was omitted in [RSDK-1653 Fix arm behavior when OOB](https://github.com/viamrobotics/rdk/pull/1822)
=> Add Doftbot OOB Rescue

components/movementsensor/adxl345/adxl345.go, components/movementsensor/mpu6050/mpu6050.go
...and also marking the optional config value as optional.
Should the documentation mention that backup copies of the 3 datasheets mentioned are available at https://drive.google.com/drive/folders/1-4yLhMyciG8mu0XWf5lq9o-1BAPpBXdJ ? Maybe not: perhaps Google Drive is private to just Viam employees.
I'm unable to test out that the `omitempty` annotation is working correctly. Things run fine on my robot (i.e., the sensor still functions as you'd expect), but I'd like to have the asterisk removed from this image:
Any ideas on that front?
=> Extra documentation for accelerometers

components/arm/yahboom/dofbot.go, components/board/board_test.go, components/board/fake/board.go, components/board/genericlinux/i2c.go, components/board/i2c.go, components/board/pi/impl/i2c.go, components/movementsensor/mpu6050/mpu6050.go, components/sensor/bme280/bme280.go
These changes were discussed in https://github.com/viamrobotics/rdk/pull/1844, but I split them to a separate PR because they're self-contained and unrelated to the main thrust of that branch. There are 3 changes in here:
- Remove `ReadWordData` from the `board.I2CHandle` interface. The I2C protocol lets you read a sequence of bytes from the device, but interpreting two bytes as a word is not well defined: some devices are big endian (e.g., the MPU6050 accelerometer), and others are little endian (e.g., the ADXL345 accelerometer). We could either have twice as many of these functions (`ReadWordBE` and `ReadWordLE`), or get rid of them and make the caller interpret the bytes themselves (which is the implementation I went with).
- Remove `WriteWordData` from the same interface, for the same …
=> Clean up board.I2CHandle interface

.github/workflows/code-coverage-comment.yml, .github/workflows/motion-benchmarks-comment.yml
This PR fixes a latent issue in CI where the auto-generated comments from the commenting bot would overwrite each other by adding a `header` field to the action.
=> add header field to auto-generated pr comments

services/armremotecontrol/builtin/builtin.go, services/armremotecontrol/builtin/builtin_ext_test.go, services/baseremotecontrol/builtin/builtin.go, services/baseremotecontrol/builtin/builtin_ext_test.go
RSDK-888
Modifies base and arm remote control services to call `Stop` on the underlying resource when a `Connect` or `Disconnect` event is triggered. Adds tests to ensure this new behavior.
I thought it would make sense to stop all movement on both types of connect events. Let me know if I should only add this functionality for `Disconnect`.
=> RSDK-888 Stop bases and arms on controller connect events

module/module.go, module/module_test.go
RSDK-1875
Adds a `Refresh` call in module before trying to access parent's resources to ensure the parent `RobotClient` has the most updated resources. Tests that `GetParentResource` will discover resources that were registered after module connected to parent.
=> RSDK-1875 Ensure parent resources are updated when fetched from module

config/reader.go, robot/impl/local_robot.go
JIRA: https://viam.atlassian.net/browse/RSDK-1935
Amends https://github.com/viamrobotics/rdk/pull/1855 to just add TLS information to our cached config, caching a merged config. The latter does not include attribute information.
=> RSDK-1935 emptying the config

.github/workflows/main.yml, .github/workflows/npm-publish.yml, web/frontend/package.json
This PR add a build step to RDK to publish Remote Control components to the NPM Repository `@viamrobotics/remote-control`.
The workflow was tested on another branch and PR: https://github.com/viamrobotics/rdk/pull/1826. The logic in the workflow was based on the TS SDK: https://github.com/viamrobotics/viam-typescript-sdk/blob/main/.github/workflows/publish.yml
Right now I am using incremental version numbers during development. At the end of the project I will update to use the same version number as git tags, and I think we keep updating the version numbers when we tag the RDK.
=> Publish RC components to NPM

module/module.go
This will allow the mod server to close down and clean up a bit more gracefully. This will end the process naturally, so we will not restart it, unlike with Fatal.
=> RSDK-2034 - Do not Fatal log module serve error

web/frontend/package.json
In my last PR I merged I accidentally had a lower version that what I published in my testing. This should fix the build failure seen: `npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@viamrobotics%2fremote-control - You cannot publish over the previously published versions: 0.1.28.`
Btw: This doesn't mean that every merge requires a version bump. That would be crazy. Its just that the version is accidentally lower than latest version so it errors. If the version is the same as latest, no error exists.
=> Update package.json to use latest version

components/board/pi/common/common.go, components/board/pi/impl/board_test.go, components/board/pi/impl/servo.go
180 degrees was hardcoded as the maxAngle for servos in `pulseWidthToAngle` and `angleToPulseWidth`. Updated to be the maxAngle from the servo config instead
=> RSDK-1764 - add maxRotation angle to the servo config

examples/customresources/demos/complexmodule/module_test.go, module/modmanager/manager.go, module/modmanager/manager_test.go
This addresses two tests that are in the top 5 by failure count. Same issue with each is that they rely on building the module at module startup time so it's always "fresh" but... under load, that build process can make the effective startup time exceed the timeouts. So added a few lines to pre-build the module (and server) binaries within the tests, and also increased a couple of timeouts.
=> [RSDK-1609] Fix module test timeouts

components/board/genericlinux/board.go, components/board/genericlinux/gpio.go
This is a follow-up to https://github.com/viamrobotics/rdk/pull/1810. Thanks to @thegreatco for noticing the issue! 
We've been acquiring file descriptors for each GPIO pin, setting their direction to input/output, and if output, setting their value, and then closing the files again. It turns out that when you close the file, the value of the output is undetermined: the pin I tried last time (pin 40) keeps its most recent value, but pins like 37 and 32 float instead.
So, this PR holds the file descriptors open for the remainder of the program (once they're opened for the first time). That way, the GPIO pins keep the same output all the way until the next time you change one of them.
The diff here is a little messed up: I took a sort of pre-amble from both `Set()` and `Get()` and …
=> [RSDK-2019] Hold onto the file descriptors for GPIO pins

components/board/genericlinux/gpio_unsupported.go
Thanks to @randhid for noticing this problem! In https://github.com/viamrobotics/rdk/pull/1896, I updated the function signature of `gpioInitialize` in the Linux-specific file, but forgot to update the non-Linux version to match.
This PR:
- creates a dummy `gpioPin` struct that contains nothing
- updates `gpioInitialize` to return a map of `gpioPin`s to match the function signature of the Linux version
- removes `gpioGetPin`, which was removed from the Linux version, too
I'm unable to test this myself, because I don't have a non-Linux environment. Do I need to implement the GPIOPin interface on the new struct for it to typecheck correctly? Hopefully Rand can tell me.
=> update gpio_unsupported.go to match gpio.go

components/sensor/ultrasonic/ultrasonic.go
Now that digital interrupts are refactored, we can return the ultrasonic sensor implementation to a simpler state. We want this for two reasons
1. To serve as a better example for using the (now) refactored digital interrupts
2. This may also resolve some stray reading issues that currently exist in the sensor
=> RSDK-1682 - simplify ultrasonic sensor implementation

components/movementsensor/gpsnmea/nmeaParser.go, components/movementsensor/gpsnmea/pmtkI2C.go, components/movementsensor/gpsrtk/gpsrtk.go
How to reproduce the bug:
- add a `time.sleep(20 * time.Second)` before starting readings in `Start()` IN `pmtkI2C.go`
- Call `getPosition()` from a script before the readings start
Bug Fix:
- If no position has been read during `Position()`, return (0,0) for position, 0 for altitude and an error
Separate from the bug described in the ticket we found that the ublox chip has pullup resistors, which cause the readings on an I2C to be corrupted. This was not causing the panic described in the ticket but was discovered while investigating the bug - what should be done with this information? Docs ticket?
=> RSDK-1909 - return 0,0 if position is called before getting any reading of position

module/modmanager/manager.go, module/modmanager/manager_test.go, module/module.go, robot/web/web.go
Down at the syscall level, there's a field in the socket address structure called .sun_path which has a max length of 104 characters on MacOS and 108 on Linux (-1 for null terminator.) testing.TempDir() on Mac gets relatively long paths that can exceed this limit. It's also possible a really long, user-configured module name (used in the socket path), combined with Mac's long tempdirs could hit this too.
This PR adds guards around the socket calls, to catch this early and return more readable errors. Previously, the error that bubbled up with just "bind: invalid arugment."
I looked into working around this using chdir(), as the use of relative paths would allow it to work regardless of the true path length, and it looked like it was gonna work great but... I hit a bug in GRPC that …
=> RSDK-2074 - Add guards around unix socket address length

components/audioinput/microphone/microphone.go
Accessing microphone labels was not using the correct index, fixed to loop over all labels.
=> Fix out-of-range error in connecting to microphone

.artifact/tree.json, components/camera/rtsp/rtsp.go, components/camera/rtsp/rtsp_test.go
Flaky tests were caused by RTSP requests to the server never getting returned.
- Added a timeout context to the RTSP client.
- Changed the test to rebuild the RTSP server in case it was in a bad state that was causing the requests to hang.
=> RSDK-1896 - add timeouts and re-tries for flaky rtsp server tests

web/frontend/src/components/base.vue
We added logic to issue a stop command on visibility changes for the base card. Unfortunately, this can interfere with scripts/commands issued by users. This updates the base card to only issue a stop command on visibility change to hidden when the user is actively pressing a base direction key.
=> RSDK-1813 Only issue stop for base when keys pressed on visibility change

robot/packages/cloud_package_manager.go, robot/packages/cloud_package_manager_test.go
RDK must replace "/" in the package names (org/package) to avoid it creating a new directory when writing the file. Currently package downloading fails because the org directory is missing.
This change replaces "/" with "-" ensure packages sit in a flat directory.
=> DATA-1119 - Fix package downloads

.artifact/tree.json, services/slam/fake/data_loader.go, services/slam/fake/slam.go, services/slam/fake/slam_test.go, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/slam-2d-render.vue, web/frontend/src/components/slam.vue
[Ticket](https://viam.atlassian.net/browse/RSDK-1065)
Also implements this [Ticket](https://viam.atlassian.net/browse/RSDK-1789)
1. Change fake slam to use the `viam-office-02-22-1` dataset which contains a map of the entire viam office. This dataset was collected, labeled & cleaned using the scripts located here: https://github.com/nicksanford/sample-slam.
2. Change the SLAM RDK Remote Control UI to use an Orthographic camera in Threejs to render the 2d view of the map with the robot marker.
4. Remove SLAM RDK Remote Control UI support for showing the result of GetMap with the image mimetype.
3. Change the way slam.vue access the bytes of the pointcloud to a workaround which fixes the PCD viewer (both 2d & 3d) breaking from time to time
Tested by:
Running fake slam:
```
ENV=development …
```
=> RSDK-1065 add-slam-ui-frontend-2d-view

components/camera/videosource/webcam.go
Z16 discovery for camera components.
- plugin RealSense to linux device
- add camera component `video0`
- view video feed in `Control` tab
=> Add Z16 to webcam constraints.

components/board/genericlinux/gpio.go, components/board/genericlinux/gpio_unsupported.go
Sorry about this! The non-Periph genericlinux GPIO pins use Linux-specific functions, so we use build tags to have a separate file that gets substituted in for non-Linux OSes. I changed the function signature on the "real" one, forgot to change the non-Linux one to match, and didn't notice the problem because neither I nor Github's CI has a non-Linux environment to test on. 
Jason, please try this out and let me know if it works!
=> bugfix: have same function signatures in gpio.go and gpio_unsupported.go for Macs

.artifact/tree.json, rimage/depth_map_raw.go, rimage/depth_map_test.go, rimage/image_file.go
This will allow an *image.Gray16 to be written to an `image/vnd.viam.dep` as well.
It also speeds up some of the writing to file if you are writing a Viam *DepthMap.
This also changes the form a `vnd.viam.dep` file. Before, each depth value was given 8 bytes of space to put in 2 bytes of depth info. The new way of encoding just gives each pixel the necessary 2 bytes. This also allows dumps of data from the DepthMap slices to be written and read faster. 
Testing with an intel realsense, and it makes correct point clouds.
=> Rsdk 2077 write gray16 images to viam depth format

.artifact/tree.json, rimage/depth_map_raw.go, rimage/depth_map_test.go, rimage/image_file.go, rimage/image_file_test.go
Changes `vnd.viam.dep` to be encoded in a Big Endian way, as that is the network byte order, as used by the C++ server and on the Internet.
=> RSDK-2077 Make sure custom depth type is big endian encoded

services/slam/builtin/cartographer_int_test.go, services/slam/builtin/orbslam_int_test.go, web/frontend/src/components/input-controller.vue
Note: remade previous PR to clean up commit history https://github.com/viamrobotics/rdk/pull/1999
updates integration tests with new endpoints to prep for map representation wrap up. Does not remove old endpoints, as those should be removed in [RSDK-1066](https://viam.atlassian.net/browse/RSDK-1066?atlOrigin=eyJpIjoiMjgwNjQ4MWM0NmUzNGM1OThkZWMzN2JlYTJhMjZhZjUiLCJwIjoiaiJ9). In addition, the internal state and pointcloud endpoints were [added previously](https://viam.atlassian.net/browse/RSDK-1955?atlOrigin=eyJpIjoiOWYyZDY1NTFiOTBjNDkwOGJkOGI0ODJkMjIxOTRjZmYiLCJwIjoiaiJ9), so this PR only adds the GetPosition method
tickets:
[cartographer integration test](https://viam.atlassian.net/browse/RSDK-1055)
[orbslam integration test](https://viam.atlassian.net/browse/RSDK-1067?atlOrigin=eyJpIjoiMj …
=> [RSDK-1055] update SLAM integration tests

services/motion/builtin/builtin_test.go
re- https://viam.atlassian.net/browse/RSDK-2269
doing:
```
go test -run TestMoveSingle/succeeds_with -count=100
PASS
ok      go.viam.com/rdk/services/motion/builtin 129.642s
```
average time 1.29642s
=> RSDK-2269 - flaky test: services/motion/builtin TestMoveSingleComponent

components/camera/rtsp/decode.go, components/camera/rtsp/rtsp_test.go, go.mod, go.sum
This is to stop the flakiness caused by the RTSP client test.
Creates a fake RTSP server rather than trying to use real data. 
The RTSP requests have to happen in a certain order, if they don't then the test fails.
Does not try to read images from the server : only sets up and tears down the RTSP camera. 
Tests were done using real video with the RTSP model on linux and mac by hand, as outlined in the ticket RSDK-1111
=> RSDK-1896 - fix rtsp flaky test

services/datamanager/datasync/sync.go
This was causing a problem with dev and testing for local environments, as the app address was hardcoded. We should be grabbing it from the config instead.
=> [DATA-fix]: Grab app address from the config

web/frontend/package.json, web/frontend/src/main-lib.ts
This is done to investigate moving the `new Client` constructor over to the RDK side always to avoid `@viamrobotics/sdk` version mismatches between library and application.
=> Make client argument to createRcApp() optional

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/slam.vue
1. Rolls back slam.vue to call GetMap (image/jpeg) for the 2d view rather than GetPointCloudMapStream
2. Removes 3d view
3. Changes 2d view to only allow polling at 5, 10, and 30 second intervals or manual refresh
4. Bump remote-control to version `0.2.4`
This leaves all the code for using the temp post map representation APIs unchanged so that we can roll forward when the new APIs have the required performance characteristics.
=> rollback-slam-vue-to-pre-map-representation

components/board/analog_smoother_test.go
Another time-based test. Doesn't fail too often. The fix effectively extends the time from 500ms to 2s while speeding the test up with more frequent checks.
=> RSDK-1863: Fix flaky analog smoother test

services/datamanager/datasync/client.go, services/datamanager/datasync/sync.go
When connecting with the cloud in the RDK syncer, remove the https protocol that is included in app address (e.g. https://app.viam.com:443 -> app.viam.com:443)
Otherwise, the full URL causes DialDirectGRPC to hang.
[note for red herring]: confirmed that AppAddress is properly populated when reaching RDK, just not in the app UI full config
**Testing**
The crashing was previously not viewable locally in logs or when shutting down viam-server locally via ctrl-C, but now see that after a few minutes the robot would silently fail. Tested that this no longer happens and that we successfully sync to app, both prod and staging.
This was immediately visible in prod since stopping viam-service would show logs of `initSyncer` hanging.
=> [DATA-1224] Only include the host portion of the URL when making a direct GRPC connection

.github/workflows/appimage.yml, Makefile
Currently `make server` fails to build and include the web UI when run locally. This means it also fails the `make appimage` target, which depends on the `server` target, and fails when built by homebrew packaging.
This removes the CI automation that worked around this for releases, and instead creates the proper dependencies within the Makefile itself. Source deps are setup so that repeated runs of `make server` won't rebuild the frontend every time, unless the frontend sources change.
Another PR will be incoming for the brew formula itself, since building the server now requires node.
=> [RSDK-2327] Add build-web as requirement for server make target

services/datamanager/builtin/sync_test.go
This test is flaky. With the change in [this PR](https://github.com/viamrobotics/rdk/pull/2052), the number of upload requests made for some given amount of capture data is now a function of both sync interval _and_ data quantity. This test was validating the number of upload requests made strictly as a function of data quantity, so became quite flaky. This is a case of over testing to an implementation: we don't actually care how data was grouped/uploaded, just that the correct data was uploaded.
This removes the check validating the number of upload requests used to upload a quantity of data.
Verified locally with:
```
builtin$ go test -race -run TestDataCaptureUpload --count=10
PASS
ok      go.viam.com/rdk/services/datamanager/builtin    80.040s
```
=> [RSDK-2335] Fix flaky TestDataCaptureUpload.

pointcloud/merging_test.go
Skipping this test since MergePointCloud function is known to create flaky tests.
Will be un-skipped once improvements specified in RSDK-1200 are complete.
=> RSDK-2117 Skip flaky test TestApplyOffset

examples/customresources/demos/complexmodule/moduletest/bad_modular_validation.json, examples/customresources/demos/complexmodule/moduletest/module_test.go, examples/customresources/models/mybase/mybase.go, robot/impl/resource_manager.go
RSDK-2326
Follow up to RSDK-1820. Adds `ValidateConfig` calls before `processComponent` and `processService` to check whether we should build the resources at all. Adds better safeguards against missing motors for `mybase`. Tests that modular components that fail validation will not cause RDK failure and are not built.
Just like with regular validation, we should not actually build resources that fail modular validation.
=> RSDK-2326 Do not build modular resources that fail validation

vision/classification/classification_utils.go
Remove "*100" but want to make sure that `classification.Score()` is already a percentage.
If so, there might be an inconstancy with [those tests ](https://github.com/viamrobotics/rdk/blob/main/services/vision/builtin/tflite_test.go#L233) (that are probably expecting a value between 0 and 1).
Also. should "_pct" be added to the attribute of the transform camera "confidence_threshold" ? It is the case for the attribute of detection.
=> RSDK-2182 - stop multiplying by a 100 confidence

components/movementsensor/movementsensor.go
If movement sensor property is unimplemented then in the readings function we will not add key/value to the readings dict.
=> RSDK-2211: MovementSensor Readings update

services/datamanager/builtin/sync_test.go
Skipping these two sync tests for now because they're non-deterministic and being flaky in CI. Will put out a PR with a fix by EOD.
=> [RSDK-1868] Skip sync tests for now.

robot/client/client_session_test.go, robot/impl/local_robot.go, robot/web/web.go, robot/web/web_test.go, testutils/inject/audioinput.go, testutils/inject/camera.go
This PR fixes two deadlocks in with `webService`. To reproduce, 
1. start the viam-server with an empty config
2. add a webcam component
3. remove the webcam component and observe the indefinite hang.
This happens because ` webService.startStream` adds to `webstream.activeBackgroundWorkers` but its argument `streamFunc` cannot be canceled with `webService.cancelFunc`. Because of this, a call to `webService.Close` or `webService.Stop` will hang indefinitely.
=> fixes for deadlocks in webService

data/collector.go, data/collector_test.go, services/datamanager/builtin/sync_test.go, services/datamanager/datasync/sync.go
Previously, both `Collectors` and `sync.Managers` would log context.Cancelled errors, even if the contexts were intentionally cancelled by the `Collector`/`sync.Manager` (i.e. their `Close()` functions were called, cancelling the parent context of all of their sub-capture/sync routines). This led to spammy logging of behavior that isn't a true error.
This fixes that: in both `Collectors` and `sync.Managers`, we ignore/don't log context.Cancellation errors that occur after `Close()` has been called.
[Ticket](https://viam.atlassian.net/browse/DATA-1200).
TestCtxCancelledNotLoggedafterClose validates that collector's don't log Error level logs when the context is cancelled. It is passing. Note that the Collector logger doesn't log non-Error level logs anywhere.
For sync, I ran updated …
=> [DATA-1200] Don't log context cancellation errors in collectors or sync.Manager if they occur after Close().

data/collector.go, services/datamanager/datasync/sync.go
I didn't realized that utils.UncheckedErr logs errors at the debug level. We want to ignore these ones entirely.
=> [DATA-1200] Replace utils.uncheckedErr with nolint:errcheck in sync/collector.

robot/packages/cloud_package_manager.go, robot/packages/testutils/fake_package_server.go
We were getting issues with some files having off-by-one calculated checksum values from the ones provided from the URL response header. The sums were the same, but the base64's were different. We should be using base64.StdEncoding rather than base64.URLEncoding, which is reserved for URLs and filenames.
**Testing**
Tested that existing packages uploaded to app still deploy correctly using this local RDK.
=> [DATA-1255] Use base64.StdEncoding on the crc32 hash on deployed files

components/sensor/power_ina219/power_ina219.go
This should fix the troubles Matt encountered with being unable to read the sensor from Viam's code while being able to read it from non-Viam code and being able to read other I2C devices from Viam.
Defer statements are unintuitive for me: the function being deferred runs at the end, but the arguments to the function are evaluated immediately. Consequently, we were closing the I2C handle immediately, and then just deferring the check of whether it closed successfully.
=> bugfix for ina219: defer closing the I2C handle

components/board/genericlinux/hw_pwm.go
Hopefully this will get @randhid unstuck. I wish we had a CI check that made sure things worked on Mac!
=> Only compile hw_pwm.go on Linux; it's unused on Mac

web/frontend/src/components/board.vue
**20230322_APP-1428: Use digital interrupt name instead of board name**
- Uses digital interrupt name instead of board name in the digital interrupts section of the board component.
=> APP-1428: Use digital interrupt name instead of board name

services/datamanager/builtin/sync_test.go
We were sorting only by the nano second field. This does not sort things correctly when we roll over to the next second. This fixes that by using time.Sub to compare times. Also changes to use a stable sort. Also changes to use TimeReceived as tiebreaker if time requested are the same.
```
builtin$ go test -race -run=TestDataCaptureUploadIntegration --count=1000 --timeout=20m
PASS
ok      go.viam.com/rdk/services/datamanager/builtin    714.245s
```
=> [RSDK-2394] Sort captured data by time, not just the nanosecond field of the timestamp.

services/slam/fake/data_loader.go
[Ticket](https://viam.atlassian.net/browse/RSDK-2350)
=> RSDK-2350-increase-slam-streaming-chunk-to-1mb

robot/impl/local_robot.go
Makes sure we do not try to close anything that does not exist by checking to see if it exists, instead of throwing a nil pointer error and crashing the server.
sample error output
```
johnnicholson@Johns-MacBook-Air rdk % go run web/cmd/server/main.go -debug -config ../viam-slam/configs/john-mac.json
2023-03-28T11:28:06.266-0400	INFO	robot_server	server/entrypoint.go:82	Viam RDK built from source; version unknown
2023-03-28T11:28:06.267-0400	DEBUG	robot_server	config/reader.go:352	reading configuration from the cloud
2023-03-28T11:28:06.343-0400	DEBUG	robot_server	rpc/dial.go:189	connected via gRPC	{"address": "app.viam.com:443"}
2023-03-28T11:28:06.438-0400	DEBUG	robot_server	rpc/dial.go:189	connected via gRPC	{"address": "app.viam.com:443"}
2023-03-28T11:28:06.522-0400	DEBUG …
```
=> Check pointers exist before closing in local robot

cli/client.go
If a user is new to the CLI, they may not know how to authenticate. This adds a message telling them what to do if they're not logged in.
=> Tell users to auth if they're not logged in.

components/gantry/multiaxis/multiaxis.go, components/gantry/multiaxis/multiaxis_test.go, components/gantry/oneaxis/oneaxis.go, components/gantry/oneaxis/oneaxis_test.go
This fixes:
- multiaxis and single-axis dependencies are not being created on the fly.
- an error after limit switch pins are not found causing an empty input rather than an array of floats into MoveToPosition.
- a zero default gantry rpm being set and fed to `motor.GoTo` - since remote control does not allow you to set gantry rpms anymore.
=> RSDK-2490 Gantry axis does not move with not limit switch pins

robot/client/client.go
we were returning the whole Subtype, so something like `go.viam.com/rdk/component/rdk:component:encoder/register` instead of `go.viam.com/rdk/component/encoder/register`
=> Fix import_guess string

robot/impl/local_robot.go, robot/impl/local_robot_test.go
RSDK-2325
Removes resources whose dependencies have also been removed from `newConfig`. Adds test for this behavior.
Previously, if motor 'm' was dependent on base 'b' and base 'b' was removed and re-added, motor 'm' would not be accessible through SDKs or the web app. Now, motor 'm' correctly reappears when base 'b' is re-added.
=> RSDK-2325 Remove orphaned resources from newConfig in Reconfigure

robot/server/server.go
Tested locally with the [Intel® RealSense™](https://www.intelrealsense.com/) camera. This removes the `Unimplemented` errors but there are still `WARN`ings (see below). Let me know if I should remove those too.
```bash
pi@raspberrypi:~/rdk $ go run web/cmd/server/main.go -config /etc/viam.json 
...
2023-03-27T17:26:18.969-0400    INFO    robot_server    zap/options.go:212      finished unary call with code OK        {"grpc.start_time": "2023-03-27T17:26:18-04:00", "system": "grpc", "span.kind": "server", "grpc.service": "viam.robot.v1.RobotService", "grpc.method": "SendSessionHeartbeat", "grpc.code": "OK", "grpc.time_ms": 0.279}
2023-03-27T17:26:19.215-0400    WARN    robot_server    zap/options.go:212      finished client unary call      {"system": "grpc", "span.kind": "client", …
```
=> RSDK-2253 ignore StreamStatus Unimplemented errors

components/board/genericlinux/data.go
This is in anticipation of adding something similar for PWM chips to fix RSDK-2332. I recommend reviewing this commit-by-commit, though perhaps it's easy enough all together, too.
No changes to functionality are intended, this is just reorganizing things so they're easier to think about and easier to extend in the future.
Tried on an Orin: GPIO functionality appears unchanged.
=> Refactor the way GPIO chips in sysfs get discovered

components/camera/fake/camera.go, components/camera/fake/camera_test.go
This change removes the chess board fake camera image and point cloud, and instead generates a fake image and point cloud to display. They are generated as follows:
-  The image is a gradient from blue to yellow, where the intensity is fully yellow in the upper left, and fully blue in the lower right.
- The point cloud is a sloping plane of this gradient, starting at height 0 at the fully yellow pixel (0,0), and sloping upwards as the intensity of blue increases. Its (x,y) position is its x,y pixel value, and its z position is the intensity of “blue” at that point.
This gets rid of the chess board images all together because they couldn't be found if not running RDK locally, but they also cannot be embedded into RDK.
=> RSDK-2524: Create new "fake" camera model that does not depend on a real image

examples/customresources/models/mybase/mybase.go, module/module.go
Ticket: https://viam.atlassian.net/browse/RSDK-2521
Important design decisions:
- Dont set Attributes to nil if we set ConvertedAttributes. This diverges from rdk behavior which sets Attributes to nil if it is converted. This was done because I think it is worth it to give customers more flexibility in case there is a bug with ConvertedAttributes in the future or in some sdk. 
- Use FromDependencies in mybase.go rather than the switch statement
=> RSDK-2521 Add ConvertedAttributes to module configs

config/data/diff_config_1.json, config/data/diff_config_2.json, config/diff.go, config/diff_test.go, module/modmanager/data/simplemoduleruncopy.sh, module/modmanager/manager.go, module/modmanager/manager_test.go, module/modmaninterface/interface.go, module/module.go, robot/impl/local_robot.go, robot/impl/local_robot_test.go
RSDK-2389
Main changes:
- Adds `Reconfigure` to module manager
- Adds `Remove` to module manager
- Refactors module manager to handle reconfiguration
- Adds `diffModules` to make `DiffConfigs` sensitive to changes in `modules` array
- Calls modular `Add`, `Reconfigure` and `Remove` from local robot `Reconfigure` to allow dynamic updates to the config's `modules` array
- Handles resources orphaned by removed/reconfigured modules in `Reconfigure`
Secondary changes:
- Adds test for module manager `Reconfigure`
- Adds test for module manager `Remove`
- Adds test for modular orphaned resources
- Adds test for mixed orphaned resources
- Modifies `TestDiffConfigs` to test module changes
- Adds `nolint:dupl` to some duplicated code
=> RSDK-2389 Support reconfiguration of modules

services/slam/builtin/builtin.go, services/slam/slam_copy/config/config.go, services/slam/slam_copy/config/config_test.go
Remove the unused dev flag in SLAM Map Representation project. Similar edits were also made in slam, viam-cartographer, viam-orb-slam3 repos, see associated PRs.
JIRA Ticket: https://viam.atlassian.net/browse/RSDK-2435
Associated PRs: 
- https://github.com/viamrobotics/slam/pull/184
- https://github.com/viamrobotics/viam-orb-slam3/pull/34
- https://github.com/viamrobotics/viam-cartographer/pull/37
=> RSDK-2435 Remove Dev Flag RDK

motionplan/cBiRRT.go
While the merge of 1899 had enough of a subtle adjustment of underlying float values that 2401 is coincidentally no longer hit on `main`, the bug still existed.
This PR was tested against the old failing `main` branch pre-1899 and a solution valid both pre- and post-1899 was developed.
=> RSDK-2401 move to position calls with particular start goal specifications will erroneously fail

components/board/nanopi/board.go, components/board/register/register.go
Bee ring is using the nanopi neo air, which is now supported OOTB by periph.io https://github.com/periph/host/pull/30
This means very little is required to use the nanopi neo air with RDK's genericlinux.
Tested this on the real hardware and confirmed that GPIO, i2c, and SPI are all working.
=> Add support for nanopi boards supported by periph.io

components/sensor/power_ina219/power_ina219.go
The previous value of maxCurrent was over the maximum for a 32-bit signed int.
Since by default types `int` are of the width native to the computer that one is running on, this failed compilation on 32-bit systems.
Solution is to explicitly type it as an int64.
=> Prevent int overflows on 32-bit

components/board/genericlinux/gpio.go
This broke way back in https://github.com/viamrobotics/rdk/pull/1896 and I didn't notice until yesterday!
Tried at my desk: at the very least pins 7 and 40 work properly again. You can set a pin high or low and its output value will be what you'd expect, but then you can connect it to either the 3.3V rail or ground and read it, and it will read the thing it's connected to, not the value it was most recently set to. I'll test the rest of the pins exhaustively when working on RSDK-1027 (making sure the pin definitions are all correct).
The new field is named `isInput` so that the default value (0/false) is the most commonly used one. and then the comments reminding you what the argument means are because it's super easy to forget and not recognize it.
and while I was looking at this, the …
=> [RSDK-2631] Allow GPIO pins on genericlinux boards to act as inputs again! :scream: 

motionplan/cBiRRT.go, motionplan/cBiRRT_test.go, motionplan/nearestNeighbor.go, motionplan/nearestNeighbor_test.go
Update NearestNeighbor to run on multiple maps in parallel, and properly handle the return of a `nil` from NN which can only be due to the ctx being cancelled
=> RSDK-1902 Random panic occurring somewhere in CBiRRT method

.artifact/tree.json
Makes a copy of artifact: `slam/example_cartographer_outputs/viam-office-02-22-1/pointcloud/pointcloud_0.pcd` for use by the octree collision tests.
=> RSDK-2312 Add new artifact for collision detection

etc/configs/fake.json
When we modified the fake arm behavior, we updated this in several places but not the `/etc` config for checking out all fake components. This just adds an `xArm6` as the faked arm model. Coincidentally, the errors emitted do indicate the underlying issue, but Eric didn't seem to follow what was happening. We might need to reevaluate that error message.
We could use model-path (I tested with this) but you have relative path resolution issues if you start the server from a different place, so I opted to keep this as simple as possible.
=> Add a valid arm-model to fake configuration

module/modmanager/manager.go
RSDK-2551
Swallows `exit status 143` errors for now. Python modules have an issue handling `SIGINT` from the module manager: they return with an exit code of 143 instead of 0.
=> RSDK-2551 Swallow 143 errors when stopping modules for now

components/input/gamepad/gamepad_linux.go, components/input/gamepad/gamepad_mappings_linux.go
Stadia controllers have a mapping that is different than the default. Controller device names are unique of the form `StadiaXXXX-XXXX` so using the model name to lookup the mapping will fail. Instead, expose a simple helper to get the mapping which checks for the prefix.
**Question:** The mapping for Stadia controllers is the same as the "Xbox Wireless Controller" excluding the "record" button. Should this change reuse the mapping or duplicate it?
**Tested:** Ran from source on a Raspberry Pi 4 with the Stadia gamepad connected by bluetooth. Verified in the Viam app in the `input_controller` control panel.
=> Add Stadia gamepad mapping

module/module.go, module/module_test.go, testutils/inject/shell_service.go
RSDK-2632
Calls `addConvertedAttributes` from `Module.ReconfigureResource`. Adds check `validateRegistered` for previous registration in `AddModelFromRegistry`. Adds test for possible `AddModelFromRegistry` errors. Adds tests for proper handling of modular resources with and without a `Reconfigure` function when `ConvertedAttributes` is accessed.
#2142 added converted attributes to `Module.AddResource` but not to `Module.ReconfigureResource` (my apologies for not catching that in review). Reconfiguration of modular resources that attempted to access `ConvertedAttributes` was failing (see associated ticket).
cc @nicksanford + @edaniels
=> RSDK-2632 Call addConvertedAttributes from Module.ReconfigureResource

cli/viam/main.go
Changes destination from a string flag to a path flag in the CLI. This allows it to properly resolve home directories when passed `~`. 
Tested locally with:
```
viam data export <filter flags> --destination ~/test_tilde
```
And confirmed it downloaded data into `$HOME_DIR/test_tilde`, rather than `./~/test_tilde` like before
=> [DATA-fix] Use path flag for destination dir.

components/board/genericlinux/board.go
This is to say, you can mention interrupts by pin number without pre-defining them in the board config, and we'll automatically convert those GPIO pins to digital interrupts. You can't convert a digital interrupt pin back to a GPIO pin afterward, but in practice no one should ever want to do that.
Tried on a Jetson Orin with an ultrasonic sensor plugged in. This config was enough to get the sensor to work:
```
{
"modules": [],
"services": [],
{
"depends_on": [],
"model": "jetson",
"name": "main_board",
"type": "board",
"attributes": {}
},
{
"name": "ult",
"type": "sensor",
"model": "ultrasonic",
"trigger_pin": "40",
"echo_interrupt_pin": "38",
"board": "main_board"
},
"depends_on": []
}
]
}
```
Note how the `main_board` component doesn't say nuthin' about …
=> [RSDK-2345] Create digital interrupts if not mentioned in the config

components/motor/roboclaw/roboclaw.go
Fixes: SetPower can now go backwards and IsPowered condition is fixed. This is still a very raw implementation.
=> RSDK-2637: minor roboclaw fixes

components/board/genericlinux/gpio.go, components/board/genericlinux/hw_pwm.go
Tried on an Orin: if you set a pin to high _or_ turn on a PWM signal, and then hit control-C to kill the RDK server, the pin goes low again and stays there. 
If you set a pin high or turn on a PWM signal, and then change the board config, the pin goes low again and stays there (until you set it to something else afterwards on the new board component). Is that the right choice? I think it might be, but would like a second opinion.
=> [RSDK-2734] turn off PWM signals when closing a board

Makefile
Updated canon images stopped including opus, as the go package itself includes prebuilt libraries.
=> Remove dynamic tag to use default opus

components/encoder/incremental/incremental_encoder.go
While working on RSDK-2737, I figured I'd clean up the incremental encoder a little. I recommend reviewing commit-by-commit: each one should be straightforward by itself, and this PR has a bunch of small, unrelated changes.
Tried on an rpi: it sure looks like the behavior is unchanged (and no behavioral changes are intended).
=> Cleanup of incremental encoder

components/base/wheeled/wheeled_base.go, components/base/wheeled/wheeled_base_test.go
This change fixes base.spinMath and adds some initial tests. The calculation for RPM was incorrect but seems to be working now based on hand timing on actual hardware and the few test cases I added. I can add more if necessary but these cover the error I have seen.
=> RSDK-2356: base.Spin changes speed for different distances

examples/customresources/demos/remoteserver/server_test.go, module/module_interceptors_test.go
Basically changing a fixed sleep into a loop what actually waits for things to be ready, should fix some flakiness in the first test, and a similar fix (waiting for assertion) in the second.
=> [RSDK-2388] [RSDK-2392] Fix timing issues in remote server and module tests

components/motor/gpio/motor_encoder_test.go
I made a mistake in where the pointer to the `incremental.Encoder` is created.
=> RSDK-1020 Part IA change back encoder test pointer change for now, keep skips

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/encoder.vue, web/frontend/src/components/remote-control-cards.vue
This change adds an RC card for the new encoder API. If the encoder only supports ticks, only the `Count` column will be shown, and if it only supports degrees, only the `Angle (degrees)` column will be shown. If the encoder supports both, then both columns will be there, as shown in the image below.
=> RSDK-2482: add rc card for encoder

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/tailwind.config.cjs
We are seeing an issue where the `h-[400px]` arbitrary class is not being respected in production builds. This will attempt to ensure it is included by adding it to the `tailwind` config safe list.
=> Add h-[400px] to safe list

components/movementsensor/movementsensor.go
I tested this manually by creating a robot with a fake movement sensor and capturing Position, LinearAcceleration, and Orientation. I didn't see a place to add unit test coverage.
Here is the exported sensor data.
[sensor_data.zip](https://github.com/viamrobotics/rdk/files/11298362/sensor_data.zip)
Here are the corresponding app changes: https://github.com/viamrobotics/app/pull/1503
=> RSDK-2692 - Add collectors for MovementSensor LinearAcceleration and Orientation

components/board/digital_interrupts.go
I don't know if we'll ever remove the "servo" type of digital interrupt (see https://viam.atlassian.net/browse/RSDK-1963), but in the meantime this comment is showing up in the [public, auto-generated documentation](https://pkg.go.dev/go.viam.com/rdk/components/board#DigitalInterrupt), and is causing some confusion (per @sguequierre). Basic digital interrupts have supported callbacks for a long time, and non-basic (servo) digital interrupts probably shouldn't be used.
Eric wrote this in 2021, which I suspect was before the current interface had been fleshed out very well.
=> remove comment about digital interrupt callbacks

web/frontend/README.md, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/app.vue, web/frontend/src/components/remote-control-cards.vue, web/frontend/src/main-lib.ts
Now that we can pass a robot client to the RC, the RC should be aware if it needs to self-manage the connection. If a client is passed, the RC will not attempt to connect/disconnect and will leave that up to whatever parent component is passing to it. If a client is not passed, the RC will create its own client and connect/disconnect as expected.
=> Check for self-managed connections

web/frontend/src/components/slam.vue
This PR removes the extra parentheses from the SLAM UI's 3D View header.
JIRA Ticket: https://viam.atlassian.net/browse/RSDK-2779
=> RSDK-2279 Remove Extra Parentheses in SLAM 3D View

components/servo/gpio/servo.go, components/servo/gpio/servo_test.go
Except for a few commits that added and removed debugging info along with other changes, my hope is that each commit is self-contained and this should be easy to review commit-by-commit if it's confusing all at once.
Important changes:
- If the frequency is not specified in the config, we've always used the current frequency of the pin. However, if the pin's frequency is currently 0, we now default to a sane value (300 Hz, chosen to be slightly slower than the default maximum of 400 Hz) instead!
- If the frequency is so fast that we cannot move all the way to the max position (because it would require holding the signal high for longer than the period of the PWM), lower the frequency so that we could spend the maximum time high and the minimum time low. 
Unimportant changes:
- Don't …
=> [RSDK-2226] audit GPIO servo code

etc/.golangci.yaml
[Ticket](https://viam.atlassian.net/browse/RSDK-1053)
This reenables the staticcheck linter now that slam deprecated APIs no longer exist
=> RSDK-1053-reenable-staticcheck-linter

web/frontend/src/components/encoder.vue
The displayed values weren't `$ref()` so they weren't updating. The RC card was always displaying 0 even when the encoder count was changing.
=> RSDK-2482 FIX: encoder RC card

web/frontend/README.md, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/app.vue, web/frontend/src/components/base.vue, web/frontend/src/components/camera/camera.vue, web/frontend/src/components/camera/cameras-list.vue, web/frontend/src/components/camera/stream-manager.ts, web/frontend/src/components/encoder.vue, web/frontend/src/components/gamepad.vue, web/frontend/src/components/movement-sensor.vue, web/frontend/src/components/navigation.vue, web/frontend/src/components/remote-control-cards.vue, web/frontend/src/components/slam-2d-render.vue, web/frontend/src/components/slam.vue, web/frontend/src/main-lib.ts
Instead of allowing the RC to accept a client, instead we are going to simplify it have the RC create and manage its own client entirely. This should avoid version mismatching with app and no longer require a peer dependency. 
This also includes a bunch of fixes to stop `setTimeout` loops that are being opened and not closed.
=> Make RC SDK client self managed

cli/viam/main.go
**Context**
CLI string in the FE was updated to include --bboxLabel, but not the BE, so the export command will fail if you copy and paste in with --bboxLabel. This updates the cli tool to include the flag `bbox_labels` since this is following the convention for all other cli flags. FE will need to be updated accordingly. 
**Testing**
Testing locally by building `go build -o ~/go/bin/viam cli/viam/main.go` and then exporting:
`viam --base-url=https://app.viam.dev:443 data export --bbox_labels=blue_square,blue_star,brown_circle,green_square,orange_triangle,pink_star,pink_triangle,yellow_circle --org_ids=0fbe951e-d4c6-427f-985f-784b7b85842c --data_type=binary --mime_types=image/jpeg,image/png --destination=exported_data`
=> [DATA-1351]: Update CLI tool BE

robot/impl/local_robot.go, robot/impl/resource_manager.go, robot/impl/robot_reconfigure_test.go
RSDK-2886
[idea] We should be able to reduce the config timer (renamed `configTicker`) to tick every 5 seconds. This should decrease test running time and increase the frequency with which we're able to detect changes in cloud configs/remotes. I think we can also use a single `triggerConfig` channel (`bool` seemed overly expressive given we only ever send `true`).
=> RSDK-2886 Reduce config ticker and simplify completeConfig goroutine

components/arm/xarm/xarm.go, components/arm/xarm/xarm_comm.go, components/camera/videosource/join_pointcloud.go, components/camera/videosource/join_pointcloud_test.go, motionplan/motionPlanner.go, robot/framesystem/errors.go, robot/framesystem/framesystem.go, robot/framesystem/framesystem_utils.go, robot/framesystem/service_test.go, robot/impl/local_robot_test.go, robot/impl/resource_manager_modular_test.go, services/motion/builtin/builtin.go, services/motion/builtin/builtin_test.go, services/motion/data/fake_tomato.json
Note that this also alters pointcloud as that uses the FS service and was affected by these changes; added @bhaney to look at that, feel free to swap to someone else if needed.
The design of this update removes any need for Motion to talk to the robot or individual resources in real-time, and moves all responsibility of keeping track of discrete resources to the frame system service.
=> RSDK-1229 RSDK-2693 Remove robot from motion service constructor, and prepare for removal from framesystem service constructor

components/board/digital_interrupts.go, components/board/genericlinux/board.go
This splits up a 150-line function that did 4 different things into four 40-line functions that each do 1 thing. The next step after that will be to change one of those 40-line helpers to have different behavior, so we can reconfigure digital interrupt pins as relevant.
No changes to behavior are intended. An unintended change to behavior that I don't think is a big deal: if you try to reconfigure a board that uses Periph and specifies digital interrupt pins (which Periph does not support), you will get slightly farther through the reconfiguration procedure before getting the same error as usual.
I recommend reviewing commit-by-commit: I think each commit should be pretty straightforward by itself. but maybe the entire PR is straightforward, too? I dunno; I'm happy to explain myself if …
=> Refactor genericlinux reconfiguration, in preparation for RSDK-2683

components/arm/arm.go, components/arm/arm_test.go
This looks simple but needed to be tested in a lot of different scenarios to make sure things were OK. Here's what we looked at:
Testing was done with a **wrapper** xArmLite around a **wrapped** xArm6 component. These have different rotation axes for some joints (specifically 2 and 4) that were originally causing a problem with getting status information in `local_robot` when moving the **wrapped** xArm6arm to good configurations. Switching to using the `ComputeOOBPosition` method works for preserving end effector pose computation when the **wrapper** arm is outside its limits. Similarly for the **wrapped** arm.
* Move a **wrapped** xArm6 to < -20.0 degrees on Joint 2, observe that `viam_server` emits errors when getting status information for the **wrapper** xArmLite arm, and now both …
=> RSDK-2645 - Fix for wrapper arm status breaking Arm RC cards when out-of-bounds

components/camera/collectors.go, services/datamanager/data_manager.go
Filed https://viam.atlassian.net/browse/RSDK-2929 as this fix is needed (and small) and adding a test for this condition is non trivial given the current structure of TestDataCaptureEnabled.
=> Add resource equality check to DataCaptureConfig.Equals

components/board/hat/pca9685/pca9685.go
The address is only 0x60 if you solder the most significant address pin; out of the box it's 0x40. 
I noticed this while helping someone on Discord, who was unable to wire up this board without specifying a non-default I2C address.
This feels like a breaking change. Is anyone relying on 0x60 being the default address? Is this even a change we're able to make at this point? I'm willing to close the PR and leave the defaults as-is, though I think this will continue to be a source of user confusion in the future if we don't change it.
I'm tagging Steve; he knows what's what with breaking changes. I didn't bother creating a Jira ticket for this, but I'm willing to do so if you want.
=> [RSDK-2940] The default I2C address of the PCA9685 board is 0x40

services/datamanager/builtin/builtin.go, services/datamanager/builtin/sync_test.go
Fix:
- sync ticker was being reset on every reconfigure which causes data manager to not sync when the sync interval is long
- updated now to ensure that the syncer is only reset when the sync config is changed
Test:
- tested locally on robot and everything is working as expected
- current tests act as unit tests for the service, further tests will be added in larger data reconfiguration integration testing
=> DATA-1419 | DATA-861 - Check sync config in reconfigure

.artifact/tree.json, services/slam/fake/data_loader.go, services/slam/fake/slam.go, services/slam/fake/slam_test.go, web/frontend/src/components/slam-2d-render.vue
This PR updates the color buckets for the SLAM 2D view based on the new probability values returned by cartographer. The new image and grayscale profile can be seen in the image below.
Below views of both the old dataset/color scheme and the new dataset/color scheme can be found. Note: the old dataset's images appear darker because prior to the probability calculations, all high probability data was being classified as 100. Now it is a gradient, this is also why the walls appear more crisp in the newer dataset
New dataset:
https://user-images.githubusercontent.com/34897732/235763093-b83bb052-380d-4df8-a135-efa4d8d4b8fe.mov
Old dataset:
https://user-images.githubusercontent.com/34897732/235764549-e289fe18-1726-4f62-b1e8-5b41d64584cc.mov
JIRA Ticket: …
=> RSDK-2939 Update SLAM 2D View Color Buckets

examples/customresources/demos/complexmodule/moduletest/module_test.go, robot/impl/local_robot.go
RSDK-2948
Moves calls to `ValidateConfig` that gather implicit dependencies to after the call to `DiffConfigs`.
This change stops running `ValidateConfig` when `Reconfigure` is called with a config identical to the current config (`Reconfigure` returns early [here](https://github.com/viamrobotics/rdk/pull/2316/files#diff-0b975da6011656cd3f2caf0435023573bdb5ac7c6a425e7917dd5cc9d6be63e4R916-R918)). Modules run in the cloud were receiving calls to `ValidateConfig` every 10 seconds to gather implicit deps even when the config hadn't changed. The use case of dynamic implicit dependencies (inconsistent return values of `ValidateConfig` from modules) is not something we wish to support at this point in time.
=> RSDK-2948 Do not call ValidateConfig with no diff in config

module/modmanager/manager.go, module/modmanager/manager_test.go, module/modmaninterface/interface.go, robot/impl/local_robot.go, robot/impl/resource_manager.go, robot/impl/resource_manager_modular_test.go, robot/impl/resource_manager_test.go, robot/robot.go, testutils/inject/robot.go
RSDK-2954
Moves the module manager to be owned by the resource manager instead of by local robot.
Currently, local robot has both a module manager object and a resource manager object. Increasingly, the module manager must interface with the resource manager and vice versa. It may be wise to have the module manager be owned by the resource manager (like the process manager). This turns the weird `MM <-> LR <-> RM` interaction into something more like `LR -> RM -> MM`.
=> RSDK-2954 Move module manager to be owned by resource manager

services/mlmodel/tflitecpu/tflite_cpu_test.go
Couldn't reproduce the test after trying on:
-  Darwin arm64
- Linux amd64
- Canon amd64 running on Linux amd64
Also, I did rebuilt tensorflowlite using [our formula](https://github.com/viamrobotics/homebrew-brews/blob/main/Formula/tensorflowlite.rb) that include a patch on the failing function.
=> RSDK-2735 Change the input of TextModel test to be deterministic

web/frontend/src/components/encoder.vue, web/frontend/src/lib/schedule.ts
This PR introduces a new util, `scheduleAsyncPoll`, which schedules a clearable timeout for an async polling function. It also introduces better practices for polling in the Encoder card:
* If a polling function is async, wait for it to entirely execute before scheduling the next poll
* Polling functions should listen for disconnection events and clear timeouts for future polls if a disconnect occurs, and resume once reconnection occurs
I'll update other components in a follow-up PR.
=> Add async cancellable scheduling function

web/frontend/src/components/slam-2d-render.vue, web/frontend/src/components/slam.vue
This PR makes it such that the 2D view of the slam map occupies the entirety of the screen on a larger monitor.
screen recording 5.4.23
=> RSDK-2959 - SLAM UI does not resize well

robot/impl/local_robot.go, robot/impl/local_robot_test.go, robot/impl/resource_manager_test.go, robot/impl/robot_reconfigure_test.go
Two parts to this. The first was simply avoiding a racey channel close. The rest is fixing up the tests themselves to avoid sleep-timing induced issues, and to allow -count > 1 (in order to catch rare races in the first place.)
=> RSDK-2958 Fix tests and races in robot/impl

components/board/digital_interrupts.go, components/board/genericlinux/board.go, components/board/genericlinux/digital_interrupts.go, components/board/genericlinux/gpio.go, components/sensor/ultrasonic/ultrasonic.go
Tried on the Orin on my desk with an ultrasonic sensor plugged in. Works great! (see below for what I used to test it)
Major changes include:
- `CreateDigitalInterrupt` returns a `ReconfigurableDigitalInterrupt` instead of a `DigitalInterrupt`. It's always returned that underlying data structure, but now it's more explicit about it.
- Renamed `sysfsBoard.reconfigureGpios` to `sysfsBoard.reconfigureInterrupts`. The interrupts have the interesting reconfiguration, and the GPIOs are just along for the ride (they're never even mentioned in the user-defined config, so they never reconfigure unless they turn into/back from interrupt pins).
- The ultrasonic sensor grabs its pins from the board every time it wants to use them, rather than grabbing them once on initialization and assuming the …
=> [RSDK-2684] Reconfigure interrupts properly on genericlinux boards

components/board/beaglebone/board.go, components/board/beaglebone/data.go, components/board/genericlinux/hw_pwm.go
There's a commit in here that sorts the beaglebone pin definitions by pin number, and then a bunch of tiny commits to make small tweaks to things. I kinda recommend reviewing commit-by-commit so you can ignore the sorting one, but reviewing lots of tiny commits could be tedious, too.
- Add definitions for pins 920, 939, 940, and 941. Standardize some of the pin names (e.g., `9_33B`-> `9_33`). Switch pin 924 to its other line: it supposedly has 2 that work, but I could only get 1 to work correctly.
- Sort the pin definitions by number
- When creating a beaglebone board component, don't use Periph for GPIO functionality! This has the added benefit that hardware PWM is now supported on 6 of the pins.
Before switching to Periph (i.e., partway through this PR, when extra pin …
=> [RSDK-2681] Support hardware PWM on beaglebone AI64

web/frontend/src/components/encoder.vue, web/frontend/src/lib/schedule.ts
This PR fixes an issue introduced when `scheduleAsyncPoll` was introduced: when using it in encoder I thought of it as a timeout function rather than an interval function, and called the scheduler each time a poll occurred. This had the effect of adding new interval polls on every poll, which created an exponentially increasing number of pollers, which eventually ate up all CPU / RAM, causing WebRTC disconnects and out-of-memory warnings.
In this PR I've fixed the issue, and renamed the function to be more similar to `setInterval`, so that no one else falls victim to this tragic fate.
=> Fix async scheduler

components/camera/register/register.go, components/camera/replaypcd/replaypcd.go, components/camera/replaypcd/replaypcd_test.go
This PR adds the skeleton code for an unimplemented replay camera with model: replaypcd.
Note: This code was previously in the replay module. Previous discussion can be found here (https://github.com/viamrobotics/replay/pull/3)
**Testing:** 
Module correctly loaded into rdk and outputted the correct error when NextPointCloud/Stream was called from the app:
**Config:**
```
{
"name": "replay",
"attributes": {},
"type": "camera",
"depends_on": [],
"model": "replay_pcd"
}
]
}
```
**Test Results:**
**JIRA Ticket:** https://viam.atlassian.net/browse/RSDK-2696
=> RSDK-2696 Add Skeleton Code for Replay Camera

components/motor/dimensionengineering/sabertooth.go, components/motor/dimensionengineering/sabertooth_test.go, components/motor/dmc4000/dmc.go, components/motor/fake/motor.go, components/motor/gpio/basic.go, components/motor/gpio/motor_encoder.go, components/motor/gpiostepper/gpiostepper.go, components/motor/i2cmotors/ezopmp.go, components/motor/roboclaw/roboclaw.go, components/motor/tmcstepper/stepper_motor_tmc.go, components/motor/ulnstepper/28byj-48.go
Now the maxRPM warning is only logged when the maxRPM of the motor is greater than 0. Additionally, the names were removed from all the motor RPM warnings
=> RSDK-2357 FIX: only log maxrpm warning when maxrpm > 0

services/vision/colordetector/color_detector.go, services/vision/colordetector/color_detector_test.go, services/vision/detectionstosegments/detections_to_3dsegments.go, services/vision/detectionstosegments/detections_to_3dsegments_test.go, services/vision/mlvision/ml_model.go, services/vision/mlvision/ml_model_test.go, services/vision/radiusclustering/radius_clustering.go, services/vision/radiusclustering/radius_clustering_test.go, services/vision/vision.go, services/vision/vision_test.go
All vision service models did not actually implement the `resource.Named` interface, and had left it nil. This caused a nil pointer de-reference whenever "Name()" was called on any vision service resource. 
Manually tested out the fixes with the QA plan for the color detector that originally found the error, and it now works.
=> RSDK-3027 - implement resource.Named for vision service models

robot/impl/local_robot.go, robot/impl/resource_manager.go
RSDK-2886 (followup)
I removed these context checks, as I thought they were unnecessary. They are not unnecessary and add extra safety (`select` selects non-deterministically and may pick a different `case` even if the context has expired).
=> RSDK-2886 Add better context checks before selects

module/modmanager/manager.go, module/modmaninterface/interface.go, resource/resource_graph.go, robot/client/client_test.go, robot/impl/local_robot.go, robot/impl/local_robot_test.go, robot/impl/resource_manager.go, robot/impl/resource_manager_modular_test.go, robot/impl/resource_manager_test.go, robot/robot.go, robot/web/web_test.go, testutils/inject/robot.go
RSDK-2876
Stops storing any `config.Config` on `localRobot`. Adds `createConfig` to the resource manager to dynamically generate a config based on the state of the manager. Stores added module and process configs in the resource manager. Updates tests.
=> RSDK-2876 Generate local robot config instead of storing

components/board/pi/impl/board.go, components/board/pi/impl/board_test.go, components/board/pi/impl/external_hardware_test.go
I've been going down a garden path of fixes and improvements, trying to get the pi boards to reconfigure themselves. Eventually, I had so many extraneous refactorings that I spun them out into this PR, and the actual pi reconfiguration will come separately. I recommend reviewing this commit-by-commit: most of them are small, self-contained changes unrelated to the commits before and after them.
- Remember to unlock the mutex if you return early
- Don't fail tests on non-pi non-x86 machines
- Move most configuration stuff out of the constructor and into a new function that the constructor calls
- Make the new function have the same function signature as `Reconfigure`, even though it currently just finishes constructing a new board and doesn't reconfigure an old one.
- If …
=> [RSDK-2691] Refactor the raspberry pi boards in anticipation of reconfiguration

robot/session_manager.go, robot/session_manager_test.go
RSDK-2796
Logs deleted session IDs as a slice of strings rather than a `map[uuid.UUID]struct{}`. Adds unrelated tests for the session manager that were missing.
Logging to app requires that all logs are convertible to proto. `uuid.UUID` cannot be converted to proto. There's only [one other place](https://github.com/viamrobotics/rdk/blob/main/operation/opid.go#L140) in RDK where we log a `uuid.UUID`, and we convert it to a string.
I added more tests for the session manager (was trying to figure out how it worked), but they do not act as a regression test for this bug fix. I'm not sure how we can easily test that all our logs are convertible to proto.
=> RSDK-2796 Do not log uuid.UUID directly

go.mod, go.sum, web/server/net_logger_test.go
This is the only place in rdk where we are using gomock and although there is value in being able to mock out specific requests to log with precision, it feels better to be consistent with how the rest of our tests work. Plus, this allows us to rely less on our knowledge about how the client/logger works.
=> remove gomock from net logger tests in favor of a mocked robot service

components/board/pi/impl/board.go, components/board/pi/impl/board_test.go
Hopefully this unblocks @chris-viam! He encountered errors about pigpio being uninitialized when changing a config on a raspberry pi. Without this change, if you start up the server and reconfigure the pi, you get errors about pigpio not being initialized. With this change, things work!
What's going on: when you change the config, you go through the reconfiguration process. The raspberry pi component is part of `resource.AlwaysRebuild`, meaning that when it gets reconfigured it just returns a special error indicating that it's safe to construct a brand new struct. The reconfiguration then constructs the new one, and closes the old one. This order is unintuitive: constructing the new one initializes pigpio, and closing the old one de-initializes it again, hence the errors Chris was seeing. …
=> Never deinitialize pigpio

components/camera/videosource/webcam.go, components/camera/videosource/webcam_e2e_test.go, testutils/vcamera/cmd/main.go, testutils/vcamera/vcamera.go
This PR adds end-to-end test for webcams. There are three files
1. **main.go** - a script to create virtual cameras that can be displayed on in app
2. **webcam_e2e_test.go** - the end-to-end tests.
3. **vcamera.go** - the builder for creating virtual cameras
I recommend reviewing them in that order which is the order of least complexity. Below is a screen recording for the test video in app. `main.go` created both cameras. 
If these test prove useful it may be worth wrapping the actual libraries rather than running bash commands for GStreamer and V4L2loopback assuming we can include them only for test dependencies. 
If I can figure out a way to install V4L2Loopback on some VM runnable by Github I'll run these tests as a Github check in PRs.
These test can only run on Linux and assumes …
=> RSDK-2100 Automated test for camera discovery service

resource/config.go, robot/impl/local_robot_test.go, robot/impl/resource_manager.go
RSDK-2876 (bug fix for original PR #2353)
Ignores non-internal, non-remote configs when generating service configs from the resource graph. Sets `ImplicitDependsOn` to `nil` after calculating dependencies for a resource with `Dependencies()`.
`localRobot.Config()` was always returning a few empty service configs and causing needless reconfiguration, as `DiffConfigs` always reported the internal services (and builtin remote services) had been "removed" in the `newConfig`. `localRobot.Config()` was also returning RDK-calculated `ImplicitDependsOn` fields (for modular and regular resources), and `DiffConfigs` always reported the `ImplicitDependsOn` field as "removed" in the `newConfig`.  This caused needless reconfiguration/potential restart of any modular resource with implicit dependencies …
=> RSDK-2876 Ignore non-internal non-remote services and implicit deps in Config

components/board/pi/impl/board.go
Thanks to @edaniels for noticing this! It is hopefully the correct way to fix the errors that https://github.com/viamrobotics/rdk/pull/2367 had been attempting to fix. With this change, every time we call `C.gpioTerminate()`, we also set `pigpioInitialized` to false. Without this change, we could get into a state where pigpio is not initialized but we mistakenly think it is, leading to trouble (we try using it and can't because it's not initialized, but we don't initialize it because we think that's already been done).
To try this out, I took my pi, made sure the RDK started up on it, and then changed the config to mention an I2C bus whose bus number was "asdf" (which is not a valid name: they must be numerical, and on a pi it's almost certainly "1"). This led to errors about invalid I2C …
=> record the state when you de-initialize pigpio

components/motor/gpio/motor_encoder.go, components/motor/gpio/motor_encoder_test.go
**Summary**
This fixes various bugs with encoded motors:
- GoFor moves in wrong direction when dirflip is true
- GoTo moves in wrong direction when dirflip is true
- SlowDownMath doesn't work correctly when RPM is negative 
Also fixed the incorrect test names in encoded motor tests since they were confusing me
**Testing**
Tested manually using encoded motor with control page.
=> RSDK-2596 - Encoded Motors Dirflip Fixes 

robot/impl/data/remote_fake.json, robot/impl/local_robot_test.go, robot/impl/resource_manager.go
RSDK-3177
Follow up to #2379. Also ignores remote components when creating a config for `localRobot.Config()`.
=> RSDK-3177 Ignore remote components in localRobot.Config

services/mlmodel/tflitecpu/tflite_cpu_test.go
The fix for the flaky test is currently in progress, while it is being fixed we are skipping it since it breaks often
=> Add a skip for TestTFLiteCPUTextModel while it is being worked on

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/audio-input.vue, web/frontend/src/components/camera/cameras-list.vue
RC camera cards are missing right and left borders in the Viam app. This does not happen when running RDK locally, and seems to be a weird Tailwind build issue.
Fix: use `border border-t-0` instead of `border-x border-b`
=> bugfix - remote control, camera card borders

doc.go
* Shows up on https://pkg.go.dev/go.viam.com/rdk#pkg-overview go docs landing page
* Some RDK overview is given at beginning of https://pkg.go.dev/go.viam.com/rdk -> could remove doc.go overview entirely?
=> remove todo comment from doc.go

components/board/pi/impl/board.go, components/board/pi/impl/pi.c, components/board/pi/impl/pi.h
Not fully tried out yet, will finish that tomorrow. but this is very close to ready! Changes include:
- When using the pigpio library to set up a digital interrupt, it's possible to have errors returned. We should check for those.
- Make a way to tear down digital interrupts that are no longer used (and check for errors here, too)
- When you close a digital interrupt, tear it down within pigpio, too
- Split the reconfiguration function, which was getting pretty large already, into smaller helpers that focus on I2C, SPI, analog readers, and digital interrupts. For everything except digital interrupts, reconfiguration involves throwing out everything old and building the new one from scratch.
- Reconfigure digital interrupts:
- For each new interrupt, if you can find an old one whose pin or …
=> [RSDK-2691] Reconfigure digital interrupts on raspberry pi boards!

.github/workflows/appimage.yml, .github/workflows/pullrequest-trusted.yml
@edaniels recent merge changed a lot of runners, but overlooked one special case with appimage testing. This fixes that (and another typo from last week.)
=> Fix AppImage test

module/modmanager/manager_test.go
The test modifies a global package variable to speed things up, but it does it at a point where it _could_ already be in use. This moves it earlier and defers a reset to the original value.
=> [RSDK-3354] Fix race in module manager test

etc/configs/fake.json
we really should be running the fake.json before merging, especially if you're gonna be changing config values.
Why `base_name` when a lot of our other drivers seems to leave `name` out? @randhid do we have guidelines around this?
=> Fix fake json

web/frontend/package.json, web/frontend/src/components/slam/index.vue
This issue was discovered when investigating RSDK-3360. Right now the displayed pose isn't actually reactive - it is not hooked up into Vue's runtime - and therefore doesn't have a guarantee for displaying the most up-to-date values. This PR fixes this by making all of the pose values part of a `$ref()`.
=> Fix reactivity for displayed pose

.github/workflows/test.yml
Buildjet has an overall concurrency limit of 32 arm64 cores. Many of our tests were waiting 15+ minutes for a 16 core runner (since only two were effectively available) negating any speed boost in normal use. This reduces things to 8 cores. Slightly slower in standalone, but should be faster in aggregate during the middle of the day.
And yes, reduces amd64 as well. It's already faster, no need for it to out-race the arm64 by an even wider margin.
=> Switch buildjet test runners from 16->8 cores

examples/customresources/demos/complexmodule/moduletest/module_test.go, module/modmanager/data/simplemoduleruncopy.sh, module/modmanager/manager_test.go, module/module_interceptors_test.go, robot/impl/local_robot_test.go, testutils/file_utils.go
Recently, newer module tests have been introduced to handle reconfiguration, and they delete and/or recreate the module binaries. Unfortunately, as multiple tests are trying to use a binary from the same location, this can cause a race condition, where a test can fail to execute a module because another test just removed it, or is in the process of recompiling it, resulting in a 'test file busy' error.
This modifies the module build helper to return a unique, temporary path on each build, so tests no longer step on each others toes.
=> [RSDK-3392] Fix module tests to use unique binary paths

components/camera/transformpipeline/pipeline.go, components/camera/transformpipeline/pipeline_test.go
Added validation function to transform pipeline to ensure that source camera is registered prior to transformation itself
=> RSDK-3094: Fix transform camera failing because of dependencies

services/vision/mlvision/ml_model.go
Change wording of info logs in mlmodel to lessen confusion and make it easier for users to find errors
=> RSDK-3095 Making mlmodel info logs less confusing

components/gantry/oneaxis/oneaxis.go, components/gantry/oneaxis/oneaxis_test.go
This change allows gantry to move away from the limit switch if it's triggered. Now the only time the gantry will stop is if the input position is past the limit switch.
=> RSDK-3293: allow gantry to move in the direction away from the limit switch

web/frontend/src/components/remote-control-cards.vue
Since RC has it's own reconnect management logic, we need to opt out of the same logic offered by the typescript SDK to avoid clobbering behavior.
=> APP-1953 Opt out of typescript SDK reconnect logic

components/board/analog_smoother.go, components/board/config.go
Ideally, we'll catch this in `Validate` and reject the config. but just in case something slips past that, we'll also have it default to 1 sample per second if someone tries to sample at 0 or below.
I haven't tried running this yet, but everything compiles, and it sure looks right to me...
edit: this fixes RSDK-3149 in addition to RSDK-3148.
=> [RSDK-3148] Don't allow sampling analog readers at a non-positive rate

components/board/genericlinux/board.go, components/board/genericlinux/digital_interrupts.go
- added struct gpioInterruptWrapperPin to wrap digital interrupts as a GPIOPin
- tested with an encoder component by reading the value of the interrupt pins while turning the encoder and ensuring they go low and high
=> [RSDK-3308] Added support for reading digital interrupt pins as input

components/motor/roboclaw/roboclaw.go
Removing AlwaysRebuild from roboclawMotor since it now has a reconfigure method.
=> rsdk-fix remove AlwaysRebuild From Roboclaw

web/frontend/README.md, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/remote-control-cards.vue, web/frontend/src/index.css, web/frontend/src/main.ts, web/frontend/src/tailwind.css, web/frontend/tsconfig.lib.json, web/frontend/vite.lib.config.ts
We are seeing conflicts in styles from what is declared in RC vs the App by tailwind. For example, we may use a class of `mt-2 sm:mt-0` in app, but once the RC is loaded by clicking on the control tab, its `mt-2` class takes priority and ignores the breakpoint styles of `sm:mt-0`. 
Instead, the RC npm package should not include the styles, and expect `tailwindcss` to be installed as a peer dependency. Furthermore, any project using the package should include its artifacts in their tailwind config `contents`. I added documentation to reflect that.
I also added a `remote-control` class to the root element in the `remote-control-cards` component. This way we can scope all of the `v-toast` override styles to the RC, and they should not affect other projects toast tyles.
=> RSDK-2914 Remove tailwind styles from main-lib, stop emit declarations for non lib files 

components/board/genericlinux/board.go, components/board/genericlinux/periph_gpio.go, components/board/genericlinux/spi.go
board.go is already too large to keep in my head all at once, and several parts of it were doing unrelated tasks. So, I pulled out the SPI- and Periph-related stuff into separate files. No changes to functionality are intended. 
I'm not convinced I've organized this properly: perhaps the `startSoftwarePWMLoop` and `softwarePWMLoop` functions should be moved from the `sysfsBoard` class into the `periphGpioPin` class or something. Similarly, I wonder if there should be some `newPeriphGpioPin` constructor-like function in the new file, rather than building the structs directly in board.go. If you've got opinions, I'd like to hear them!
I also strongly dislike that `periphGpioPin` contains a pointer to the board that owns it, and uses the state from the board. but changing that is a much …
=> [RSDK-3216] Split more of the genericlinux board.go into separate files

.artifact/tree.json, services/slam/fake/slam_test.go
Generate the new dataset by flipping pointclouds across y-axis and add it to fake SLAM
Tested by running through the fake SLAM dataset, shown oriented correctly.
https://viam.atlassian.net/browse/RSDK-3120?atlOrigin=eyJpIjoiN2U2ODgwYmJiMDE4NGJiMzgwMzkwMmJlNmU0NGY3ZmYiLCJwIjoiaiJ9
Separated datasets available here:
https://drive.google.com/drive/folders/11yEWlxnbHSaij14stRY09d9gw2CkscCt?usp=share_link
=> [RSDK-3120] Flip fake SLAM dataset

components/gantry/oneaxis/oneaxis.go, components/gantry/oneaxis/oneaxis_test.go
Currently there are two functions for homing with limit switches, one for one limit switch and one for two limit switches. This PR combines them into one function called `homeLimSwitch` that internally makes the necessary distinctions between one or two limit switches.
=> RSDK-3260: combine home one and two limit switch logic

web/frontend/src/api/movement-sensor.ts, web/frontend/src/components/arm/index.svelte, web/frontend/src/components/audio-input/index.svelte, web/frontend/src/components/base.vue, web/frontend/src/components/camera/index.svelte, web/frontend/src/components/motor/index.svelte, web/frontend/src/components/movement-sensor/index.svelte, web/frontend/src/components/operations-sessions/index.svelte, web/frontend/src/components/remote-control-cards.vue, web/frontend/src/components/servo/index.svelte, web/frontend/src/lib/error.ts
This PR migrates `arm.vue` to Svelte and adds a few optimizations to all migrated svelte components:
* Wraps them in an improved `<Collapse>` which does not render any DOM elements until opened. Doing this has so far reduced the amount of elements rendered at app startup from ~1,600 to ~800 for the default fake config. We'll be able to further reduce this when all components are migrated and these optimizations will be backported to PRIME when the migration is complete. This optimization so far raised us about 5 points in lighthouse's performance tab (45/100).
* If a svelte component polls for updates, polling only starts once a `<Collapse>` has been opened for that specific component.
=> Migrate arm to Svelte and avoid unnecessary DOM element creation / network requests

services/slam/fake/data_loader.go, services/slam/fake/slam_test.go
https://viam.atlassian.net/browse/RSDK-3341
- Reduce fake.maxDataCount during fake slam integration test
- Delete skip
=> [RSDK-3341] shorten-TestFakeSLAMStateful-remove-skip

components/encoder/ams/ams_as5048.go, components/encoder/incremental/incremental_encoder.go, components/encoder/single/single_encoder.go
Tried on a Jetson Orin Nano (not the Orin AGX! The new, smaller one). Everything seems to work, though I was unable to reproduce the original problem behavior. I was able to set up an incremental encoder, then swap the two pins so it needs to go through Reconfiguration, and things continued to work afterwards (and the encoder even kept its position, rather than resetting to 0 during reconfiguration! On the main branch, the position resets to 0 during reconfiguration). 
I'm a little surprised that you need to create the context twice, but it does make other things easier. During reconfiguration, we shut down the background goroutine if any is running by cancelling the context, then start up a new one with a new context after we're done reconfiguring. We call `Reconfigure` from within …
=> [RSDK-3496] Use a background context for the background goroutine

module/modmanager/manager.go, module/modmanager/manager_test.go, robot/impl/resource_manager.go, robot/impl/resource_manager_modular_test.go
tl;dr for the bug is that module resources don't get Close()ed on shutdown.
This sets up a deferred close pattern for module removal, such that a "Remove" request to a module leaves the module running until its last resource is properly closed, instead of terminating the module process right away.
Additionally, ordering of calls in resource manager's Close() is corrected, so that the module manager is closed last, after resources are removed.
Lastly, some small cleanup around locking (and variable naming) in the module manager is done.
=> [RSDK-3537] Fix module close/removal flow

services/navigation/builtin/builtin.go, services/navigation/builtin/builtin_test.go, services/navigation/navigation.go
RSDK-2923 was merged prematurely; we would like to hide this functionality until we are ready to make the switch to an end to end system that uses the Motion service.  This PR reverts Nav service functionality to where it was previous to this, while keeping the code around where it can be accessed through the `ModeExperimental` mode
=> RDK-3571 hide new nav service internals

components/board/genericlinux/data.go, components/board/ti/board.go, components/board/ti/data.go, utils/hardware_info.go
One sneaky thing with this is that the PWM chips are not enabled by default, and I haven't figured out how to turn them on yet. This also happens on the raspberry pi's (did you know it's got proper hardware PWMs on a couple pins in addition to the DMA-based stuff on all the other pins!? I didn't until earlier this week), which makes me suspect there are lots of boards that don't enable their PWM chips by default. So, I made that optional: if we can't find the PWM chips we're expecting, we log that fact and then continue on.
Also, when getting the compatible devices from the device tree, we read a list of items separated by null bytes, but need to remember to remove the null byte at the very end (so we don't decide we match on the empty string). 
Tried on a TI board: without this change, …
=> [RSDK-2782] Move the TI boards off of Periph

web/frontend/README.md
Font icons were missing in local development for me because the asset wasn't copied to the static folder. I updated the documentation to explain that step and hopefully prevent others from running into the same situation I did.
=> APP-2024 Update docs for running RC for local development.

.artifact/tree.json, services/mlmodel/tflitecpu/tflite_cpu_test.go
**Change to a better BERT model**
This new model still include a Gather() function, but doesn't fail
**Manual tests**
Tested on MacOS with:
- built from source libtensorflowlite_c
- with brew with the default formula for tensorflowltite 2.12
- with [our formula](https://github.com/viamrobotics/homebrew-brews/blob/main/Formula/tensorflowlite.rb)
**Follow-up PR** is removing the older BERT model from artifacts (@kharijarrett :) )
=> RSDK-2735 change BERT model

module/modmanager/manager.go, robot/impl/local_robot_test.go
RSDK-3537
Followup to #2486 . We were missing the case where a module is removed that handles no resources.
=> RSDK-3537 Immediately remove modules with no handled resources

components/board/genericlinux/data.go
- looks in /sys/class/pwm and checks symlinks to find the pwm chip listed in the pinDefs
- eliminates need to specifically name which directories in /sys/devices to look under
=> [RSDK-3563] Use symlinks in /sys/class/pwm to find pwm chips

components/motor/roboclaw/roboclaw.go
**Summary**
This is a breaking change to change the number_of_motors roboclaw config field to motor_channel to be more clear. Previous improvements to the roboclaw driver are [here](https://github.com/viamrobotics/rdk/commit/1846d0f6559f3971d38c6b3960ffc61f750bcc52).
=> RSDK-3270 Change roboclaw config field number of motors to motor channel

components/gantry/multiaxis/multiaxis.go, components/gantry/multiaxis/multiaxis_test.go, components/gantry/register/register.go, components/gantry/singleaxis/singleaxis.go, components/gantry/singleaxis/singleaxis_test.go
1. add move_simultaneously parameter in multi axis config
2. remove Axis from one-axis config
3. rename one-axis → single-axis
4. only allow gantry to use position reporting motors as dependencies
5. rename multiaxis → multi-axis
=> RSDK-3645: gantry scope config changes

components/encoder/ams/ams_as5048_test.go
fixes test flakiness. Seems like having two WaitForAssertion calls in the same test was causing issues.
=> RSDK-3609 TestAMSEncoderReset flaky test fix

services/datamanager/builtin/capture_test.go, services/datamanager/builtin/sync_test.go
This PR adds a test to verify that when a robot resource changes but all other fields in the DataCaptureConfig stays the same, the data manager captures data using the new collector instead of the old one.
Ticket: https://viam.atlassian.net/browse/RSDK-2929
=> RSDK-2929 Add data manager test to verify collector restarts when a resource changes

.github/workflows/test.yml, Makefile, etc/e2e.sh
This updates `e2e.sh` to kill zombie child processes at the end of the script.
Killing processes using `pkill` is not allowed in CI without `sudo`. The target does not use `sudo` so someone running it locally does not require the user's password. Instead, the flag `-k` is used in the Github Workflow (and passed down in the makefile target definition) to avoid calling `pkill`.
The default to kill the child process must first be merged as false so the workflow still passes. I'll follow up this PR with another PR to flip the default to true.
This change was [validated](https://github.com/viamrobotics/rdk/pull/2553/checks) by using an [empty commit/PR](https://github.com/viamrobotics/rdk/pull/2553) against the branch. I'm currently [documenting the …
=> APP-2044 Kill test-e2e child process on exit except in Github Workflow

components/gantry/singleaxis/singleaxis.go, components/gantry/singleaxis/singleaxis_test.go
This PR implements a background loop that is constantly checking if a limit switch is hit. If so, the motor will move in the opposite direction until the limit switch is no longer hit. This works for all types of movement so the motor move commands will now stopped if a limit switch is hit (in addition to the gantry move commands). I am not 100% confident on the all of the `context` stuff so would appreciate a close look at the structure of that specifically.
RSDK-3533 is also addressed in this PR
=> RSDK-3207: change the way to check when gantry limit switches are hit

robot/impl/local_robot_test.go, services/mlmodel/tflitecpu/tflite_cpu.go, services/mlmodel/tflitecpu/tflite_cpu_test.go, services/vision/mlvision/ml_model_test.go
There's a bug now because labelpath was originally written as a pointer to a string and not just a string. It's also supposed to be optional so when we walk the config and it gets visited and it's nil, it ends up panicking with a nil pointer dereference.  I could have hacked around it but I think the better fix is to make the attribute a direct string like every other one.
Tested on a Mac and I'm able to get my bounding boxes with numbers instead of classes. :)
=> RSDK-3684 - Make LabelPath Optional Again

services/datamanager/datasync/upload_data_capture_file.go
Session ID is neither populated in RDK nor used in app, so remove. This is the only place it's used in RDK.
=> DATA-1524 - Remove unused session ID from upload metadata

referenceframe/frame_system.go
a hardware test was done to validate this solution.
cfg for the robot:
```
{
"model": "fake",
"arm-model": "ur5e"
},
"depends_on": [],
"name": "a",
"type": "arm",
"frame": {
"orientation": {
"value": {
"th": 0,
"x": 0,
"y": 0,
"z": 1
},
"type": "ov_degrees"
},
"parent": "world",
"translation": {
"x": 0,
"y": 0,
"z": 0
}
}
},
{
"name": "g",
"type": "gripper",
"model": "fake",
"attributes": {},
"depends_on": [],
"frame": {
"parent": "world",
"translation": {
"x": 0,
"y": 0,
"z": 40
},
"orientation": {
"type": "ov_degrees",
"value": {
"x": 0,
"y": 0,
"z": 1,
"th": 0
}
},
"geometry": {
"x": 1,
"y": 1,
"z": 1,
"translation": {
"x": 0,
"y": 0,
"z": 0
}
}
}
}
]
```
script used (golang):
```
// Access myArm
myArmComponent, _ := arm.FromRobot(robot, "a")
// move to …
```
=> RDSK-3752 - Configured gripper pose gets doubled

cli/data.go, components/camera/replaypcd/replaypcd.go, components/camera/replaypcd/replaypcd_utils_test.go
Pulled these changes out of https://github.com/viamrobotics/rdk/pull/2591. Switch use of deprecated FileIDs in BinaryDataByIDs to BinaryIDs.
Tested CLI locally and ran replaypcd tests.
=> RSDK-3795 - Switch from deprecated file IDs to binary IDs

services/navigation/builtin/builtin.go
Ticket: https://viam.atlassian.net/browse/RSDK-3299
The ticket above asks for verification that the navigation service continues to the next waypoint when `MoveOnGlobe` errors out. This seems to be the case since the returned error from `MoveOnGlobe` is passed through `navOnce` to [this log statement](https://github.com/viamrobotics/rdk/blob/87f32df5ab71fee742c0237b8b9fdcaf7ac68bab/services/navigation/builtin/builtin.go#L433), after which we continue processing the next waypoint.
This PR adds more information to the log statement to clarify that we're skipping the waypoint.
=> RSDK-3299 - Clarify navigation behavior in log statement when MoveOnGlobe errors out

etc/code-samples-action.py
The code samples refactor changed our file format for adding code samples. This broke a script that warns users about breaking code samples. This fix adjusts that script to correctly get the component and function names
=> pull function name out of dict correctly

components/motor/dimensionengineering/sabertooth.go, components/motor/dimensionengineering/sabertooth_test.go, components/motor/dmc4000/dmc.go, components/motor/dmc4000/dmc4000_test.go, components/motor/errors.go, components/motor/fake/motor.go, components/motor/fake/motor_test.go, components/motor/gpio/basic.go, components/motor/gpio/motor_encoder.go, components/motor/gpiostepper/gpiostepper.go, components/motor/i2cmotors/ezopmp.go, components/motor/motor.go, components/motor/motor_test.go, components/motor/roboclaw/roboclaw.go, components/motor/tmcstepper/stepper_motor_tmc.go, components/motor/tmcstepper/stepper_motor_tmc_test.go, testutils/inject/motor.go
This makes the motor interface more uniform with our Motor API, and removes an intermediate interface and unimplemented methods from many motor drivers. 
Tested on a motor with a single encoder to verify `motor_encoder.go` does not show any regressions, server started and stopped cleanly and APIs functioned as expected from RC card.
=> Remove LocalMotor and GoTillStop

components/board/genericlinux/board.go, components/board/genericlinux/i2c.go
@biotinker wanted to use this code from a modular component outside the genericlinux package. So, now it's available!
Everything compiles fine, and the ADXL345 accelerometer can still be used from a Jetson Orin Nano.
=> [RSDK-3608] Make the genericlinux I2C classes public

components/gantry/singleaxis/singleaxis.go, components/gantry/singleaxis/singleaxis_test.go
The initial changes in this PR successfully implement homing as a background coroutine, however this meant all axes would home at once, which is not what we want. The solution is to remove homing from construction/reconfiguration, and add logs and errors that inform users they must run Home before they can use MoveToPosition
=> RSDK-3539: Make the gantry homing sequence asynchronous to the constructor

services/vision/obstacledistance/obstacle_distance.go, services/vision/obstacledistance/obstacle_distance_test.go, services/vision/register/register.go
Add new vision model, for taking readings from a camera (probably an underlying sensor) and returning it as well formatted vision object.
For documentation purposes please pay special attention to the following error:
`obstacles_distance expects only one point in the point cloud from the camera. Underlying camera generates more than 1 point in its point cloud`
This just means that clouds from NextPointCloud should only be returning a singular point in their cloud, because it's supposed to be just one reading from an ultrasonic sensor or something of the sort, should just be one value.
=> [RSDK-3649] Create the obstacles_distance vision model

components/movementsensor/client.go
This is not true. Calling readings from the movement sensor client calls the interface method, which in turn calls each API. 
Test with remotes just to find any bug(s)
=> Remove errant comment about movement sensor Readings not going over the network

components/arm/client.go
While trying to debug modular resources and creating a new client from the connection, it was super helpful to have the error message as part of the logs. The error message should be available for easy debugging.
=> print out error message

examples/customresources/demos/complexmodule/moduletest/module_test.go, module/module_interceptors_test.go, web/server/entrypoint_test.go
@dgottlieb found that tests are flaky on slow machines at times, as they attempt to build viam-server from scratch in the same process as running it, which leaves the connection timeout ticking. In correcting that, I also found a race condition where two tests (in separate packages) could both attempt to build at the same time, and this can cause problems.
This uses the module build helper to build viam-server itself, and skips the frontend entirely (as it's not needed for these tests.) It builds to temporary locations, so won't interfere with later tests or leave cruft behind.
=> Fix viam-server build/race issues in tests

web/frontend/package.json, web/frontend/src/components/slam/2d-renderer.svelte, web/frontend/src/components/slam/motion-path.svelte, web/frontend/src/lib/components/dropzone.svelte
This is a bit of a power-user feature requested by motion team for debugging. Currently there's no API for returning motion planning paths to overlay on SLAM maps, and this provides a good debugging solution in the interim. Users can now drop text files on the slam map, and if they're populated with x,y positions then a motion path will show up. Most users won't ever discover this. Maybe in the near future we'll hook this up to an API.
https://github.com/viamrobotics/rdk/assets/103450731/85166f1d-cb01-4261-81ce-445fe2572594
cc @jeremyrhyde @nicksanford Just so the SLAM team knows about this feature as well.
=> Add drag-n-drop path visualization to SLAM 2d map.

services/datamanager/builtin/builtin.go, services/slam/collector.go, services/slam/slam.go
This implements `GetPosition` collector to allow for us to use DataCapture with SLAM endpoints
You can use this config with the command `ENV=development go run web/cmd/server/main.go -debug -config ~/scripts/rdk-slam-local.json` to test it out. You'll see the data from a fake-slam component being loaded into the directory `~/.viam/capture/rdk:sensor:slam/fake-slam/GetPosition`. We will add subsequent tests in [DATA-1668](https://viam.atlassian.net/browse/DATA-1668?atlOrigin=eyJpIjoiMTIzZTcxOWY3ZjJmNDU5YjgzNzNhNmIyZTQ3YzU5MDUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
```
{
"services": [
{
"type": "data_manager",
"capture_dir": "",
"sync_disabled": true,
"tags": [],
"sync_interval_mins": 0.1
},
"name": "Data-Management-Service"
},
{
"name": "fake-slam",
"type": "slam",
"model": …
```
=> DATA-1646 - Define and register collector for GetPosition

components/gantry/singleaxis/singleaxis.go, components/gantry/singleaxis/singleaxis_test.go
This PR adds a check during homing to see if the wrong limit switch is hit. If so, the gantry stops and errors so that it's no longer possible to go past a limit switch during homing. Additionally, the start position after homing is now 50% of the length of the axis with both one and two limit switches.
=> RSDK-3738: [Gantry] Order of limit pins is significant

components/gantry/singleaxis/singleaxis.go
This PR fixes the data race in the single axis `moveAway` function
=> RSDK-4015: flaky test in components/gantry/singleaxis, times out after 10 minutes

components/base/wheeled/wheeled_base.go
This PR fixes runAll for case with 4 motors. Before, only one motor on the left and one motor on the right would receive the commands, but now all motors will move in parallel.
=> RSDK-4048: Verify that RunInParallel can run multiple functions at once

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/remote-control-cards.svelte, web/frontend/src/lib/components/robot-client.svelte, web/frontend/src/main-lib.ts
createRcApp was given an incorrect body when we converted it to Svelte: props was merged into its config rather than being a top level property. This PR fixes that.
=> Fix createRcApp function in library mode

components/encoder/incremental/incremental_encoder.go, components/encoder/single/single_encoder.go, components/motor/gpio/motor_encoder_test.go
Make `CancelCtx` private (now `cancelCtx`) for encoders and update tests accordingly.
=> RSDK-2672: tests using Incremental/Single encoder should use constructor, not initialization

module/modmanager/manager.go, module/modmanager/manager_test.go, module/testmodule/fakemodule.sh, resource/errors.go, robot/impl/local_robot.go, robot/impl/local_robot_test.go, robot/impl/resource_manager.go, robot/impl/robot_reconfigure_test.go, utils/env.go
RSDK-3329
RSDK-4070
Only restarts modules in the OUE handler when the `handles` field has been set on the module (the module responded to a ready request and returned its handler map). Changes hard-coded 30 second listen/ready timeouts to be 60 second defaults that can overridden with `VIAM_RESOURCE_CONFIGURATION_TIMEOUT` variable). Adds a test that immediate crash of a module does not result in an attempted restart.
=> RSDK-3329, RSDK-4070 - Do not restart modules that crash before ready and respect resource configuration timeout

components/camera/replaypcd/replaypcd.go, components/camera/replaypcd/replaypcd_test.go, components/camera/replaypcd/replaypcd_utils_test.go
We are matching on a string in carto code and want to match on a var so that the strings do not need to be kept in sync. This error needs to be public so we can access it there
=> RSDK-4074 - make errEndOfDataset public

components/board/fake/board.go, components/motor/gpiostepper/gpiostepper.go, components/motor/gpiostepper/gpiostepper_test.go
Functional changes to enable pins (done as a fly by):
1. pins are set to proper disable values at on initialization
2. enable is only done once on GoFor instead of on every step. Functionally the same, but removes an unnecessary pin on/off cycle.
3. Both high and low pins are supported in `enable()`. Previously, config validation allowed both but `enable()` respected one.
Test changes:
1. Lots more config validation tests
2. All tests are hermetic now
3. More explicit testing for high/low pins
4. Explicit testing for board pins
5. Eliminated many time-based tests and shortened their runtimes
Fake board's pin getter/setters now have a mutex
Tested with a NEMA17 motor on a A4988 driver
=> RSDK-2911: GPIO Stepper motor driver tweaks and test improvements

web/frontend/src/components/slam/motion-path.svelte
This PR includes a small state update fix for when users drag n' drop multiple files to visualize paths. Dropping files after a previous drop would fail to trigger a state change. Now it works!
=> Fix state updates for motion path visualization when multiple files are dropped

components/board/customlinux/board_nonlinux.go
RSDK-3395
Adds a missing package comment from https://github.com/viamrobotics/rdk/pull/2613.
Without this comment, lint fails on MacOS (or any other non-linux OS).
=> RSDK-3395 Add missing package comment

module/modmanager/manager.go, robot/impl/local_robot.go, robot/impl/local_robot_test.go
Adds some debug logs in the module manager for which resources are actually getting registered from modules (helpful when your WIP module is not returning the correct handler map). Updates confusing "unknown resource type" error message in `local_robot` (the "and/or", in particular, made it seem like APIs and models were registered as separate things).
(credit to @zaporter-work for the idea on better messaging here).
=> Add better logs for module resource registration

config/reader.go, robot/packages/cloud_package_manager.go, robot/packages/testutils/fake_package_server.go
Ticket: https://viam.atlassian.net/browse/APP-2115
This PR:
- Expands on package logic to support preserving the permissions of the original tarball (useful for modules).
- Fixes a bug with single-file tarballs in a subdirectory
- Adds the platform field to the agent info
=> APP-2115 - cloud_package_manager improvements

components/input/client_test.go, components/input/server_test.go, components/posetracker/client_test.go, components/posetracker/server_test.go, components/sensor/client_test.go, components/sensor/server_test.go
This PR checks against error variables in the `sensor` client and server tests in addition to checking if the error is nil or not. Since the changes were small, this PR also covers RSDK-3505 (same thing but for `posetracker` component) and RSDK-3506 (same thing but for `input` component)
=> RSDK-3504: Review sensor server and client tests

services/motion/builtin/builtin_test.go
I just did a mechanical "refactor" so we can give each parallel test its own copy of variables to write to, avoiding the (testing only) data race. I felt that coming up with a more thoughtful way to manage the environment (compared to the new function that has 4 return values) was going to be more time consuming.
=> RSDK-4158: Create separate environments for parallel motion planning tests.

components/encoder/single/single_encoder.go
revert single encoder change to continue to double counting ticks until we can determine if this is the correct solution
=> REVERT RSDK-3975

components/arm/arm.go, components/arm/client_test.go, components/arm/server_test.go, components/base/client_test.go, components/base/server_test.go, components/board/client_test.go, components/board/server_test.go, components/camera/client_test.go, components/camera/server_test.go
This PR checks against error variables in the `board` client and server tests in addition to checking if the error is nil or not. Since the changes were small, this PR also covers RSDK-3511 (same thing but for `base` component), RSDK-3513 (same thing but for `arm` component), and RSDK-3517 (same thing but for `camera` component)
=> RSDK-3510: review board server and client tests

components/movementsensor/movementsensor.go
Fixes panic if position is invalid. All other collector methods check the error first before wrapping or accessing the returned value.
=> DATA-fix - Check that collector error is non-nil if not returning directly

components/gantry/client_test.go, components/gantry/server_test.go, components/generic/client_test.go, components/generic/server_test.go, components/gripper/client_test.go, components/gripper/gripper.go, components/gripper/server_test.go
This PR checks against error variables in the `gripper` client and server tests in addition to checking if the error is nil or not. Since the changes were small, this PR also covers RSDK-3508 (same thing but for `gantry` component) and RSDK-3512 (same thing but for `generic` component)
=> RSDK-3507: Review gripper server and client tests

resource/resource_registry.go, resource/resource_registry_test.go
Provide a starting point for more structured dependency reporting.
=> RSDK-4156: Make the dependency error string less painful.

module/modmanager/manager.go, module/testmodule/main.go, robot/impl/local_robot_test.go
APP-2099
Deregisters resources more consistently for crashed modules when attempting a restart. Modifies existing test to ensure crash and restart will deregister all of crashed module's resources. Also adds a test to ensure that implicit dependencies can be used across modules (complexmodule's `mybase` can depend upon new `rdk:test:motor` models served by testmodule).
=> APP-2099 Test implicit deps across modules and deregister crash resources

components/camera/videosource/static.go, components/camera/videosource/static_test.go
x264 requires the dimensions of the static image to be even. This was breaking streaming from a static image source when it had odd dimensions. This PR handles the case where the dimensions are odd by cropping the image by one pixel along each odd dimension. The cropped image is then stored in memory rather than read from disk as it was before.
=> [RSDK-4032] image file as camera does not work with given png

services/slam/fake/slam.go, services/slam/fake/slam_test.go, web/frontend/src/components/slam/index.svelte, web/frontend/tsconfig.json
The current granularity of the comparison between the most recent and previous map timestamps is on the order of seconds, which means that any users who presses the map refresh more than once in the same second will inadvertently induce localizing mode. 
This PR reduces the granularity to nanosecond level. 
It also changes the logic used in fake slam to determine whether the session is in localizing or mapping mode. Instead of updating the timestamp in the GetPointCloud function when not in localizing, the timestamp will be updated within getLatestMapInfo. A similar change will be made to viam-cartographer.
=> RSDK-4193: New logic for GetLatestMapInfo

services/motion/builtin/builtin_test.go
Data race was caused by a shared logger between tests running in parallel. Change MoveOnMap tests which run in parallel to not share the same logger and other structures.
=> RSDK-4238: Fix data race in MoveOnMap

components/board/genericlinux/hw_pwm.go
Tried on an Odroid C4: without this, the kernel spews a bunch of errors and the whole process locks up (in a way that cannot be quit with control-C or backgrounded with control-Z, since it's stuck in kernelspace). With this, hardware PWM works normally.
I strongly dislike sleeping to avoid race conditions, but this one isn't easily fixable without a sleep, since it has to do with how quickly things are happening in kernel space and we don't have control over which kernel our users are running.
Should we make this configurable, so that non-Odroid users don't need to sleep? Part of me says "yes, that's the code that will run most efficiently," and part of me says "no, adding extra tunable features just makes stuff more complicated, and nobody will notice a spare microsecond when turning PWM …
=> [RSDK-4296] sleep to avoid race condition in odroid's sysfs implementation

components/camera/client.go, rimage/transform/distorter.go
Distortion Models with name "" no longer cause a GRPC error that says, "no such distortion model"
=> RSDK-4342 Fix Camera Client GetProperties error on empty Distortion model

components/motor/gpiostepper/gpiostepper.go
2 fixes: 1. goroutine started with a new cancellable background context. 2. motor names in logs and errors fixed.
Tested with GoTo and GoFor. Tested that reconfigs terminate and restart the worker routine.
=> RSDK-4336: gpiostepper thread in a waitgroup

cli/viam/main.go
add `viam version` and `viam -debug version` to viam cli
```sh
~/repo/rdk$ go install -ldflags="-X go.viam.com/rdk/config.Version=v1.2.3" ./cli/viam && viam version
version v1.2.3 git=46a090d5+ api=v0.1.164
~/repo/rdk$ go install ./cli/viam && viam version
version (dev) git=46a090d5+ api=v0.1.164
```
- built-in BuildInfo has a `.Main.Version` -- I think this works when you do a remote build (i.e. reference a package path), but not local. depending on how CI ends up working for this, we may be able to replace ldflags with info.Main.Version
- there is also `go:embed` but it requires a file on disk
=> RSDK-4145 cli version flag

cli/auth.go, cli/client.go, cli/data.go, cli/module_registry.go, cli/print.go, cli/viam/main.go, go.mod
RSDK-4076
Adds colored `Infof`, `Warningf` and `Errorf` print functions. Prints errors to stderr and exits instead of fatally logging them. Elaborates on/fixes typos for existing errors messages. Lowercases all error messages and removes the term "error", as the fact that it's an error will be clear in eventual output. 
The following code in an `Action`:
```go
fmt.Fprintf(c.App.Writer, "a regular message\n")
rdkcli.Infof(c.App.Writer, "an info messsage")
rdkcli.Warningf(c.App.Writer, "a warning messsage")
rdkcli.Errorf(c.App.ErrWriter, "an error messsage")
```
Results in:
and an exit status of 1.
=> RSDK-4076 Better colors and messages for CLI

components/powersensor/collectors.go, components/powersensor/fake/powersensor.go, components/powersensor/powersensor.go, components/powersensor/register/register.go, components/register/all.go, etc/configs/fake.json, web/server/entrypoint_test.go
Adds collectors to capture voltage, current and power on the powersensor component. 
Tested with fake power sensor and confirmed it was capturing data for all 3 functions.
=> RSDK-4246 Add collectors to power sensor

components/board/customlinux/board.go, components/board/genericlinux/board.go, components/board/genericlinux/config.go
With this in place, we only have a single underlying config struct for everything, and we only go through a single reconfiguration process for all of these boards. The next step after this will be to make that reconfiguration actually update the pin definitions on boards whose pin definitions have changed.
Major steps include:
- Create a new type, `UnderlyingConfig`, which is what "really" gets used in all the boards that use genericlinux stuff. It contains every field that any of these boards could have (i2cs, spis, analogs, digital interrupts, and pin definitions)
- Create a new function type, `ConfigConverter`, which turns whatever config the user thinks this component uses into an `UnderlyingConfig`.
- Make two `ConfigConverter`s: `ConstPinDefs` generates a `ConfigConverter` with a …
=> Preliminary work on RSDK-4092: get a single config for genericlinux and customlinux

cli/client.go
RSDK-4377
This seems to fix the double input CLI shell issue on my Ubuntu x86 linux laptop.
=> RSDK-4377 Set raw and -echo for CLI shell service

services/navigation/builtin/builtin_test.go, services/navigation/store.go
This fixes at least three different lurking race conditions.
First, the "MoveOnGlobe error results in skipping the current waypoint" was failing to cancel the context with which it manually started `startWaypoint`, such that it would pick up the subsequent test's waypoints, and leave that test's `SetMode` with no way to stop it.
Second, the "Calling RemoveWaypoint on the waypoint in progress cancels current MoveOnGlobe call" was racing to see if its own `startWaypoints` loop would actually manage to start the intended waypoint before it removed it.
Finally, memory stores were not properly handling cancelled contexts, resulting in a variety of really strange behavior.
The interplay of contexts and functions here, especially in the test suite, is complex and fragile and fairly difficult to …
=> Fix race conditions in nav service tests

components/board/genericlinux/board.go, components/board/genericlinux/board_test.go, components/board/genericlinux/digital_interrupts.go, components/board/genericlinux/gpio.go
and while I was at it, I noticed that every GPIO pin and digital interrupt was storing a pointer to the entire board, when all it really needed was a pointer to the `sync.WaitGroup` within the board. So, I cleaned that up, too. 
Each commit should be self-contained, though all 3 combined are hopefully straightforward, too. 
Thanks to @gvaradarajan for suggesting the name! Now, within this package it's just `Board`, which should be straightforward, and in other packages it's `genericlinux.Board`, which is what we've already been calling it. 
I haven't yet tried this out on a board, but I don't anticipate any problems and will make sure things work correctly before I merge. but in the meantime, I think this is ready for review.
=> [RSDK-3951] Rename SysfsBoard

.github/workflows/cli.yml, .github/workflows/main.yml, .github/workflows/stable.yml, Makefile
- Add workflows/cli.yml, which saves a pre-built CLI in GCP
- this copies most of the behavior in staticbuild / appimage
bucket contents after first run (the ones that have the branch name, cli-build-poc-2, would normally only be created in a tag / release context i.e. from stable.yml):
```sh
wget https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-latest-linux-amd64 \
&& chmod +x viam-cli-latest-linux-amd64 \
&& ./viam-cli-latest-linux-amd64 version
```
(change linux-amd64 to darwin-amd64 on intel mac, or darwin-arm64 on apple silicon)
- 'latest' build doesn't depend on tests (because the CLI doesn't have tests), the 'stable' build does (because we don't want to do a release until everything is working)
=> RSDK-4373 poc for CLI build

components/camera/camera.go, components/camera/camera_test.go, components/camera/client.go, components/camera/client_test.go, components/camera/replaypcd/replaypcd.go, components/camera/server.go, components/camera/server_test.go, components/camera/videosource/webcam.go, resource/response_metadata.go, resource/response_metadata_test.go, testutils/inject/camera.go
- Creates a new resource struct called `ResponseMetadata` to match the proto message.
- Creates a new struct called NamedImage so that the client/server camera code can successfully pass through the SourceName field for the get_images method
=> Rsdk 4095: Edit the camera interface to match new get_images proto

motionplan/nearestNeighbor.go, motionplan/nearestNeighbor_test.go
To start: I didn't see anything wrong with the concurrency control of how the parallel nearest neighbor code worked. But it did rely on an extra moving piece (the `ready` flag which came with its own mutex).
So I don't think I'm actually fixing anything, but figured I'd publish my thoughts/suggestions in PR format, and if we want to accept them (and cross our fingers), that's great.
=> RSDK-4430: Idiomize map-reduce used in motionplan nearest neighbor algorithm.

web/frontend/package-lock.json, web/frontend/package.json
We want to publish the RC to unblock users hitting https://viam.atlassian.net/browse/RSDK-4451 in the app. This PR bumps the version of RC for publication with the included fix from: https://github.com/viamrobotics/rdk/pull/2772
This code was tested on a bot using the app image from the above PR.
=> Bump RC for app hotfix

spatialmath/quat_test.go, spatialmath/quaternion.go
Got around to writing more tests with the proposed fix. There were discrepancies in amd64 and arm64 and some failing cases on both - the "vanilla" case isn't well-named since it produces near zero trigonometric product.
Things discovered:
- There is always a discrepancy between the two conversion functions, very often numerical, and is handled by the 1e-6 epsilon comparison in the test.
- The happy clamping factor seems to be 1e-12 rather than 1e-16 in `quaternion.go`.  Right now, two tests are failing because it is finding equivalent angles and trying to compare them in one or more axes.
- Should we edit the tests and the conversion function further to prefer 0 to Pi results? I'm indifferent here - I feel like functionally, we'll be going one way (quaternion -> euler, or quaternion -> …
=> RSDK-2010 Euler fix

config/config.go, config/config_test.go, config/proto_conversions.go
1. slam_map as a type that rdk looks for in config.go
2. add test for slam map case
3. add packagespb.PackageType_PACKAGE_TYPE_SLAM_MAP 
ran viam server with this config:
```
{
"packages": [
{
"name": "rsdk-2191",
"type": "slam_map",
"version": "1691788595",
"package": "a848d8aa-c258-4492-9ca6-90c6d7b78308/rsdk-2191"
}
],
"components": []
}
```
and saw the pbstream appear in the .viam directory of my machine
=> RSDK-4429 - add slam map package type to RDK

components/camera/replaypcd/replaypcd.go, components/camera/replaypcd/replaypcd_test.go, components/camera/replaypcd/replaypcd_utils_test.go
This PR implements the Properties function for the `replaypcd` component as well as updates the config to include `organization_id` and `location_id` as described in the scope doc for IMU integration for replay movement sensors.
**JIRA Ticket:** https://viam.atlassian.net/browse/RSDK-4306
=> RSDK-4306 Update Propertiesfor ReplayPCD

components/arm/universalrobots/ur.go, components/arm/universalrobots/ur5e_test.go
This is a potential solution for the `TestArmReconnection` flaky test. Not sure if this changes the test too much to the point where it's not accomplishing what was originally intended.
=> RSDK-2261: TestArmReconnection flaky

robot/impl/local_robot.go, robot/impl/resource_manager.go, robot/impl/robot_reconfigure_test.go
Adds waitgroup to local robot for tracking reconfigure threads. This allows us to delay completing a test until all background threads are complete, thus eliminating a class of race condition risks.
=> RSDK-4469 - add reconfigure waitgroup

module/modmanager/manager.go, module/modmanager/manager_test.go, module/testmodule/fakemodule.sh, robot/impl/local_robot_test.go
RSDK-4166
Moves handling of modular startup failures to a single `defer func() { if !success { ... } }` block. Tries to unify behavior between regular modular startup failure and modular "re"startup failure (after crash). Removes special logic in `attemptRestart` for "immediate crashes". Modifies related tests.
=> RSDK-4166 Better handling of modular startup failures

robot/impl/local_robot.go
The lock can create a deadlock when `Close` happens concurrently to processing a `localRobot.Status` call. Specifically when the `Close` method is waiting on its sub-components to shutdown. An alternate fix would be to release the lock while waiting for the sub-components to shutdown.
I argue the lock acquisition in `Close` can be removed because:
- All `localRobot` members accessed in `Close` are assigned to in construction.
- All `WaitGroup.Wait` calls have had the corresponding `Add` calls done during construction.
- If the lock acquisition is providing necessary synchronization for calls into `localRobot` member fields, I argue those sub-components should own their synchronization requirements. We should file separate tickets as those problems are observed.
=> RSDK-4551: Remove the localRobot lock acquisition from `Close`.

cli/app.go, cli/client.go, cli/data.go, cli/module_registry.go
RSDK-4446
Moves all CLI string flags to a `const` block at the top of `cli/app.go`. Modifies all usages of `c.String` and `c.Bool` to use these constants.
=> RSDK-4446 Unify CLI arguments into single style

components/board/genericlinux/board.go, components/board/genericlinux/board_test.go
This pr implements status for the genericlinux boards similar to numato and pi. Note not all boards have implemented status. The create status function is implemented in the board interface and relies on the names of digital interrupts and analogs in configuration to be present to report them. It is unknown how this interact with out new reconfigure flow.
*** this status method may be moved with different functionality eventually.
=> Add Status to genericlinux board

services/vision/client.go, services/vision/obstaclesdepth/obstacles_depth.go, services/vision/obstaclesdepth/obstacles_depth_test.go, services/vision/server.go, vision/object.go, vision/object_test.go, vision/segmentation/detections_to_objects.go, vision/segmentation/segments.go
A handful of fixes necessary for obstacles_depth to work well. Successfully tested on hardware (RPi). Quick list:
1. Currently, when you don't put in parameters (to get default), you get an error because Hmin isn't less than Hmax.
2. There was a typo in the trace/span
3. Update vision server (segmentsToProto) to handle a nil pointcloud instead of freaking out.
4. Update vision client (protoToObjects) to not delete geometries from the object
=> RSDK-3646 - Obstacles Depth (fixes)

components/base/register/register.go, components/base/sensorbase/sensorbase.go, components/base/sensorbase/sensorbase_test.go, components/base/wheeled/wheeled_base.go
This moves the movement sensor attribute field from the wheeled base and creates the sensor base model that takes in a base and a movement sensor for feedback to API calls.
- Spin behaviour is retained, it stops within 3degs of requested call using the sdk and rc card. Both are still blocking with the new wait for success function.
- The SetVelocity control loop will be addressed in a separate pr
- registration of this resource will be done in a separate pr.
=> RSDK-4459 Create sensor base model 

components/base/kinematicbase/differentialDrive.go, components/base/kinematicbase/kinematics.go, pointcloud/basic_octree.go
Update default values in `kinematics.go` and `basic_octree.go` to reflect values that work better for executing plans.
Implement max move straight distance of 1m to fix error building up when moving long distances.
=> RSDK-4576: Change default values for kinematic base

examples/apis.json
powersensor code sample was problematic because the old function (`Voltage`) returned 3 values (bool, float, err), but the docs assumes there are always only ever 2 values returned (cc @Kschappacher we might want to add `return_types` to the `api.json`).
This PR changes the code sample function to be `Power`, which only returns a float and an error, so docs should work
[Ticket](https://viam.atlassian.net/browse/RSDK-4635)
=> [RSDK-4635] Fix issue with Power Sensor code sample

services/vision/mlvision/classifier.go, services/vision/mlvision/detector.go
@bhaney and @kharijarrett
Two changes in this PR:
- RSDK-4634 is just a quality of life improvement. Previously, the errors that you can see with `-debug` didn't provide the nested error that actually caused the detector or classifier to decide that the model wasn't useable, but now it does.
- RSDK-4750 is a little more important. The full TFLite effdet model can take any size input, so the `image` metadata reports the height/width as `-1, -1`. For such models, skip the resizing step and send the image as is.
=> RDSK-4634 and RSDK-4750: Small vision service improvements

components/base/wheeled/wheeled_base.go, components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go
@dgottlieb found an interesting bug yesterday: if you mutate the data in a config struct during reconfiguration, it looks different from the raw config afterwards, which triggers reconfiguration, which mutates the data, and you get stuck in a loop. Dan is working on a fix within the config-monitoring code, but in the meantime I think we should fix this in the components, too, so that nobody copies and pastes this, thinking it's the standard approach to take. 
I wish Go let you declare certain data as immutable, but the compiler isn't going to help with this. As a general rule, if you can avoid side effects (e.g., mutating your arguments when the caller of the function isn't expecting them to mutate), code becomes easier to reason about and more likely to be bug-free.
Everything compiles, …
=> Dont mutate config data during initialization/reconfiguration

components/camera/transformpipeline/mods.go, components/camera/transformpipeline/mods_test.go, components/camera/transformpipeline/transform.go, rimage/depth_map.go
This PR supports rotating images/videos 90,-90, and 270 in addition to 180, which we currently support. For color streams, as implemented, users can rotate an arbitrary number of degrees in either direction (e.g., 45 or -45), but the height and width are subject to constraints imposed by libx264. For example, the height and width must be divisible by two. Therefore, we'll only document the safe rotations, the ones tested below, since they either do not change the width and height or swap them.
[Screencast from 08-21-2023 07:24:01 PM.webm](https://github.com/viamrobotics/rdk/assets/34226620/a5f93574-55e0-4080-94a6-0aacc22e4dff)
=> Rotate Transform Should Support 90 & 270 turns

go.mod, go.sum, ml/api.go, ml/inference/inference.go, ml/inference/tflite.go, ml/inference/tflite_test.go, services/mlmodel/client.go, services/mlmodel/client_test.go, services/mlmodel/mlmodel.go, services/mlmodel/mlmodel_test.go, services/mlmodel/server.go, services/mlmodel/server_test.go, services/mlmodel/tflitecpu/tflite_cpu.go, services/mlmodel/tflitecpu/tflite_cpu_test.go, services/vision/mlvision/classifier.go, services/vision/mlvision/detector.go, services/vision/mlvision/ml_model.go, services/vision/mlvision/ml_model_test.go, services/vision/mlvision/segmenter3d.go, testutils/inject/mlmodel_service.go
- Imported gorgonia/tensor library to implement flat tensors
- Edited the RDK server.go and client.go to use flat tensors.
-  For backwards compatibility (until python is updated) the pb.Struct methods still works
- BREAKING CHANGE: The RDK tflite API was changed to use FlatTensors rather than interface maps
- BREAKING CHANGE: tflite_cpu model in RDK was edited to use flat tensors, and get rid of use for pb.Struct
- BREAKING CHANGE: vision service/mlmodel detector and classifier code was updated to use flat tensors.
- Manually tested this on effDet0 using the tflite file.
- Manually tested on a classifier model that previously didn't work, RSDK-3009
- Manually tested on both a detector and classifier model with no metadata made by Viam
@tahiyasalam cc - no need to review unless something …
=> RSDK-4195, RSDK-3352, RSDK-3009, RSDK-3096: add support for flat tensors to RDK, in mlmodel/tflite_cpu and vision/mlmodel

components/motor/gpiostepper/gpiostepper_test.go
Very hard to actually repro this, only failed once in CI and I couldn't repro locally. Theory is that IsPowered() returns true before doCycle() is ever called, so it's possible for IsPowered == true while position is still 0.
=> RSDK-4414: flaky gpiostepper test fix

web/frontend/src/components/slam/index.svelte
Forgot to actually call `endSession` override on SLAM card
-- EDIT -- 
Discovered when testing app overrides that when start session fails, the timer + end session displays, though it doesn't tick. Just added some error handling to make sure we reset to initial state and clear any intervals
=> add end session to slam overrides

robot/web/options/options.go, robot/web/web.go, web/server/entrypoint.go
Mainly to support [a more rigorous dial scenario testing](https://github.com/viamrobotics/sdk-integration-tests/pull/14), but probably a useful configuration to expose in general.
=> RSDK-4334 add option to disable server discovery via mdns

components/movementsensor/wheeledodometry/wheeledodometry.go, components/movementsensor/wheeledodometry/wheeledodometry_test.go
This PR implements the `Reconfigure` function for the wheeled odometry model, as well as increasing the time interval threshold per RSDK-4599
=> RSDK-4458: Implement wheeled encoder reconfigure

components/board/genericlinux/i2c.go
This is a follow-up to a discussion on Slack. Hazal had reported that, when she names but does not use a nonexistent bus, she encounters all kinds of trouble, and I said I'd take a look. Here's what I found:
- On an Orin Nano, you would have trouble naming a nonexistent I2C bus, hence this PR.
- On an Orin Nano, you can name nonexistent SPI buses, and it's okay as long as you don't use them.
- On an rpi, you can name nonexistent I2C buses, and it's okay as long as you don't use them.
- On an rpi, you cannot name nonexistent SPI buses: we return an error during reconfiguration because the code knows the board only has 2 SPI buses. I'd prefer to check for this during `Validate()` instead, but the rpi board uses the genericlinux config, and its `Validate` cannot assume that only buses 0 and …
=> Don't balk at nonexistent SPI buses if they're unused

components/board/jetson/data.go
Tried on a board: pins 15 and 33 work great! Pin 32 claims to have PWM support, but I couldn't figure it out. I ran `jetson-io.py`, and it said it was already enabled. but there are 4 PWM chips with 1 line each:
- Device `3280000.pwm` sends output to pin 15. It works great.
- Device `32c0000.pwm` sends output to pin 33. It works great.
- Device `32a0000.pwm` claims the device is already in use and cannot be exported, even immediately after rebooting when nothing unusual should already be in use.
- Device `39c0000.tachometer` doesn't seem to do anything obvious.
but the 2 existing PWM lines are probably good enough for most purposes.
=> [RSDK-4639] Make sure Orin Nanos have hardware PWM support

cli/app.go, cli/module_registry.go
This change should make it so that when you upload your meta.json file there must be visibility set in the file. 
**OLD - no longer relevant**
Creating a private module in staging:
Creating a public module in staging:
Bad Value:
No Value:
=> APP-2541: make visibility required for cli create command

examples/filters/sensorfilter/module/main.go, examples/filters/sensorfilter/sensor_filter.go
Tested on a viam rover with an ultrasonic sensor attached. Built from source (to include recent changes in [DATA-1803](https://github.com/viamrobotics/rdk/pull/2830) that are not yet in the most recent RDK version) and ran that on robot - verified that fromDM flag and filter error propagation works as expected!
[DATA-1803]: https://viam.atlassian.net/browse/DATA-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DATA-1874 Add example modular sensor for filtering data capture

components/base/kinematicbase/differentialDrive_test.go, components/base/kinematicbase/fake_kinematics_test.go, services/motion/builtin/builtin.go, services/motion/builtin/builtin_test.go, services/motion/localizer.go, services/navigation/builtin/builtin_test.go, services/slam/client.go, services/slam/client_test.go, services/slam/collector.go, services/slam/fake/data_loader.go, services/slam/fake/slam.go, services/slam/fake/slam_test.go, services/slam/grpchelper/grpchelper.go, services/slam/server.go, services/slam/server_test.go, services/slam/slam.go, testutils/inject/slam_service.go
Ticket: https://viam.atlassian.net/browse/RSDK-3979
Tested using fake slam.
This PR has to be merged before the corresponding PR in viam-cartographer can be merged: https://github.com/viamrobotics/viam-cartographer/pull/257
=> RSDK-3979 - Remove "Get" from slam service method names

cli/app.go, cli/auth.go, cli/auth_test.go, testutils/inject/app_service_client.go
Ticket: https://viam.atlassian.net/browse/RSDK-4724
help msg for `viam organization api-key create`:
```
NAME:
viam organization api-key create - create an api key for your organization
USAGE:
viam organization api-key create [command options] [arguments...]
OPTIONS:
--name value    the name of the key (defaults to your login info with the current time)
--org-id value  the org to create an api key for
```
creating a key:
```
➜  cli git:(zp/2496) ✗ ./main --base-url="https://pr-2344-appmain-bplesliplq-uc.a.run.app:443" organization api-key create --org-id "43e11169-62e6-4dda-96b1-be2cad5d1878"
Info: using default key name of "zack.porter@viam.com-2023-08-30T16:45:13-04:00"
Info: successfully created key:
key id: 2a3380da-f047-0000-b6bf-5f4d0000f5c
key value: …
```
=> RSDK-4724 - Update CLI to support api-key create

components/camera/videosource/logging/logger.go, components/camera/videosource/webcam.go, web/server/entrypoint.go
This PR removes the libx264 dependency for `make webserver`. I manually verified this by 
```
➜  app git:(main) ✗ make webserver
... do stuff
│   ✔ done
│ ✓ built in 6.45s
└─ Done in 7.5s
GOOS=linux GOARCH=amd64 go build  -o bin/linux/amd64/webserver cmd/webserver/cmd.go
➜  app git:(main) ✗ ldd bin/linux/amd64/webserver  | grep x264
➜  app git:(main) ✗ cat go.mod | grep rdk     
go.viam.com/rdk v0.8.0-rc0
replace go.viam.com/rdk => /usr/local/libs/rdk
➜  app git:(main) ✗ 
```
=> remove libx264 dep

.gitignore, cli/auth.go, cli/auth_test.go, cli/boards.go, cli/client.go, cli/client_test.go, cli/data.go, cli/module_registry.go, cli/print.go
RSDK-4734
Avoids base URL logic for logging out (just clears the cache). Adds a new `printf` method to replace the numerous `fmt.Fprintf` calls. Capitalizes all printed messages and errors returned to the user (Go standard is lowercase but _CLI standard_ is uppercase; maintains all errors as lowercase-starting internally). Modifies tests accordingly.
=> RSDK-4734 More polishing of CLI

components/sensor/bme280/bme280.go
This adds a close of the open handle right before we call open handle again from the nested `setMode` function, which was deadlocking genericlinux's mutex.
Tested on a jetson orin and seems like pigpio handles already open handlesthis through the pi driver already.
=> [RSDK-4483] BME280 Sensor Error building resource on different boards 

components/powersensor/ina/ina.go
- changing the configuration register to the default values
- calling calibrate() each time we read power and current instead of just once at build time. This is so that if another process is also writing to the ina registers we will still have the expected values in them 
- changing the readregisters calls to signed integer so that negative values can be properly read 
tested manually with ina219 connected to a DC motor, @mcvella also confirmed this solved the issues he was seeing.
=> RSDK-4744 INA219 current readings incorrect fix

services/datamanager/datacapture/data_capture_file.go
Tested with a fake SLAM service capturing data with PointCloudMap, no longer get the error:
`error uploading file /Users/katherinewu/.viam/capture/rdk:service:slam/fake-slam/PointCloudMap/2023-09-06T15:36:39.376396-04:00.capture: rpc error: code = InvalidArgument desc = request contains SensorData with non-struct contents`
=> DATA-1913 Change PointCloudMap data type to tabular

components/board/beaglebone/data.go
The 4 pins that we have hardware PWM support on do not have GPIO functionality: they always read their input as low even when it's connected to high, and they always output low even when you set them high. (but setting them to do PWM stuff does the right thing.)
I figured this out months ago, then forgot, and had to figure it out again this week. Ideally we'd get these pins to have GPIO functionality in addition to PWM, but for now at least document what's happening.
=> [RSDK-4640] document Beaglebone's GPIO shortcomings

components/encoder/incremental/incremental_encoder.go, components/motor/gpio/motor_encoder.go, control/derivative_test.go, protoutils/messages_test.go, rimage/gray_image_helpers.go, utils/average.go
- this includes just the fixes from #2790, specifically:
- reordered structs to fix sync/atomic unaligned panic
- test failures and crashes from bit width
- add back build tags which remove unavailable libraries
- atomicalign linting in CI, test in 32 bits
=> 32-bit struct order and fixes

module/modmanager/manager.go, module/module.go, module/module_test.go, robot/web/web.go
Ticket: https://viam.atlassian.net/browse/RSDK-4877
Discovered by @ethanlook . 
Fix suggested by James:
``
Yeah, there's no way around the path char limit and Mac's temp directory already eats up a lot of those characters. Truncating it is probably best. Or... we could stop using the name in the path. It was more elegant for debugging and I hate "mystery filenames" in general, but 16 random characters work just as well.
Or some combo of the two, truncate namespace +random extension combine with truncated name plus random. So humans would at least see some of the namespace and name, but It'd always be a fixed length.
``
This keeps the current behavior of using the module name if possible, but if that would be too long, it truncates the name and adds some random chars.
=> RSDK-4877 - Long module names can result in socket path errors on macos

components/board/pi/impl/board.go, components/board/pi/impl/i2c.go, components/board/pi/impl/pi.c, components/board/pi/impl/pi.h, components/board/pi/impl/servo.go, components/board/pi/impl/utils.go, components/board/pi/pi_notsupported.go, components/board/pi/pi_supported.go, ml/inference/tflite.go, services/mlmodel/register/register.go, services/mlmodel/tflitecpu/tflite_cpu.go, services/register/all.go, services/register/all_tflite.go
- this adds `no_tflite` and `no_pigpio` build flags, which can be used to toggle off tensorflow lite and pi GPIO libraries so that people can make 32-bit builds
- this is part of closed giant PR #2790 
- note: I excluded changes to test files; will add those back when we do 32-bit tests in CI
- `go build -tags no_tflite,no_pigpio ./web/cmd/server`
=> RSDK-4829 32-bit build tags

components/base/wheeled/wheeled_base.go, components/base/wheeled/wheeled_base_test.go, components/movementsensor/wheeledodometry/wheeledodometry.go, components/movementsensor/wheeledodometry/wheeledodometry_test.go
=> [RSDK-4883][RSDK-4891]Stop when SetVelocity is all zeros and Change units in WheeledOdometry

web/server/entrypoint.go
Adds printing of backtrace on restart
Screenshot of backtrace on local output.
Screenshot of backtrace as it appears in app.
=> RSDK-4871 - add backtrace printing on restart

robot/impl/local_robot_test.go
Was reading through some robot tests when I stumbled upon this test (I must've missed it). 
Everything that this test is supposed to test is already tested elsewhere. Unfortunately, this test also passes when it should clearly fail (the placeholders are invalid and are never evaluated).
I don't see the value in fixing this test given that the things it tests are tested elsewhere and because it was already broken.
If you feel strongly that it should be replaced, happy to look into putting something in its place.
=> Remove mistakenly passing package replacement test

components/board/genericlinux/board.go, components/board/genericlinux/gpio.go
With this change, you can hammer multiple I2C devices all you want simultaneously through multiple different approaches both in the RDK server and out of it, and all is well.
...and while I was looking at this part, I noticed that we're not turning off hardware PWM when we shut down the RDK server, so I added that in, too.
Tried on an Orin Nano and a Beaglebone: the Orin Nano worked both with and without this change, while the BB only worked with it.
=> [RSDK-1939] Don't kill the I2C bus when closing GPIO pins

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/base/index.svelte
Refocusing browser window with base RC open causes base to execute currently queued command.
The current bug is caused by our on key event for the `Run` button, under discrete tab. Being that the button is active, when one clicks `alt tab` for instance, this triggers the function call.
The fix adds a helper function that validates that the user is actually hitting the `return` key and not just any key, and from there executes the callback.
=> bugfix: onKeyUp handler on base

components/movementsensor/wheeledodometry/wheeledodometry.go
This PR fixes the reconfigure issue so that if a motor is no longer position reporting, it will return the correct error instead of panic later on. I've also flipped X and Y in order to match the orientation we use where Y is forward and X is side to side
=> RSDK-4951: Wheeled Odometry does not reconfigure when motor with the same name changes position reporting properties.

cli/data.go, services/datamanager/builtin/sync_test.go, services/datamanager/datasync/upload_arbitrary_file.go
Name an arbitrary file with its original file path. This PR:
* Uploads arbitrary files with the absolute directory path as their file name.
* In CLI export, saves files according to their original directory structure. 
* Data capture files are still saved at the top-level directory with timestamps prepended in order to sort. Timestamps are not prepended to arbitrary files that have a predetermined directory structure.
* In CLI export, unzips gzipped files, whether they were gzipped server-side or the user uploaded a gzipped file.
**Testing**
Tested with:
```
"additional_sync_paths": [
"/tmp/my/path/example.txt",
"/tmp/other"
],
```
And the names were correctly saved into app:
Tested again with absolute and relative paths, both of which are saved as their absolute paths:
``` …
```
=> [DATA-1868] Upload arbitrary files with their full original file paths and maintain their directory structure upon export

services/motion/builtin/builtin.go
Reverts viamrobotics/rdk#2938
This is necessary because the builtIn motion service is configured with weak dependents and this breaks when we take it out of the normal reconfiguration process.  It was hypothesized that we could and should be "always rebuilding" instead of reconfiguration but without the weak dependents being passed in there is no way for motion to have access to resources like SLAM and movement sensors
=> RSDK-5006 revert "RSDK-4932 always rebuild motion service instead of reconfiguring"

components/motor/gpio/motor_encoder.go, components/motor/gpio/motor_encoder_test.go
This PR implements `GetMotorState` and `SetMotorState` which allows users to access the internal state that rpmMonitor uses. Kind of wondering if this is how we want to do it or just export motor.state? or should a user only be able to access certain parts of the motor state instead of everything?
Also went back through the test file to get everything working again
=> [RSDK-4900][RSDK-4981]: add functionality to access rpmMonitor state and redo test file

referenceframe/frame_system.go, referenceframe/frame_system_test.go, services/motion/builtin/builtin.go
Fixing this flaky test is a blocker for being able to build on 32 bit systems since it fails on that architecture
At a high level what I have done is rewrite the test such that it is testing the underlying FrameSystemGeometries function rather than the FrameSystemToPCD function, since the original function is just calling a function to convert them to PCDs after.  This conversion to PCD is tested in spatialmath and should not be repeated here.  Rather this new function tests that Geometreis in the frame system are returned where they should be, and are committed if there is not sufficient information to locate them.  In testing this, I found a small bug in the function in question and fixed it.
=> RSDK-4973 fix flaky test TestFrameSystemToPCD

components/motor/gpio/motor_encoder.go, components/motor/gpio/motor_encoder_test.go
this PR replaces the use of `NewEncodedMotor` with `WrapMotorWithEncoder` so there aren't so many related creator functions
=> RSDK-5015: simplify/combine constructors to one function

module/modmanager/manager.go, resource/graph_node.go, robot/impl/local_robot.go, robot/impl/resource_manager.go, robot/impl/resource_manager_test.go, robot/impl/robot_reconfigure_test.go
If we kill a module process, the viam-server starts the module back up but the WeakDependents are not updated - so in cases where the module now serves a different model, certain things will not get updated (sensors, motion, etc). Causes issues when you have a sensor that no longer exists showing up on the sensors service card. (not sure of a good test for this, open to suggestions!)
if we switch the model of a modular resource to an invalid model and then back, we were also unable to reinstantiate the resource - we closed the old one but because the invalid model never succeeded, on reconfiguring it back to the valid model the rdk recognizes it as a regular reconfigure. Since the old resource is already gone, the module will respond with various kinds of ResourceNotFound errors - this …
=> RSDK-4171, RSDK-4546 - Fix weird module behavior on process kill and model switch

robot/session_test.go
Was unable to reproduce or make much progress here. As a minimum first step, I'm adding stacktrace logging so that we'll have more information when we next hit the error.
I decided to only log the current thread to avoid overloading debugging efforts with too much extraneous info and this issue doesn't look to me like an async one. This is not a strong preference; happy to log everything if folks feel otherwise.
Note that this screenshot is just to show formatting; I wasn't able to actually reproduce the error so this doesn't actually have anything particularly interesting in it!
=> RSDK-3837 - Sessions with remote flaky test fix

components/motor/gpio/loop.go, control/constant.go, control/control.go, control/control_block.go, control/derivative.go, control/encoder_speed.go, control/endpoint.go, control/filters.go, control/gain.go, control/pid.go, control/pid_test.go, control/sum.go, control/trapezoid_velocity_profile.go
This pr changes the attribute map accessors to stop using the possibly deprecated in the future helper functions - another rpr will be made to refactor them into structs. 
Also changes the endpoint's controllable to State and SetSTate and wrap encoded motor's  SetPOwer and Position in those functions to ensure the interface is fulfilled.
=> Control Loop Base Part I: Refactors for more general endpoints

components/board/customlinux/board.go
Getting hardware PWM right is turning out harder than hoped. So, to keep pushing forward with the customlinux productionization, Rand suggested that we temporarily only use software PWM, and come back to enable this later. The board definition files should still contain info on which pins have hardware PWM support, we just won't use that right now.
This still needs to be tried out on a couple different boards (ideally some kind of Orange Pi, since those are the ones we've been having the most trouble with recently), on pins both with and without hardware PWM support.
=> [RSDK-5107] Only use software PWM on customlinux boards

components/camera/transformpipeline/detector_test.go, services/vision/mlvision/detector.go, services/vision/mlvision/ml_model_test.go
This is a heuristic fix to take into account different representations of bounding boxes from ML detectors.
- in the proportion representations, the bounding box coordinates are between 0 and 1 and proportion to the distance within the image.
- In the absolute representation, the bounding box coordinates are the actual absolute coordinates within the image.
manually tested on a model with proportional bounding boxes
=> RSDK-4571: Add a heuristic for detection bounding boxes from ml models

components/board/genericlinux/gpio.go, components/board/genericlinux/hw_pwm.go
...and while I was at it, wrap the GPIO-related errors with extra context around which device and which line this was for.
Tried on an Odroid C4: the debugging logs in the PWM stuff work as intended, with output like this when successfully setting a 10 Hz PWM with 50% duty:
```
2023-09-22T19:27:40.955Z	DEBUG	robot_server.rdk:component:board/b	genericlinux/hw_pwm.go:38	Writing 0 to /sys/class/pwm/pwmchip0/export
2023-09-22T19:27:40.957Z	DEBUG	robot_server.rdk:component:board/b	genericlinux/hw_pwm.go:38	Writing 1 to /sys/class/pwm/pwmchip0/pwm0/enable
2023-09-22T19:27:40.958Z	DEBUG	robot_server.rdk:component:board/b	genericlinux/hw_pwm.go:38	Writing 0 to /sys/class/pwm/pwmchip0/pwm0/duty_cycle
2023-09-22T19:27:40.958Z	DEBUG	robot_server.rdk:component:board/b	genericlinux/hw_pwm.go:38 …
```
=> [RSDK-5026] Add debugging logs when setting PWM through sysfs

components/board/customlinux/board.go, components/board/customlinux/setup.go, components/board/customlinux/setup_test.go
...as described in the scope doc. The code still compiles, but I haven't yet tried it out further. 
This will require changing our robot config files to use the new key name (`board_defs_file_path`) instead of the old one (`pin_config_file_path`). The reason for the change is that the file contains immutable definitions, rather than mutable configuration options, and although it currently only contains pin stuff it might generalize to board stuff in the future (e.g., maybe we need a section about pinmux registers or something :wink:).
=> rename pin configs to board definitions

.github/workflows/cli.yml
- switch order of steps in cli workflow so setup-go happens **after** our codebase is checked out
- setup.go uses go.sum to cache builds when it's present
- this is currently popping warnings in our CI (screenshot), which should go away
This hasn't been tested in our CI (PRs use main branch) but I ran on laptop with `act` and got:
```
[Viam CLI/viam-cli]   ✅  Success - Main build
```
=> setup-go caching in CLI build

components/base/sensorcontrolled/sensorcontrolled.go, components/base/sensorcontrolled/spin.go
This pr moves the spin controls related functions into the spin.go file in sensorbase. Minor clean-up, for log comments as well.
=> Move rest of spin functions into spin.go in sensor base

services/motion/builtin/builtin.go, services/motion/builtin/builtin_test.go, services/motion/builtin/move_attempt.go, services/motion/builtin/replanner.go, services/navigation/builtin/builtin.go, services/navigation/builtin/builtin_test.go, services/navigation/navigation.go, services/navigation/store.go, utils/logger.go
[Ticket](https://viam.atlassian.net/browse/RSDK-4886)
Also fixes: https://viam.atlassian.net/browse/RSDK-4934
Moves the non ticket related improvements / fixes from https://github.com/viamrobotics/rdk/pull/2919/files#diff-c413f7c41e0f0eba4493f6ea317ff6a9e356e70224e9d0956ae5cb8dacaf8973 into a separate PR.
1. Adds `log_file_path` to nav service
2. Improve logging by adding String methods to `motion.moveResponse` & `motion.replanResponse` & logging in nav interface methods which change state
3. Fix an off by one error in the nav waypoint store which resulted in a panic if a user tries to remove a waypoint from an empty store. https://viam.atlassian.net/browse/RSDK-4934
=> Rsdk 4886 misc improvements

services/motion/builtin/builtin_test.go
Most recent merge into RDK main failed b/c some of the tests of TestReplanning timed out on the arm64 test runner.
This change bumps the timeout from 5 to 30 seconds.
=> hotfix-bump-motion-TestReplanning-timeout

services/navigation/builtin/builtin.go, services/navigation/store.go
This PR modifies the validation for the builtin navigation service such that if no store is provided in the config, we use a memory store by default.
This was tested by using the provided bad config below and confirming that it does not panic on startup.  Prior to this fix this same config would cause a panic
```
{
{
"name": "basey",
"model": "fake",
"type": "base",
"attributes": {},
"depends_on": []
},
{
"name": "movie",
"model": "fake",
"type": "movement_sensor",
"attributes": {},
"depends_on": []
}
],
"services": [
{
"name": "navy",
"type": "navigation",
"base": "basey",
"movement_sensor": "movie",
"motion_service": "builtin"
}
}
]
}
```
=> RSDK-4949 fix panic when no store information is added in config

utils/parallel.go, utils/parallel_test.go
A typo of Ceil vs Floor sometimes caused groupSize to be bigger than it needed to be, which both caused double counting sometimes, and also sometimes caused access to an index beyond the length of the inputs.
=> RSDK-5108: change Ceil to Floor for GroupWorkParallel

robot/impl/local_robot.go, robot/impl/local_robot_test.go, robot/robot.go, robot/web/web.go, robot/web/web_c.go, robot/web/web_notc.go, web/server/entrypoint.go
causes really bad issues if someone ever changes the network config and so restarts the web server
as part of this, updated some of the internal interfaces since web.Stop won't ever return an error.
also split up web workers and mod workers so the Wait() is preserved when StopWeb is called
=> RSDK-5197 - Don't stop module server on web reconfigure 

cli/app.go, cli/boards.go
CLI command to list the name and version of board definitions packages that are in an organization. 
example output:
=> RSDK-5171 List board definitions packages in CLI 

robot/web/web_test.go
RSDK-4473
Forces a direct gRPC connection to remotes in `TestWebReconfigure`, `TestWebWithAuth` and `TestForeignResource` where possible. Adds a few missing `Close` calls to opened connections.
I found that using `CreateBaseOptionsAndListener` to reserve a remote address and dialing that address with WebRTC can occasionally cause a hang in client message reception when the connection is used for a basic gRPC request. _And_, this only happens when multiple, parallel tests are doing all of those things. I'm not sure why yet, but since the answer is non-obvious, I think we should just force direct gRPC connections in the offending tests for now. I would not be surprised if another test pops up with the same issue, but this should get rid of some of the flakiness in our test suite for the …
=> RSDK-4473 Use direct gRPC connections in web tests that hang

cli/app.go, cli/auth.go, cli/client.go
A person in the Viam discord ran into an error while trying to authenticate with the CLI in a "headless" environment, i.e. Rapsbian Lite or Linux VM, due to the default behavior for opening a browser before waiting for a response from the app to confirm a successful login. 
I noticed an existing field in the `authFlow` struct for disabling this behavior but it wasn't exposed as a CLI flag. This PR exposes a new `--disable-browser-open` boolean flag to `viam login` to resolve the issue described above. 
Please let me know if there's a better way to add this behavior. 
Help text:
Error handling:
=> feat(cli/auth): allow disabling browser open during login

motionplan/motionPlanner_test.go, motionplan/tpSpaceRRT_test.go
This change results in a 140% speedup on my machine, from ~22 seconds to ~9 seconds. It will take longer on the CI machine but the % speedup should hold.
=> RSDK-5166 Add limited number of smoothing iterations to de-flake test

robot/impl/local_robot.go, robot/impl/resource_manager.go, robot/impl/robot_reconfigure_test.go
we get a cascade of resource configuration timeouts when we kill a server when it's hanging on reconfiguration, that was because we end up going through the reconfiguration for the rest of resources instead of exiting out early.
Should reduce noise when debugging issues
=> RSDK-5220 - Early exit reconfiguration on context.Done()

web/frontend/package.json, web/frontend/src/components/board/index.svelte
Some boards use strings for pin names (e.g. revolution pi). This allows arbitrary strings for pin name inputs.
=> APP-2828 Allow string pin names in board card

motionplan/tpspace/ptgGroupFrame.go
Desired behavior: log a warning message that will use a lower angular velocity because the current math is linear velocity / angular velocity is not possible given the current turning radius
=> RSDK-4843 Add warning message for angular velocity change

.github/workflows/cli.yml, Makefile, go.mod, go.sum
- this is the other half of https://github.com/viamrobotics/goutils/pull/205
- bump to goutils 0.1.45 which includes fixes for windows and 32-bit
- publish windows binary of CLI (with .exe extension)
- I ran the binary from `GOOS=windows GOARCH=amd64 EXE_SUFFIX=.exe make cli-ci` on the lab machine, can confirm it at least starts and pops a browser on login
=> DATA-2031 publish CLI for windows

components/board/customlinux/board.go, components/board/customlinux/setup.go, components/board/customlinux/setup_test.go
...and while I was in here, I noticed that there's a trivial helper function only used in 1 place in a separate file, so I inlined that.
(The linked Jira ticket is about getting ready to document everything, but this PR came because I was trying to write docs and noticed that this never got cleaned up properly.)
The digital interrupts section of the config is used to give human-readable names to a digital interrupt pin. but in the customlinux component, you've already specified your own arbitrary human-readable name for each pin, so there's no reason to have a second one. This was mentioned in the scope doc, and I just didn't clean this part up earlier. Instead of this section, any pin can implicitly be converted into a digital interrupt by just using it as such.
The analogs section of …
=> [RSDK-3802] remove analogs and interrupts from the customlinux config

components/arm/universalrobots/ur.go, components/arm/universalrobots/ur5e_test.go
What it says on the tin.
Max speed for ur5e from spec: https://www.universal-robots.com/media/1807465/ur5e-rgb-fact-sheet-landscape-a4.pdf
Movej API in URSCRIPT takes in rad/s for velocity and rad/s^2 for acceleration: https://s3-eu-west-1.amazonaws.com/ur-support-site/115824/scriptManual_SW5.11.pdf
=> [RSDK-5198] Change units in UR driver to match config field units

components/board/genericlinux/i2c.go, components/board/hat/pca9685/pca9685.go
This has a couple changes:
- In the genericlinux package, there's now a `GetI2CBus` function. If you give it a bus number, it gets the raw I2C bus straight from the OS, and otherwise it tries to get the bus from the board component like we used to do. This way, you can either specify the I2C bus the old way (by naming the board and the entry in the "i2cs" map within the board) or the new way (just name the raw I2C bus on the machine). This function has a TODO to remove it again when all robot configs are converted from the old approach to the new one.
- In the PCA9685 component, make the `board_name` and `bus_name` entries in the config optional, and also add an optional `i2c_bus` int. In the `Validate` function, make sure that either the first two or that last one is present.
- In the …
=> [RSDK-5240] Let the PCA9685 component talk directly to the I2C bus

cli/data.go, cli/data_test.go
- transform `:` to `_` when running `data export` on windows because `:` is not allowed in filenames
- (incidental) factored out `filenameForDownload` from `downloadBinary` so it can be tested in isolation
=> RSDK-5264 remove reserved characters from filenames

components/board/hat/pca9685/pca9685.go
This is literally never used, nor do I understand what it could be used for (~~I believe every PWM pin on this board can be set to its own frequency independent of the rest~~ _edit: the board does have just one frequency for all pins. but this config value is still unused_).
I've made a corresponding change to the Docs repo in https://github.com/viamrobotics/docs/pull/1970
=> remove unused config value from PCA9685

components/board/config.go, components/board/genericlinux/board.go, components/board/genericlinux/board_test.go, components/board/genericlinux/config.go, components/board/mcp3008.go, components/board/pi/impl/board.go, components/board/pi/impl/board_test.go
This combines the two tickets for moving the current common board config for MCP3008 ADC for only pi and generic linux boards. Haven't removed the common config from the other boards yet to avoid breaking changes in this PR. Also changed name `Analogs` to `AnalogReaders` in generic linux.
=> RSDK-5177 RSDK-5178 Move common analog config to generic linux only

services/motion/builtin/builtin_test.go, services/motion/builtin/move_request.go
This corrects a major issue with regard to planning in TP-space; specifically, that all poses (goals, obstacles, etc) must be specified relative to the starting position of the robot; that is, the base being planned for must have a ZeroPose between it and the frame system's World.
Prior to this PR, the heading of the base's starting position was inserted between the base and World for each solve FS call. This had the side effect of transforming *every* PTG transform call by that much resulting in paths that bear little resemblance to a path that would actually get the robot to the goal, unless that heading was 0.
This PR transforms the goal and all geometries to place them at the correct positions relative to the starting pose of the base.
As part of this, tests were also updated such …
=> RSDK-5271 Fix move_request for MoveOnGlobe to always plan relative to the base's current pose

components/board/hat/pca9685/pca9685.go, components/board/hat/pca9685/pca9685_nonlinux.go
Sorry to break the Mac build! Michael, give this a try and LMK if it works.
=> The PCA9685 is Linux-only

cli/data.go, cli/data_test.go
* Fix gz file extension naming for non-directory files
* Replace colon characters in filename for macOS since they are also not allowed on that platform.
**Testing**
Manually tested on directory-and-non-directory gzipped-and-non-gzipped files on a Mac.
=> [DATA-2050] Bug fixes for data export CLI

components/movementsensor/replay/replay.go, components/movementsensor/replay/replay_test.go, components/movementsensor/replay/replay_utils_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-4858
Implements `Properties` that reflect whether or not the respective endpoint returns data.
Tested by recording fake data with two different combinations of endpoints and then testing the replay movement sensor by polling `Properties` and all endpoints.
=> RSDK-4858 - Implement implicit Properties for replay movement sensor

cli/module_registry.go
Ticket: https://viam.atlassian.net/browse/RSDK-5325
With v:
```
➜  animalsoundspammer git:(main) ✗ viam module upload --platform linux/amd64 --version v1.0.0 ./package/module.tgz
Uploading... 100% (22705662/22705662 bytes)
Version successfully uploaded! you can view your changes online here: https://app.viam.com/module/zack/test_underscore
```
Without v:
```
➜  animalsoundspammer git:(main) ✗ viam module upload --platform linux/amd64 --version 1.0.1 ./package/module.tgz
Uploading... 100% (22705662/22705662 bytes)
Version successfully uploaded! you can view your changes online here: https://app.viam.com/module/zack/test_underscore
```
=> RSDK-5325 - MRR should gracefully handle a v prefix for semver

services/datamanager/datasync/upload_data_capture_file.go
Store timestamp from the GetImages response metadata instead of the time that the method was called and complete (requested and received) by the datamangement service.
**Testing**
Tested on a fake camera.
=> Use the GetImages ResponseMetadata timestamp for the data capture timestamp

robot/impl/local_robot.go, robot/packages/cloud_package_manager.go, robot/packages/cloud_package_manager_test.go
This change requests package files from App using header based auth of part secret.
Testing: I manually tested along with changes in https://github.com/viamrobotics/app/pull/2585/files. I investigated adding unit tests but currently there is mocking in place that does not do file downloads. Instead I think our our manual test cases cover this.
=> APP-2833: Add Headers for Package File Handler Authentication (secret-based)

web/frontend/src/components/slam/index.svelte
This PR handles some UI improvements to the SLAM card, namely:
- Hiding the refresh map error when map is successfully obtained
- Preventing user from adding destination markers when in cloud SLAM mode
- Ensuring that empty point clouds are also accounted for 
- Adding a loading state if user is in cloud SLAM mode and there is not yet a map loaded into frontend
- The text differs depending on if the user started the session or is coming back to a session they started previously and sets a refresh rate
For the video, I stubbed it to show the loading state - normally the left panel would look different in cloud slam mode.
https://github.com/viamrobotics/rdk/assets/16711130/bc40e301-f593-433e-8610-2c7316945f73
=> UI error handling, loading states

components/movementsensor/replay/replay_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-5315
Skipping test until the bug is fixed
=> RSDK-5315 - Skip flaky test until bug fix is in

cli/client.go, cli/client_test.go
Ticket: https://viam.atlassian.net/browse/APP-2546
Any thoughts on how you'd do this? I just put this PR out here to spark discussion. I've liked all your choices for the cli so far. To that end, if you have a different idea, feel free to just submit your own pr and we can close this
Here was what I came up with in 1-2 mins
Option1:
```
Organizations for "zack.porter@viam.com":
Dan's Org (id: 04307f0a-27c7-4b60-acba-99de6528ec6f)
Ethan's Org (ethanlook) (id: 42710bbc-538f-437f-9f33-70e497adb057)
Peter B's Org (peter) (id: a9cbebc7-e812-4ada-b886-b075f45d51e1)
Roxy's Org (roxy) (id: 2440e58c-038b-4abd-a11b-08b7549ea632)
SLAM Dev (id: 1d77887c-f295-4517-b562-ef00a4c6122c)
```
Option2:
```
Organizations for "zack.porter@viam.com":
Dan's Org
id: 04307f0a-27c7-4b60-acba-99de6528ec6f
Ethan's …
```
=> APP-2546 - add namespace to organizations list CLI command

.github/workflows/appimage.yml, .github/workflows/test.yml
- include 32-bit appimage in 'appimage deploy' step
- working run of this [here](https://github.com/viamrobotics/rdk/actions/runs/6499096458) (it runs to the intentional short-circuit step in 'deploy')
- GCS upload went [here](https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-test-32bit-armhf.AppImage)
=> RSDK-5063 upload 32-bit appimage

.github/workflows/appimage.yml
- use same BUILD_CHANNEL logic in `appimage-32bit` job + `deploy` job
- previously, build_channel for the 32-bit image was `release_type`
- this worked on main branch where `release_type == 'latest'` and `ref_name == 'main'` (and main gets converted to 'latest')
- but not in the RC case, where `release_type == 'rc'` and `ref_name == 1.2.3-rc`
This runs to short-circuit ([here](https://github.com/viamrobotics/rdk/actions/runs/6500312911/job/17655700179)) from a manual workflow_dispatch
=> fix appimage for RC case

components/board/genericlinux/i2c.go, components/board/hat/pca9685/pca9685.go
Thanks to @biotinker for pointing out that devicetree overlays might let you name your I2C bus something non-numerical! I'll update the scope doc to match, and here's a PR to update the one component I've migrated so far.
=> [RSDK-5240] the I2C bus number should be a string, in case it's not a number

resource/graph_node.go, resource/resource_graph.go, resource/resource_graph_test.go, robot/impl/local_robot.go
RSDK-5368
The “logical clock” logic shared between local robot, the resource graph and graph nodes represents a somewhat complex system used to determine when `updateWeakDependents` should be run in the local robot. There is both a lack of comments explaining this logic and some inaccurate statements in the existing comments and inline documentation. This PR adds more comments, attempts to fix the inaccuracies, and adds a couple "missing" locks.
=> RSDK-5368 Add more safety and inline docs about logical clocks in resource graph

cli/app.go, cli/archive.go, cli/archive_test.go, cli/boards.go, cli/module_registry.go
Ticket: https://viam.atlassian.net/browse/RSDK-5269
This adds the ability to provide a path to a single file or a path to a directory to the `viam module upload` subcommand. Either of these will be automatically compressed and added to a temporary tarball that will be uploaded instead.
There is a bit of optimization left on the table because the validate step scans through the archive (after it has been written) but the additional code complexity to take advantage of this inefficiency did not seem worth the cost. (I tested. The validation step was negligible) 
I added the ability to include a whole directory because this is a common use case for cpp modules to ship separate libraries that are still required (so including the entire install dir is reasonable and we dont need to make people …
=> RSDK-5269 - CLI Support single file uploads and auto-compression

services/datamanager/builtin/builtin.go
Colons are not supported in file paths for Windows or Darwin. Replace with an underscore, similar to what we do in the export CLI (https://github.com/viamrobotics/rdk/pull/3039).
**Testing**
Tested capture/sync locally. File paths have underscores, but the synced UploadMetadata still contains the correct type with colons (e.g. `rdk:component:arm`)
=> [DATA-2064] Replace colons in file paths since not always supported

services/datamanager/builtin/builtin.go, services/datamanager/builtin/sync_test.go, services/datamanager/datacapture/data_capture_buffer_test.go, services/datamanager/datasync/sync.go
We already correctly don't retry upload (until the syncer is restarted, e.g. if the robot restarts or you change a sync configuration) if we get an app server error of `InvalidArgument`. This PR still logs here but also moves the files into a failed directory so that they're not retried even if the syncer/robot is restarted. 
**Testing**
Tested on a fake `.prog` file which failed to read the DataCaptureMetadata.
More testing by (@tahiyasalam)
Tested on many fake `.prog` files that were just text.
Tested on many data capture files with no metadata by returning nil [here](https://github.com/viamrobotics/rdk/blob/c0472a4fe60c8a200706912e45fc43aa2a64b967/services/datamanager/datacapture/data_capture_file.go#L109), with the robot [here](https://app.viam.dev/robot?id=095152bb-cc3e-4eec-bbee-9d57 …
=> [DATA-2060] Move corrupted data capture files into a separate directory

components/motor/gpio/motor_encoder.go, components/motor/gpio/motor_encoder_test.go
This still feels pretty hacky, but this change respects the offset of `ResetZeroPosition` by tracking the offset on the motor struct. I'm wondering what we want to do for the situation in which you reset the encoder position. the offset will still be there and I'm not really sure how to disregard it since encoder isn't aware of motor. but maybe this behavior is fine?
=> RSDK-4831: fix ResetZeroPosition for encoded motor

services/datamanager/builtin/builtin.go, services/datamanager/datacapture/data_capture_file.go
Similar to the CLI, restrict the filepath substitutions to OS where colons are not supported — Windows and Darwin.
**Testing**
Tested locally on capture/sync. File paths have underscores (e.g. `~/.viam/capture/rdk_component_arm/fakearm/JointPositions/2023-10-16T17_37_27.47088-04_00.capture`), but the synced UploadMetadata still contains the correct type with colons (e.g. rdk:component:arm)
=> [DATA-2064] Replace reserved characters in the filename in addition to the file directory

cli/data.go, cli/data_test.go, services/datamanager/builtin/builtin.go, services/datamanager/datacapture/data_capture_file.go
Since the filesystem rather than the OS seems to constrain what characters are supported in a filepath, simply always replace reserved characters in both data collection and the export CLI. In both of these use cases, the filepath only affects local capture/export and is not used in the cloud.
Tested capture/sync and export on a Mac.
=> Replace filepath regardless of OS in both collectors and the export CLI

resource/resource_graph.go
In addition to ensuring all of the tests passed (resource package + local robot test), I had an in-between run that computed children/parents with both algorithms. Then invarianted the answers were the exact same. Looking at the history, it was always the intention for the code to be getting children/parents directly.
=> RSDK-5375: Simplify resource graph traversal.

config/module.go, module/modmanager/manager.go
Without this patch, specifying any of these params triggers config diffs every reconfigure.
This is quite the footgun. It might not be a bad idea to change the modmanger module to store a config.Module rather than its own copy of every field.
=> Fix Modmanager Module Config Retrieval

components/motor/i2cmotors/ezopmp.go, components/motor/i2cmotors/ezopmp_nonlinux.go
With this PR, you should be able to use an ezopmp motor with a board implemented as a modular component in a separate process.
This compiles fine, but I don't have a pump to actually try it out further. but the component is not officially documented on our website, there is only a single robot config that includes this component, and it hasn't been online in over a year. So, this component is approximately unused, and if it breaks in some subtle way, we can fix it once we start supporting the component in earnest.
=> [RSDK-5241] Make the ezopmp motor talk directly to the I2C bus

go.mod, go.sum
Opts into [this change](https://github.com/viamrobotics/goutils/pull/211), which will eliminate some flaky tests.
=> RSDK-4293 Upgrade goutils to v0.1.52

web/frontend/package.json
These two dependencies will be built into the NPM bundle until we can discover why they're failing to render in app.
=> Remove prime blocks and core as peer dependencies

resource/graph_node.go, resource/resource_graph_test.go, robot/client/client.go, robot/client/client_test.go, robot/impl/local_robot.go, robot/impl/local_robot_test.go, robot/robot.go, robot/server/server.go, robot/server/server_test.go
[RDSK-3534](https://viam.atlassian.net/browse/RSDK-3534)
Scope [here](https://docs.google.com/document/d/19q8tnosleJvNyT1-ikjqOSPqeZeWmOBS1t8yRzOqaSU/edit#heading=h.tcicyojyqi6c).
Upgrades `api` version to [this commit](https://github.com/viamrobotics/api/commit/57108c60d0da8f46df147a496845bdf2160facd6). Adds `*time.Time lastReconfigured` field to resource graph nodes (similar to `updatedAt`, but optionally contains the `time.Time` at which `SwapResource` was called). Exposes that field with `LastReconfigured` method. Adds `LastReconfigured` field to `robot.Status` and fills that field in `localRobot.Status` method. Converts field to proto in `robot/server`. Converts field from proto in `robot/client`. Adds tests for resource graph, robot client, robot servers and remotes.
=> RSDK-3534 Expose `LastReconfigured` timestamp in resource `Status`

.github/workflows/appimage.yml, .github/workflows/releasecandidate.yml
Restore 32-bit appimage uploads by reverting f171081d
Test run:
- [deploy step](https://github.com/viamrobotics/rdk/actions/runs/6580286212/job/17878197064)
- [links](https://github.com/viamrobotics/rdk/actions/runs/6580286212#summary-17878197064)
These files are indeed in our storage bucket and have the expected executable types:
```sh
$ file viam-server-deploy-appimage-*
viam-server-deploy-appimage-aarch64.AppImage: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=..., stripped
viam-server-deploy-appimage-armhf.AppImage:   ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=..., …
```
=> RSDK-5063 include 32-bit appimage in deployment

cli/client.go
https://viam.atlassian.net/browse/RSDK-5225
currently when using the CLI, when trying to view a robot using a robotID the CLI will call ListRobots, loop look thru the org/location's robots for a match on robotID. 
This change makes it so the CLI does not depend on ListRobots when using a robotID. 
further context: 
cloud robots(used by cloudslam) are not returned by ListRobots, so we cannot use the CLI to view the logs from a cloud robot unless this change is made
=> [RSDK-5225] have robot cli not depend on listrobots

components/movementsensor/gpsnmea/pmtkI2C.go, components/movementsensor/gpsnmea/serial.go
Testing: 
- At startup we now get 0 for linear velocity
- With movement the linear velocity change and 0 is the output when stalled.
=> RSDK-5401: set linear velocity to 0 instead of NaN

pointcloud/basic_octree.go, pointcloud/basic_octree_test.go, pointcloud/basic_octree_utils.go
This implements and tests the `Transform` function for `BasicOctree`, a prerequisite for solving https://viam.atlassian.net/browse/RSDK-5415, as octrees must be able to be transformed into the frame of the base.
Also tagging @nfranczak as I know you worked on octree stuff somewhat recently.
=> RSDK-3743 implement geometry interface functions in basic octree

web/frontend/src/components/slam/index.svelte
https://viam.atlassian.net/browse/RSDK-4174
ticket adjusts the available refresh rates while cloudslam is in use, and additionally sets the default refresh rate to 5Hz instead of manual. The ticket was only supposed to change the refresh rate options so I can remove the default change if preferred.
tested using a local app environment with fake slam. can push the config I used if requested
=> [RSDK-4174] Update refresh rates for cloudslam

robot/session_test.go
Remove the stop deadline checks from sessions tests since it causes flakes. Also remove stop delay checks since it doesn't seem necessary.
Qs:
=> RSDK-2493 remove session stop deadline from test

components/sensor/sht3xd/sht3xd.go, components/sensor/sht3xd/sht3xd_nonlinux.go
It could optionally do that before, but this change removes the choice of going through the board to do it. I don't yet have one of these sensors so haven't tried this on real hardware, but everything compiles, and I think it's a straightforward change. Peter has these sensors and could try it out, or I ought to get one of them this coming week and can try it out then.
There are 3 pre-existing configs that use this component. Two of them have not been online since April, and one hasn't been online since July. The first two look to be 2 identical(?) copies of a BeeRing prototype, and the third claims to be a Mac running a fake board and missing some required fields, so I don't see how that could ever have worked to begin with. @biotinker, you know BeeRing folks; can you let them know about …
=> [RSDK-5242] make sht3xd talk directly to the I2C bus all the time

services/motion/builtin/builtin_test.go
We add `t.Skip` to `TestCheckPlan` to resolve test failures in CI.
The final fix for the flaky test will be covered in RSDK-5404.
=> skip TestCheckPlan

motionplan/motionPlanner_test.go
The root of the problem here is believed to be that we are attempting to run this resource intensive plan at a time when the CPU of the CI machine is very busy.  If we remove the `t.Parallel` call this won't be run at the same time as other difficult motion tests and therefore should un-flake the test.
=> RSDK-5403 fix flaky test TestReachOverArm

web/frontend/package.json, web/frontend/src/main.ts, web/frontend/svelte.config.d.ts, web/frontend/tsconfig.build.json, web/frontend/tsconfig.json, web/frontend/tsconfig.lib.json
Fixes an issue with npm publish in CI I introduced in https://github.com/viamrobotics/rdk/pull/3116
The issue is that `tsc` is used directly to generate `d.ts` files for npm, and without some kind of `include` or `exclude` rules `tsc` would run on the `dist` directory. I  removed previous include rules [here](https://github.com/viamrobotics/rdk/pull/3116/files#diff-265deb75fe9de6e9c242bfe9e5772af619fa0e04f28a2688d602cf712540232eL15). Strangely, setting `dist` in the `exclude` array instead of this solution doesn't solve the problem. If anyone has a better solution I'd love to know!
=> Fix npm publish

components/movementsensor/replay/replay.go
Hey yall, as part of [DATA-1887](https://viam.atlassian.net/browse/DATA-1887), the format of collected movement sensor data changed in a way that would break the parsing of a replay IMU. This pr fixes that and remains backwards compatible by handling both types. After migrating to the new formats fully, the old code can be removed(maybe a new-eng ticket).
**Testing**
I tested this by configuring a replay IMU based on data captured in the new format and verifying no errors appeared in the logs and I was able to see matching IMU data in app.viam.com
[DATA-1887]: https://viam.atlassian.net/browse/DATA-1887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RSDK-5432 Update replay movement sensor to handle new and old data formats

.github/workflows/macos.yml, .github/workflows/pullrequest-trusted.yml
- Add a build step to create a macos binary. Note, this is just for verification, not intended to be used for release.
- Trigger it in pull requests
- https://github.com/viamrobotics/rdk/actions/runs/6632650018
- This is slooow, like 15 minutes. See RSDK-5474, we *could* bottle tflite to speed this up. We could also use the `no_tflite` flag to remove that dependency
- Is it worth adding a Brewfile so this shares config with setup.sh?
=> RSDK-5299 build for macos

motionplan/tpSpaceRRT.go, motionplan/tpSpaceRRT_test.go, motionplan/tpspace/ptgGroupFrame.go
`tpspace.NewPTGFrameFromPTGFrame` was failing when being called with a `solverFrame`.
The actual test for this is part of the MoveOnMap PR, which was failing without this fix. This PR was split out so that smoothing could be working again.
=> RSDK-5476 TP-space properly smoothing from Move calls

.github/workflows/test.yml
- The 'all tests passing' step was consuming test32 but not doing anything with it. Add test32 to printed output and bash test
=> RSDK-5500 consume test32 in rollup

motionplan/plannerOptions.go, services/motion/builtin/builtin.go, services/motion/builtin/builtin_test.go, services/motion/builtin/move_attempt.go, services/motion/builtin/move_request.go, services/motion/motion_test.go, services/motion/pbhelpers.go
[Ticket](https://viam.atlassian.net/browse/RSDK-5420)
1. Ensure that all inputs to MoveOnGlobe (other than the `extra` config params being provided to the motion planner package) are within expected ranges & don't contain invalid values such as NaN.
2. Ensure that if no polling frequencies are provided for replanning pollers, those pollers never execute. This prevents divide by zero issues.
- Change `builtin.newMoveAttempt` to detect if the `PositionPollingFreqHz` and or `ObstaclePollingFreqHz` is 0 & if so, have the corresponding replanners never be scheduled.
-  Add `builtin.ValidatedMotionConfiguration` struct & `builtin.newValidatedMotionCfg` which validates that a `motion.MotionConfig` has valid values & returns either an error if they are invalid, or a …
=> [RSDK-5420] - Handle non positive frequency values for position and obstacle polling

components/gantry/singleaxis/singleaxis.go, components/gantry/singleaxis/singleaxis_test.go
This PR parametrizes gantry testlimit timeout based on `mm_per_rev`, `rpm`, and `length_mm`
=> RSDK-3514: parametrize gantry testlimit timeout 

cli/module_registry.go, components/camera/videosource/logging/logger.go, config/logging_level_test.go, data/collector.go, examples/customresources/demos/complexmodule/client/client.go, examples/customresources/demos/simplemodule/client/client.go, examples/customresources/demos/simplemodule/module.go, logging/level.go, logging/logger.go, logging/logging.go, module/example_test.go, module/module.go, utils/logger.go, web/server/entrypoint.go
The motivation here is that if i have to implement a new logger, I'd like to match the log output. Zap has a very rich set of customization that would be expensive to keep parity with. Thankfully we only use a small subset of it. This patch/refactor removes unused (or lightly used) code and consolidates the configuration down to (nearly) a single spot.
The [first commit](https://github.com/viamrobotics/rdk/pull/3136/commits/af3ccd8fcbb848214fb0690ad91fe475c0ea5232) actually makes changes. The second only moved code within the logging files. It should be sufficient to just review the first commit and sanity check the latter.
Changes (that I hope to remember to add to the commit message):
* `ReplaceGoabl` -> `ReplaceGlobal`
* The `New*Logger` APIs have been reduced to `NewLogger` and …
=> RSDK-5481: Reduce surface area of log creation APIs.

resource/config.go
Compares converted attributes for the data manager service removed in https://github.com/viamrobotics/rdk/pull/2897. 
The associated configs linked [here](https://github.com/viamrobotics/rdk/blob/e0d441fc7815cc4eecc5096ed18054307628cba7/services/datamanager/builtin/builtin.go#L44) and used [here](https://github.com/viamrobotics/rdk/blob/e0d441fc7815cc4eecc5096ed18054307628cba7/services/datamanager/builtin/builtin.go#L358) were no longer detecting changes at the resource-level data manager configuration. If one of the flags was changed or the resource itself was entirely removed, a stale ResourceConfig persisted and was not updated within `Reconfigure`.
Confirmed that this fixes data manager capture/sync issues.
=> DATA-2090 - Compare ConvertedAttributes in data manager configs

.github/workflows/test.yml, Makefile, etc/test.sh, gostream/codec/mmal/encoder.go, gostream/codec/mmal/utils.go
This PR reverts the changes made in https://github.com/viamrobotics/rdk/pull/3000 to hide mmal and instead hide that lib behind a build flag. 
* Tested the build, test, and linter locally.
* Running the changes to `test.yml` [here](https://github.com/bazile-clyde/rdk/actions/runs/6671417812/job/18133286606)
=>  RSDK-4567 hide mmal behind build flags

motionplan/motionPlanner.go, motionplan/motionPlanner_test.go, motionplan/planManager.go, motionplan/tpSpaceRRT.go, motionplan/utils.go, services/motion/builtin/builtin_test.go
This PR will pre-construct a goal tree from a pre-existing plan, allowing solving to happen very quickly.
Note that by far most of our runtime is still spent in smoothing, so this only helps to a point.
=> RSDK-3236 support for requesting a new path from an existing partial plan

components/base/kinematicbase/differentialDrive.go, components/base/kinematicbase/differentialDrive_test.go, components/base/wheeled/wheeled_base.go, components/base/wheeled/wheeled_base_test.go, examples/customresources/models/mybase/mybase.go, spatialmath/errors.go, spatialmath/geometry.go, spatialmath/geometry_test.go, spatialmath/geometry_utils.go
This PR does two things
- removes a warning that was occurring when no geometry was configured for a base
- if no frame is specified for the base the kinematic wrapper wrapping it will assign it a point collision geometry
=> Rework collision geometries for bases

.github/workflows/docker.yml, .github/workflows/license_finder.yml, .github/workflows/npm-publish.yml
With Clyde's latest changes, the old canon images no longer have everything needed to fully build RDK (docker workflow failed multiple times over the weekend), so removing them from workflows.
Test run here: https://github.com/viamrobotics/rdk/actions/runs/6695691340
=> Remove canon

resource/resource_graph_test.go, robot/impl/local_robot_test.go
RSDK-5537
Raises times used in assertions for `LastReconfigured` tests. Times like `5 * time.Second` were causing issues on slow test runners. We just want to assert that `LastReconfigured` is non-nil (if a pointer) and contains a reasonable value.
=> RSDK-5537 Relax LastReconfigured test time assertions

cli/app.go, cli/data.go, cli/module_registry.go
Surprisingly, v2 of our cli library does not auto populate empty string flags (and ignores the default value).
This causes `update-models` to try and open "" (and fail) if the `--module` flag is not provided.
=> Cli fix update-models default module flag value

web/frontend/package.json
This is a temporary measure. Remote control will be moved to use [SvelteKit packaging](https://kit.svelte.dev/docs/packaging). Once that is done we'll be able to sync the version of Svelte between app and remote control and allow Svelte peer dependencies like `prime-core` again without unintended production runtime effects.
=> Remove `prime-core` and `prime-blocks` as peer deps.

cli/app.go, cli/data.go
**Testing**
Successfully tested configuring a user and getting the hostname on the https://pr-2735-appmain-bplesliplq-uc.a.run.app PR deployment from https://github.com/viamrobotics/app/pull/2735 (with actual values redacted):
```
go run cli/viam/main.go data database hostname --org-id={org-id}
MongoDB Atlas Data Federation instance hostname: {hostname}
go run cli/viam/main.go data database configure --org-id={org-id} --password={new-password}
Configured database user for org {org-id}
```
=> DATA-1432 - Add commands to interact with a MongoDB Atlas Data Federation instance to CLI

config/module.go, module/modmanager/manager.go, module/modmanager/manager_test.go, robot/impl/local_robot_test.go
This was discussed in https://github.com/viamrobotics/rdk/pull/3095
I did this refactor to prevent more people running into this surprising behavior.
In that PR, we mentioned that there won't be many more fields added to modules, however, it just came up that more people want to add fields to modules. Doing this preemptively. 
If either of you don't like this change, happy to close and keep things as they are.
=> Refactor modmanager.module to hold config.Module rather than copying fields

components/camera/ultrasonic/ultrasonic.go, components/camera/ultrasonic/ultrasonic_test.go
Hey yall, in testing we found out that the ultrasonic sensor readings were in meters but treated as millimeters. This is a smale PR to fix that.
=> RSDK-5613 Scale ultrasonic readings to millimeters

motionplan/tpSpaceRRT.go, services/motion/builtin/builtin_test.go
There's one function that wasn't being updated properly in pos-only mode, because TPspace needs to use a more complicated goal construction for doing nearest-neighbor
The result being that when checking if we were at the goal, we were properly evaluating the distance to the goal without considering orientation, but when actually extending towards a point (i.e. the goal), we were considering orientation
Result being that even though matching orientation wasn't required for a success, we were still attempting to fulfill orientation
=> RSDK-5593 Correct position-only mode. Add test to verify.

components/movementsensor/mpu6050/mpu6050.go, components/movementsensor/mpu6050/mpu6050_nonlinux.go, components/movementsensor/mpu6050/mpu6050_test.go
...instead of going through the board component to do it.
To get the tests to work, I've split `NewMpu6050` into that function (which constructs a real I2C connection) and `makeMpu6050` (which takes in an I2C connection plus all the same things as `NewMpu6050` and constructs everything else). That latter command can be called during tests to inject a mock I2C bus.
When folks are happy with this code, before I merge this PR I should write a migration script to update the configs in production.
I'm tagging @gvaradarajan for a review because he wrote most of the tests here.
=> [RSDK-5248] make the MPU6050 talk to the I2C bus directly

components/sensor/bme280/bme280.go, components/sensor/bme280/bme280_nonlinux.go
Before this is merged to RDK, we need to have a migration script merged to app! I'll work on that next...
=> [RSDK-5243] Use the raw I2C bus when configuring a BME280 sensor

motionplan/motionPlanner_test.go, motionplan/planManager.go, motionplan/plannerOptions.go, motionplan/rrt.go, motionplan/tpSpaceRRT.go, motionplan/tpSpaceRRT_test.go, services/motion/builtin/builtin_test.go
This seeds the goal tree of TPspace RRT with a variety of orientations when in position-only mode, allowing solving to work bidirectionally (faster) in this mode.
As a drive-by I noticed that the initial node used to seed the first iteration of TPspace RRT was not being computed properly, and was instead at an incorrect orientation, which would have mildly negatively impacted path quality and solve times.
=> RSDK-5095 tp space position only solving should seed the goal tree with different ending orientations

module/modmanager/manager_test.go, robot/impl/local_robot_test.go
RSDK-5439
`TestCrashedModuleReconfigure` was flaking because the `ResourceConfigurationTimeout` was being set too low, and occasionally the test module could not even respond to a ready request in time (`ResourceConfigurationTimeout` [governs](https://github.com/viamrobotics/rdk/blob/main/module/modmanager/manager.go#L674) how long we wait for a module to respond to a ready request). We could raise it even higher, but I thought 2s was enough.
=> RSDK-5439 More intelligently set `ResourceConfigurationTimeout` in `TestCrashedModuleReconfigure`

components/board/genericlinux/i2c.go, components/board/hat/pca9685/pca9685.go
https://github.com/viamrobotics/rdk/pull/3030 let the PCA9685 board either talk directly to the I2C bus or go through its parent board to get to that bus. https://github.com/viamrobotics/app/pull/2811 will migrate all the relevant configs from the old approach to the new one (and I will run that migration when the next release is cut). This PR removes the old approach entirely.
I haven't tried this on actual hardware yet, but will be sure to do that before merging.
=> Talk to the I2C bus your own dang self: PCA9685 redux

components/movementsensor/replay/replay.go, components/movementsensor/replay/replay_test.go
Tickets: 
* https://viam.atlassian.net/browse/RSDK-5315
* https://viam.atlassian.net/browse/RSDK-5304
Done:
* The issue was that the context would timeout while requesting data, which changes the error message that's returned.
Tested 100 times:
```bash
➜  replay git:(kk/rsdk-5315-fix-flaky-test go test -run=TestNewReplayMovementSensor -count=100 -timeout 99999s     
PASS
ok      go.viam.com/rdk/components/movementsensor/replay        1111.645s
```
=> RSDK-5315 - Fix flaky test in replay movement sensor

components/movementsensor/adxl345/adxl345.go, components/movementsensor/adxl345/adxl345_nonlinux.go, components/movementsensor/adxl345/adxl345_test.go, components/movementsensor/adxl345/interrupts.go, components/movementsensor/errors.go
We need to optionally keep the dependency on the board this time, because if you enable any of the interrupts they must still go through the board! but if you _don't_ use interrupts, you don't have a dependency on the board any more.
Github thinks @susmitaSanyal is the person to review this.
To get the tests to work, I split `NewAdxl345` into a part that builds a (real, hardware-backed) I2C bus and a part that takes in an I2C bus and does every thing else, and then we test that second one while passing in a mock I2C bus. and then for tests where we don't do any interrupt-based stuff, we can get rid of the mock board in the dependencies.
Tried on a raspberry pi: we can still talk to the ADXL as expected!
Because we might need to keep the board dependency, the migration script for this …
=> [RSDK-5247] Make the ADXL345 talk to the I2C bus directly

services/datamanager/builtin/builtin.go
Previously, if the selective syncer was enabled but the sensor was improperly initialized, we would sync by default. This was a bug. This PR changes the behavior so that if the selective syncing is enabled but we are unable to initialize the sensor, we do not sync but keep collecting data and trying to reconfigure.
- valid selective syncer with sync enabled and disabled, synced on trigger and did not sync respectively
- regular sync with sync enabled disabled did not sync
- invalid selective with sync enabled did not sync
=> DATA-2107 - Don't sync if selective syncer is broken

services/motion/builtin/builtin_test.go, spatialmath/pose.go
This PR also solves RSDK-5659
The geometry size necessary to not escape the Viam office SLAM map, is too large to adequately explore the octagon SLAM map. This PR makes the geometry size configurable.
Additionally this PR finds and corrects an issue with the PoseAlmostEqualEps function which has likely been the culprit of several flaky tests
=> RSDK-5644 Flaky Test

module/modmanager/manager_test.go, module/module.go, module/module_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-5678
I am glad I did this. The test in `module_test.go` was pretty... awful
=> RSDK-5678 - Module socket path truncation uses randomness which causes problems during module reconfigures

components/base/kinematicbase/fake_kinematics.go, components/base/kinematicbase/fake_kinematics_test.go, motionplan/tpSpaceRRT.go, services/motion/builtin/builtin_test.go
This will ameliorate (not entirely remove, though should make observation highly unlikely) a race condition seen in TestObstacleDetection.
As a drive-by this reduces the number of smoothing iterations run for tp-space for perf reasons, as that was observed to be too expensive.
=> RSDK-5680 Update fake PTG kinematics to take a sleep time

module/modmanager/manager.go, module/modmanager/manager_test.go
Small bug that crept into the cleanup data directory code -- it prints that it is removing the module data directory even if that directory doesn't exist in the first place. This does not cause any adverse runtime effects, it just prints a weird message every reconfigure for people who don't have modules.
Bad behavior: (highlighted with ******) (this robot does not have any modules)
```
2023-11-09T14:24:44.429Z	INFO	robot_server	config/logging_level.go:34	Log level initialized: info
2023-11-09T14:24:44.429Z	INFO	robot_server	server/entrypoint.go:83	Viam RDK{"git_rev":"ae024968ae6aec8d7e4c41d5659561963a536d15"}
2023-11-09T14:24:44.429Z	INFO	videosource	logging/logger.go:138	Starting videosource logger
********2023-11-09T14:24:46.609Z	INFO	robot_server	modmanager/manager.go:564	Removing …
```
=> Fix modmanager cleanup directory log bug

cli/app.go
Full help msg:
```
NAME:
viam module upload - upload a new version of your module
USAGE:
viam module upload <version> <platform> [other options] <packaged-module.tar.gz>
DESCRIPTION:
Upload an archive containing your module's file(s) for a specified platform
Example uploading a single file:
viam module upload --version "0.1.0" --platform "linux/amd64" ./bin/my-module
(this example requires the entrypoint in the meta.json to be "./bin/my-module")
Example uploading a whole directory:
viam module upload --version "0.1.0" --platform "linux/amd64" ./bin
(this example requires the entrypoint in the meta.json to be inside the bin directory like "./bin/[your path here]")
Example uploading a custom tarball of your module:
tar -czf packaged-module.tar.gz ./src requirements.txt run.sh
viam module …
```
=> APP-3077 - Include additional module platforms

config/reader.go, go.mod
Ticket: https://viam.atlassian.net/browse/RSDK-5572
Result of testing on physical hardware: 
Tested on RPI0W1.1 (armv6) => success (reports arm32v6)
Tested on RPI4 (32b) => success (reports arm32v7)
=> RSDK-5572 - Change agentinfo platform reporting for arm to use new variants

components/motor/tmcstepper/stepper_motor_tmc.go, components/motor/tmcstepper/stepper_motor_tmc_nonlinux.go, components/motor/tmcstepper/stepper_motor_tmc_test.go
I haven't yet tried this out on real hardware; that's the next step. and the step after that is to make a migration script in the app repo to update the pre-existing configs. Changes in this PR include:
- the component should only build and only have tests for Linux. The Mac build doesn't have a way to talk to the SPI bus directly.
- We've split `NewMotor` into that function (which constructs an SPI bus and calls the second half), and `makeMotor` (which does everything else). This lets us use `makeMotor` in tests while passing in a fake SPI bus.
- The `"spi_bus"` entry in the config should now describe the actual SPI bus on the OS, such as `"0"` or `"1"`, rather than something named in your board's config like `"main_spi_bus"`. 
- If you haven't configured an enable pin, you don't need a …
=> [RSDK-5249] Make the TMC Stepper motor controller talk to the SPI bus directly

services/datamanager/datasync/sync.go
The offending error not exported directly ([here](https://github.com/protocolbuffers/protobuf-go/blob/a8317fb7c5685299af5de3be21c5514f65837202/proto/decode.go#L294)), so instead using [Error](https://github.com/protocolbuffers/protobuf-go/blob/a8317fb7c5685299af5de3be21c5514f65837202/proto/proto.go#L26) from the protobuf package that apparently matches all errors from that package. I think this should be fine, since we likely do not want to retry in this event, since the protobuf errors are not transient.
=> Add check for protobuf errors (e.g. invalid wire format)

components/sensor/collector_test.go, data/collector.go
Autocasting to a pointer does not work and will fail to detect that the message is a GetReadingsResponse type, and lint was previously erroring that the assignment copied a lock value. Instead, use reflection to check the type and pass the readings directly.
=> DATA-fix - Fix GetReadingsResponse special-case check

web/server/entrypoint_arm64.go
Currently, there is an issue setting up the encoder factory on non-raspberrypi arm64 devices where the encoder check thinks that `V4l2m2m` codec is available since it is built into ffmpeg but is not supported by the OS.
This PR simply attempts to open up the encoder to determine if it is actually supported.
___
Tested that h264 encoder factory works on RPI and x264 works on Jetson.
=> Hotfix to check if h264 encoder is supported by the OS

web/frontend/src/components/navigation/hooks/use-nav-mode.ts
See the error on TS-SDK version bump here: https://github.com/viamrobotics/rdk/actions/runs/6815121936
A new value was added to the enum but the typings defined for nav mode in RDK were hard coded. This makes the type dynamic to the possible enum values.
=> Fix: improve nav mode types to be resilient to upstream changes

services/motion/builtin/builtin_test.go
This was a math error. Position only mode will result in a goal orientation that is a multiple of 22.5 degrees.
The intention for this test was to select a goal orientation sufficiently far from such a multiple such that it would not be represented in the possible goals, and thus have a different ending orientation.
Unfortunately, I failed to do basic math when I wrote that test and instead made the goal orientation 45, a perfect multiple of 22.5, thus giving this test a 1/16 chance of failing.
=> RSDK-5699 Fix flaking test

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/api/power-sensor.ts, web/frontend/src/components/navigation/index.svelte, web/frontend/src/components/power-sensor/index.svelte
this will currently not pass checks because I have made one more typescript change that needs to be reviewed and merged.
Description from JIRA: 
Recently TypeScript SDK changes were made which removed the types MovementSensorReadings and PowerSensorReadings, because there is now an API for MovementSensor and PowerSensor which should make these types obsolete. For MovementSensor, no issues. However for PowerSensor, the RC card is now broken because it relied on that PowerSensorReadings type. 
Ideally, this type wouldn’t be necessary, because MovementSensor and PowerSensor both rely on the same API from common, so neither of them should need a *sensorReadingsType. Since MovementSensor is still working correctly, hoping that power-sensor/index.svelte can be updated accordingly to match the …
=> RSDK-5708: Modify PowerSensor implementation to follow MovementSensor implementation for the RC card

components/motor/gpio/basic.go
Bug was introduced in this commit: https://github.com/viamrobotics/rdk/commit/85163fd8a8b452269531054926e4407838aa6964
=> fix enable pin bug when turning off gpio motor

services/datamanager/datasync/sync.go
Tested locally with the file from the canary bot and observed that the file is moved to the quarantine directory and not uploaded.
=> DATA-2120 - Do not retry on `cannot parse invalid wire-format data`

components/movementsensor/gpsnmea/gpsnmea.go, components/movementsensor/gpsnmea/pmtkI2C.go, components/movementsensor/gpsnmea/pmtkI2C_nonlinux.go, components/movementsensor/gpsnmea/pmtkI2C_test.go, components/movementsensor/gpsnmea/serial_test.go, components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go, components/movementsensor/gpsrtkpmtk/gpsrtkpmtk_nonlinux.go, components/movementsensor/gpsrtkpmtk/gpsrtkpmtk_test.go, components/movementsensor/rtkutils/ntrip.go
The rough idea here is that, when you specify an I2C bus, you give it the bus number instead of a board name and i2c entry on that board. Then, we're not dependent on the board at all, and it's possible to use this sensor even if your board is a modular component running outside the RDK entirely.
This is a breaking change, but there are currently _no_ configs that use `gps-nmea-rtk-pmtk` components, and only 2 that use `gps-nmea` with I2C connections. Of those two, one is owned by @biotinker and he and I are already in contact about updating it, and the other was a PoC that hasn't been online since February. I'll announce the breaking change in the relevant channel anyway. 
I don't have a Mac, and worry that this change might break the build on Macs again. Susmita, could we try building …
=> [RSDK-5245] [RSDK-5246] Remove board dependency on GPS I2C devices

services/motion/builtin/builtin.go, services/motion/builtin/builtin_test.go, services/motion/builtin/state/state.go, services/motion/builtin/state/state_test.go, services/motion/client_test.go, services/motion/motion.go, services/motion/motion_test.go, services/motion/server_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-4810) [Other Ticket](https://viam.atlassian.net/browse/RSDK-5158)
This is a sub PR that implements some self contained changes required for the main PR: https://github.com/viamrobotics/rdk/pull/3204
The builtin changes are needed to ensure that motion doesn't break when it reconfigures & that it doesn't leak resources when closed.
The motion.go changes are to provide more descriptive types for users of the API & make the plan state machine more explicit.
The change from uuid.NewUUID -> uuid.New is to remove unnecessary error handling that caused a lot of unnecessary noise in the code.
Changes:
- Rename motion.builtin.lock to motion.builtin.mu (to follow go convention)
- Add state member to motion.builtIn struct 
- Implement Close() for …
=> RSDK-4810-add-state-to-builtin

module/modmanager/manager.go, module/modmanager/manager_test.go, module/testmodule/main.go
Ticket: https://viam.atlassian.net/browse/RSDK-5709
This sets the module CWD to `dirname m.cfg.ExePath`
For reasoning, see the discussion on the linked google doc.
This PR is a measure to arrive at consensus (so discussion is expected and it is totally fine with me if we close this PR and decide to solve this some other way)
=> RSDK-5709 - Module CWD should not be viam-server CWD

robot/client/client.go
RSDK-5365
Only applies `defaultResourcesTimeout` when not in a test.
My guess is this is also related to the following failures: RSDK-5365, RSDK-4969, RSDK-3837 and RSDK-5595. Curious if you all agree (I'm looking for an inability to connect to a remote after a 5 second gap in logs, and an assertion failure related to not finding expected remote resources).
=> RSDK-5365 Do not apply defaultResourcesTimeout in tests

config/config.go, config/config_test.go, config/placeholder_replacement.go, config/proto_conversions.go, config/proto_conversions_test.go
I checked and migrated all robots that had a missing package type before doing this. Now users will get an error in robot logs if type is missing or unsupported.
=> APP-2950: remove package type defaults

cli/app.go, cli/archive.go, cli/module_registry.go
I was working on another PR and noticed that we had forgotten to clean up the `name` field from the original versions of the cli.
This is a bit of cleanup... This whole file should be split into multiple smaller pieces, but it works for now
I've manually tested:
module creation (on an org with namespace & on org without namespace)
module update (on an org with namespace & on org without namespace)
module upload (on an org with namespace & on org without namespace)
@michaellee1019 It might seem like there are lots of details, but most of the changes are just from moving a few big functions.
=> Remove Module manifest Name field and small refactor

components/encoder/ams/ams_as5048.go, components/encoder/ams/ams_as5048_nonlinux.go, components/encoder/ams/ams_as5048_test.go
tested on scuttle AMS encoders. This change also needs a change in app to remove board from the "fancy config" and a migration script.
=> RSDK-5244 Make the AMS encoder talk to i2c bus directly

components/board/genericlinux/board.go, components/board/genericlinux/board_test.go, components/board/genericlinux/config.go, components/board/mcp3008helper/mcp3008.go, components/board/pi/impl/board.go
Tried on both a raspberry pi and a jetson orin: works on both!
Here's an example of the old config for a board:
```
{
"model": "pi",
"name": "main_board",
"type": "board",
"spis": [
{
"bus_select": "0",
"name": "main_spi_bus"
}
],
"analogs": [
{
"name": "reader",
"pin": "0",
"spi_bus": "main_spi_bus",
"chip_select": "24",
"average_over_ms": 100,
"samples_per_sec": 20
}
]
}
}
```
and here's an example of the new version:
```
{
"model": "pi",
"name": "main_board",
"type": "board",
"spis": [],
"analogs": [
{
"name": "reader",
"pin": "0",
"spi_bus": "0",
"chip_select": "24",
"average_over_ms": 100,
"samples_per_sec": 20
}
]
}
}
```
This shouldn't be merged until we've got a way to migrate the configs for all the boards …
=> [RSDK-5251] Get the analog readers on all boards to configure their SPI buses themselves

components/board/board.go, components/board/client.go, components/board/client_test.go, components/board/fake/board.go, components/board/fake/board_test.go, components/board/genericlinux/board.go, components/board/genericlinux/board_test.go, components/board/hat/pca9685/pca9685.go, components/board/numato/board.go, components/board/pi/impl/board.go, components/movementsensor/rtkutils/gpsrtk_test.go, components/servo/gpio/servo_test.go, robot/impl/local_robot_test.go, robot/impl/resource_manager_test.go, testutils/inject/board.go
There will be another PR for this ticket to do more of this once #3215 is merged, but this is a start and it's already a pretty big PR, so I'll send this out as-is. Now that all components talk to their I2C and SPI buses directly, there is no need for a component in the RDK to request either the names or access to any named buses from the board. Time to remove that as dead code!
If this PR is large, you can go commit-by-commit to get simpler subpieces. Once #3215 is merged, we can also remove `I2CByName` similar to `SPIByName`, which in turn will let us remove the entire `LocalBoard` struct (so there's no distinction between a board and a local board).
and the next next step is to remove the "i2cs" and "spis" sections from the board configs, but that's a totally different Jira ticket.
=> [RSDK-5621] Remove unused I2C- and SPI-related functions

components/arm/client.go, components/arm/client_test.go, components/arm/fake/fake.go, components/arm/server.go, components/arm/server_test.go, components/arm/wrapper/wrapper.go, module/modmanager/manager_test.go, motionplan/kinematic_test.go, referenceframe/model_json.go, referenceframe/urdf/model.go, referenceframe/urdf/model_test.go
This PR makes it possible for an arm model within the RDK to return a kinematic representation in a format other than SVA, which is all that was previously possible.
=> RSDK-5742 return raw kinematics file from arm server

gostream/codec/h264/encoder.go, gostream/codec/h264/ffmpeg/avcodec/avcodec.go
See [RSDK-5791](https://viam.atlassian.net/browse/RSDK-5791). This PR fixes the two errors in the lines below. They appear on RPis even without a camera component.
```
Nov 16 20:29:01 viamrostwo viam-server[12190]: [h264_v4l2m2m @ 0xffff78000b70] Using device /dev/video11
Nov 16 20:29:01 viamrostwo viam-server[12190]: [h264_v4l2m2m @ 0xffff78000b70] driver 'bcm2835-codec' on card 'bcm2835-codec-encode' in mplane mode
Nov 16 20:29:01 viamrostwo viam-server[12190]: [h264_v4l2m2m @ 0xffff78000b70] requesting formats: output=YU12/yuv420p capture=H264/none
Nov 16 20:29:01 viamrostwo viam-server[12190]: [h264_v4l2m2m @ 0xffff78000b70] Failed to set timeperframeFailed to set gop size: Invalid argument
```
I manually tested this by running the server - you don't need to enable debug logs - and …
=> RSDK-5791: fix HW encoder failure messages on RPis

config/logging_level.go
RSDK-5806
Actually calls `logger.SetLevel` in `InitLoggingSettings`.
`InitLoggingSettings`, from what I can tell, is what's called on the initial logger passed into `robotimpl.New` from the web server entrypoint to appropriately set the global log level based on the presence of `-debug` and/or "debug" in the JSON config. While this allows correct debug-level logging for most logs, the module manager [checks](https://github.com/viamrobotics/rdk/blob/main/module/modmanager/manager.go#L812) the level of _its_ passed-in logger, not the global log level, to determine if `--log-level=debug` should be passed as a CLI argument to the module process. We _could_ check `logging.GlobalLogLevel` in the module manager, but that means that tests like …
=> RSDK-5806 Set logger.Level not just GlobalLogLevel

robot/packages/cloud_package_manager.go
I refactored the logic to detect if there are package changes into a common function. I did this so we could have an overall message that records when the package sync starts (and actually does something) and then print out the total time that processing package downloads took.
I did the refactoring this way because I wanted to log the message only when there are actual package changes that will be made, and don't want to print it out every 10 sec when the sync process runs.
Results in:
```
11/16/23, 4:51:38.315 PM   info   robot_server.package_manager   packages/cloud_package_manager.go:198   Package sync complete after 664.170848ms  
11/16/23, 4:51:37.651 PM   info   robot_server.package_manager   packages/cloud_package_manager.go:133   Package changes have been detected, starting sync …
```
=> Add info messages for package download time.

components/board/board.go, components/board/client.go, components/board/fake/board.go, components/board/genericlinux/board.go, components/board/hat/pca9685/pca9685.go, components/board/numato/board.go, components/board/pi/impl/board.go, robot/client/client_test.go, robot/impl/local_robot_test.go
Turns out this wasn't used anywhere except tests! Super easy to take out: we don't even need to keep it around in some separate non-board package.
=> [RSDK-5809] Remove board.ModelAttributes

services/vision/client.go, services/vision/client_test.go
In maybe the silliest over-sight of the year, we never updated the default mime type for encoding images that we sent over the vision service. We didn't even check for the requested MIME type in the context. We just always assumed raw RGBA encoding.
This should have been fixed with https://viam.atlassian.net/browse/RSDK-1153 when we switched it over for cameras, but forgot to do it for the vision service.
This will speed up the vision service as well, since we won't be encoding/decoding raw images any more over the wire.
=> RSDK-5818: Check context for mimetype when calling client Classification/Detections

.github/workflows/appimage.yml
- new release of the gcp auth action breaks compatibility with our environment (release info [here](https://github.com/google-github-actions/auth/releases/tag/v1.2.0))
- specifically because node20 is not compatible with the glibc in our base image
- this PR temporarily downgrades to 1.1.1 for old behavior while we investigate what to fix in our base image
- https://github.com/viamrobotics/rdk/actions/runs/6947880375/job/18902654503#step:6:15
- (this failed because I set 'release type' to a bad value, but the auth step succeeded)
=> downgrade action step

motionplan/solverFrame.go, motionplan/utils_test.go, services/motion/builtin/move_request.go, services/motion/localizer.go, spatialmath/geo_obstacle.go, spatialmath/geo_obstacle_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-4810)
This PR adds spatialmath & motionplan helper functions required to convert a motion plan into the geopoints the robot will move to during the plan.
- Add `motionplan.PlanToPlanStepsAndGeoPoses` which converts a plan to the relative poses the robot will move to (relative to the origin) & the geo poses.
- Add `spatialmath.GeoPoseToPose` and `spatialmath.GeoPointToPoint`
- Remove `spatialmath.GeoPointToPose` as it's api was confusing (returned a pose who's orientation was always the zero orientation). Its functionality is now subsumed by  `spatialmath.GeoPointToPoint`
=> RSDK-4810-spatialmath-and-solverframe

gostream/media_utils.go
Encountered a small edge case where the context had an empty mime type in its hint
=> RSDK-5818: small edge case of empty MIMEType hint

components/board/fake/board.go, web/frontend/src/components/board/index.svelte
Adds the get analog option to poll the value of an analog pin.
I think we could remove the top analogs section that displays all the analog readers by name and their values now that we have this ? Lmk if I should remove in this PR.
=> RSDK-5739 Add Get Analog to board RC card

services/motion/builtin/builtin_test.go
This is one that keeps coming up and is likely the result of a bug that I documented on RSDK-5758. That ticket is still under review and the unskipping of this test will come with its resolution
=> 5883 skip a flaky test

resource/graph_node.go, resource/graph_node_test.go, robot/impl/resource_manager.go
This reverts commit 4be5f0d9c07e9feb9b4f4d971f178e09c30b2279.
This is causing configuration flows to abort too early for cameras.
=> Revert "RSDK-4307: Add max reconfig limit per resource (#3018)"

cli/module_registry.go
In a different PR (https://github.com/viamrobotics/rdk/commit/052b2e96938acfb904864074eaada3f475e314ae), I performed a bad rebase which removed this change. This brings it back
=> Add omitempty to fix bug (undo bad rebase)

components/base/kinematicbase/ptgKinematics.go, services/motion/builtin/builtin.go, services/motion/builtin/builtin_test.go, services/motion/builtin/move_request.go, services/motion/builtin/state/state.go, services/motion/builtin/state/state_test.go, services/motion/builtin/state/verify_main_test.go, services/motion/motion.go, services/motion/motion_test.go, spatialmath/geo_obstacle_test.go
First Attempt: https://github.com/viamrobotics/rdk/pull/3010
Second Attempt: https://github.com/viamrobotics/rdk/pull/3238
https://viam.atlassian.net/browse/RSDK-4810
https://viam.atlassian.net/browse/RSDK-4811
https://viam.atlassian.net/browse/RSDK-4812
https://viam.atlassian.net/browse/RSDK-4814
- change moveReqeusts of type MoveOnGlobe to include steps which are smuggled geoposes.
- create services/motion/builtin/state package to manage the state of the builtin motion service's executions, which supports starting executions, stopping executions by resource, stopping all executions from a motion/builtin/state struct, recording succeeded & failed replans, recording succeeded & failed ends to executions, recording stopped executions, and recording plan status updates, all such that data …
=> RSDK-4810 integrate StopPlan and MoveOnGlobeNew with ExecutionId system

components/encoder/incremental/incremental_encoder.go, components/motor/gpio/motor_encoder.go
Add a lock to accessing offset in reset zero position for component:gpio:motor, tested with a single and incremental encoder. Ran the test a few hundred times with `go test -race`. Let's see what CI does
=> RSDK-5508 Test Datarace: go.viam.com/rdk/components/motor/gpio.TestMotorEncoder1

web/server/entrypoint_arm64.go
Tested on Raspberry Pi 4 (bullseye) to confirm that streams are working well.
=> Default to x264 on arm64/linux

components/camera/videosource/static.go, services/vision/detectionstosegments/detections_to_3dsegments_test.go, vision/segmentation/detections_to_objects.go
Now that the getImages method is available, the detection to 3D segments model can be sped up.
Needed to add the Images method to the static source and file source cameras
=> Using get_images to speed up detection and projections

components/camera/videosource/logging/logger.go
This may be causing the server to hang on shutdowns. Either way, we should definitely make CLI commands preemptable.
* I could not reproduce the error since it's non-deterministic.
* I tested that the logs are still written to the log file under `~/.viam/debug/components/camera/*`, both with and without cameras.
=> preempt logger CLI cmds

components/board/genericlinux/gpio.go, components/board/genericlinux/pin_types.go, components/board/pi5/board.go, components/board/pi5/data.go, components/board/register/register.go
Not tested at all yet; I'll try it out on Monday. but I'm excited to have this already!
Thanks to non-Viam-employee [Dan Makes Things](https://www.makerforge.tech/posts/viam-custom-board-pi5/) for the head-start on this!
**Setup:** first, you need to edit `/boot/config.txt` on your pi5 to add the following line somewhere:
```
dtoverlay=pwm-2chan
```
and then power cycle your machine (I'd expect a reboot would be enough, but that didn't work for me. Maybe I needed to reboot twice?).
**Limitations:**
- ~~In theory, pins 27 and 28 ought to have GPIO capabilities. Dan and I couldn't figure out which lines on the GPIO chip they were, so we skipped them and I left a comment.~~ edit: Rand notes that [these pins should remain unused](https://www.raspberrypi.com/documentation/computers/images/GPIO- …
=> [RSDK-5895] Add support for a rpi5 board!

web/frontend/src/components/camera/index.svelte
Quick fix for camera streaming issues. First the legacy prime select seems to be emitting two events, a regular one and a custom one. I added a check to make sure we only attempt to evaluate the custom event, this should not be a requirement moving forward using prime-core.
Another fix was to pass the `triggerRefresh` value to the `<Camera />` component so manually refreshing cameras will work.
=> Fix camera refresh event and triggering

services/motion/builtin/builtin.go, services/motion/builtin/builtin_test.go, services/motion/builtin/state/state_test.go, services/motion/client.go, services/motion/client_test.go, services/motion/explore/explore.go, services/motion/motion.go, services/motion/server.go, services/motion/server_test.go, services/navigation/builtin/builtin.go, services/navigation/builtin/builtin_test.go, services/navigation/client_test.go, services/navigation/path.go, services/navigation/path_test.go, services/navigation/server_test.go, testutils/inject/motion_service.go
Tickets:
https://viam.atlassian.net/browse/RSDK-5161
https://viam.atlassian.net/browse/RSDK-4819
https://viam.atlassian.net/browse/RSDK-5193
https://viam.atlassian.net/browse/RSDK-5525
- Change `nav.SetMode` to call `motion.MoveOnGlobeNew` rather than `motion.MoveOnGlobe` & poll `motion.PlanHistory` until the plan terminates, retrying the waypoint on failure & moving on to the next waypoint on success. Also (for use by nav.Paths) record the executionID & waypoint of the in progress moveOnGlobe call & unset it when moveOnGlobe terminates. 
- Change nav to always set position only mode on motion
- Uncomment the tests cases for `nav.SetMode` that affect waypoints & fix the tests to work with `motion.MoveOnGlobeNew`
- Implement `nav.Paths`
- Change MoveOnGlobeNew's go interface method to …
=> RSDK-5161 make Navigation service use MoveOnGlobeNew

etc/configs/fake.json, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/api/navigation.ts, web/frontend/src/api/types/navigation.ts, web/frontend/src/components/navigation/lib/geometry.ts, web/frontend/src/components/navigation/stores.ts
This renders transient obstacles in a different color than static ones and closes out [RSDK-4028](https://viam.atlassian.net/browse/RSDK-4028).
- Bump RC version
- Add labels to fake config for testing
- Update to latest `prime-blocks`
- Use types exposed by `prime-blocks` to avoid duplicated types
- Update obstacle name to use geometry labels
- Render transient obstacles a different color
[RSDK-4028]: https://viam.atlassian.net/browse/RSDK-4028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RSDK-4028: Render transient obstacles

motionplan/tpSpaceRRT.go, motionplan/tpSpaceRRT_test.go
Currently, if a PTG is evaluated for extendability and hits an obstacle, the whole PTG is discarded.
This PR updates behavior such that for the forwards tree, we are able to extend with the good section of the PTG rather than discarding it entirely.
=> RSDK-5942 ptgs should be able to partially extend

services/motion/builtin/builtin.go, services/motion/builtin/builtin_test.go, services/motion/builtin/move_request.go, services/motion/motion_configuration.go, services/motion/motion_test.go, services/navigation/builtin/builtin.go, services/navigation/builtin/builtin_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-4512)
- Update default motion configuration (used by motion.MoveOnGlobe) to the values used during hardware testing for both motion & nav
```go
defaultAngularDegsPerSec = 20.
defaultLinearMPerSec     = 0.3
defaultObstaclePollingHz = 1.
defaultPlanDeviationM    = 2.6
defaultPositionPollingHz = 1.
defaultSmoothIter           = 20
```
=> RSDK-4512 - Update default motion configuration

cli/module_registry.go
Update docs link to use `viam module` CLI reference parent header, rather than its `create` | `update` | `upload` subsection table named `Command options`.
- This should help future-proof us as well, since these parent anchor targets only change when eng changes the names of these commands! ;)
=> Update docs link

rimage/transform/cmd/extrinsic_calibration/main.go, rimage/transform/cmd/extrinsic_calibration/main_test.go
Fixes the flaky test. I mocked out `transform.RunPinholeExtrinsicCalibration` since it 
1. relied on a random number generator ([link](https://github.com/viamrobotics/rdk/blob/5c1ac8c233d7c9bbcac57b99dc80a909f7cf4a0d/rimage/transform/calibrate_pinhole_extrinsics.go#L50)) and 
2. was only a wrapper around a third-party library function, `optimize.Minimize`
We should _not_ rely on random number generators in unit tests since it is, by design, non-deterministic and can likely result in flaky tests that are difficult to track down. Unit tests should also not test third-party library code. That's better handled in integration or end-to-end tests. 
I ran the tests 10,000 times, and each time passed.
```
go test -count 10000 ./rimage/transform/cmd/extrinsic_calibration
```
=> RSDK-6006 flaky extrinsic_calibration test on golang 1.21

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/api/navigation.ts, web/frontend/src/components/navigation/hooks/use-obstacles.ts, web/frontend/src/components/navigation/index.svelte, web/frontend/src/components/navigation/stores.ts
- Bump `@viamrobotics/remote-control` version
- Add `useObstacles` hook to poll for obstacles (including transient ones)
- `getObstacles` => `formatObstacles`
- Get rid of global `obstacles` store
- Remove dependency on `svelte-inview`
- Fix criteria for transient obstacles (label starts with `transient`)
=> RSDK-4028: Poll for transient obstacles in nav card

cli/module_registry.go, module/modmanager/manager.go, module/modmanager/manager_test.go, robot/impl/local_robot.go, robot/impl/resource_manager.go, robot/impl/resource_manager_test.go
@benjirewis - Feels like we should be able to do this without much issue, though I'm not sure if there was a reason why we didn't do this before.
The behavior before was that if you startup the server and realize that the module is broken, ctrl+c ing the server will only exit the server after 90s no matter what. now you can ctrl+c and the server will exit.
However, if you don't ctrl+c the server, the next bit of configuration (next module, starting the webserver) will only start after the startup timeout (5mins). Added another ticket to exit the loop early if the process is not in recovery or running (RSDK-6030).
=> RSDK-5952 - Exit server on ctx cancel even if module is stuck

components/camera/replaypcd/replaypcd.go, components/camera/replaypcd/replaypcd_test.go, components/camera/replaypcd/replaypcd_utils_test.go
https://viam.atlassian.net/browse/RSDK-5961
This PR changes the replaypcd sensor's behavior when caching a batch of data. Before when using a batch size greater than 1, the replaypcd would make BinaryDataByID calls to app to pull down a batch of data. Now the replaypcd sensor will use the url from the BinaryDataByFilter metadata to make an http request for data from gcs directly.
tested locally using a replay sensor with and without cartographer. Testing with cloudslam soonTM.
=> [RSDK-5961] update replaypcd to pull batched data from gcs

cli/app.go, cli/module_build.go, cli/module_build_test.go, cli/module_registry.go
Ticket: https://viam.atlassian.net/browse/RSDK-6027
Allows for:
`viam module build logs --id xyz123 --wait` => wait for all platforms to build and then print all logs
`viam module build logs --id xyz123 --platform linux/amd64 (--wait / no wait)` => wait for and print just the logs for that platform
`viam module build list --id xyz123` => can now be run outside of the dir with the meta.json (because it doesn't need it)
=> RSDK-6027 - Add wait functionality to cli logs + allow for platform omission

logging/impl.go
This worked for the issue I reproduced. Can you double check this works for you @cheukt?
=> RSDK-6063: Obey debug logger level when downconverting rdk logger -> zap logger.

.github/workflows/test.yml, Makefile, etc/test.sh, services/vision/obstaclesdistance/obstacles_distance_test.go, utils/parallel.go, vision/segmentation/chunks_test.go, vision/segmentation/er_ccl_clustering_test.go, vision/segmentation/plane_segmentation.go, vision/segmentation/plane_segmentation_test.go
tl;dr This attempts to fix some issues around using go 1.21 and testing.
Problem 1: Go 1.21 now imports and init()s packages in a well-defined order. This breaks some stuff in vision that was using init() to set global vars during testing. This attempts to fix those issues as they are effectively "bugs."
Problem 2: A secondary problem is that go test with "-coverprofile" enabled runs *very* slow when combined with "-race" and that problem magnifies the more concurrent processes there are. To fix this, the test.sh and makefile are updated to run seperate -race and then -coverprofile test runs.
These sum to the fact that, due to *bad* behavior happening (e.g. one test/file was setting a global, and it was being applied to ALL tests in the package) we were getting away with the coverage …
=> Go 1.21 Parallelism and Test Fixes

components/board/jetson/data.go
These have never worked, and can never work until we have someone (possibly a helpful user on Discord?) with the hardware. All this hardware has been discontinued, and can only be bought secondhand from places like eBay. We can add any of this back in again later if such a Discord user shows up.
=> [RSDK-3596] remove broken board definitions for discontinued jetson models

components/board/client_test.go
it's actually expected for an error of some kind, but actually put something in the inject so it doesn't panic
=> RSDK-6091 - Fix board test panic

components/movementsensor/dualgps/dualgps.go, components/movementsensor/dualgps/dualgps_test.go, components/movementsensor/properties.go, components/movementsensor/register/register.go, components/movementsensor/utils.go, components/movementsensor/utils_test.go
This PR implements a driver "dual-gps-rtk" that uses two GPS chips mounted on a vehicle to calculate the heading between them with a known offset to the vehicle's heading. See pictures in scope: https://docs.google.com/document/d/1khQS1HBJDZGyUFttJzdmT1dwRMU3lTIaqIK4MY2G7ew/edit#heading=h.tcicyojyqi6c
Not doing- implementing anything other than CompassHeading.
Still has to be tested outdoors.
=> RSDK-5933 Implement dual-gps-rtk movementsensor model

cli/app.go, cli/module_build.go
```
➜  cli git:(zp/refcli) ✗ viam module build start --help
NAME:
viam module build start
USAGE:
viam module build start [command options] [arguments...]
DESCRIPTION:
start a remote build
OPTIONS:
--module value   path to meta.json (default: "./meta.json")
--ref value      git ref to clone when building your module. This can be a branch name or a commit hash (default: "main")
--version value  version of the module to upload (semver2.0) ex: "0.1.0"
```
=> Add ref to module build start

services/datamanager/datasync/upload_arbitrary_file.go
Error in `uploadArbiraryFile` if it has been modified in the past 10 seconds, which is the same default as in the data manager.
**Testing**
Wrote to three files: one every 5 seconds, another every 10, another every 20 seconds, and synced files every 6 seconds. The 5 and 10 second files overlapped in a way that they were never passed into `SyncFile` within the data manager based on [this check](https://github.com/viamrobotics/rdk/blob/fa7f86261a32a5b2fda6451b1610f1acef775a72/services/datamanager/builtin/builtin.go#L615-L616). The 20 second file was passed into SyncFile but consistently errored within this new `datasync` check.
Since an error is returned, this correctly gets logged to the console and the sync is retried since it is a [retryable …
=> DATA-2135 - Error and retry if an arbitrary file gets modified during sync time

components/movementsensor/gpsrtkserial/gpsrtkserial.go
Background: 
Sometimes ntrip caster connection is flaky. We rely on getting ntrip stream upon successful connection to caster. This flaky connection causes panic later in the code.
To prevent this, I added a retry logic where we will check for a successful connection 5 times and if we fail after that, we can error out of the function. This prevents the panic later in the code since most flaky connection is resolved within 3 tries. 
This PR also includes fixes for https://viam.atlassian.net/browse/RSDK-6077 and https://viam.atlassian.net/browse/RSDK-6078.
=> RSDK-6076: prevent panic. 

web/frontend/src/components/slam/index.svelte
Prevents double clicking on `Start Session` from generating multiple live cloud SLAM sessions
**JIRA Ticket:** https://viam.atlassian.net/browse/RSDK-5962
**Related PRs:** https://github.com/viamrobotics/app/pull/3160
=> RSDK-5962 Double Click Generates 2x Live Mapping Sessions

components/movementsensor/merged/merged.go, components/movementsensor/wheeledodometry/wheeledodometry.go
This adds a log statement to report which named movement sensor (merged) or base and motor pairs (wheeled odometer) is being used in the list or potential dependences given by the user in the config.
=> RSDK-6068 Add debug logger statements to wheeled_odometry and merged movement sensor

services/vision/mlvision/ml_model.go
Sometimes, the shapes or names of the output tensors do not match what ml model expects. 
Like in the following example, the input tensor is called "input_tensor" and not "image". And there are more output tensors than necessary for the ml model, and it didn't know that "detection_boxes" or "detection_classes" were where the relevant info was stored. 
Now that the logs shows the names and shapes of the output tensors, it will be easier to rename the output tensors and have the models work with the mlmodel service. In the config for the triton model, I can now do
```
"tensor_name_remappings": {
"inputs": {
"input_tensor": "image"
},
"outputs": {
"detection_scores": "score",
"detection_boxes": "location",
"detection_classes": "category"
}
```
which will fix the problem and the model will …
=> RSDK-5929: Add tensor names and sizes to logs for easier debugging upon mlmodel failure

motionplan/tpSpaceRRT.go, services/motion/builtin/builtin.go
The use of `defaultIdenticalNodeDistance` was mostly preventing any smoothing iteration from running, an issue that was exacerbated after merging RSDK-5758.
RSDK-5758 additionally made it unnecessary to run a second iteration of the smoother to reconnect to the goal, accounting for any drift from the smoothing connection. This should improve smoother runtimes substantially.
Accordingly I increased the default number of smoother iterations slightly; experimentation showed 30 providing a large improvement over 20.
=> RSDK-6145 TP-space smoothing is not functioning

components/movementsensor/imuwit/imu.go
If a wit imu is disconnected when viam server is running, we're in danger of forever spamming error logs until the device is connected again. 
This stops spamming these logs after 20 log lines, increments the numBadIMU readings in the the error case, and adds a little more context as to why this error may be happening.
Past a count of 20 log lines, we demote the EOF error that results from disconnecting the serial port to a Debug line.
=> Stop spamming logs when wit imu disconnects

components/board/customlinux/board.go
all pins that have both gpio and pwm defined in their board defintion files will be hardware pwm only.
=> RSDK-5105 enable hardware pwm on custom linux

components/board/customlinux/board.go, components/board/customlinux/setup_test.go, components/board/genericlinux/board.go, components/board/genericlinux/config.go
Olivia, is this what you had in mind? The constructor already had a logger present, but the `ConfigConverter` was using the global logger. So, this PR adds a logger to the arguments to that function type. The only other `ConfigConverter` doesn't log anything, so nothing in it changed.
If you intended something else with this ticket, I'm happy to undo/redo anything you want.
=> [RSDK-6168] Plumb a logger through the customlinux ConfigConverter

services/datamanager/builtin/builtin.go
Ran all `services/datamanager/builtin` tests multiple times using `-c 50` 
Also tried running with a config locally, turning capture on and off
=> RSDK-5931 - Fix test timeout for TestDataCaptureUploadIntegration

cli/module_build.go, cli/module_build_test.go, utils/value.go, utils/value_test.go
- previously, the `logs --wait` command would return 0 even if some or all of the platforms failed
- now it will return an error with information about the failed platforms
=> APP-3483 fail CLI --wait command when a build fails

components/movementsensor/utils.go, components/movementsensor/utils_test.go
The problem:
- `NewLastError()` never set the `size`, so it was initialized to 0
- If you call `Get()`, towards the end it sets `errs` to be a list of length `size` (a list of length 0)
- If you then call `Set()` you try to read `errs[0]` and panic because that's now out of range
The fix is easy: just initialize `size` to the right value.
There might need to be a second PR for this ticket, related to all the EOF errors Kat encountered talking to the IMU. but in the meantime, this is an important bugfix.
=> [RSDK-6073] bugfix: initialize the size of the LastError storage

components/motor/gpio/loop.go
This is an intermediate step to removing the control config from the robot config. It won't be used until we add PID values to the gpio motor config
=> RSDK-6192: Migrate motor control loop to a structure like sensor-controlled control loop

components/motor/fake/motor.go
Set defaults for pins, max speeds and anything needed for a fake motor to construct.
Refactor the constructor to make the constructor more readable in a NewFakeMotor helper function; this should be exported like all our fake resource functions should be. 
This should be passed to the robot constructor without arguments, same as our cleanest drivers
ie Constructor: NewFakeMotor rather than Constructor:NewFakeMotor(ctx, logger.....)
=> RSDK-2063: Fake motor default attributes and refactor

cli/app.go
Changing all of the usage text for data / datasets to be better explain the intended use
Tested locally by using running the commands (as an example: `go run cli/viam/main.go data dataset remove`)
=> DATA-2189 - Update CLI usage strings with parameter keys

robot/impl/resource_manager.go, robot/impl/robot_reconfigure_test.go
causes an issue for modular resources (and probably real resources as well) with remote deps.
when the remote changes for any reason (reconfig, going down) and a dependency is missing, we would close the resource (missing dep) but did not explicitly remove the resource from the node. This meant that when the remote dep came back, we would try to just reconfigure the existing resource.
for modular resources, this is an issue because we already closed it and now the module would be unable to find said resource.
depending on how well written the local resource is, that would cause issues (since we already closed it), but at least for fake components that isn't an issue since we don't check for much during reconfiguration.
Beyond just closing the resource, we also remove it from the node. Now …
=> RSDK-5838 - Remove resource from node if missing dependencies

etc/test.sh, go.mod, go.sum, services/datamanager/builtin/sync_test.go
- revert a recent change that hid failures in 1 of our 2 test suite runs
- add conditional skips in some places with go-detect-race
- (incidental) add ability to run test.sh on a specific package
- we broke this last month when prepping the test suite for go 1.21
- the breakage only affects `-race` mode -- any failures that appeared in coverage runs would have still failed the test suite
=> unbreak return code pass-through in test.sh

.github/workflows/docker.yml
- 2vcpu -> 4vcpu in the devenv:arm64 run of docker.yml
- `make lint-go` was failing consistently after go 1.21 upgrade, probably an OOM, example here ([run 1](https://github.com/viamrobotics/rdk/actions/runs/7401700035/attempts/1), [run 2](https://github.com/viamrobotics/rdk/actions/runs/7401700035))
- it succeeded on this branch ([run here](https://github.com/viamrobotics/rdk/actions/runs/7401990917)) (with unrelated downstream failures)
=> APP-2917 increase runner size in docker build

services/motion/builtin/move_request.go
We missed an error check. This PR fixes this
=> Fix panic when MoveOnMap is called incorrectly

gostream/ffmpeg/avcodec/avcodec.go
This frees the avcodec context in `EncoderIsAvailable`. I created the ticket https://viam.atlassian.net/browse/RSDK-6162 to add a `Close` method to our encoders so we can free resources as needed.
=> free avcodec context

.github/workflows/releasecandidate.yml
This was a straight copy from the other yml files. The biggest unknown to me was whether we needed to add the github token/slack webhook url secrets to a new spot. Or if secrets are global to all github actions in a repo.
=> RSDK-6248: Add CI failure devops slackbot message to RC runs.

web/frontend/src/components/pcd/pcd-view.svelte
Ticket: https://viam.atlassian.net/browse/RSDK-5524
**Done:**
* Changed camera's PCD default point size from 1 to 3
**Before:**
* <img width="1129" alt="Screenshot 2024-01-09 at 10 08 03 AM" src="https://github.com/viamrobotics/rdk/assets/3912676/07fe4e3f-bd36-407d-a62e-f7b04b5d1ab3">
**After:**
* <img width="1272" alt="Screenshot 2024-01-09 at 10 09 13 AM" src="https://github.com/viamrobotics/rdk/assets/3912676/4b8d6d5b-38f8-4ebf-b770-d15556193a32">
=> RSDK-5524 - Change rplidar point cloud viewer's default point size from 1 to 3

utils/math_test.go
The following tests were essentially tests of the gonum statuv package and testing if they fulfilled their promised randomness. As we shouldn't test an external packages behavior, and also avoid random variables in tests, the flaky portions of the tests have been removed.
=> RSDK-1166: Remove random sampling from a test

components/board/jetson/data.go
As a reminder for anyone else who wants to set up one of these boards: you need your laptop running Ubuntu 18.04 in order to install an OS onto a Jetson TX2. Why did NVidia set things up this way? No idea.
As a reminder for anyone trying to figure out which chip goes with which pins: if multiple chips have the same number of lines (so you can't distinguish them by ngpio values), run `dmesg | grep "registered GPIO"` to see the answers.
Tried on a Jetson TX2: works as expected.
=> [RSDK-6089] add missing pin definitions for the Jetson TX2

motionplan/tpSpaceRRT.go
[Ticket](https://viam.atlassian.net/browse/RSDK-6052)
1. Changes the `DistanceFunc` created in `tpSpaceRRTMotionPlanner.make2DTPSpaceDistanceOptions` to cache the `*ik.Solution` results computed for each `nearest` node so that they can be retrieved in `*tpSpaceRRTMotionPlanner.getExtensionCandidate` & don't need to be recomputed again.
2. It turns out the performance uplift is not as great as we would have hoped (only a few percentage points at most) but it does (arguably) improve code clarity.
Sanity checked in gazebo:
https://github.com/viamrobotics/rdk/assets/5927876/068ea883-3198-4f67-8598-463a2cc9baa8
=> RSDK-6052 - De-duplicate work being done by neighbor manager in IK solving

cli/module_build.go
Oops.
We do this for `viam module upload`. I just forgot that it should go here too.
We decided that it is better to keep this in the cli rather than put this in the backend to keep a cleaner API (and to avoid internal confusion)
=> `viam module build start` version should be resilient to v prefix

.github/workflows/appimage.yml, .github/workflows/test.yml
- pin 3 arm64 jobs to a specific datacenter
- remove coverage test run (keep the data race run)
- in theory reduce CI timeouts in the image pull step
- coverage decision in [slack](https://viaminc.slack.com/archives/C01Q5S8V6TB/p1704920325076189), but basically to speed up tests + halve our flake risk
https://github.com/viamrobotics/rdk/actions/runs/7495123827
=> RSDK-6289 pin CI datacenter

web/frontend/src/components/servo/index.svelte
When you used the control to go to an angle below zero, a vague "assertion failed" toast came up since the proto angle is an unsigned int. Changed to be more clear.
=> RSDK-6323 GPIO servo display better error message

components/servo/gpio/servo.go
It's fixed. worked nicely. 
Checked against python sdk, pi, jetson nano.
=> Rsdk-1989: gpio servo doesnt work

components/arm/xarm/lite6_kinematics.json, components/arm/xarm/xarm.go
UFactory (the company that makes the xArm arms) does not produce any hardware named "xArm Lite." Instead, they make one named "Lite 6" which is similar to the "xArm 6."
Not tested: I can't find one of these in the office, so am unsure how to test. Any advice is appreciated!
I'm also unsure whether to write a config migration, though I'm leaning towards not writing one. There are no fragments and 4 robots that use this component. None of them have been online since August. Two of them only have arm components, and two of them include fake components, which makes me think none of them are "real" robots.
Github thinks I should tag @biotinker on this, and I'm also tagging a random member of Bucket.
=> [RSDK-3178] Rename component xArmLite -> lite6

gostream/codec/x264/encoder.go
This PR simply downsizes the x264 encoder bitrate from `3.2 megabits` to `1.2 megabits`.  We have been noticing potential livestream issues in bandwidth constrained WANs. This should only affect 1080+ framesizes because anything smaller will not even hit the 1.2 megabit throughput size.
- Tested that larger framesizes (1080p+) still stream with suitable quality to the web application.
=> Set x264 bitrate to 1.2 megabits

services/motion/builtin/builtin_test.go
This PR skips MoveOnMapNew/Long_Distance to prevent unit test failures.
https://viam.atlassian.net/browse/RSDK-6326 will un-skip this test and fix the flakiness.
=> skip MoveOnMapNew/Long_Distance

gostream/codec/h264/encoder.go, gostream/codec/video_encoder.go, gostream/codec/vpx/encoder.go, gostream/codec/x264/encoder.go, gostream/stream.go
This PR adds a `Close` method to the `videoEncoder` interface. 
The `h264` codec uses avcodec`FreeContext` call and the `x264` encoder uses mediadevices built in `Close` function. These calls are hit when the stream calls`Stop`. (See `stream.go` changes).
_Note: PR does not add back in use for h264 hardware encoder._
- Tested that this fixes `STREAMON` ioctl errors when using h264 codec. (`[h264_v4l2m2m @ 0x7f6c000e40] VIDIOC_STREAMON failed on output context`)
- Tested there are no regressions with x264 codec.
- Vpx tests are passing
=> RSDK-6162 - Add Close to video encoders

web/frontend/src/components/slam/index.svelte
This PR fixes inputting destination coordinates on SLAM rc card. Before, the input type expected was a number which caused typing things that could not be parsed as a number to cause issues (i.e. 1., -, etc...)
https://github.com/viamrobotics/rdk/assets/121991867/f775916f-7ae6-4430-8735-5e071965a23d
=> RSDK-4555 - fix inputting destination coordinates on SLAM rc card

motionplan/constraint.go, services/motion/builtin/builtin_test.go
This PR adds a check whether a motion starts with a moving geometry colliding with a WorldState pointcloud, and if so, errors.
=> RSDK-6265 Add check for starting in collision with a pointcloud

components/camera/client.go, components/camera/client_test.go, components/camera/extra.go, components/camera/extra_test.go, components/camera/server.go, components/camera/server_test.go, data/collector.go
We're making the `extra` value in our context more generic to support more use cases. 
~@kaywux~ @agreenb This will break the hard-coded functionality for data for which this was originally implemented. If that will be difficult to update or will immediately be broken - because it isn't a separate code base pinned to a specific version of the RDK - let me know!
I added my own unit test, but @njooma, I'm relying on you to make sure this works as expected with the SDKs.
=> RSDK-6281 pass extra through the server

pointcloud/basic_octree.go, pointcloud/basic_octree_utils.go
The issue comes when an octree has a nodeRegionOverlap of, say, 1mm, and a point gets placed in that 1mm border region. Then that octree is split into octants, each of which have border regions of only 0.5mm. If the point is less than 1mm but greater than 0.5mm from the original octree, it will fit into none of the octree's octants and cause an error, truncating the pointcloud.
This PR fixes this issue by making `nodeRegionOverlap` an absolute value such that all octree octants will always have the same buffer region, guaranteeing a point fits.
=> RSDK-6393 errors in octree transform are truncating slam maps

.github/CODEOWNERS
As we rebuild RC for the robot details redesign, we will rebuild RC in App with styles that match the redesign, comprehensive testing, and restructuring components. To reduce churn in RDK, we will not make these changes in-place in RDK. Instead, we will build the new RC in App and then replace RC in RDK after it is complete.
During this period, RC will still exist in RDK and folks will want to make changes. To make sure that the team is aware of these changes, I am adding myself as a code owner on RC in RDK. This, along with required code owners approval, will make sure that I can incorporate these changes back into the new RC.
Read more about code owners [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-ow …
=> APP-3656: Add CODEOWNERS for RC

.github/workflows/test.yml, components/board/genericlinux/gpio.go, gostream/codec/h264/encoder.go, gostream/stream.go
- run linter in datarace step, not just coverage
- temporary `//nolint` comments for two locations that are now failing
- lint previously only ran in the coverage step, removing coverage from our test suite disabled lint
- passing [here](https://github.com/viamrobotics/rdk/actions/runs/7612350596/job/20729774629)
=> RSDK-6398 copy linter from coverage to unit tests

cli/module_registry.go
Tested this manually. We still have not gotten around to adding tests to this code path.
You can replicate Alexa's issue by manually creating the tarball instead of the auto-bundling.
```
Error validating module: the module archive contains a directory at the entrypoint "testdir" instead of an executable file. For more details, please visit: https://docs.viam.com/fleet/cli/#module
```
=> CLI module upload validation should catch directory entrypoints

.github/workflows/test.yml
The problem: I've made changes to some code that only builds on a raspberry pi. The tests pass, but the linter isn't happy. The linter on my laptop doesn't check this code because it's not running on a pi. I can run it on a pi, but that takes _ages,_ to the point that frankly I'm guessing what the linter might have done and trying to make the same changes blindly (and if that doesn't work, I'll try removing the go build directives at the top of the file, and then perhaps getting annoyed when the linter says this code doesn't compile on a non-pi machine). 
The solution: when the CI check fails, not only run `git status` to show which files changed, run `git diff` to show what the changes were. Run `git diff` first, so that if there is a giant diff, the very last thing (and the thing we …
=> Show diff when linter creates untracked changes

components/board/board.go, components/board/client.go, components/board/config.go, components/board/digital_interrupts.go, components/board/digital_interrupts_test.go, components/board/fake/board.go, components/board/fake/board_test.go, components/board/genericlinux/board.go, components/board/pi/impl/board.go, components/board/pi/impl/board_test.go, components/board/pi/impl/digital_interrupts.go, components/board/pi/impl/digital_interrupts_test.go, components/board/pi/impl/external_hardware_test.go, components/encoder/incremental/incremental_test.go, components/encoder/single/single_encoder_test.go, components/motor/gpio/motor_encoder_test.go, go.mod, go.sum, testutils/inject/digital_interrupt.go
Github thinks @martha-johnston should review this, so I'll assign to her instead of using the randomizer.
I had this much, much cleaner this morning, where the only part left in the `board` package was the interface, and all the implementation details were left up to the boards. but then it turned out that a bunch of unit tests were using these as well, and I had to put a bunch of stuff back.
Main changes:
- The `PostProcessor` type is defined in board/digital_interrupts.go, rather than board/board.go. 
- There is a copy of all the digital interrupt stuff (including the configs) in board/pi/impl/ now. That component uses this new copy.
- The main (non-pi) version of digital interrupts no longer has a `ServoDigitalInterrupt` implementation.
- The main (non-pi) version of digital interrupt …
=> [RSDK-1963] servo digital interrupts are only in the raspberry pi code

.github/workflows/appimage.yml
- include RELEASE_TYPE and broaden wildcard for armhf appimage
- we were uploading viam-server-vx.y.z-armhf appimages on release, but not viam-server-stable-armhf
This one failed because my modified pr run wasn't compatible with the deploy step, but the armhf upload paths are correct:
https://github.com/viamrobotics/rdk/actions/runs/7619333281/job/20752458473#step:5:26
=> APP-3134 RSDK-6391 include stable armhf in appimage workflow

cli/module_registry.go, cli/print.go
I was talking with Hazal during the happy-hour and she was voicing how it was unintuitive that she had to both create a meta.json (as the docs and other modules say to do) and yet also not create it until she runs `viam module create`.
This PR updates that behavior so that if a meta.json exists in the current directory (with a matching moduleid as what was requested via the cli args), it will create the module (in the registry) and then update that module (reducing the number of steps by 1)
It maintains the existing behavior for directories where there is no meta.json.
User flow:
1) New user wants to create a module
2) User copies files from some online examples (including a meta.json)
3) They start editing files / get their module to a semi-working state as a local module
4) They edit …
=> CLI module create behavior with existing meta.jsons

components/audioinput/client.go, components/camera/client.go, components/camera/client_test.go, components/camera/fake/camera.go, gostream/media.go, resource/resource.go
Replace the camera client's stream cancellation context with a per-stream stop channel, so that we can continue to close streams after a camera client is closed.
1. Run two instances of RDK locally, with the following two respective configurations in separate terminals
main.json
```
{"network":{"bind_address":"localhost:8081"},"remotes":[{"name":"robot1","address":"something-unique"}]}
```
remote.json
```
{"network":{"fqdn":"something-unique","bind_address":":8080"},"components":[{"name":"camera1","type":"camera","model":"fake","attributes":{"animated":true}}]}
```
2. Visit: http://localhost:8081 and view the stream for `robot1:camera1` - you should see an animated image:
3. Stop and restart the server running `remote.json` - go back to step 2 and the image should still be animated.
=> RSDK-6340 Allow streams to restart after disconnect
