go.mod, go.sum
=> RSDK-559 Propagate cancels to remotes

components/camera/fake/camera.go, components/camera/fake/camera_test.go
Had multiple people express frustration with fake camera just returning a single dot in the image.
A full image and pointcloud is a better test environment.
=> Fake Camera will now return full Image and Pointcloud

examples/mycomponent/mycomponent_test.go, robot/impl/robot_reconfigure_test.go
Temporary disable tests to relieve CI
=> Disable resource intensive tests

services/slam/builtin/builtin_test.go
See ticket description: https://viam.atlassian.net/browse/RSDK-647
=> [RSDA-647] Increase time padding in slam data loop tests

services/slam/builtin/orbslam_yaml.go, services/slam/builtin/orbslam_yaml_test.go
quick fix for slam when using a remote camera
=> force map saving and loading to be string

services/slam/builtin/builtin.go, services/slam/builtin/builtin_test.go, services/slam/builtin/orbslam_yaml_test.go
https://viam.atlassian.net/browse/DATA-453
=> [DATA-453] Get lazy png image for mono case

components/camera/videosource/webcam.go
See reasoning here: https://viam.atlassian.net/browse/RSDK-704
=> RSDK-704 - resolve symlink prior to getting named videosource

components/camera/videosource/webcam.go
JIRA: https://viam.atlassian.net/browse/RSDK-716
=> RSDK-716 fix webcam driver lookup - try to use provided path if symlink eval fails

services/slam/builtin/builtin.go, services/slam/builtin/builtin_test.go, services/slam/internal/slam_test_helper.go
https://viam.atlassian.net/browse/RSDK-713
=> [RSDK-713] Fix flaky tests for slam data process

components/movementsensor/imuwit/imu.go
That I introduced :(
1. Actually skip incomplete lines, and keep track of number of skipped messages. Not exposing this value yet.
2. Fix the race condition issue in GetReadings where variables were accessed outside of a mutex. Also call methods instead of accessing variables directly.
=> Fix wit imu bugs

components/camera/videosource/webcam.go, components/sensor/charge/renogy.go
=> Add serial prefix to sensors

README.md, doc/dependency_decisions.yml, etc/setup.sh
JIRA: https://viam.atlassian.net/browse/RSDK-475
Combines and supersedes:
* https://github.com/viamrobotics/rdk/pull/1298
* https://github.com/viamrobotics/rdk/pull/1310
=> RSDK-475 license clean-up + setup

services/datamanager/datacapture/data_capture_file.go, services/datamanager/datacapture/data_capture_file_test.go
Accompanying app PR otw.
EDIT: arrived https://github.com/viamrobotics/app/pull/699
=> [DATA-fix] .dat extension, not .csv.

components/movementsensor/collectors.go, components/movementsensor/movementsensor.go
* Add LinearVelocity, AngularVelocity, and CompassHeading
* Position returns a *Point struct, and Linear/AngularVelocity return a Vector struct
Tested with:
```
{
"network": {
"fqdn": "something-unique",
"bind_address": ":8080"
},
{
"name": "move",
"type": "movement_sensor",
"model": "fake",
"service_config": [
{
"type": "data_manager",
"capture_methods": [
{
"method": "Position",
"capture_frequency_hz": 1
},
{
"method": "LinearVelocity",
"capture_frequency_hz": 1
},
{
"method": "AngularVelocity",
"capture_frequency_hz": 1
},
{
"method": "CompassHeading",
"capture_frequency_hz": 1
}
]
}
}
]
}
],
"services": [
{
"name": "data_manager1",
"type": "data_manager",
"model": "builtin",
"sync_interval_mins": 0,
"capture_dir": "/tmp/capture"
}
}
]
} …
```
=> Add movement sensor collectors

services/slam/builtin/builtin.go, services/slam/builtin/orbslam_yaml.go, services/slam/client.go, services/slam/server.go, services/slam/slam.go, services/slam/slamlibraries.go
Implements the RDK part of this ticket: https://viam.atlassian.net/browse/DATA-524
=> SLAM: Add "this is an experimental package" disclaimer

components/board/arduino/motor.go, components/motor/dmc4000/dmc.go, components/motor/dmc4000/dmc4000_test.go, components/motor/errors.go, components/motor/fake/motor.go, components/motor/fake/motor_test.go, components/motor/gpio/basic.go, components/motor/gpio/basic_test.go, components/motor/gpio/motor_encoder.go, components/motor/gpio/motor_encoder_test.go, components/motor/gpiostepper/gpiostepper.go, components/motor/gpiostepper/gpiostepper_test.go, components/motor/i2cmotors/ezopmp.go, components/motor/roboclaw/roboclaw.go, components/motor/tmcstepper/stepper_motor_tmc.go, components/motor/tmcstepper/stepper_motor_tmc_test.go
This is the first time I've ever written Go. Please give me a thorough, nitpicky, overly-harsh review! Are my lines too long? Is the comment superfluous and removable? Did I put the new test in the wrong location?
I added a test, which failed, and then changed the code until the test passed.
=> [RSDK-686] It's an error to tell a motor to move at 0 RPM

services/datamanager/builtin/builtin.go
Fixes bug pointed out [here](https://github.com/viamrobotics/rdk/pull/1481#discussion_r993655508). Thanks for the call out @agreenb !
=> [DATA] Copy map properly.

config/reader.go
a corresponding change to add more detail in error messages is in https://github.com/viamrobotics/app/pull/747
=> RSDK-739 remove misleading log when getting cloud config

.github/workflows/docker.yml, .github/workflows/main.yml, .github/workflows/pullrequest.yml, .github/workflows/test.yml, .gitignore, Makefile, etc/analyzetests/main.go, etc/test.sh, go.mod, go.sum, resource/resource_test.go, tools/tools.go
Next time: package coverage percentages
=> Record test results in MongoDB

robot/impl/resource_manager.go
more or less a hack until we get service dependencies in - this assumes we don't have anything depending on services right now, which I am pretty sure is still the case
=> RSDK-714 Start services at end of reconfiguring process

.artifact/tree.json, services/slam/builtin/builtin_test.go, services/slam/builtin/cartographer_int_test.go, services/slam/builtin/orbslam_int_test.go
https://viam.atlassian.net/browse/DATA-568
I used point clouds from [data_Feb_25_2022_test_inside_hectagon_2nd_take](https://drive.google.com/drive/folders/1y13Bi5kkSqI2nfBXT0CKkVH_yzqOloC_).
=> [DATA-568] Add cartographer integration tests

services/slam/builtin/cartographer_int_test.go
Adjusts tests to work with added updating and localization modes:
* https://viam.atlassian.net/browse/DATA-631
* https://viam.atlassian.net/browse/DATA-114
=> [DATA-114 + DATA-631] Adjust test for updating & localization mode

components/arm/xarm/xarm_test.go, motionplan/cBiRRT.go, motionplan/planManager.go, motionplan/plannerOptions.go, motionplan/rrtStarConnect.go, motionplan/utils.go
Fixes a crucial bug in motion planning fallbacks that would execute *both* plans without collision checking in between
=> Motion fallback fix

components/camera/videosource/join_pointcloud.go, components/camera/videosource/join_pointcloud_test.go
updates the schema with the required changes:
- removes stream
- changes closeness_mm to proximity_threshold_mm
=> [data-759] update join pointcloud model with new schema

components/camera/videosource/webcam.go
Motivated by (https://docs.google.com/document/d/18p3LV6ghH-m0xGjO7MZRz4zK0X8JePmGZRAXBtm0k7E/edit)
=> [DATA-755] Update webcam config

robot/web/options/options.go, web/server/entrypoint.go
filed a follow up ticket (RSDK-1033) to address this more completely
=> RSDK-855: Error when switching from local config to cloud config

robot/client/client.go, robot/client/client_session.go, robot/session_web.go
PS: This coupling is a bit scary. My understanding was this was done to help with better error messages. Eg. Saying you're disconnected.
=> Exempt AuthTo from disconnect check

components/input/webgamepad/webgamepad.go, robot/web/web.go
Very short. Fixes the capitalization in the webgamepad model, which I inadvertently changed, and one typo in a debugw
=> Fix two small bugs introduced by modules

robot/impl/resource_manager.go
=> RSDK-892: Don't log error if remote hasn't connected yet

services/slam/builtin/cartographer_int_test.go
Had to add a 100ms sleep to ensure a map is saved.
=> Fix cartographer integration test

services/slam/builtin/builtin_test.go, services/slam/builtin/cartographer_int_test.go, services/slam/builtin/orbslam_int_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-1621
This change is necessary for this PR to pass integration tests: https://github.com/viamrobotics/slam/pull/127
[RSDK-1621]: https://viam.atlassian.net/browse/RSDK-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RSDK-1054] Fix delete_processed_data bug

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/movement-sensor.vue
Adding linear acceleration to frontend.
=> Rsdk-1024: vue changes

protoutils/messages.go, web/frontend/src/components/base.vue, web/frontend/src/components/motor-detail.vue
This reverts commit 0cbe97c4d69ec0305e3cb36f8b7f1555eda4cb8c.
CC @erh
=> Revert "[RSDK-1592] Motor and Base Wrappers for local webapp (#1715)"

components/movementsensor/gpsrtk/model_test.go
Closed robot after initializing. Testing 10000 times on mac, building amd64 right now for that test as well.
=> RSDK-1716 - race condition log after test end in gpsrtk

components/movementsensor/mpu6050/mpu6050.go
Not yet tested, will do that now...
=> Angular velocity units should be degrees per second, not radians per second

components/sensor/ultrasonic/ultrasonic.go
Recreating https://github.com/viamrobotics/rdk/pull/1798 to make github actions run properly.
=> Revert ultrasonic sensor result value back to meters

components/base/wheeled/wheeled_base.go, components/base/wheeled/wheeled_base_test.go, components/movementsensor/fake/movementsensor.go, components/movementsensor/imuwit/imu.go
This reverts commit 24d6f39707d5c030b0da74feb4da9d2c1f3109a8.
=> Revert "[RSDK-1242] use imu to fix spin (#1737)"

go.mod, go.sum
This PR simply changes "no properties found" log to Debug visibility.
=> RSDK-1130 Bump gostream

motionplan/constraint.go, motionplan/constraint_test.go, motionplan/errors.go, motionplan/motionPlanner.go, motionplan/motionPlanner_test.go
This should provide all information needed in order to troubleshoot the arm failure that @nfranczak and @Fahmina saw and any future arm failures.
Testing done on this PR includes running both passing and failing requests on a real arm and observing the correct, expected result each time. This means:
- success for a successful move
- "physically unreachable" error when asking a 3-foot arm to reach 20 feet away
- A error saying that 100% of IK solutions failed the collision constraint, when the goal lies inside a collision object.
All of the above have been captured in unit tests that are added to this PR as well.
=> RSDK-1681, RSDK-1796 Add additional motion planning logging, add reasons why IK fails in cases where it does so

components/board/pi/common/common.go
Updating pi/common/common.go to pass board name as dependency.
Test: 
- Tested on pi with pi servo without adding dependencies.
=> RSDK-1810: implicit dependencies

components/sensor/collector.go, components/sensor/register/register.go, components/sensor/sensor.go, components/sensor/sht3xd/sht3xd.go
This PR is the first chunk of code necessary to get our external partner Bee Ring supported on stock RDK.
There are two pieces of this PR:
1) adds support for the `sht3xd` temperature sensor
2) adds support for having sensor data upload to the "Sensor Data" part of our Data Management system
Since I don't usually make PRs that touch so many different bits of RDK  feel free to add anyone else to the PR if I missed them/they should take a look
=> Bee ring implementation needs

components/movementsensor/adxl345/adxl345.go, components/movementsensor/gpsnmea/serial.go, components/movementsensor/movementsensor.go, components/movementsensor/movementsensor_test.go, components/movementsensor/mpu6050/mpu6050.go
and also spellchecked altitude
=> RSDK-1883 - return default orientation vector over nil for movementsensors

web/frontend/src/app.vue
My last merge https://github.com/viamrobotics/rdk/commit/29e0f8cf668f1fc9ed9d000dc375b6670afddffc had one incorrect line in it and reverted the RFC fix in https://github.com/viamrobotics/rdk/commit/d224a2ce6cbacfcc3d78b2a716494cffda7dd847
=> Fix Merge Error for RFC 7064 Fix

web/frontend/package.json
The latest changes, including improvements to base card, is not published and available, which is causing issues with the Base Card.
=> Update FE to version 34 in NPM

components/encoder/fake/encoder.go
=> Change fake encoder update_rate_msec to an omitted empty field

components/base/wheeled/wheeled_base.go, components/base/wheeled/wheeled_base_test.go
A few refactor logger statements and checks that a now-blocked PR. No functional changes.
=> Refactor base and add logger

web/frontend/package.json, web/frontend/src/components/camera/camera.vue
In the case where multiple cameras exist, the SDK will emit events for each camera streams. On the frontend, there will be one instance of the camera component per camera. This code change checks the component's camera name against the camera stream name, and ignores the event if the name does not match.
Tested locally using two cameras:
=> Use Correct Stream Event When Multiple Cameras Exist

services/slam/builtin/builtin.go, services/slam/client.go, services/slam/fake/slam.go, services/slam/server.go, services/slam/slam.go
adds GetPositionNew stub for use in future PRs for Map Representation
https://viam.atlassian.net/browse/RSDK-1066
=> [RSDK-1066] add GetPositionNew stub to SLAM Service

components/board/genericlinux/board.go, components/board/genericlinux/gpio.go
Tried on the Orin on my desk, using the PWM to blink an LED: works great at lots of duty cycles and low frequencies (up to 5 Hz), but my eye isn't good enough to see how reliable it is at high frequencies. I should also try hooking this up to a motor controller, but I'll send the PR out before I've set that up.
The previously-written software PWM loop relied heavily on the internals of both the board struct and the periphPgioPin struct, and was kind of a pain to work with. I had started trying to refactor it into a more abstract function that could take any GPIOPin interface, but it became more and more awkward. I'd still like to go back and clean that up, but that's a low-priority task for my spare time.
=> [RSDK-1862] software PWM for Jetson Orin

data/collector.go, data/collector_test.go
`TestCtxCancelledLoggedAsDebug` was flaky because it used time.Sleep instead of explicit signaling. This changes it to use a channel to signal when the capture function has been called at least one time (the thing we care about).
We also had a sleep to ensure that the logger had been flushed. But we should be doing that as part of the collector's close function. This updates `.Close()` to flush the logger before returning.
We had defined this Capturer interface, which was the exact same thing as a CaptureFunc. I'm not sure why I did that a year ago, but it's not necessary. I removed
Ran 10,000 times locally without a test failure with:
`go test -race --count=10000 -run TestCtxCancelledLoggedAsDebug`
Previously this would fail.
Also reran all datamanager tests without failure.
=> [RSDK-2036] Fix flaky collector test.

components/motor/gpio/motor_encoder.go, components/motor/gpio/setup.go
- multiple gofor calls
- overshooting
- "jerk" with lots torque
=> fixes for multiple rpm issus

module/module_interceptors_test.go
Should've caught this one when doing the same for the other module-based tests.
=> [RSDK-2132] Prebuild module/testmodule

.github/workflows/code-coverage-comment.yml, .github/workflows/code-samples-check.yml, etc/code-samples-action.py
Want to make this comment smarter about what prs it comments on
=> APP-1287 - make comment only on specific files

components/board/genericlinux/gpio_unsupported.go, etc/code-samples-action.py, web/frontend/src/components/base.vue
Fixes a bug we had with the initial angle value of a spin being set to 0. Also this pr changes the step on the spin slider to 15 to allow for more angles of spinning from the UI.
=> APP-1240 - Spin bug due to missing starting value

components/input/fake/input.go, components/input/fake/input_test.go
add support for RegisterControlCallback and also randomize event values so can test UI easier.
will add in a test or 2
=> RSDK-2138 Add streaming to fake input

services/slam/fake/data_loader.go, services/slam/fake/slam.go, services/slam/fake/slam_test.go, web/frontend/package-lock.json
[Ticket](https://viam.atlassian.net/browse/RSDK-1865)
- Implement GetPosition for fake slam
- Implement GetPointCloudMapStream for fake slam
- Implement GetInternalStateStream for fake slam
=> RSDK-1865-add-map-rep-methods-to-fake-slam

components/board/pi/impl/board.go
Audit contains mostly missing comments.
=> RSDK-1876 : pi audit

components/arm/arm_test.go, components/arm/universalrobots/ur5e_test.go, motionplan/collision.go, motionplan/collision_test.go, motionplan/constraint.go, motionplan/constraint_test.go, motionplan/dubinsRRT_test.go, motionplan/motionPlanner_test.go, motionplan/solverFrame.go, referenceframe/frame.go, referenceframe/frame_json.go, referenceframe/frame_test.go, referenceframe/model.go, referenceframe/model_test.go, referenceframe/static_frame_system_test.go, referenceframe/transformable.go, referenceframe/transformable_test.go, referenceframe/worldstate.go, spatialmath/box.go, spatialmath/capsule.go, spatialmath/geometry.go, spatialmath/point.go, spatialmath/sphere.go
And first-class geometry Label as the name of the geometry.
=> RSDK-2153 Update GeometriesInFrame to accept/return a slice rather than a map

etc/code-samples-action.py
Add fleet management github handle to allow users to easily tag us.
=> Update code sample comment

web/frontend/package-lock.json, web/frontend/src/components/slam-2d-render.vue, web/frontend/src/components/slam.vue
- [Ticket](https://viam.atlassian.net/browse/RSDK-1066) & [Ticket](https://viam.atlassian.net/browse/RSDK-2213) Migrate slam.vue from calling `GetPosition` and `GetMap` to `GetPositionNew` and `GetPointCloudMapStream`
- [Ticket](https://viam.atlassian.net/browse/RSDK-2108) Change zy orientation in slam-2d-render.vue to the final state
- [Ticket](https://viam.atlassian.net/browse/RSDK-2108) Change robot marker to always draw on top of pointcloud points
- [https://viam.atlassian.net/browse/RSDK-2162](There may be a bug in where the robot marker is drawn in slam-2d-render.vue)
Manual Testing Steps:
1. Loaded all datasets of fake slam & confirmed that they all continue to render after removing hack described in [this ticket](https://viam.atlassian.net/browse/RSDK-2108)
2. Confirmed that the …
=> RSDK-2213 migrate-slam-frontend-to-map-rep-apis

web/frontend/src/components/input-controller.vue
the intermediary data structure (`controls`) holding the status of the gamepad was not tracking updates. i fixed this by wrapping it in a computed ref.
i have yet to test with an actual gamepad, but with the fake input_controller this seems to be working fine.
=> [APP-1342] fixed reactivity bug in gamepad controller

etc/setup.sh
Tested on bullseye
Tested on Mac
Tested on linux x86_64
=> update setup.sh for dependency libjpeg-turbo

etc/test.sh
See https://github.com/gotestyourself/gotestsum/issues/66
=> use gotestsum --format standard-verbose to capture races

services/slam/builtin/cartographer_int_test.go, services/slam/builtin/orbslam_int_test.go, web/frontend/src/components/input-controller.vue
removing old map and internal state endpoints from integration tests
=> [RSDK-1055] Remove old integration test endpoints

web/frontend/package.json
ticket: https://viam.atlassian.net/browse/RSDK-2255
=> [RSDK-2255] bump frontend for SLAM temp changes

.artifact/tree.json, services/slam/builtin/builtin.go, services/slam/builtin/builtin_test.go, services/slam/client.go, services/slam/client_test.go, services/slam/fake/data_loader.go, services/slam/fake/slam.go, services/slam/fake/slam_test.go, services/slam/server.go, services/slam/server_test.go, services/slam/slam.go, testutils/inject/slam_service.go
Reverts viamrobotics/rdk#2014
Not to be merged until the following have merged & their artifacts have been published:
https://github.com/viamrobotics/viam-cartographer/pull/12
https://github.com/viamrobotics/viam-orb-slam3/pull/16
=> Revert "RSDK-2242 Removing Pre-Map Represetnation Endpoints"

components/board/pi/impl/board.go, components/board/pi/impl/i2c.go, components/board/pi/impl/servo.go
=> RSDK-2049 - include nicer error messaging from pigpio C library in pi implementation

services/baseremotecontrol/builtin/builtin.go
Arm control could probably benefit from this same change to speed itself up out of its one op at a time lock.
=> RSDK-1907 - Fix throttle race in base remote control

components/board/digital_interrupts.go, components/board/genericlinux/board.go, components/board/genericlinux/gpio.go, components/board/genericlinux/gpio_unsupported.go
Tried on an Orin with the ultrasonic sensor: seems to work! I only held books in front of the sensor, so it might be off by several centimeters. but I could get plausible readings when the book was ~1 and ~2 feet away, and a large distance returned when there was nothing in front of the sensor.
=> [RSDK-1866] Support digital interrupts on the Orin

web/frontend/package.json
Bumping RC version to push camera bug fix to app
=> bump RC page

components/board/arduino/board.go, components/board/board.go, components/board/client.go, components/board/client_test.go, components/board/fake/board.go, components/board/genericlinux/board.go, components/board/hat/pca9685/pca9685.go, components/board/numato/board.go, components/board/pi/impl/board.go, components/board/server.go, testutils/inject/board.go
This is the backing implementation for https://github.com/viamrobotics/api/pull/215 in the RDK. Please feel free to add other reviewers (and/or remove yourself) if you aren't the best/right reviewer.
=> RSDK-2230: Add minimal support for power modes

config/config.go, config/config_test.go, config/resource.go, config/resource_test.go
Add the bit about needing to start with a letter and then put the whole thing into a constant
=> Update invalid name error

pointcloud/basic_octree.go, pointcloud/basic_octree_test.go, pointcloud/basic_octree_utils.go, pointcloud/basic_octree_utils_test.go
given `pointsAndData`:
```
pointsAndData := []PointAndData{
{P: r3.Vector{X: 0, Y: 0, Z: 0}, D: NewValueData(2)},
{P: r3.Vector{X: .5, Y: 0, Z: 0}, D: NewValueData(3)},
{P: r3.Vector{X: .5, Y: 0, Z: .5}, D: NewValueData(10)},
{P: r3.Vector{X: .5, Y: .5, Z: 0}, D: NewValueData(1)},
{P: r3.Vector{X: .55, Y: .55, Z: 0}, D: NewValueData(4)},
{P: r3.Vector{X: -.55, Y: -.55, Z: 0}, D: NewValueData(5)},
{P: r3.Vector{X: .755, Y: .755, Z: 0}, D: NewValueData(6)},
}
```
this is what `printBasicOctree` returns:
```
0.000000e+00 0.000000e+00 0.000000e+00 - InternalNode | Depth: 0 Children: 8 Side: 2 Size: 7 MaxChildProbability: 0.100000
-+- -5.000000e-01 -5.000000e-01 -5.000000e-01 - InternalNode | Depth: 1 Children: 8 Side: 1 Size: 2 MaxChildProbability: 0.050000
-+--+- -7.500000e-01 -7.500000e-01 …
```
=> RSDK-2331 - Update Octree implementation to cache max probability of any child

components/arm/xarm/xarm_comm.go
@biotinker is OOO today, but this was a high priority problem @mestcihazal ran into when working with xArms and I have been able to recreate and fix on my end.
Pretty small fix overall so @biotinker is included primarily for awareness. If you approve, @randhid, we can just get this in and I'll alert DevRel of the fix.
=> Fix for not sending joint steps when diff is small

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/keyboard-input.vue
This disables text selection on base control buttons
https://viam.atlassian.net/browse/RSDK-2509
=> disable selecting text on wasd buttons

spatialmath/quat_test.go
Add a check for architecture and skip this test for now.
=> RSDK-2010 Part I Skip TestEulerAnglesConversion test on arm64

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/base.vue
This is causing noise when switching between tabs/windows and should not be necessary.
=> Remove stop call on unmounted

components/arm/fake/fake.go, components/arm/xarm/xarm.go, components/arm/xarm/xarm_comm.go, components/arm/xarm/xarmlite_kinematics.json
Adds support for the xarm lite arm
=> RSDK-2607 add support for xarm lite

services/mlmodel/tflitecpu/tflite_cpu.go
This fixes a misnaming of the service type
=> Fix a bug, change vision.tflite_cpu to mlmodel.tflite_cpu

etc/packaging/appimages/viam-server-aarch64.yml, etc/packaging/appimages/viam-server-x86_64.yml, packaging.make
This should fix the segfaults on Pis.
=> Remove upx from appimages

etc/Dockerfile.antique-cache
:facepalm: It's always the little things.
=> Fix antique-cache docker build

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/board.vue
I'm having trouble building this due to James' recent changes to the canon shells, so haven't tried it out yet. but my hope is that this is right, and you can review it while I figure out how to build again. I certainly won't merge it until I can take a screenshot and compare it to the old version.
=> Rename PWM -> PWM Duty Cycle

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/remote-control-cards.vue, web/frontend/src/lib/resource.ts
Attempt to disconnect on browser tab unload to reduce connection errors causing noise in logs.
=> Disconnect before browser tab unload

components/camera/videosource/webcam.go
@edaniels missed this in https://github.com/viamrobotics/rdk/pull/2276. Tested it works.
=> nit: switch to bool 

etc/packaging/static/package_release.sh, packaging.make
Dumb copy/paste leftover in the makefile meant I wasn't actually running the right file when I manually tested.
=> Fix static release script

robot/impl/local_robot.go, robot/impl/local_robot_test.go
=> RSDK-2877 Do not overload usage of term Orphaned

spatialmath/box.go, spatialmath/capsule.go
Also, drive-by fix a pointer receiver method that the linter noticed
=> RSDK-2885 Fix race

components/board/genericlinux/board.go
This fixes the failing check in main
=> remove unused import

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/navigation.vue
=> Add height style to maps container

components/gripper/softrobotics/sample.json
=> Update softrobotics gripper sample.json

components/motor/gpio/motor_encoder.go, components/motor/gpio/motor_encoder_test.go
=> Revert " Remove cfg from encoded motor structure "

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/arm.vue, web/frontend/src/components/audio-input.vue, web/frontend/src/components/base.vue, web/frontend/src/components/board.vue, web/frontend/src/components/camera/camera.vue, web/frontend/src/components/camera/cameras-list.vue, web/frontend/src/components/do-command.vue, web/frontend/src/components/encoder.vue, web/frontend/src/components/gamepad.vue, web/frontend/src/components/gantry.vue, web/frontend/src/components/gripper.vue, web/frontend/src/components/input-controller.vue, web/frontend/src/components/motor-detail.vue, web/frontend/src/components/movement-sensor.vue, web/frontend/src/components/navigation.vue, web/frontend/src/components/operations-sessions.vue, web/frontend/src/components/pcd/pcd-view.vue, web/frontend/src/components/sensors.vue, web/frontend/src/components/servo.vue, web/frontend/src/components/slam.vue, web/frontend/tailwind.config.cjs
[Sliders for motor power are too narrow](https://viam.atlassian.net/browse/RSDK-2981)
- Fix slider width
- Fix Tailwind config and update classes
- Add max width to video on camera component
I have bumped the remote control version.
=> Rsdk 2981 bugfix sliders width

web/frontend/src/components/slam-2d-render.vue, web/frontend/src/components/slam.vue
This PR makes it such that
1. “Move” is only green iff there is a base + there exists a destination to get to
2. change the makeMarker method in `slam-2d-render.vue` from `side: THREE.DoubleSide`  into `side: THREE.FrontSide`
=> RSDK-2982 - SLAM UI miscellaneous changes

services/motion/motion.go
Going to use this for getting the Motion service within the Nav service.
=> Add FromDependencies to Motion service

components/board/genericlinux/data.go, components/board/upboard/board.go, components/board/upboard/data.go, utils/hardware_info.go
Reopening this PR with changes from main branch merged in. 
Tested with jetson orin.
=> X86 support on genericlinux

robot/web/options/options.go, robot/web/web.go, web/runtime-shared/templates/webappindex.html
free free to change reviewers, wasn't sure who was right
=> use static RC on app.viam.com if we can't find it locally

services/vision/mlvision/classifier.go, services/vision/mlvision/detector.go
Mistakes were made. Now they're fixed. Tested with the model that was used and everything vibes (fails as classifier, functions as detector).
=> RSDK-3111 - Avoid panic on attemptToBuild*

components/base/wheeled/wheeled_base.go, components/base/wheeled/wheeled_base_test.go
=> Revert "RSDK-1880: wheeled base audit"

components/base/wheeled/kinematics_test.go, components/base/wheeled/wheeled_base.go, components/base/wheeled/wheeled_base_test.go
wheeled base audit code from PR (https://github.com/viamrobotics/rdk/pull/2368). 
Recent changes include: 
- Checks in Reconfiguration function. 
- Update in waitForMotorsToStop function definition. 
Tests: 
- Local host with fake 
TODO:
=> Update wheeled audit

robot/web/web.go, robot/web/web_test.go
RSDK-2418
Only stores a single, parent cancel function on the web service as opposed to a slice. Adds test that starting a web service with streams and immediately closing it does not result in a hang.
Starting a stream (whether audio or video) created a new context and stored its cancelation function on the web service. All contexts created within the web service were child contexts of the original `cancelCtx`, though, so I don't think this was necessary. Furthermore, `addCancelFunc` required a lock as it mutated `svc.cancelFuncs`. That locking occasionally caused deadlock, as:
> if `Close` happens too soon after `Start`ing with streams (hence the intermittent nature of the failure), [this](https://github.com/viamrobotics/rdk/blob/main/robot/web/web.go#L325) `addCancelFunc` method (which …
=> RSDK-2418 Only store one cancel function in web service

services/slam/fake/slam_test.go
https://viam.atlassian.net/browse/RSDK-3340
=> RSDK-3340 skip TestFakeSLAMStateful

components/input/gamepad/gamepad_linux.go
- tested with rover and generic game controller
=> [RSDK-3266] Fix gamepad controller initialization to use background context

motionplan/motionPlanner.go, motionplan/plannerOptions.go, referenceframe/worldstate.go, referenceframe/worldstate_test.go
Function returns table containing the following information about every geometry in the WorldState it is called on: Name, Geometry Type + Dimensions, Parent Frame
String() replaces use of toProtobuf() for logging in motionPlanner
=> RSDK-2405 Create function for string representation of WorldState

rimage/depth_map.go
This method is/was the missing piece for the obstacle avoidance with depth map POC.
=> RSDK-2967 - Get data from depthmap

module/module_interceptors_test.go, testutils/robottestutils/robot_utils.go, web/server/entrypoint_test.go
I added a unit test to validate the number of resources created on a server based on /etc/configs/fake.json and added two helper functions to the robottestutils package.
=> [RSDK-3364] Add Test to Validate Number of Resources from fake.json

components/board/genericlinux/data.go, components/board/genericlinux/pin_types.go
move pwmChipData and noBoardError back into linux only file
=> move unused types

components/base/wheeled/sensorbase.go
Small bug, err value wasn't being redefined within a goroutine.
=> RSDK-3683 Fix race in sensor base

web/frontend/src/components/arm/index.svelte, web/frontend/src/components/slam/index.svelte
This PR contains a quick UI cleanup done in collaboration with @nathartman. Screens attached of the cleanup:
In the "Modify all" view:
Before:
=> Clean up arm debug UI

.github/workflows/npm-bump-version.yml
This is the RDK side of the request.
=> RSDK-3416 Add Workflow to bump remote-control versions

components/base/wheeled/sensorbase.go, components/base/wheeled/wheeled_base.go
I made a mistake the first time I merged and forgot to uncomment this.
=> fix sensor base code

web/server/entrypoint.go
Currently a restart (really a shutdown) requested via App causes the server to hang, as it's waiting on a context that is only cancelled by an external signal (e.g. SIGTERM, SIGINT.) This moves the code to inside serveWeb() (instead of effectively wrapping around it) so that the shared context is one that is cancelled in all scenarios.
=> RSDK-3687 Move slow-shutdown watcher code

examples/apis.json
This update the Vision service function to a non deprecated function. Also this updates the format of our Apis.json files to be standard across SDKs
=> APP-1951 - reformat the structure of the code samples file

components/movementsensor/client.go, components/movementsensor/merged/merged.go, components/movementsensor/merged/merged_test.go, components/movementsensor/register/register.go
Adds a "merged" movementsensor model that takes the first movement sensor of each property in a configuration and combines data to the merged model.
=> [RSDK-3696] Add merged movement sensor model

components/base/kinematicbase/kinematics.go, components/base/kinematicbase/kinematics_test.go, services/motion/builtin/builtin.go, services/navigation/builtin/builtin_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-3570
=> RSDK-3570 - Allow kinematic Bases to be configured with desired speed

vision/object.go, vision/object_test.go
Add distance helper function to Golang SDK for PointCloud Objects, simple distance from origin.
=> [RSDK-3660] Add distance helper function to RDK/Golang SDK

components/movementsensor/gpsnmea/nmeaParser.go, components/movementsensor/gpsnmea/nmeaParser_test.go, components/movementsensor/gpsnmea/pmtkI2C.go, components/movementsensor/gpsnmea/pmtkI2C_test.go, components/movementsensor/gpsnmea/serial.go, components/movementsensor/gpsnmea/serial_test.go
Also need to export most of the GPSData fields to be used in the module.
=> Export GPSData fields

motionplan/nearestNeighbor.go
=> RSDK-3839 services motion flaky test test move on globe

components/movementsensor/imuwit/imu.go
Caveats as comment in code, testing on my with IMU to see how close we are to North on a level surface.
=> Extract compass heading from Wit IMU magnetomoeter - with caveats

components/encoder/single/single_encoder.go
This PR fixes the issue where single encoders were double counting ticks. Now it will only increase the encoder position if the tick value has changed. Tested on a viam rover with a pi and 996 ticks was equivalent to 1 revolution as expected, and as seen with an Arduino
=> RSDK-3975: Single line encoder double counts on a single line physical encoder

web/frontend/src/components/movement-sensor/index.svelte
=> Movement Sensor RC Altitide -> Altitude

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/arm/index.svelte, web/frontend/src/components/base/index.svelte, web/frontend/src/components/camera/camera.svelte, web/frontend/src/components/gantry/index.svelte, web/frontend/src/components/gripper/index.svelte, web/frontend/src/components/motor/index.svelte, web/frontend/src/components/pcd/pcd-view.svelte, web/frontend/src/components/servo/index.svelte, web/frontend/src/components/slam/index.svelte, web/frontend/src/lib/components/collapse.svelte
Use latest Prime icon system
https://viam.atlassian.net/browse/APP-2049
=> App 2049 icons

components/servo/client_test.go, components/servo/server_test.go
This PR checks against error variables in client and server tests in addition to checking if the error is nil or not.
=> RSDK-3503: Review servo server and client tests

config/config.go, config/proto_conversions.go, config/proto_conversions_test.go
Ticket: https://viam.atlassian.net/browse/APP-2325
=> APP-2325 - Add Type to PackageConfig from/to proto

components/movementsensor/utils_test.go
Adding tests for recently added functions in `movementsensor/utils_test.go`
=> RSDK-3447: New tests in utils

components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go, components/movementsensor/gpsrtkpmtk/gpsrtkpmtk_test.go, components/movementsensor/gpsrtkserial/gpsrtkserial.go, components/movementsensor/gpsrtkserial/gpsrtkserial_test.go
This PR includes tests for rtk over i2c and serial and some cleanups.
=> Rsdk-3264: RTK tests 

web/frontend/package-lock.json, web/frontend/package.json
@viamrobotics/prime  0.4.0  →  0.4.1
=>  @viamrobotics/prime  0.4.0  →  0.4.1

web/frontend/package-lock.json, web/frontend/package.json
Update version of remote control package
@viamrobotics/remote-control "version": "2.0.8"
=> remote control bump 2.0.8

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/navigation/components/map.svelte, web/frontend/src/components/navigation/components/nav/index.svelte, web/frontend/src/components/navigation/components/nav/obstacles.svelte, web/frontend/src/components/navigation/components/nav/waypoints.svelte, web/frontend/src/components/navigation/components/robot-marker.svelte, web/frontend/src/components/navigation/index.svelte
- https://viam.atlassian.net/browse/RSDK-4250
- https://viam.atlassian.net/browse/RSDK-4283
=> [APP-2355] - Add mobile support to navigation card

web/frontend/package-lock.json, web/frontend/package.json
- Fixes input events as done [here](https://github.com/viamrobotics/prime/pull/292).
=> @viamrobotics/prime  0.4.4  →  0.4.5

resource/resource.go, services/motion/client.go, services/motion/motion.go, services/motion/register/register.go, services/motion/server.go, services/navigation/builtin/builtin.go, services/navigation/builtin/builtin_test.go, services/navigation/navigation.go, services/navigation/register/register.go, services/navigation/store.go
Done:
* Removed duplicate package descriptions. See the problem it addresses in the screenshots below.
* Used Grammarly to improve the readability of the package descriptions.
=> Improve motion, navigation & resource package descriptions

components/base/kinematicbase/ptgKinematics.go
@Fahmina if you're curious.
Testing: ran this on the agilex and confirmed that it would navigate to selected waypoints. Note that this also requires the PositionOnly bug to be fixed.
=> Fix time math

cli/auth.go, cli/viam/main.go
RSDK-4287
Slightly elaborates on help messages for CLI and cleans up code.
This is more of an onboarding-to-the-CLI change for me; in the next PR I'll add better error handling and colored output for warnings/errors (yellow/red).
=> RSDK-4287 Improve CLI help messages

services/motion/builtin/builtin_test.go, services/navigation/builtin/builtin_test.go
This will be followed by another PR actually fixing the underlying issue, but for now we'll skip to unblock the rest of the company
=> Skip flaky test pending fix

motionplan/cBiRRT.go, motionplan/nearestNeighbor.go, motionplan/planManager.go, services/motion/builtin/builtin_test.go, services/navigation/builtin/builtin_test.go
Tracked down both race conditions and fixed them
=> RSDK-4279 hang in test start waypoint calling set mode cancels current and future move on globe calls

web/frontend/package.json, web/frontend/src/lib/components/robot-client.svelte
Before, RC could get into a connect retry loop even if the component was unmounted. This explicitly does not retry connection if unmounted.
=> APP-2420 Do not reconnect if not mounted

web/frontend/src/components/input-controller/index.svelte
Follow-up to https://github.com/viamrobotics/rdk/pull/2768 after debugging and pinpointing the issue to the input controller. Leaving the gamepad logic untouched for now to just reduce potentially introducing new issues.
=> Handle undefined input controller status event values

operation/manager.go, operation/manager_test.go
The old description that mostly described what went into a patch that now goes on top of this one:
> The synchronization effort is largely achieved by making `SingleOpManager.CancelRunning` (and consequently `New`) blocking. A condition variable is waited on until the operation becomes "closed". Other notes:
> * `wheeledBase.runAll` is problematic. It starts motors without locks. So we play some games with the wheeled base mutex and the single operation manager to guarantee that MoveStraight/Spin/SetVelocity play nicely together.
> * `runAll` usages in `wheeled_base` must register an operation with `New` to be safe. 
>  * `wheeledBase.SetVelocity` does not register an operation with `New` therefore it no longer uses `runAll`.
>  * The implementation of `runAll` was duplicated some into …
=> RSDK-4116: Ensure access to wheeled base left/right motors are synchronized.

services/vision/obstaclespointcloud/obstacles_pointcloud.go, services/vision/obstaclespointcloud/obstacles_pointcloud_test.go, vision/segmentation/er_ccl_clustering.go, vision/segmentation/er_ccl_clustering_test.go, vision/segmentation/radius_clustering.go
Implement ER_CCL Algorithm from "A Fast Spatial Clustering Method for Sparse LiDAR Point Clouds Using GPU Programming" by Tian et al. 2020. Faster alternative to RCC.
=> RSDK-4133: ER_CCL Algorithm Implementation

components/camera/videosource/logging/logger.go, components/camera/videosource/webcam.go, config/reader.go, web/server/entrypoint.go
Add camera debug logger (#2722)
This draft PR adds a file with camera debugging info to `~/.viam/debug_camera_component_<time>.txt` by default after the server starts. A new file is created each time the server starts. This file contains a lot of information and can be copied to tickets to help team AV debug camera problems.
TODO
* Better formatting (it's ugly but gets the job done)
* Make it more generic? Lots of things are hard-coded in now. I will see what needs to be more generic after feedback.
* Test rolling log. I haven't stress tested the hard cap on memory. The library I hastily depended on only allows us to limit the file size in N MBs where N is an int. It should be half a MB.
UPDATES
* Added more info to the log per @seanavery comments
* Better formatting
* Tied the lifetime …
=> camera debugger poc

components/powersensor/register/register.go, components/powersensor/renogy/renogy.go, components/sensor/sht3xd/sht3xd_nonlinux.go
Changing close so that the client is created in the constructor and the handler only closes in Close() instead of closing and reopening in every function.
=> RSDK-4629 Renogy Power Sensor - close and register

vision/segmentation/er_ccl_clustering.go, vision/segmentation/er_ccl_clustering_test.go
This is a quick fix that adds missing defaults and fixes the names of some configs in the test
=> Fix default values in er_ccl clustering

components/movementsensor/gpsnmea/gpsnmea.go, components/movementsensor/gpsnmea/nmeaParser.go, components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go, components/movementsensor/gpsrtkpmtk/gpsrtkpmtk_test.go, components/movementsensor/gpsrtkserial/gpsrtkserial.go
This PR includes description of RTK, flaky test fix RSDK-4282, HDT message in parser and general cleanup.
=> Rsdk:4463 cleanup rtk

components/board/register/register.go
Adding the upboard to the register.
=> upboard to the register

cli/module_registry.go
Ticket : https://viam.atlassian.net/browse/APP-2538
@dannenberg This fixed the issue on Michael's mac -- I imagine that it will fix it on yours.
=> APP-2538 - module upload on mac terminal causes flashing and/or beeping

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/base/index.svelte
https://viam.atlassian.net/browse/RSDK-4453
fix bugs for continuous base controls
=> fix tabbing issues

components/movementsensor/imuwit/imu.go
PR includes fix for the magnetometer. Modified `scalemag` function to get better compass heading. 
Tested with imu on my desk and on leo-rover.
=> RSDK-4586: IMU magnetometer fix

components/base/fake/fake.go, components/board/fake/board.go, components/board/hat/pca9685/pca9685.go, components/board/pi/impl/servo.go, components/camera/ultrasonic/ultrasonic.go, components/camera/ultrasonic/ultrasonic_test.go, components/encoder/fake/encoder.go, components/encoder/fake/encoder_test.go, components/generic/fake/generic.go, components/gripper/fake/gripper.go, components/gripper/yahboom/dofbot.go, components/input/fake/input.go, components/input/fake/input_test.go, components/input/mux/mux.go, components/input/webgamepad/webgamepad.go, components/motor/dimensionengineering/sabertooth.go, components/motor/dmc4000/dmc.go, components/motor/fake/motor_test.go, components/movementsensor/fake/movementsensor.go, components/sensor/ds18b20/ds18b20.go, components/sensor/fake/sensor.go, components/sensor/ultrasonic/ultrasonic.go, components/sensor/ultrasonic/ultrasonic_test.go, components/servo/fake/servo.go
add `resource.Named` and `logger` to all components and make sure the constructor passes both in
=> RSDK-4637: Go through resources drivers and add logger and resurce.Named to structs

components/movementsensor/imuwit/imu.go
This PR includes changes to get proper compass heading from properly parsed magnetic field.
=> RSDK-4675: compass heading 0->360

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/slam/index.svelte, web/frontend/src/main.ts
I also threw in a few other fixes that I'd like to get into app on top of the version bump
=> Override fixes

services/navigation/builtin/builtin.go, services/navigation/builtin/builtin_test.go, web/frontend/src/components/navigation/index.svelte
=> Revert "RSDK-4625 - getWaypointLoop should not close out forever if there are no waypoints"

components/movementsensor/fake/movementsensor.go
=> Remove unused config value in fake movement Sensor

cli/app.go, cli/auth.go, cli/auth_test.go, cli/client.go
Combines the commands and adds aliases.
didn't add bash autocomplete because I couldn't get it to work quickly
=> RSDK-4775 - Resolve CLI singular/plural subcommand confusion

components/base/register/register.go
Robin - you add movement sensor that is orientation reporting to the config ( so just implement your orientation in the visual odometry) and test with my control loop.
=> [RSDK-4488] Register sensor controlled base

components/arm/universalrobots/ur5e_test.go
In my branch this line was removed but it didn't get included in the last PR somehow? not sure what happened
=> RSDK-2261 FIX

cli/module_registry.go
Ticket: https://viam.atlassian.net/browse/APP-2713
=> APP-2713 - "Visibility Field" should autopopulate to "Private"

cli/module_registry.go
Ticket: https://viam.atlassian.net/browse/RSDK-4924
=> RSDK-4924 - .tgz is shorthand for .tar.gz but is not accepted by the cli validation

components/motor/gpio/motor_encoder.go
move timer so motors move at correct speed
=> RSDK-482 FIX

components/base/kinematicbase/ptgKinematics.go
This PR updates PTG kinematic bases such that a GoToInputs call will only call SetVelocity as needed, when desired velocity changes, rather than calling it constantly on each loop iteration.
=> RSDK-4945 PTG bases should only call SetVelocity if the velocities have changed

services/motion/builtin/builtin.go
This PR shifts motion service to always rebuild rather than reconfigure @nfranczak
=> RSDK-4932 always rebuild motion service instead of reconfiguring

.artifact/tree.json, components/camera/align/join.go, components/camera/align/join_test.go, components/camera/videosource/static.go, pointcloud/pointcloud_utils.go, vision/object.go, vision/segmentation/er_ccl_clustering.go, vision/segmentation/er_ccl_clustering_test.go, vision/segmentation/plane_segmentation.go
- Increase obstacles_pointcloud performance to 2.27 Hz on an Orin Nano for a 100,000 point pointcloud.
- Removes superfluous labeling of every point in the point cloud segment
- reduces time by replacing map access with slice access (big maps seem to have slower access times)
- both in the plane finding algorithm, and in the clustering algorithm 
- Adds a way to create point clouds from the new intel realsense module by making join_color_depth use "get_images" if both the color and depth camera attributes have the same name
- remove caching from image_file model -- it's much nicer to have the image in CONTROL change as soon as the file changes, rather than having to restart the server
- Used the intel realsense D435 at 424 x 240 resolution to create a point cloud of ~100,000 points.
- …
=> RSDK-4133, RSDK-4613, RSDK-4462 : Optimize the obstacles_pointcloud model, modify join_color_depth to work with new realsense module

components/base/sensorcontrolled/sensorcontrolled.go, components/base/sensorcontrolled/spin.go
The file was gettign a bit large so I moved all the Spin  internal logic to a separate file in the package.
=> Move out sensor controlled spin into separate file

components/motor/gpio/motor_encoder.go
Not sure if this is too much info, or not enough info, or structured weirdly, open to suggestions!
=> RSDK-4902: add rpmDebug back

components/motor/gpio/motor_encoder.go, components/motor/gpio/setup.go
=> RSDK-4902: FIX

components/camera/replaypcd/replaypcd.go, components/camera/replaypcd/replaypcd_utils_test.go
https://viam.atlassian.net/browse/RSDK-5112
tested locally with a replay camera!
=> [RSDK-5112] remove gzip code for replay cameras

components/board/register/register.go
Here we go... :grimacing: :grinning:
=> register the customlinux component

components/motor/gpio/motor_encoder.go
realized in initial testing I need to close control loop if it exists. wanted to merge this in now since I will be OOO for the next 2 weeks.
=> RSDK-4915: implement controls 

Makefile, etc/Dockerfile.antique-cache, packaging.make
Context: https://viaminc.slack.com/archives/C01Q5S8V6TB/p1695219771686349
=> Skip server static compression by default

cli/app.go, cli/auth.go, cli/auth_test.go, cli/client_test.go, cli/print.go, testutils/inject/app_service_client.go
Manual tests verified with Zack.
=> RSDK-4737: Create robot/location api-keys from the client 

services/vision/obstaclesdistance/obstacles_distance.go, services/vision/obstaclesdistance/obstacles_distance_test.go
Replaces the usage of the MergePointCloud method with a more straight forward (and still parallel) way of calculating the median for each point cloud.
=> bug fix: make obstacles_distance no longer uses buggy MergePointCloud function

components/movementsensor/client.go, components/movementsensor/properties.go, components/movementsensor/replay/replay.go, components/movementsensor/replay/replay_test.go, components/movementsensor/replay/replay_utils_test.go, components/movementsensor/server.go
The refactoring done in this PR is a result of working on this ticket: https://viam.atlassian.net/browse/RSDK-4858
I separated the refactoring from the feature work to make the review easier. This PR is a prerequisite for the feature work done in the following PR: https://github.com/viamrobotics/rdk/pull/3016
=> Replay movement sensor improvements

components/camera/replaypcd/replaypcd.go, components/camera/replaypcd/replaypcd_test.go, components/movementsensor/replay/replay.go, components/movementsensor/replay/replay_test.go
updates replay cameras to allow for start and end times in the future.
=> [RSDK-3906] remove past restrictions on replay camera

components/camera/align/extrinsics.go, components/camera/align/homography.go, components/camera/align/join.go, components/camera/align/join_test.go, components/camera/camera.go, components/camera/fake/camera.go, components/camera/ffmpeg/ffmpeg.go, components/camera/ffmpeg/ffmpeg_test.go, components/camera/rtsp/rtsp.go, components/camera/rtsp/rtsp_test.go, components/camera/transformpipeline/composed_test.go, components/camera/transformpipeline/pipeline.go, components/camera/transformpipeline/pipeline_test.go, components/camera/transformpipeline/segmenter_test.go, components/camera/ultrasonic/ultrasonic.go, components/camera/ultrasonic/ultrasonic_test.go, components/camera/velodyne/velodyne.go, components/camera/videosource/join_pointcloud.go, components/camera/videosource/server.go, components/camera/videosource/static.go, components/camera/videosource/static_test.go, robot/impl/resource_manager_test.go, services/vision/obstaclesdepth/obstacles_depth_test.go
https://viam.atlassian.net/browse/RSDK-4712
Please look at the chart on Jira for a more organized chart of the changes made.
Is this a breaking change btw? Since we made changes to some methods and API?
=> RSDK-4712 Ensure all camera structs have loggers and fulfill the resource.Named interface.

.github/workflows/appimage.yml
Temporarily restore appimage.yml to 6275ceb8 to unblock release
=> revert appimage workflow

components/board/analog_smoother.go, components/board/numato/board.go
Verified new analog config works on the numato, fixed issues with closing cleanly. Thank you Alan for your help debugging this!
=> RSDK-5179 Numato bug fixes 

components/movementsensor/fake/movementsensor.go, components/movementsensor/gpsnmea/gpsnmea.go, components/movementsensor/gpsnmea/pmtkI2C.go, components/movementsensor/gpsnmea/serial.go, components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go, components/movementsensor/gpsrtkserial/gpsrtkserial.go
Tests: 
- GPS RTK : Serial and I2C 
- GPS NMEA : Serial and I2C
=> RSDK-5353: Adding satellites in view to Readings

config/placeholder_replacement.go, config/placeholder_replacement_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-5316
=> RSDK-5316 - Add placeholder support for environment variables

.github/workflows/appimage.yml, .github/workflows/main.yml
We need the `.AppImage.zsync` file for aix to self-update.
[Here](https://github.com/viamrobotics/rdk/actions/runs/6589975268/job/17905909854). Destination is correct, zsync is included.
```
Uploading /home/runner/work/rdk/rdk/etc/packaging/appimages/deploy/viam-server-appimage-zsync-armhf.AppImage.zsync to gs://packages.viam.com/apps/viam-server/viam-server-appimage-zsync-armhf.AppImage.zsync
Uploading /home/runner/work/rdk/rdk/etc/packaging/appimages/deploy/viam-server-appimage-zsync-armhf.AppImage to gs://packages.viam.com/apps/viam-server/viam-server-appimage-zsync-armhf.AppImage
```
=> RSDK-5063 include zsync in 32-bit upload

components/movementsensor/replay/replay.go
This PR creates a new context with a 15 sec timeout for calls to tabular data by filter during properties initialization to prevent errors from being sent to app if data doesn't appear in the 3 minute window.
**JIRA Ticket:** https://viam.atlassian.net/browse/RSDK-5457
=> RSDK-5457 Replace Context in TabularDataByFilter call in Replay Movement Sensor

web/frontend/src/lib/components/robot-client.svelte
@npmenard @purplenicole730 I have no idea how to test this, so I will rely on you to confirm things are working as expected.
=> Set priority in RC

services/motion/explore/explore_test.go, services/navigation/builtin/explore_test.go
Skip the flaky test.
Created https://viam.atlassian.net/browse/RSDK-5605 to unskip it once the problem is corrected.
=> RSDK-5594 Skip tests

components/movementsensor/gpsnmea/pmtkI2C.go, services/datamanager/builtin/builtin.go, services/datamanager/data_manager.go
Corresponding module: https://github.com/viam-labs/trigger-sync-examples-v2
- selective sync enabled, syncs on trigger
- selective sync enabled with no syncer, does nothing
- selective sync enabled, syncing off 
- selective sync disabled, regular sync enabled
=> DATA-2092 - Support selective sync modules in datamanager

.gitignore
Ignore core dumps related to running canon emulations
=> Ignore QEMU core dumps

Makefile
I added this comment in https://github.com/viamrobotics/rdk/pull/3000, but now it's stale.
=> remove stale comment from Makefile

robot/packages/cloud_package_manager.go
Ticket: https://viam.atlassian.net/browse/APP-3075
Requires: https://github.com/viamrobotics/app/pull/2829
=> APP-3075 - Stop passing Platform into GetPackage calls

components/base/kinematicbase/ptgKinematics.go, motionplan/tpspace/ptg.go, motionplan/tpspace/ptgDiffDrive.go, motionplan/tpspace/ptg_test.go
Initial PR to fix issue for Intermode
=> RSDK-5713 diff drive ptg appears to be giving incorrect velocities

cli/app.go, cli/module_build.go, cli/module_registry.go
Ticket: https://viam.atlassian.net/browse/RSDK-5607
Questions for reviewers:
- Have I understood the module build process correctly? It runs the setup command and then runs the build command.
=> RSDK-5607 - Cli Viam module build local

cli/module_registry.go
I realized that I forgot to manually test that the instant after I merged. Waste of time. My bad.
Tested now.
=> Add omitempty to fix bug

web/frontend/src/components/board/index.svelte
Value for the analog write inputs was wrong.
=> RSDK-5732 fix board RC card bug 

.github/workflows/cli.yml, .github/workflows/droid.yml, .github/workflows/staticbuild.yml, .github/workflows/testcleanup.yml
Follow-up to https://github.com/viamrobotics/rdk/pull/3259. (Do this in more places).
=> pin auth action everywhere

web/frontend/src/components/slam/index.svelte
This PR removes the 3D map view from the SLAM card.
OLD
NEW
**JIRA Ticket:** https://viam.atlassian.net/browse/RSDK-5513
=> RSDK-5513 Remove 3D Map View from SLAM RC card

examples/customresources/README.md
This should be `component` per Rand in #team-bucket.
=> Fix base API triplet

components/base/wheeled/wheeled_base.go, module/modmanager/manager.go, module/modmanager/manager_test.go, resource/errors.go, robot/impl/local_robot.go, robot/impl/local_robot_test.go, robot/impl/resource_manager.go, utils/env.go, utils/errors.go
adds a separate var (+ separate env var)
oueTimeout has been removed as well
=> RSDK-5917 - Increase module startup timeout

services/motion/motion.go
[Ticket](https://viam.atlassian.net/browse/RSDK-6001)
=> RSDK-6001 - Fix typo in the motion.go doc comment

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/api/navigation.ts, web/frontend/src/components/navigation/hooks/use-paths.ts, web/frontend/src/components/navigation/index.svelte
- Bump `@viamrobotics/remote-control` version
- Add `usePaths` hook that polls `navClient.getPaths`
- Provide paths to `@viamrobotics/prime-blocks` `NavigationMap` component
=> RSDK-4825: call GetPaths RPC and render in the nav card

components/camera/transformpipeline/classifier.go, components/camera/transformpipeline/detector.go, vision/classification/postprocessor.go, vision/objectdetection/postprocessor.go
Tested this on Mac with classifier and detector and it works. I'm using a map instead of a slice of strings because it'll be faster (especially in the case where people have like 20+ valid classes).
=> RSDK-5920 - Add class filter to transform camera 

cli/README.md, cli/app.go, cli/auth.go, cli/auth_test.go, cli/client.go, cli/data.go, cli/flags.go, cli/flags_test.go
Updates all user facing instances of robot to machine. Decided against update every mention because that's a huge surface area.
AliasStringFlag was added because otherwise errors show like 
instead of
also tested using robot as an alias
=> APP-3022 - Update CLI to use "machine" over "robot"

README.md
We should describe/document the behavior of environment variables.
There is also `VIAM_DEBUG` which seems to skip a couple tests; I did not think it was worth mentioning in the README.
=> Describe environment variable behavior in README

logging/impl.go
Thanks for catching these. Also we need to chat about how I can better setup github so I get the updates I need without the firehose of the entire rdk repo.
=> RSDK-5278: Fix shouldLog predicate for Error.

services/datamanager/builtin/sync_test.go, services/datamanager/datasync/upload_arbitrary_file.go
Test locally with config in Data/ML Dev in staging
=> DATA-fix - Flip inequality

components/movementsensor/dualgps/dualgps.go, components/movementsensor/dualgps/dualgps_test.go
Takes the midpoint between the two GPS devices and reports that as the position.
Takes an average of the altitudes reported and reports that.
Returns nan with an error.
=> Implement Position in dual-gps-rtk driver

components/movementsensor/gpsnmea/pmtkI2C.go, components/movementsensor/gpsnmea/serial.go
Adding a debug statement to make it clearer that user might need to take their gps outside.
=> RSDK-6197: clearer debug statement for gps nmea parser

motionplan/tpSpaceRRT.go
[Ticket](https://viam.atlassian.net/browse/RSDK-6215)
=> [RSDK-6215] - Fix motion data races

testutils/inject/robot.go
I tested this with the command `go test ./robot/web -run TestWebWithStreams -count 1000 -race`
=> RSDK-6237 fix data race in TestWebWithStreams

cli/README.md
I stumbled upon this during my vacation and realized that some cleanup of the README could be nice.
=> Update CLI readme to include installation methods

components/base/wheeled/wheeled_base.go
adjusted the `MoveStraight` function to closer match the `SetVelocity` function since that one works better. The only difference was that `MoveStraight` did not call `CancelRunning`. Once added, the behavior improved but still is not perfect, likely because RPM monitor in gpio/motor_encoder.go is attempting to control the position. Hopefully when controls are fully implemented this issue will be fully resolved.
More info about testing and results in the JIRA ticket
=> RSDK-5921: MoveStraight does not move as straight as SetVelocity or SetPower

services/motion/builtin/move_request.go
Tested on hardware before and after and confirmed to work.
=> RSDK-6273 Remove requirement for a base to be in the frame system to move

components/board/genericlinux/gpio.go
Tried on a Jetson Orin with a servo: the difference is night and day! Stop by my desk for a demo if you're interested.
=> [RSDK-6347] more accurate sleep for SW PWM

referenceframe/urdf/model_test.go, referenceframe/urdf/testfiles/example_gantry.urdf, referenceframe/urdf/testfiles/example_gantry.xml, referenceframe/urdf/testfiles/ur5_minimal.urdf, referenceframe/urdf/testfiles/ur5_viam.urdf
- Change the URDF files in RDK to pass [check_urdf](https://wiki.ros.org/urdf)
=> fix urdf test files

robot/impl/robot_reconfigure_test.go, utils/errors.go
removes text around the env vars
=> Update resource/module timeout msg

web/frontend/src/components/remote-control-cards.svelte
@ethanlook we need to run the formatter PR on this repo ASAP or accept incoming PRs will include formatting changes. It is becoming incredibly annoying to write PRs.
=> Remove if statement around do command card

.github/CODEOWNERS
Same as #3452, but adding @micheal-parks.
=> APP-3656: Add @micheal-parks as web/frontend CODEOWNER

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/slam/index.svelte
[Ticket](https://viam.atlassian.net/browse/RSDK-6435)
Depends on:
1. https://github.com/viamrobotics/rdk/pull/3450
2. https://github.com/viamrobotics/prime/pull/470
Manually Tested using Fake SLAM:
https://github.com/viamrobotics/rdk/assets/5927876/25a12ca5-434b-4ae8-9876-ce404bdd1ec1
Testing drag & drop:
https://github.com/viamrobotics/rdk/assets/5927876/596daab7-a1d6-4d6f-8a82-e5fca75b456d
=> RSDK-6435 - Integrate refactored Prime SlamMap2d into the RC card

components/movementsensor/gpsnmea/nmeaParser.go
I recommend reviewing this commit-by-commit: they're mostly self-contained.
=> little cleanup steps in nmeaParser.go

web/frontend/src/api/motion.ts
https://viam.atlassian.net/browse/RSDK-6439
=> RSDK-6439 - [Frontend] [RC] Reduce motion.MoveOnMap plan_deviation_m on SLAM RC card

robot/packages/cloud_package_manager.go
just a drive by when i was looking into something in the vicinity
=> Change cloud manager Debug logs to Debugf

web/frontend/package-lock.json, web/frontend/package.json
bump due to 
https://github.com/viamrobotics/prime/pull/472
=> RSDK-6494 - bump prime blocks dep

components/base/kinematicbase/differentialDrive.go, components/base/kinematicbase/ptgKinematics.go
Update default base geometry from a point, to a 300mm-diameter sphere
=> RSDK-6502 Give base a bigger default geometry

components/movementsensor/gpsnmea/nmeaParser.go, components/movementsensor/gpsnmea/serial.go, components/movementsensor/gpsnmea/serial_test.go
Each commit in this PR should be self-explanatory and (nearly) independent of the others. This is just general tightening-up of the code.
=> [RSDK-5462] clean up gpsnmea/serial.go

components/movementsensor/rtkutils/ntrip.go
removed extra check in ParseSourcetable which was causing failure.
=> quick-fix: parser wasn't parsing

components/movementsensor/gpsrtkserial/gpsrtkserial.go
Again, review commit-by-commit. Each one has a description of why it's the right thing to do.
=> [RSDK-5462] Fewer mutexes in the GPS RTK Serial component

components/movementsensor/gpsrtkserial/gpsrtkserial.go, components/movementsensor/gpsrtkserial/gpsrtkserial_test.go
I should finish understanding the second half of this file, but the current PR is already large enough to be its own thing.
Like the previous PRs on this, I recommend reviewing commit-by-commit because they're all fairly self-contained but they overlap with each other. No changes to behavior are intended!
=> [RSDK-5462] More simplifying the control flow of GPS stuff, nearly to the main refactor

etc/configs/fake_cloud_slam.json
**JIRA Ticket:** https://viam.atlassian.net/browse/RSDK-6432
=> RSDK-6432 Create fake slam reference config

services/motion/builtin/builtin_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-6326)
=> RSDK-6326 - Unskip TestMoveOnMapNew bump timeout

components/base/kinematicbase/ptgKinematics.go
This fixes the one line of code I added after I completed testing. I sadly missed this.
=> Fix ErrorState bug in PTGKinematicBase

components/base/sensorcontrolled/sensorcontrolled.go, components/movementsensor/adxl345/adxl345.go, components/movementsensor/adxl345/adxl345_test.go, components/movementsensor/adxl345/interrupts.go
Doing a little cleaning when I notice things, none of these have to be exported constants or functions.
=> Unexport some component constants and functions

control/setup_control.go
add setup_control file with helper functions for creating, tuning, and starting a control loop
=> RSDK-6465 [part1]: add helper functions for a control loop

services/motion/builtin/builtin_test.go
skip TestObstacleReplanningSlam until https://github.com/viamrobotics/rdk/pull/3639 is merged.
=> skip TestObstacleReplanningSlam

config/config.go, config/config_test.go, config/module.go, resource/config.go, resource/config_test.go, utils/variables.go, utils/variables_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-6798
Scope: https://docs.google.com/document/d/1gWTPjK9rrbc4aPrK44E1rg8Wt7Fa7jlfeU6NKUUq1R4/edit
Requests:
@nataliajacobowitz Can you please verify that the function `ErrInvalidName` is returning reasonable strings and that the regex looks correct (I think it matches your scope)
@michaellee1019 @dgottlieb  added for context / code review
=> RSDK-6798 - Update RDK resource & package & module name regexes

module/modmanager/manager.go
Addresses https://viam.atlassian.net/browse/RSDK-6806
=> [RSDK-6806] Add warning for slow starting modules

robot/impl/local_robot_test.go
same fix as https://github.com/viamrobotics/rdk/pull/3648
=> RSDK-6828 - Fix local robot test flake

control/pid.go
Since most of our API asks are Positional goals with velocity targets, this might be a useful tuner for the controls package.
If anyone knows of a resource with more significant digits for the computation let me know!
=> Add Ziegler Nichols PD Tuning computation to the Control Package

module/modmanager/manager.go
Followup from six week check-in
=> Update slow module startup ticker to 2 secs

components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go, components/movementsensor/rtkutils/cachedData.go
Changes in this PR includes implementation of compass degree error for GPSRTK and some minor cleanup in gps rtk pmtk. 
Here I am calculating the distance between two points (using last position and current position) and calculating theta between them using the radius of 5m when we have a lower fix and 10cm when we have a higher fix.
=> Rsdk-6731: compass degree error gps

cli/auth.go
https://viam.atlassian.net/jira/software/c/projects/APP/boards/64
=> [APP-4223]: Update auth client and audience (for device authorization flow in CLI)

control/control_loop.go, control/pid.go, control/pid_test.go
more info on the problem [here](https://viam.atlassian.net/browse/RSDK-6753)
small change, but I'm a bit confused by this "fix" so I left some comments/questions
=> RSDK-6753: sensor controlled base fails when oversaturating the controller

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/slam/index.svelte
https://viam.atlassian.net/browse/RSDK-6872
this PR updates the frontend to request edited maps while in localizing mode
=> [RSDK-6872] return edited map in localizing mode

config/proto_conversions.go
https://viam.atlassian.net/browse/RSDK-7087
=> [RSDK-7087] Display failed fragment mod updates in robot logs

components/base/sensorcontrolled/movestraight.go, components/base/sensorcontrolled/sensorcontrolled_test.go
https://viam.atlassian.net/browse/RSDK-7112
=> [RSDK-7112] fix compass heading sensor function

rimage/image_file.go, rimage/lazy_encoded.go
A simple method on LazyEncodedImage that allows access to the decoded image
=> rsdk-7241: adds a way to decode lazy encoded images

README.md
change link from rsdk to support portal for reporting issues
=> Change README.md support link 

components/base/sensorcontrolled/velocities.go, components/motor/gpio/loop.go, control/setup_control.go
I think this should work but I'll test tomorrow in office to confirm.
=> [RSDK-6874][RSDK-7279]: Rover making endless noise after calculating control parameters & fix tuning

components/board/board.go, components/board/client.go, components/board/client_test.go, components/board/collector.go, components/board/collectors_test.go, components/board/fake/board.go, components/board/fake/board_test.go, components/board/genericlinux/board.go, components/board/genericlinux/board_test.go, components/board/hat/pca9685/pca9685.go, components/board/numato/board.go, components/board/numato/board_test.go, components/board/pi/impl/board.go, components/board/pi/impl/external_hardware_test.go, components/board/pinwrappers/analogs.go, components/board/server.go, components/board/server_test.go, components/board/status.go, components/gripper/softrobotics/gripper.go, components/input/gpio/gpio.go, components/input/gpio/gpio_test.go, robot/impl/local_robot_test.go, robot/impl/resource_manager_test.go, testutils/inject/analog.go, testutils/inject/analog_reader.go, testutils/inject/board.go, web/frontend/src/components/board/index.svelte
Still a few renames to go in resource manager and injects, feel free to pick those up if you have time today.
=> [RSDK-7321] Rename AnalogReaders -> Analogs

web/frontend/package.json, web/frontend/src/components/arm/index.svelte
This is a patch fix for the current arm bug in prod. End position is an optional.
=> Mark end position as optional

components/board/pinwrappers/analogs.go, components/movementsensor/mpu6050/mpu6050.go, gostream/stream.go, utils/stoppable_workers.go
This is the core piece of https://github.com/viamrobotics/rdk/pull/3581. Once this is in, I'll start making other PRs for various other teams to start using this elsewhere.
I workshopped the name at the 20% happy hour: folks didn't like the more playful names, and thought this one was pretty good.
=> Create StoppableWorkers struct

components/board/numato/board.go
I was hoping to get to more boards during 20% Happy Hour today, but this was the only one I finished. 
No changes to behavior are intended: my goal is just to start using StoppableWorkers in all the places that fit this pattern. This one doesn't _quite_ fit perfectly because the background goroutine doesn't actually check a context to see if it should shut down, but it's close enough that I think this is still a useful change (if you disagree, let's talk, and maybe I'll close this PR!).
=> use StoppableWorkers in the Numato board

web/frontend/src/components/board/index.svelte
I know we said to do this post config debugging, but I am blocked sitting on a e2e test to run and this is a simple enough fix
=> No w-full digital interrupts

logging/proto_conversions.go, robot/web/stream/server.go, robot/web/stream/stream_test.go, robot/web/web_c.go, robot/web/web_test.go
There's a windows file too, but I left it untouched.
=> RSDK-7203: Remove audio intentions from gostream configuration.

components/motor/gpio/motor_encoder.go
found a bug during testing where the rpm monitor would exit before the success condition used by WaitForSuccess was completed, which would cause goFor calls to hang indefinitely. since [controlled motors](https://github.com/viamrobotics/rdk/blob/4794a927bcf1e2addebb720701ddea0aa3ed012a/components/motor/gpio/loop.go#L266) now implement their own GoFor logic, we no longer need a separate blocking function to handle both cases. This means GoFor with an encoder without controls will now exit whenever the motor meets or exceeds the desired position. 
Another possible solution would be to update rpmMonitor to use the same success condition as WaitForSuccess, but the way rpmMonitor is currently implemented the motor will not reverse directions, and the power the motor uses is purely determined …
=> [RSDK-7504] make rpm monitor blocking

web/server/entrypoint.go
https://viam.atlassian.net/browse/RSDK-7563
=> [RSDK-7563] - default v4l2 diagnostic logger to off

components/movementsensor/gpsutils/cachedData.go
It should be used in 2 more files in this directory (i2c_data_reader.go and serial_data_reader.go), but first I need to add an extra feature to `StoppableWorkers`. That will come later, but in the meantime, at least this file can have its pattern updated.
`start()` used to spawn a new goroutine. Instead, it now _is_ the code that runs in the new goroutine, which means everything inside it was unindented another level. So, the diff looks bigger than it really is. I'd **review this with whitespace changes ignored.**
=> use StoppableWorkers in gpsutils/cachedData.go

robot/session_test.go
- add subloggers to all tests, but only added comments to a few of the more confusing ones.
- came away with a slightly different understanding of what the tests were doing @dgottlieb, happy to discuss if there are questions
=> Add sublogger + some comments to session tests

components/movementsensor/adxl345/adxl345.go, components/movementsensor/adxl345/adxl345_test.go
Not yet tried on actual hardware; will do that soon.
Slowly but surely, my goal is to replace this pattern everywhere with the `StoppableWorkers` struct!
=> Use StoppableWorkers in the ADXL345 implementation

components/board/numato/board.go, components/board/pinwrappers/analogs.go
- numato hung on close if you disconnected the board
- when you disconnected the board the errors spammed the logs, changed to only log every 10 seconds
=> RSDK-7623 numato bug fixes

robot/impl/resource_manager.go
Move two flyby refactors out of https://github.com/viamrobotics/rdk/pull/3707 to reduce noise. This PR is no-op in terms of functionality changes.
* rename `*localRobot` variables from `robot` to `lr` so we don't conflict with the `robot` module
* move the remote processing loop in `completeConfig` into a function
=> RSDK-6925 Prefactors

cli/app.go, cli/ml_training.go
Manually tested all commands as part of [custom ML training test plan](https://docs.google.com/document/d/1zHQIZbp6KmS_7jSVQt5o9BRDtwmXNKpUWRAxzdkR-hk/edit?usp=sharing)
=> DATA-2647 - Add command for submitting custom training job and refactor existing train commands

vision/objectdetection/detection_utils.go
Rather than loading the image, and writing the bounding boxes in a for-loop over the original image, create a blank image, write the bounding boxes on the blank image, and then overlay all the bounding boxes at once on the original image.
=> RSDK-7631: Change the overlaying bounding boxes 

services/datamanager/builtin/builtin.go, services/datamanager/datasync/noop_sync.go, services/datamanager/datasync/sync.go
1. Tested with sync interval of 1 minute
2. Tested with sync interval of .1 minute (the default)
=> DATA-2652 - Keep retrying sync if within the sync interval

.github/workflows/appimage.yml, .github/workflows/staticbuild.yml, .github/workflows/test.yml
=> migrate runners

.github/workflows/appimage.yml
install libfuse2 in more cases
=> fix libfuse install

module/modmanager/manager_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-7667)
=> RSDK-7667 - remove test SubscribeRTP timeout

components/base/kinematicbase/execution.go, motionplan/tpSpaceRRT.go, motionplan/tpSpaceRRT_test.go, motionplan/tpspace/ptg.go, motionplan/tpspace/ptgGridSim.go, motionplan/tpspace/ptgGroupFrame.go, motionplan/tpspace/ptgGroupFrame_test.go, motionplan/tpspace/ptgIK.go, motionplan/tpspace/ptgIKFrame.go, motionplan/tpspace/ptg_test.go
This change should be a transparent no-op from a user's perspective. Prerequisite to the testing updates coming with RSDK-7558
=> RSDK-7515 update ptg inputs to no longer be negative

vision/classification/classifier.go, vision/classification/classifier_test.go
Fix bug that returned "max" when it should have been "min".
Also adds log such that negative N requests return all classifications
=> fix top N classification bug and add tests

module/modmanager/manager_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-7959)
=> RSDK-7959 - Skip Test modmanager.TestRTPPassthrough

components/motor/dimensionengineering/sabertooth.go, components/motor/dimensionengineering/sabertooth_test.go, components/motor/dmc4000/dmc.go, components/motor/dmc4000/dmc4000_test.go, components/motor/fake/motor.go, components/motor/fake/motor_test.go, components/motor/gpio/basic.go, components/motor/gpio/basic_test.go, components/motor/gpio/controlled.go, components/motor/gpio/encoded.go, components/motor/gpio/mathutils.go, components/motor/i2cmotors/ezopmp.go, components/motor/motor.go, components/motor/roboclaw/roboclaw.go, components/motor/tmcstepper/stepper_motor_tmc.go, components/motor/tmcstepper/stepper_motor_tmc_test.go, components/motor/ulnstepper/28byj-48.go, components/motor/ulnstepper/28byj-48_test.go
this update will need to be added in SetRPM for current open PRs
=> RSDK-7979: use checkSpeed helper in all motor drivers

components/base/kinematicbase/execution.go, motionplan/ik/metrics.go
Follow-up PR for RSDK-7558 adding a couple of missed tweaks.
This is necessary for passing extended motion tests.
=> RSDK-6700 testing for motion

cli/client.go
I think this might be helpful to people
=> Include link to update instructions

components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go, components/movementsensor/gpsrtkserial/gpsrtkserial.go
I strongly urge you to review this commit-by-commit! and for the commits that mention flattening the code, review while ignoring whitespace changes.
No changes to behavior are intended: this is just some cleanup of parts I had misunderstood and had to ask Susmita about.
Tried on piworld: works like normal.
=> [RSDK-7081] Simplify control flow in receiveAndWriteSerial

.github/CODEOWNERS
Changes:
- Add @zaporter-work 
- Update the comment with the correct epic and team
=> Update web/frontend CODEOWNERS

cli/app.go
Following up on [this PR](https://github.com/viamrobotics/rdk/pull/4167) to:
- change the help text
- rename from download to export to make more consistent with data export
=> DATA-2677 - Update CLI commands to be consistent

components/movementsensor/gpsutils/vrs.go
This is what was required to fix ntrip/RTK for my wisconsin system. Two things... need line endings on sending the GGA message to start the data flow, and secondly, need to actually WAIT for a GGA message to be available before starting. (My desktiop is fast, and network is hardwired, so probably out raced stuff in a way a Pi on wifi doesn't.)
=> Fix GPS-RTK ntrip problems

vision/objectdetection/color_detector.go, vision/objectdetection/color_detector_test.go
Changes the error message to explain why the color won't work well for the color detector.
=> Adds clearer error message for color detector

services/mlmodel/tflitecpu/tflite_cpu.go, services/mlmodel/tflitecpu/tflite_cpu_test.go
Check to see if the file is indeed a tflite file, and error if it isn't
=> Rsdk-8278: check tflite_cpu file ext

components/movementsensor/gpsrtk/gpsrtk.go, components/movementsensor/gpsutils/ntrip.go
Thanks to @susmitaSanyal for pointing these things out even after I merged!
=> pr feedback from #4215

components/arm/fake/fake.go, components/arm/fake/fake_test.go
This fixes a bug in the `fake` arm model that returns radians instead of degrees.  Unit tests really should have caught something as trivial as this, so adding those here.
=> fix bug in fake arm and add unit tests

cli/module_registry.go
I was just hunting for something to change -- I need a rdk release to test some changes I made in app. This link was outdated.
See: https://docs.viam.com/cli/#module
=> Update cli module docs url

components/motor/gpio/controlled.go
As far as I can tell from app, there's no kick, but to double check can I run some tests while you look at the motors in person @JohnN193 ?
=> RSDK-8328: Controlled motor does not handle ResetZeroPosition

components/motor/gpio/encoded.go
fixing power before calling SetPower and capping ramp rate at config level
=> Rsdk-8162: fixing rpm power

cli/app.go
This seems like a huge diff, but I am just literally moving something
=> DATA-2941 - Move CLI commands for adding/removing to a dataset

cli/ml_training.go
=> DATA-2983 - Improve with upload command

cli/app.go, cli/ml_training.go
Another day, another CLI update
=> Allow URL to be set in update command for training scripts

examples/apis.json
Updates the `apis.json` file to use the new fields we use for code sample generation. See similar changes for the Python SDK here: https://github.com/viamrobotics/viam-python-sdk/pull/635
=> Update apis.json with new fields

gostream/media.go, gostream/media_test.go
[RSDK-8602](https://viam.atlassian.net/browse/RSDK-8602)
[RSDK-8602]: https://viam.atlassian.net/browse/RSDK-8602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RSDK-8602] Release stream image after for loop termination (Gostream) 

operation/web.go
for a repro, look at https://viam.atlassian.net/browse/RSDK-8663
=> RSDK-6985 - Filter out SetHeader errors

components/input/input.go, components/motor/motor.go, components/movementsensor/movementsensor.go, components/posetracker/pose_tracker.go, components/powersensor/powersensor.go, components/sensor/sensor.go, components/servo/servo.go, resource/resource.go
* Add the rest of the components
* Add brief descriptions for some components
=> DOCS-2498: Link from RDK docs to main docs on component pages part 2 

robot/web/stream/server.go
This corrects a bug introduced in RSDK-7403.
=> RSDK-8821: Remove stream server assumption that all streams are cameras.

services/datamanager/builtin/builtin_capture_test.go, services/datamanager/builtin/builtin_sync_test.go, services/datamanager/builtin/builtin_test.go
fixes: https://viam.atlassian.net/browse/RSDK-8872
=> RSDK-8872 - flakey test fix

cli/module.schema.json
Forgot to include this in the PR which added this option to the CLI: https://github.com/viamrobotics/rdk/pull/4412
=> APP-6561: Add public_unlisted as visibility type in module schema

components/camera/videosource/webcam.go
This PR addresses noisy logger when monitored camera is in a reconnect try loop.
=> [RSDK-7560] - Make monitored webcam reconnect logs debug

logging/logger_registry.go, web/server/entrypoint.go
reverts https://github.com/viamrobotics/rdk/pull/4452
cc: @Kschappacher
=> RSDK-8902 - Add appender to all loggers in registry

logging/impl.go, logging/logger.go, logging/proto_conversions.go, robot/impl/local_robot_test.go, robot/server/server.go
=> RSDK-9041 Unconditionally output all incoming LogRequests

components/board/genericlinux/board.go, components/board/genericlinux/board_test.go, components/board/mcp3008helper/mcp3008.go
https://viam.atlassian.net/browse/RSDK-9010
=> [RSDK-9010] change MCP3008 analog reader config from pin to channel 

ftdc/custom_format.go, ftdc/custom_format_test.go, ftdc/ftdc.go, ftdc/ftdc_test.go, resource/graph_node.go, resource/graph_node_test.go, resource/resource_graph.go, resource/resource_graph_test.go, robot/impl/local_robot.go, robot/impl/resource_manager.go, robot/impl/robot_options.go, web/server/entrypoint.go
Another mess of a PR. Annotating inline
=> RSDK-8819: Instrument robot with FTDC. Gated on startup flag.

ftdc/cmd/parser.go, ftdc/custom_format.go, ftdc/custom_format_test.go, ftdc/ftdc.go, ftdc/ftdc_test.go
An example image from invoking:
```
$ go run ftdc/cmd/parser.go viam-server.ftdc
$ gnuplot plot.gpl && open plot.png
```
=> RSDK-8819: Add an FTDC -> gnuplot compiler.

components/movementsensor/dualgps/dualgps.go
Sneaking this in before you modularize it.
=> Add check for Position Supported in dualgps creator

resource/discovery.go, robot/impl/discovery_test.go, robot/impl/local_robot.go
=> make errors reported during discovery

module/modmanager/manager.go
The underlying data structures are threadsafe.
=> RSDK-9353: Remove unnecessary locks. 

services/mlmodel/mlmodel.go
* improve infer and metadata examples
* adds needed import, from robot
* mirrors example i did that worked although built off of original example
=> DOCS-2953: QA ml model service docstrings

ftdc/ftdc.go, robot/impl/local_robot.go, robot/web/web.go, robot/web/web_c.go, robot/web/web_notc.go
I'm kind of curious why a test hasn't hit this. In case you have any ideas. I might dig deeper into that.
=> RSDK-9369: Check for rpc server existence before accessing.

app/data_client.go
rename to be consistent with other SDKs
=> rename query parameter

services/vision/collectors.go, services/vision/collectors_test.go
https://viam.atlassian.net/browse/RSDK-9661
from https://github.com/viamrobotics/rdk/pull/4662
This is a dead code that is not used.
=> [RSDK-9661] - vision.CaptureAllFromCamera data collector remove dead mime_type

services/datamanager/builtin/disk_summary_logger.go, services/datamanager/builtin/disk_summary_logger_posix.go, services/datamanager/builtin/sync/stats.go, services/datamanager/builtin/sync/sync.go
https://viam.atlassian.net/browse/DATA-3570
=> DATA-3570 - downgrade frequent DM logs to debug

services/baseremotecontrol/base_remote_control.go, services/datamanager/data_manager.go, services/generic/generic.go, services/mlmodel/mlmodel.go, services/motion/motion.go, services/navigation/navigation.go, services/slam/slam.go, services/vision/vision.go
Add method backlinks to all services
=> DOCS-3353: Add method backlinks to services

components/movementsensor/movementsensor.go, components/powersensor/powersensor.go, components/sensor/sensor.go, components/servo/servo.go, resource/resource.go
* Add backlinks movement sensor - servo
=> DOCS-3353: Add backlinks part 3

cli/module_generate.go
Fixes issue with generic module generation failing from user prompts. cc @abe-winter @zaporter-work
=> RSDK-9764 - fix special case of generics for user prompted modulegen

config/module.go, config/module_test.go, config/reader.go
=> Fix MergeEnvVar panic

README.md
We no longer have a local rc card
=> Remove mention of localhost in rdk readme

cli/auth.go
=> Fix no browser warning in the cli

services/motion/motion.go, spatialmath/box.go, spatialmath/capsule.go, spatialmath/mesh.go, spatialmath/mesh_test.go, spatialmath/point.go, spatialmath/sphere.go, spatialmath/triangle.go
Prereq for coverage V2, as we need to do collision checks against meshes.
Drive-by fix to our example code for GetPose
=> RSDK-10025 Update mesh to fill geometry interface

components/button/button.go, components/switch/switch.go
=> Remove comments on blocking from button and Switch interface methods.

cli/auth.go
Ignore the hotfix here's an actual fix
=> APP-7706 - fix ensureloggedin logic for api key login

spatialmath/dualquaternion.go
Default to precision of 6.
This has been driving me nuts so I fixed it
=> RSDK-10053 Set default precision on pose pretty-print

robot/impl/local_robot.go, web/server/entrypoint_test.go
=> RSDK-10166 Allow moving from initializing -> running with no-resource Config

robot/web/stream/server.go
=> Only print pointer value for remove video stream log

services/datamanager/builtin/sync/file_deletion_windows.go
Info log is too noisy. Request from Eliot to change to a debug
=> RSDK-10206 Switch no files log from info to debug

cli/app.go
Used to be inference infer, fixed to be just be infer.
=> Inference Help Text Fix

motionplan/collision.go, spatialmath/mesh.go
Also a drive-by addition of a `String()` method to meshes
=> Quick fix to collision spec

robot/impl/local_robot.go
we retry each remote on a ticker, so no need to try connecting to something that isn't there for more than once
feel free to merge if this looks good
=> Reduce dial attempts

services/datamanager/builtin/sync/connectivity.go
cc @nicksanford 
I still have to test this on a pi but should work/be quite similar.
=> RSDK-10352 Allow datasync network check to succeed behind BLE-SOCKS bridge

module/module.go
=> RSDK-10368 Actually surface Golang modular resource reconfigure errors

services/vision/fake/vision.go
- add fake camera name attribute to act as default camera
=> [RSDK-10168] - add default camera behavior to fake

services/vision/register/register.go, services/vision/register/register_cgo.go
I believe this is the only thing we need to change to make the color detector available on windows?
=> We would like the color detector on windows

cli/module_generate/_templates/python/src/models/tmpl-resource.py, cli/module_generate/scripts/generate_stubs.py
**DRAFT UNTIL https://github.com/viamrobotics/viam-python-sdk/pull/918 IS RELEASED**
=> Add new validate in python

grpc/shared_conn.go
- edited log message for spelling
(noticed in logs)
=> copy edit loppback -> loopback

cli/module_generate.go
Add additional cloud build platforms. These 4 platforms are the only ones that trigger a cloud build
=> [RSDK-10654] cloud build platforms

referenceframe/model.go
Nothing uses it and it has been deprecated for a year.
=> Remove ComputePosition from RDK

grpc/app_conn.go
we'll get a bit more info with this change, at least the error will be shown
=> More logs around initial dial to app

config/logging_level.go, logging/impl.go, logging/log_config.go, logging/log_config_test.go, logging/logger_registry.go, logging/logger_registry_test.go, logging/logging.go, logging/net_appender.go, utils/file.go
Pattern validation missed some cases that made matching specific remote resources impossible.
=> RSDK-10893: Remove pattern validation.

ftdc/cmd/parser.go, robot/web/web.go, robot/web/web_test.go
Also:
- Refactor stats to reduce code for new stats. 
- And the number of concurrent map accesses.
=> RSDK-10982: Add more FTDC stats and renderings.

app/app_client.go
https://viam.atlassian.net/browse/RSDK-11147
=> [RSDK-11147] Fix GetRobotPartMetadata to use the correct protobuf request

examples/apis.json
=> RSDK-10680 - support commented code samples

ftdc/ftdc.go
May want to look at the commits separately. First one is simplest/duplicates code. The second one refactors away the code duplication.
=> RSDK-11219: On restart, upload the latest FTDC file.

ftdc/cmd/parser.go
Just copied your diff from offline.
=> Fix FTDC issue writing starting datapoints

cli/module_generate/scripts/generate_stubs.go
Remove `NewClientFromConn` when generating a golang. mod
=> [RSDK-10361] Remove unnecessary client code

spatialmath/mesh.go
A recent PR improved mesh.ToPoints, however we were actually relying on the old bad behavior of ToPoints for collision checks with boxes. The new behavior did far, far more work and made mesh collision checks unreasonably slow.
This PR fixes the new version and improves on the old behavior and makes this even faster than it was.
=> Fix boxIntersectsVertex which was tanking mesh collision speed

etc/lint_register_apis.sh
I merged that hotfix a bit too fast and left half this linter script commented out 😅
=> Fix lint_register_apis.sh

ftdc/ftdc.go, robot/impl/local_robot.go
This PR answers the first part of this [ticket](https://viam.atlassian.net/jira/software/c/projects/RSDK/boards/69?assignee=712020%3A41710d7e-57d4-4faa-993a-66e0e9f5b64b&selectedIssue=RSDK-11245). Doing the suggested windows check worked well. Happy to wait until the outage is fixed for another confirmation that this fix works as expected.
=> RSDK-11245 Logical FTDC on windows

Makefile, module/module_interceptors_test.go, testutils/file_utils.go, testutils/robottestutils/robot_utils.go, web/server/entrypoint_test.go
add a few that seemed the most important
and re-enable some tests for arm 32bit
=> RSDK-11487 - Add tests for expected registered models

web/networkcheck/network-check.go
RSDK-11564
Does not report test results for DNS connectivity checks against 127.0.0.53:53 in the event that we get `connection refused` (or when running on MacOS / Windows). Some Linux distros, including Raspberry Pi OS, do not have `systemd-resolved` installed or running by default.
Tested on Linux and MacOS. Seems to work as expected with `systemd-resolved` running and with it stopped.
=> RSDK-11564 Ignore connection refused errors from systemd-resolved in DNS conn tests

pointcloud/pointcloud.go, pointcloud/pointcloud_test.go
This is a follow-up to https://github.com/viamrobotics/sanding/pull/224, which suggested making a more general way to convert point clouds to arrays of points.
=> Point cloud to points

motionplan/armplanning/real_test.go
plan motion now returns three values.
=> Pirouette test fix
