- components/audioinput/client.go
- components/audioinput/client_test.go
Resolve [this issue](https://github.com/viamrobotics/rdk/pull/3467) for audio streams
1. Run two instances of RDK locally, with the following two respective configurations in separate terminals
main.json
```json
{"network":{"bind_address":"localhost:8081"},"remotes":[{"name":"robot1","address":"something-unique"}]}
```
remote.json
```json
{"network":{"fqdn":"something-unique","bind_address":":8080"},"components":[{"name":"audio_input1","type":"audio_input","model":"fake"}]}
```
2. Visit: http://localhost:8081 and open the stream for `robot1:audio_input1` - you should hear a droning tune.
3. Stop server running `remote.json` - the tune from step 2 will cut out.
4. Restart the server running `remote.json` - perform step 2 again and you should be able to hear the tune again (you may have to …
> RSDK-6475 Allow audio streams to restart after disconnect

- resource/graph_node.go
- robot/impl/local_robot.go
- robot/impl/resource_manager.go
- robot/impl/resource_manager_test.go
I was wondering why trying to build a resource model that doesn't exist wasn't logging - turns out we didn't have a logger set
> RSDK-6473 - Create all graph node loggers before errors

- gostream/codec/h264/encoder.go
- gostream/stream.go
- web/server/entrypoint_linux.go
This PR adds h264 encoder check and initialization to entrypoint. All flaky behavior and encoder bugs have been fixed. Code diff includes linter fixes for encoder closeouts.
- Tested that livestreams are robust against start/stops and webrtc session refreshes
- Tested this branch against canary runners overnight
- Tested entrpoint defaults to x264 on non-RPI4 boards
- Tested with multiple input src pixel formats (YUYV, MJPEG)
- Halfed cpu utilization for 1280p video
> RSDK-5916 - Add h264 encoder to entrypoint

- components/movementsensor/gpsnmea/gpsnmea.go
- components/movementsensor/gpsnmea/pmtkI2C.go
- components/movementsensor/gpsnmea/pmtkI2C_test.go
- components/movementsensor/gpsnmea/serial.go
- components/movementsensor/gpsnmea/serial_test.go
...and also, don't bother storing the baud rate for later because we never use it later.
This is a breaking change! 
I recommend reviewing while ignoring whitespace changes: I unindented a pretty large block of code, and the linter got another one.
> [RSDK-6491] Remove the DisableNMEA option from NMEA GPS

- .github/actionlint.yml
Apparently there's a `make lint` command (which runs actionlint) that I don't think gets exercised in CI. Or on most peoples machines for that matter.
https://viaminc.slack.com/archives/C03LCAHM2TT/p1706647821008169
> RSDK-6512: Add buildjet-pinned-location_de_arm to actionlint allow-list.

- components/movementsensor/gpsnmea/pmtkI2C.go
- components/movementsensor/gpsnmea/serial.go
- components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go
- components/movementsensor/gpsrtkserial/gpsrtkserial.go
- components/movementsensor/utils.go
- components/movementsensor/utils_test.go
I got surprised that functions like `IsZeroPosition` seemed to take two arguments, because I couldn't figure out what the second one would do. On closer inspection, although these things methods on a struct, they never use anything within the struct itself! To avoid this confusion, I've made them functions instead (so they don't operate on a struct to begin with).
As a low-priority stretch goal, I'd prefer to rename `GetLastPosition` and `SetLastPosition` to the more standard `Get` and `Set` so there's less duplication when typing `g.lastPosition.GetLastPosition()`, but that might not be worth the hassle right now.
> [RSDK-5462] miscellaneous cleanup: static functions should not be methods

- robot/impl/discovery_test.go
- robot/impl/local_robot.go
Ticket: https://viam.atlassian.net/browse/RSDK-6401
Talked with @maximpertsov in person on Friday who confirmed that while it is strange to query the modmanager as if it was a resource, this is the right / intended usage of the discovery API.
This PR will enable the APP FE to correctly populate the api&model dropdowns for adding a local-module-provided component / service (instead of forcing the user edit the raw JSON)
Also considered adding API routes for this: https://github.com/viamrobotics/api/pull/437 However, it seems like people would rather use the same API routes that already exists.
> RSDK-6401 - Add discovery query capabilities to the modmanager to discover local modular resource registrations

- components/powersensor/ina/ina.go
This PR adds a mutex to protect the i2c bus for the ina219 power sensor, preventing competing bus usage from corrupting values.
> RSDK-5905 power sensor bad voltage readings

- components/motor/gpio/motor_encoder.go
there was a lock issue that was causing the motors to spin aimlessly and not stop until the server shut down. seems to be fixed now but it was only occurring every once and a while so I'm going to test many more times to make sure it doesn't pop up again.
also, GoFor is now blocking when using the control loop
> RSDK-6308: Using control config on left and right motor of a base doesn't work with SDK

- web/frontend/src/api/motion.ts
- web/frontend/src/components/remote-control-cards.svelte
- web/frontend/src/components/slam/index.svelte
[Ticket](https://viam.atlassian.net/browse/RSDK-6542)
Changes:
1. Pass the full `commonApi.ResourceName` object to roboClient APIs rather than hard coding the namespace, subtype, & type such that they only work with rdk builtin components.
1. Change the signature of the Slam component to take the motion services so the slam card is compatible with non builtin motion services
1. Change the slam card to call `motion.stopPlan` on the motion client rather than `robotClient` as it deletes error prone boilerplate 
Manually tested both on a modular base & fake slam & fake base.
> RSDK-6542 - Fix SLAM RC Card incompatible with non builtin bases

- components/powersensor/ina/ina.go
Usually, a mutex is used to protect mutable data in a struct from race conditions. The one added in #3523 does not do that because all fields in the struct are immutable, so naively someone might think this mutex is unnecessary and remove it again. So, this comment explains why it's in here.
> add comment explaining the mutex in the power monitor

- services/motion/builtin/builtin.go
- services/motion/builtin/state/state.go
- services/motion/builtin/state/state_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-4813)
Manually using the following script:
```go
package main
import (
"context"
"fmt"
"log"
"time"
"go.viam.com/rdk/logging"
"go.viam.com/rdk/robot/client"
"go.viam.com/rdk/services/motion"
"go.viam.com/utils/rpc"
)
func main() {
logger := logging.NewLogger("client")
robot, err := client.New(
context.Background(),
"HOST",
logger,
client.WithDialOptions(rpc.WithEntityCredentials(
"KEY",
rpc.Credentials{
Type:    rpc.CredentialsTypeAPIKey,
Payload: "SECRET",
})),
)
if err != nil {
logger.Fatal(err)
}
defer robot.Close(context.Background())
ms, err := motion.FromRobot(robot, "builtin")
if err != nil {
logger.Error(err)
return
}
for {
ctx, cancelFn := context.WithTimeout(context.Background(), time.Second*5)
res, err := ms.ListPlanStatuses(ctx, …
```
> RSDK-4813 - Evict plan execution information older than TTL 

- web/frontend/src/components/slam/index.svelte
[Ticket](https://viam.atlassian.net/browse/RSDK-6534)
Change:
1. Change SLAM RC card's `refreshPaths()` function to call `listPlanStatuses` to list all plans & only call `getPlan` if the base is in the `listPlanStatuses` response. This prevents the RC card from causing the motion service to log errors due to receiving requests for plans for a component that has not yet had any plans created.
Tested using fake slam:
```
{
"services": [
{
"name": "slam",
"type": "slam",
"model": "fake"
}
],
{
"depends_on": [],
"name": "base",
"model": "fake",
"type": "base",
"frame": {
"orientation": {
"type": "ov_degrees",
"value": {
"y": 0,
"z": 1,
"th": 0,
"x": 0
}
},
"geometry": {
"y": 350,
"z": 100,
"translation": {
"x": 0,
"y": 0,
"z": 0
},
"x": 350
},
"parent": …
```
> RSDK-6534 - Minimize unnecessary GetPlan error logs

- etc/analyzetests/main.go
It has started to time out more frequently (I've seen it two times in the last two days)
https://github.com/viamrobotics/rdk/actions/runs/7760606306/job/21167217579?pr=3493
https://github.com/viamrobotics/rdk/actions/runs/7746263818/job/21124304190
Seems like a symptom of more tests and more development.
If someone wants to investigate this, I can create a ticket; voting to just bump the timeout for now.
> Bump analyzetests context timeout

- components/arm/universalrobots/ur.go
- components/arm/universalrobots/ur5e_test.go
- components/arm/universalrobots/ur_parser.go
- components/arm/universalrobots/ur_parser_test.go
This PR fixes a bug that causes this driver to quit in the middle of a move call if it is not configured to run fast enough.  This is because it had a static timeout of 10 seconds.  This work updates it to use a larger number if it is estimated that the motion will not complete in time.  
In the process of doing this I noticed a lot of places where this driver could be cleaned up and I think since its one of our premier arm drivers we should clean up the code to use best practices where possible and easy.  
It was tested on the Motion team's Arm QA plan, which was previously failing. Testing revealed that this does indeed fix the issue.
> RSDK-6514 Improve UR arm driver to use longer timeouts for longer motions

- services/navigation/builtin/builtin_test.go
- services/navigation/builtin/explore.go
[Ticket](https://viam.atlassian.net/browse/RSDK-6557)
1. Fixes `TestStartWaypoint/Reach_waypoints_successfully` by waiting until success goroutine has completed before running test assertions
2. Fixes panic in nav builtin test which exercises explore mode caused by explore mode not being constructed with a framesytsem service
> RSDK-6557 fix flaky test TestStartWaypoint

- .github/workflows/staticbuild.yml
Reverts the main part of viamrobotics/rdk#3493
Needed to unblock https://github.com/viamrobotics/rdk/actions/runs/7803011876
The release is using the github actions from main, however, the release is missing the required scripts :facepalm: 
We cannot cherry pick the commit in because the rc has already been published but no artifacts have been generated. (SO claims that we could force push to main to update the tag with my commit but I worry that would break more than we expect)
I will un-revert this after the release artifacts have been generated. 
Postmortem: It would be great if releases ran the same github actions workflows for release as what was ran for the RC. Not sure if this is possible. I should have realized this and it is something I will be more careful about going forward.
> Unblock release by removing manifest from main

- .github/workflows/staticbuild.yml
Reverts viamrobotics/rdk#3541
Release went out successfully.
Future patches will have the required scripts so it is okay to add back.
Checked with tenzing offline.
> Revert "Unblock release by removing manifest from main"

- go.mod
- go.sum
- resource/resource_graph_export.go
- services/motion/builtin/state/state.go
- utils/value.go
- utils/value_test.go
- web/server/entrypoint.go
- bump golang.org/x/exp to get the new exp/slices interface
- fix `slices.SortFunc` calls
- add local `cmp.Compare` until we move to go1.21
- a downstream repo with a transitive dependency on recent x/exp failed to build. go.mod min version selection uses the newer one, which broke our SortFunc calls. exp/slices changed the interface [here](https://cs.opensource.google/go/x/exp/+/302865e7556b4ae5de27248ce625d443ef4ad3ed) to be compatible with the go 1.21 standard library
- this change will cause a compile error on downstream repos that depend on the old exp/slices
> RSDK-6429 bump exp/slices

- components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go
- components/movementsensor/gpsrtkpmtk/gpsrtkpmtk_test.go
- components/movementsensor/gpsrtkserial/gpsrtkserial.go
- components/movementsensor/gpsrtkserial/gpsrtkserial_test.go
- components/movementsensor/rtkutils/ntrip.go
- components/movementsensor/rtkutils/ntrip_test.go
- components/movementsensor/rtkutils/vrs.go
There's probably going to be another one or two of these, but this PR is already big enough.
- The `rtkI2C.connect()` function used approximately nothing from the `rtkI2C` struct but a bunch of stuff from `rtkI2C.NtripInfo`.
- Similarly, the `rtkSerial.connect()` function did roughly the same thing.
- So, let's put that in the `NtripInfo` struct instead, and just call it from two places. Similarly, the two sets of tests can be de-duplicated into just one location.
This PR should be easy to review commit-by-commit: the last few commits aren't exactly on the same topic as the rest.
Tried on `piworld`, both with a bare nmea component, and both an I2C and a serial RTK component: we've still got the race conditions from the double-start, resulting in a bunch of checksum errors, but it's …
> [RSDK-5462] Remove duplicate functions when connecting to ntrip URLs

- components/base/sensorcontrolled/sensorcontrolled.go
- components/motor/gpio/motor_encoder.go
locking around the loop.Stop call caused a deadlock or something in auto tuning. removed that and spammed base calls on the RC card and everything seems to be working so I think the true fix was the stop we added at the beginning of set velocity
> RSDK-6282 fix PID autotuning in sensor controlled base

- web/frontend/package-lock.json
- web/frontend/package.json
- web/frontend/src/api/motion.ts
[Ticket](https://viam.atlassian.net/browse/RSDK-6430)
- Change the RC card to use motion.MoveOnMap rather than the deprecated (and soon to be deleted) motion.MoveOnMapNew
- Cut a new RC Card version `2.10.1`
> RSDK-6430 - Change RC card to use new MoveOnMap signature

- components/movementsensor/gpsnmea/data_reader.go
- components/movementsensor/gpsnmea/serial.go
I recommend reviewing this commit-by-commit!
I want feedback now, before this goes further. The general change is:
- Create a new `DataReader` interface that provides a channel full of NMEA sentences from a device
- Create a `SerialDataReader` struct that implements this interface for a serial device
- Use the `SerialDataReader` in the `SerialNMEAMovementSensor`
Future changes I anticipate, once this is in:
- Create an `I2cDataReader` that also implements `DataReader` for an I2C device.
- Make `NewSerialGPSNMEA` and `NewPmtkI2CGPSNMEA` both return the same struct, except that they pass in different implementations of `DataReader` to that struct. Get rid of all the duplicated code between `gpsnmea/pmtI2C.go` and `gpsnmea/serial.go`
Tried on `piworld`: gps-nmea (serial) and gps-nmea-rtk-i2c …
> [RSDK-6525] Start pulling the data-reading code out of the data-interpretation code for NMEA

- components/movementsensor/gpsnmea/pmtkI2C.go
- components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go
We are encountering two issues with I2C connection. 
1. Frequently the NMEA packets will start without "$"
2. Sometimes packets will contain half of an NMEA message. 
This PR includes these two fixes. 
Tested: in NY cors against gpsrtkPMTK.
> RSDK-6570: i2c parser bug

- components/board/genericlinux/board_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-6437
Proposing skipping test for now. Lots of failures in team-devops
> RSDK-6437 - Skip Generic linux TestNewBoard

- components/board/analog_smoother.go
- components/board/genericlinux/board.go
- components/board/genericlinux/board_test.go
Didn't close board in test and analog smoother wasn't shutting down properly.
```
go test -timeout 30s -race -count 1000 -run ^TestNewBoard$ go.viam.com/rdk/components/board/genericlinux
ok      go.viam.com/rdk/components/board/genericlinux   2.057s
```
> RSDK-6437 fix TestNewBoard flaky test

- components/movementsensor/adxl345/adxl345.go
- components/movementsensor/dualgps/dualgps.go
- components/movementsensor/fake/movementsensor.go
- components/movementsensor/imuvectornav/imu.go
- components/movementsensor/imuwit/imu.go
- components/movementsensor/merged/merged.go
- components/movementsensor/movementsensor.go
- components/movementsensor/mpu6050/mpu6050.go
- components/movementsensor/replay/replay.go
- components/movementsensor/replay/replay_test.go
- components/movementsensor/wheeledodometry/wheeledodometry.go
The RC card currently polls GetAccuracy, sees an error and refuses to show up since it is unimplemented in most drivers.
This PR adds a helper function that will not error, but populates the drivers with the values that will indicate to the RC card to hide the CompassHeading, HDOP, VDOP, and NMEAFIX from the card for drivers that cannot report them.
> RSDK-6599 Add non-erroring GetAccuracy implementations to FIX RC Card polling of API

- examples/customresources/demos/complexmodule/moduletest/module_test.go
- examples/customresources/demos/remoteserver/server_test.go
- module/module_interceptors_test.go
- testutils/robottestutils/robot_utils.go
- web/server/entrypoint_test.go
I was successfully in factoring out the "WaitForServing" function that could be shared for all uses without a problem.
I was unable to factor out the code to loop over trying ports. I (broadly speaking) think it's doable, but the challenge in the code right now is that all of the tests have their way of building up config objects/files. I didn't want to go down that refactoring rabbit hole. Particularly because there's probably a lot of options that would slow down the review.
> RSDK-6024: Have tests that use random numbers for ports ensure the server came up successfully before connecting.

- services/mlmodel/mlmodel.go
- services/vision/mlvision/classifier.go
- services/vision/mlvision/detector.go
- services/vision/mlvision/ml_model.go
- services/vision/mlvision/ml_model_test.go
- services/vision/mlvision/segmenter3d.go
This change adds a new optional config parameter to the mlmodel vision service, which allows you to rename your input and output tensor names on the fly so that you can have your mlmodel work with the vision service.
For example, if your mlmodel has an input tensor called "input_0", and output tensors "detection_classes", "detection_boxes", and "detection_scores", but the vision service expects that the input tensor is called "image", and other names for the outputs, too. you can easily fix this in the config by doing 
```
{
"type": "vision",
"model": "mlmodel",
"remap_output_names": {
"detection_classes": "category",
"detection_boxes": "location",
"detection_scores": "score"
},
"mlmodel_name": "onnx",
"remap_input_names": {
"input_tensor": "image"
}
},
"name": …
```
> RSDK-6618: Allow remapping of tensor names in vision mlmodel, transpose image channels

- components/camera/ffmpeg/ffmpeg.go
issue is ffmpeg builtin model has a go routine that will never exit (because of ManagedGo) if it panics.
another possible fix is to remove the panic, but seems like that was intentional so that we retry? @bazile-clyde 
and thus, the reconfiguration will hang on Close and mean that the new config never gets loaded in
> RSDK-6625 - Invalid ffmpeg config causes config loop

- robot/packages/cloud_package_manager.go
- robot/packages/cloud_package_manager_test.go
- set rwx permissions when we create a missing directory
- (incidental) remove receiver from `unpackFile` so it can be tested
Tar archives sometimes, but not always, have entries for directories (depending on the path you give to the `tar` command). When directory entries are missing, we create them. But directories need `+x` permission to write files into them. We were cloning file permissions onto the directory.
This was causing some modules to crash with 'permission denied' inside `unpackFile`.
> fix tar unpacking with missing directory entries

- web/frontend/package-lock.json
- web/frontend/package.json
- web/frontend/src/components/movement-sensor/index.svelte
`getAccuracy` calls were throwing errors when unimplemented, which borks the whole card.
- Move `getProperties` call into try/catch, just in case
- Add separate try/catch for calling `getAccuracy`
- See comment
Just code review should suffice, we'll test E2E when upgrading version in App. I tested running locally and it worked.
> APP-3923: catch errors with GetAccuracy in movement sensor card

- components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go
This PR fixes a bug exacerbated by https://github.com/viamrobotics/rdk/pull/3070: when a genericlinux I2C bus has an open handle, no other handles can be opened on it. Before #3070, the bug already existed on non-rpi4 boards, but now it occurs on the rpi4's as well. Perhaps having these locks in the I2C interface at all is a mistake, since other I2C handles can be opened on the same physical wires as long as you use a separate `buses.i2cBus` object to open them. but that's a discussion for another day.
Tried on the `piworld` board: on the main branch, the I2C RTK device never gets a fix greater than 1 (using NMEA messages only), and it does not shut down quickly. On this branch, its fix can get to 2 (using both NMEA and NTRIP messages), and hitting control-C shuts down the server …
> [RSDK-5462] don't deadlock on opening I2C handles in the RTK code

- data/registry.go
- services/datamanager/builtin/builtin.go
Forgive me if this sucks and I'm not following standards. Also, new to go -- so if the code needs cleanup, please please please let me know.
As per https://viam.atlassian.net/browse/DATA-2275 we want to log when capture frequency has not been set. To help things along, I've also added to the builtin service a map of state so that we can keep track of state changes so that we don't log the same message over and over again as this method is called many times by many different services.
Manually tested this via setting up a fake app on the website and running locally and then changing the value in the Data capture configuration - Frequency slot.
1. Start with blank
2. Start with 1 and then change to 0
3. Start with 0 and then change to 1
Example log: `2024-02-09T16:20:27.166Z        INFO …
> Data 2275/log capture frequency

- components/arm/arm.go
- components/arm/arm_test.go
- components/arm/client.go
- components/arm/eva/eva.go
- components/arm/fake/fake.go
- components/arm/universalrobots/ur.go
- components/arm/wrapper/wrapper.go
- components/arm/xarm/xarm.go
- components/base/kinematicbase/differentialDrive.go
- components/base/kinematicbase/fake_kinematics.go
- components/base/kinematicbase/ptgKinematics.go
- components/gantry/client.go
- components/gantry/fake/gantry.go
- components/gantry/multiaxis/multiaxis.go
- components/gantry/singleaxis/singleaxis.go
- components/gantry/singleaxis/singleaxis_test.go
- referenceframe/primitives.go
- services/motion/builtin/builtin_test.go
- testutils/inject/arm.go
This PR changes the signature of our InputEnabled interface to be variadic. This allows for components executing inputs to be aware of more than one intended configuration at a time, allowing for blending between trajectories, and correction if going off course.
Use of a variadic function allows essentially all calling code to persist as-is, unlike for example changing the signature to `[][]Input`.
As `InputEnabled` is an interface used purely in Go within RDK, there are no grpc API changes associated with this update.
> Make GoToInputs variadic

- cli/app.go
- cli/auth.go
- cli/auth_test.go
- cli/data.go
- cli/dataset.go
- cli/module_registry.go
- cli/train.go
[RSDK-6094](https://viam.atlassian.net/browse/RSDK-6094)
Uses `createUsageText` for more CLI commands that previously had the format `viam module upload <version> <platform> [other options] <packaged-module.tar.gz>`, so the format now looks like `viam module upload --version=<version> --platform=<platform> [other options] <packaged-module.tag.gz>`. Cleans up existing `UsageText`s.
[RSDK-6094]: https://viam.atlassian.net/browse/RSDK-6094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-6094 Further improve CLI usage strings

- components/movementsensor/rtkutils/ntrip.go
No behavioral changes are intended. This is a follow-up to https://github.com/viamrobotics/rdk/pull/3548: I removed the duplicated code, but didn't notice that the control flow within that code was so messy. 
Before this PR, when we have successfully connected, `err` would be `nil`, so we would break out of the for loop. We could get out of the for loop either by successfully connecting or by failing to connect too many times, so we'd then check if the error is not `nil` to find out which situation we're in, and then store the client and return. After this PR, when we successfully connect, we just store the client and return, and if we ever get out of the for loop, it's because we were unable to connect after the maximum number of attempts.
My next instinct was to make `c` and `err` local …
> [RSDK-5462] More gps cleanup

- robot/impl/local_robot.go
- utils/errors.go
not the actual fix but should make future failures easier to distinguish
> RSDK-6476 - Update warning logs around timeouts around weak dependencies

- components/base/kinematicbase/differentialDrive.go
- components/base/kinematicbase/differentialDrive_test.go
- motionplan/collision.go
- motionplan/collision_test.go
- motionplan/constraint.go
- motionplan/constraint_test.go
- motionplan/motionPlanner_test.go
- motionplan/planManager.go
- motionplan/plannerOptions.go
- motionplan/tpSpaceRRT_test.go
- pointcloud/basic_octree.go
- pointcloud/basic_octree_utils_test.go
- services/motion/builtin/builtin_test.go
- services/motion/explore/explore_test.go
- services/motion/explore/explore_utils_test.go
- spatialmath/box.go
- spatialmath/capsule.go
- spatialmath/capsule_test.go
- spatialmath/geometry.go
- spatialmath/geometry_test.go
- spatialmath/point.go
- spatialmath/sphere.go
[Ticket](https://viam.atlassian.net/browse/RSDK-6563)
- Delete the `spatialmath.CollisionBuffer` global
- Change the following `Geometry` interface methods to take a new `collisionBufferMM float64` parameter:
- `CollidesWith(Geometry, float64) (bool, error)`
- `DistanceFrom(Geometry, float64) (float64, error)`
- `EncompassedBy(Geometry, float64) (bool, error)`
- Change all code that ends up calling those `Geometry` interface methods to provide a `collisionBufferMM float64` parameter
- Change the `motionplan.Replan` function to take an extra parameter of `"collision_buffer_mm"` and return errors if it is not a positive float64 & use it over the default if it is a positive float64
- Add tests to `motionplan.Replan`,  `motion.MoveOnMap` and `motion.MoveOnGlobe` that prove they validate & use …
> RSDK-6563 - Expose inflation factor

- services/motion/builtin/builtin_test.go
I'm not sure how this was allowed but somehow the CI did not catch this issue before it got merged in main. This is a hotfix to address this issue
> Remove references to now defunct MoveOnMapNew method

- robot/impl/robot_reconfigure_test.go
test should really only care if the deadline is passed correctly into the constructor, so updated the test to be more centered around that
> RSDK-6476 - Update resource construct timeout test

- .artifact/tree.json
- services/vision/mlvision/detector.go
- services/vision/mlvision/ml_model.go
- services/vision/mlvision/ml_model_test.go
These edits allow the vision service to create an object detector without the requirement of having a categories tensor. 
This might be the case when a detector is only detecting one category, or the author decides to stuff the category information in another dimension. 
This also adds an optional parameter allowing the user to specify the bounding box order for their model
> RSDK-6672: Object detection without category tensor

- Makefile
- cli/app.go
- cli/client.go
- cli/config.go
- cli/print.go
- config/reader.go
- doc/dependency_decisions.yml
- go.mod
- go.sum
RSDK-4975
On installs older than one week, warns users when their CLI is out of date against the latest stable release.
> [RSDK-4975] CLI update warning

- robot/impl/local_robot.go
The warning is more for developers, not users. It should be removed. We already have a ticket to remove the deprecated robot constructor in the camera transform and vision service (RSDK-6566, RSDK-2808)
> rsdk-6560 its not really a warning, everything will still work

- Makefile
- cli/client.go
This PR reverts a change made to the Makefile which sets the GIT_TAG to (dev) when there is no release version associated with the build. This change mistakenly propagated to the App view.
> revert GIT_TAG to latest hash

- operation/opid.go
- operation/opid_test.go
did some testing - an parent operation cancelled this way will properly propagate to the child operations, even if it's not explicitly tracked by the operation manager.
> RSDK-6678 - Do not overwrite existing operation

- robot/impl/local_robot_test.go
Add a helper to encapsulate basic setup and teardown that we do throughout the local robot test suite. Noticed this while working on https://github.com/viamrobotics/rdk/pull/3599
> Add local robot test helper

- rimage/image_file.go
- services/mlmodel/tflitecpu/tflite_cpu_test.go
- services/vision/mlvision/classifier.go
- services/vision/mlvision/detector.go
- services/vision/mlvision/ml_model.go
- services/vision/mlvision/ml_model_test.go
This adds three optional attributes for pre-processing the input image:
input_image_bgr (optional): a bool value: Set this to be true if the ML model expect the input image to have BGR pixels, rather than RGB pixels.
input_image_mean_value (optional): a []float list: If the ML model expects the input image to be normalized, what is the mean value of the RGB (or BGR) values. If left blank, a default will be applied.  
input_image_std_dev (optional): a []float list: If the ML model expects the input image to be normalized, what is the standard deviation of the RGB (or BGR) values. If left blank, a default will be applied.
> RSDK-6751: Add preprocessing options to input image for the mlmodel vision service

- config/config.go
- config/config_test.go
- robot/impl/local_robot_test.go
- robot/packages/cloud_package_manager.go
- robot/packages/cloud_package_manager_test.go
Since the `.viam` directory is already private, there isn't a need to add additional private directories underneath it. This makes it so that `.data` is removed in favor of data. Since the packages are downloaded on each viam-server restart, I felt that it wasn't necessary to do a rename/move of the existing folder.
Symlinks are regenerated and don't need to be rewritten.
Tested using the PR app image:
stable:
```
datadir@datadir:~ $ sudo ls -al /root/.viam/packages
total 16
drwx------ 3 root root 4096 Feb 26 16:37 .
drwxr-xr-x 5 root root 4096 Feb 26 16:37 ..
drwx------ 4 root root 4096 Feb 26 16:37 .data
lrwxrwxrwx 1 root root   71 Feb 26 16:37 pet-feeder -> /root/.viam/packages/.data/ml_model/viam-pet-feeder-2023-11-27T13-28-53
```
pr-3608 after an initial install of stable:
``` …
```
> Rename .data -> data directory

- cli/module_registry.go
Did manual testing with a few situations to make sure we have the correct user experience here. I never ran `update` as a step in the flow.
```
go run cli/viam/main.go --base-url="https://app.viam.dev" module create --public-namespace test --name test456
michaellee@RyMongo-531 rdk % go run cli/viam/main.go --base-url="https://app.viam.dev" module create --public-namespace test-leave --name test456
Info: Using "https://app.viam.dev" as base URL value
Successfully created 'test-leave:test456'
You can view it here: https://app.viam.dev/module/test-leave/test456
Configuration for the module has been written to meta.json
michaellee@RyMongo-531 rdk % go run cli/viam/main.go --base-url="https://app.viam.dev" module upload --version 1.2.3 --platform linux/arm64 meta.json
Info: Using …
```
> APP-3700: Run Update on every Upload in Module CLI

- grpc/conn.go
- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/module.go
- robot/client/client.go
fixes by creating a unique sock address for each module lifetime, and adding a reconfigurable client connection to swap for existing connection/clients
> RSDK-6344 - Fix socket clashes on reconfigured modules

- config/config.go
- config/reader.go
- config/reader_test.go
When RDK pulls a new cloud config file, it still tries to read TLS certificate data from the cached config if it exists. However, RDK validates the entire config file at this step and fails hard if there is any validation errors (aborting startup). 
Since RDK only needs TLS data at this point, it should not validate the cached config for anything beyond the relevant TLS fields.
> RSDK-6344 Read partial config when getting cached TLS information

- gostream/codec/x264/encoder.go
- web/server/entrypoint_linux.go
Currently the encoder factory in the linux entrypoint will use the `v4l2m2m` hardware encoder interface if available. Although it has the benefit of offloading cpu utilization, there have been a few regressions:
- Image quality is not as good as `x264` given the same bitrate.
- Edge case issues with unusual frame-sizes and aspect ratios.
- Flaky behavior in hardware encoder bringup.
This PR simply reverts back to using x264 as the default option.
- Tested on RPI4 board.
- Verified that diff resolves issues with soleng PI4 module setup.
- Verified that diff resolves issues with large frame sizes from wanview RTSP feeds.
> RSDK-6761 Remove hardware encoder default

- components/movementsensor/imuwit/imu.go
This PR includes CompassDegreeError accuracy value for imu. If pitch is less than 45 degree and roll is between -1 and 1 we will display CompassDegreeError of 0.5 which is defined in the datasheet.
> RSDK-6174: CompassDegreeError for imu

- .github/workflows/appimage.yml
- .github/workflows/test.yml
- Undo datacenter pins in CI
This was a workaround for slow docker pulls, but introduced a new failure where we waited forever for a runner. The slow pull failure condition was preferable because:
| failure condition | hang time |
---|---
slow docker pull | timeout-minutes (30 minutes)
waiting for runner in pinned datacenter | forever
we prefer the failure condition that manifests sooner, because it allows the next commit on `main` branch to start
> revert `location_de_arm` pin

- cli/client.go
- services/shell/builtin/builtin.go
This happens in particular if the SHELL profile does not contain any TERM env var. It's harmless to add xterm with 256 color support nowadays (i.e. for decades now)
- driveby fix to not echo control characters
> services/shell: Add TERM=xterm-256color when not present

- examples/customresources/demos/simplemodule/module.go
- logging/proto_conversions.go
- logging/proto_conversions_test.go
- module/log.go
- module/module.go
- robot/client/client.go
- robot/impl/resource_manager_modular_test.go
- robot/server/server.go
RSDK-6280
Uses the module's log level for the logger used in `parent -> module` connection establishment. Tries to actually send module log fields across the wire, unmarshal them to `zap.Field`s in the RDK, and output them with the logger. Adds new conversion functions `FieldToProto` and `FieldKeyAndValueFromProto` and tests for them.
> RSDK-6280 Better logic for module logging fields

- module/modmanager/manager_test.go
* makes error string matches more lax because it can be both "EOF" or "client conn closing", depending on which comes first
* changes the restart interval at the start of the test, so we don't run into a race situation later on
> RSDK-6764,6765 - Module reloading test flakes

- services/mlmodel/tflitecpu/tflite_cpu.go
Adds a validate function to the tflite_cpu config to enforce the required model_path attribute
> RSDK-4465: Add validate function to tflite cpu

- data/collector.go
- data/collector_test.go
As per https://viam.atlassian.net/browse/RSDK-6348?atlOrigin=eyJpIjoiZWI0Y2JjNDYzZmZjNDliMGI0NzE1M2VkYTMxOThiNjkiLCJwIjoiaiJ9 we have an issue where, if something goes wrong, there's the possibility (and reality) that we'll log the same error message millions of times until it's resolved. This fix adds a map of
String: ErrorMessage -> Timestamp: LastLogged
and ensures that identical error messages only show up a maximum of once every 2 seconds.
Open to changing the frequency if anyone has any thoughts on the matter.
EDIT
Here is a screenshot of testing where I return an error from the webcam component:
Note the errors come in every 3 seconds
> RSDK-6348/error frequency

- components/camera/fake/camera.go
- components/camera/fake/camera_test.go
- robot/impl/resource_manager_test.go
- services/motion/explore/explore_utils_test.go
I confirmed that a resolution of 40000 pixels for width and height causes viam-server to crash on a mac, and no image to be shown on the RC card.
With the new limits in the Validate field we at least guard against bringing up the server and getting it into a state where it cannot shut down cleanly.
Camera can show images with the config:
```
{
"width": 10000,
"height": 10000
}
```
Complains when we go above 10000 and does not show or build the resource
And viam server stops cleanly after a restart or SIGINT.
Without this Validate check, allowing a fake camera to construct itself with just a fake camera configured at best causes the server to hang on shutdown, or crashes viam-server according to the QA testers.
> [RSDK-6178] Don't allow extremely large fake camera resolutions.

- vision/classification/classifier.go
Before there was an error if you requested top N classifications but actually number of classifications were less than N. Now it checks before returning
> RSDK-6824: change from topN to up-to topN

- data/collector.go
- data/collector_test.go
https://viam.atlassian.net/browse/RSDK-6837
This test was broken because of a race condition introduced by the test.
This was tested by running it with the -race flag and getting the OK.
Also, c.closed is only used in these two spots so it feels safe to move.
EDIT: Tested by running and trying to use the app online without any unexpected behavior
>  RSDK-6837/make-closing-threadsafe #3661 

- components/motor/gpio/motor_encoder.go
Actually not a PI5 issue, it's an uncovered bug from the addition of controls helper functions on motors that have incremental encoders. Because the tuning process is running in the background, `m.loop` is nil until the motor reconfigures with non-zero PID values. When the motor is tuning and the loop tries to set the power to (essentially) 0, `setPower` forces the power to be 0.1 because loop is still nil, which causes the motor to keep moving.
This change to check `len(m.controlLoopConfig.Blocks)` instead of `m.loop` shouldn't cause any issues because in order for there to be a controlLoopConfig by the time it gets to a setPower call (that originates from a GoFor call), there should a loop.
This check should potentially be removed anyways, because I'm not 100% sure why we want to force …
> RSDK-6823: Motor doesn't stop after controls auto tuning on PI5

- components/motor/gpio/motor_encoder.go
- control/control_loop.go
- control/setup_control.go
To make sure the loopCancelCtx is actually cancelled at stop, `cancel()` is now called in `loop.Stop`.
Additional changes in this PR include removing unnecessary stopping and restarting of the control loop when a new `GoFor` call is made, and removing an always nil returned error from `MonitorTuning`
> RSDK-5755: Utilize control loop context for closing control loops in motor encoder

- config/reader.go
- config/reader_test.go
- config/watcher.go
- testutils/injectpb/robot_service_client.go
Stub out network calls and test the entire config reader flow
> RSDK-1960, RSDK-539 Test entire config flow

- config/reader.go
- config/watcher.go
tested locally, also we weren't timing out our watcher reads at all before...
instead of adding another arg into the method, used `shouldReadFromCache` to determine whether or not we're in an initial read situation. @maximpertsov 's work around testing and creating a remoteReader struct should make that easier (possibly through a struct var)
also removes a ticker that we don't use
> RSDK-6877, RSDK-6878 - Aggressive timeouts on first config reads

- config/proto_conversions.go
RSDK-5300
Changes the `Debugw` log that contains errors encountering when converting to proto to an `Errorw`.
> RSDK-5300 Error log proto conversion issues

- robot/impl/local_robot.go
- robot/packages/deferred_package_manager.go
- robot/packages/deferred_package_manager_test.go
Ticket : https://viam.atlassian.net/browse/RSDK-6904
// DeferredPackageManager wraps a CloudPackageManager and a goroutine that is establishing a connection to app. It starts up
// instantly and behaves as a noop package manager until a connection to app has been established.
//
// Raison d'être: AquireConnection will waste 5 seconds timing out on robots that have no internet connection but have downloaded
// all of their cloud_packages
//
// This puts an optimization on top of that behavior: On the first start of the package manager, if all of the expected packages are
// present on the system, put the connection establishment in a goroutine and use a noop_package_manager for the first Sync.
// If there are missing packages, this will still block to prevent a half-started robot. …
> RSDK-6904 - Deferred Package Manager

- components/base/kinematicbase/ptgKinematics_test.go
- motionplan/constraint.go
- motionplan/constraint_test.go
- motionplan/motionPlanner.go
- motionplan/motionPlanner_test.go
- motionplan/planManager.go
- motionplan/plan_test.go
- motionplan/plannerOptions.go
- motionplan/tpSpaceRRT.go
- motionplan/tpSpaceRRT_test.go
- services/motion/builtin/builtin_test.go
- services/motion/builtin/move_request.go
This PR updates TP-space planning in `motionplan` to remove the requirement that obstacles, goals, etc all be transformed to be relative to the base.
Instead, we now pass a `StartPose` as part of the `PlanRequest` which allows us to correctly position the seed node of the TPspace RRT tree.
This also includes a minor refactor of `planManager` which adds `planRelativeWaypoint` to consolidate planner setup there.
> RSDK-6843 ptg motion plans should not be required to start at the origin

- logging/net_appender.go
- logging/net_appender_test.go
RSDK-6908
Stops unconditionally removing batches from the net logger queue for every `write`; only removes batches from queue in the case of `write` success. Keeps the mutex unlocked during actual `write` I/O. Re-adds test removed in https://github.com/viamrobotics/rdk/pull/3678 to ensure batches are not dropped.
> RSDK-6908 Do not drop net logger batches

- components/motor/gpio/basic.go
- components/motor/gpio/basic_test.go
I am pretty sure this was not written expecting that PowerPct would always return positive. Just an oversight on taking the absolute value of the power percentage.
Still need to fix tests, but it should be returning negative percentages even when on now.
Please
> Allow IsPowered to return negative power percentages.

- components/movementsensor/gpsutils/nmeaParser.go
VTG message provides true track which is the heading relative to the Earth's geographical poles. This PR checks if this information is provided in the VTG message and updates compass heading based on true track.
> RSDK-6946: compass heading from vtg messge

- logging/net_appender.go
RSDK-7000
> Eliot previously wrote a `TODO(erh): sample?` line in the pieces of net appender code where we were overflowing. He was referring to selectively kicking logs out of the queue to get a variety of log shapes, so that “if something is spamming ‘Foo’ over and over you don’t lose all other information”. I’ll change those TODO lines to reference this ticket.
> RSDK-7000 Reference selectively overflowing in net appender

- components/motor/gpio/basic.go
So we don't forever clamp to the minimum power if the power is zero
> Add zero check to power being sent into SetPower 

- robot/packages/cloud_package_manager.go
- robot/packages/cloud_package_manager_test.go
- robot/packages/testutils/fake_package_server.go
https://viam.atlassian.net/browse/RSDK-6975
Test:
systemd viam-server fails to download `oak` module version 0.1.4
static build off this branch is able to
> [RSDK-6975] Leading zeroes in hash seem to break module download

- components/movementsensor/gpsrtkpmtk/gpsrtkpmtk.go
Removed `mu` and `ntripconfigMu`. Renamed `ntripMu` to `mu`. 
Tested in our GPS rig.
> RSDK-7019: remove unnecessary mutex in GPS RTK I2C

- components/movementsensor/gpsrtkserial/gpsrtkserial.go
- components/movementsensor/gpsutils/ntrip.go
- components/movementsensor/gpsutils/vrs.go
`rtk2go.com `source table often comes with incomplete information. `ParseSoutcetable `calls `parseStream` at every line of the source table and we encounter error. This PR avoids that by only calling `parseStream` when we see the mount point. This reduces function calls when parsing the source table and avoids running into error on mount points that we don't care about.
> RSDK-6984: optimizing sourcetable parser

- components/camera/transformpipeline/transform.go
Ticket: https://viam.atlassian.net/browse/RSDK-7009
The emptyConfig in the transform camera code is causing problems in app. See https://viam.atlassian.net/browse/APP-4204
We need to give each emptyConfig a different name so that the json-schema has different $id values. 
Old generated jsonschema
```json
{
"$schema": "https://json-schema.org/draft/2020-12/schema",
"$id": "https://go.viam.com/rdk/components/camera/transformpipeline/empty-config",
"$ref": "#/$defs/emptyConfig",
"$defs": {
"emptyConfig": {
"properties": {},
"additionalProperties": false,
"type": "object"
}
},
"type": "object",
"title": "depth_to_pretty",
"description": "Turns a depth image source into a colorful image, with blue indicating distant points and red indicating nearby points."
},
``` 							
New generated …
> RSDK-7009 - Transform camera schema should not be emptyConfig

- examples/customresources/demos/complexmodule/moduletest/module_test.go
- examples/customresources/demos/simplemodule/module.go
- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/module_interceptors_test.go
- module/testmodule2/.gitignore
- module/testmodule2/main.go
- module/testmodule2/run.sh
- robot/impl/discovery_test.go
- robot/impl/local_robot_test.go
- robot/impl/resource_manager_modular_test.go
- testutils/file_utils.go
- web/server/entrypoint_test.go
Follow-up to https://github.com/viamrobotics/rdk/pull/3641 - we [stopped locking on individual module adds](https://github.com/viamrobotics/rdk/pull/3641/files#diff-a4308b77f384da81096eda21bf023471e80818dda86e74f9335f99a6a57d07c9L148-L149) to enable parallel adding, but there's no reason we can't lock while adding a batch.
Also adds:
* A new test module that isn't simple or complex module, to support testing scenarios that involve two modules
* Improves the `BuildTempModule` testing helper
> RSDK-7008: lock module manager while adding in parallel

- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/version_reconfigure_test.go
- robot/impl/local_robot.go
- robot/impl/local_robot_test.go
- robot/impl/resource_manager.go
https://viam.atlassian.net/browse/RSDK-7042
Adds (or bumps to `Info`) logs for:
- Adding a module
- Reconfiguring a module
- Removing a module
- Successful add of a batch of modules
- Adding (configuring) a resource
- Reconfiguring a resource
- Removing a resource
- Adding (configuring) a modular resource
- Reconfiguring a modular resource
- Removing a modular resource
- Connecting to a remote
- Successful connection a remote
- Successful reconfiguration of a robot
Uses upper-cased log messages and prefers structured logging where possible in the module manager and in a few places in the resource manager.
cc @viamrobotics/netcode 
Here is an example of what logs look like now for a complex set of reconfigurations/state changes (a run of `TestOrphanedResources`). I'll update this file as …
> RSDK-7042 Add better info logs wrt (re)configuration

- robot/impl/resource_manager.go
- robot/impl/robot_reconfigure_test.go
RSDK-7005
Adds a 30 second timeout for `closeResource` in the resource manager. Adds a test to ensure timeout is respected.
If builtin resources wrote a hanging `Close` method, Golang modular resources wrote a hanging `Close` method, Python modular resources wrote a hanging `close` method, or C++ modular resources wrote a hanging destructor, the RDK would hang in shutdown. `localRobot.Close()` closes the resource manager, which calls `closeResource` for every graph node. `closeResource` had no, existing associated timeout.
cc @viamrobotics/netcode .
> RSDK-7005 Add timeout for closing resources

- data/collector.go
- logging/net_appender.go
- logging/net_appender_test.go
- services/datamanager/datasync/sync.go
almost always guaranteed to run into a panic when shutting down a viam-server if a data collector is present in config
Culprit is calling Sync concurrently in data manager shutdown. while we could remove all references to logger.Sync to our codebase, that doesn't stop future regressions. We could also try and think of a way to make this threadsafe, but unless we make logger more complicated and slower, I don't think we would be able to avoid double logs. Therefore, I think the best solution is to make sync() single threaded and remove the possibility of others calling into net appender's sync
Also did fix the actual panic so that the logger can continue working and not affect normal usage
cc @agreenb - the logger will flush its own logs eventually, so removing the Sync calls in …
> RSDK-7064 - Logger panics if sync called concurrently

- .github/workflows/cli.yml
- bump setup-go in cli job from 1.20 -> 1.21
- cli job is failing on main
- guessing this isn't exercised in PRs so we didn't discover until merging
- the `go build ./...` command technically exercised this part of the codebase, but in an environment that had go 1.21
https://github.com/viamrobotics/rdk/actions/runs/8423487311/job/23065230004
> bump golang version in cli job

- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/testmodule/main.go
- robot/impl/local_robot_test.go
RSDK-7035
Stops attempting to add the old module process' resources back to the new module process as part of module reconfiguration. Uses `ResolveImplicitDependenciesInConfig` to put all resources handled by a reconfigured module in `conf.Added.Components/Services` instead of `conf.Modified.Components/Services`. Adds test that modular resources do not `Reconfigure` after their module reconfigures or crashes w/ successful restart. Adds info-logs to indicate that a reconfigured or removed module's resources will be re-added or removed, respectively.
We had an issue where reconfiguring a module would stop the old process, start the new process, add the old process' resources to the new process, and _then_ **reconfigure the new resources** in the new process to have correct implicit …
> RSDK-7035 Do not re-add old resources as part of module `Reconfigure`

- components/camera/videosource/logging/logger.go
[RSDK-7071](https://viam.atlassian.net/browse/RSDK-7071)
[RSDK-7071]: https://viam.atlassian.net/browse/RSDK-7071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [RSDK-7071] Remove lscpu call in camera logger that causes orange pi board to hang

- robot/impl/local_robot_test.go
RSDK-7075
The merge of https://github.com/viamrobotics/rdk/pull/3726 and https://github.com/viamrobotics/rdk/pull/3731 happened too close to each other. `TestModularResourceReconfigurationCount`, added in #3726, was waiting for the exact log message: `Module successfully restarted`, but #3731 changed the timing and contents of that message slightly. The CI required to merge #3731 ran without this test, so we didn't see the failure until merge (apparently git merge conflicts didn't catch it).
> RSDK-7075 Fix modular resource reconfiguration test

- config/reader.go
- robot/session_manager.go
update so that we only shorten timeout to 1s if cached config exists. Prevents slow I/O from stopping server startup
also log the last modified time for cached config if we use it to start up
```
2024-03-25T18:50:39.112Z        WARN    robot_server    config/reader.go:627    unable to get cloud config; using cached version        {"config last updated":"2024-03-25T14:50:23-04:00","error":"context deadline exceeded"}
```
no new tests because there isn't a way to ensure that timeout changed (hard to test that timeout is between 1 and 5s, for example) without running into possible race conditions
tested locally, seems correct
> RSDK-7011, RSDK-7030 - Update initial config flow

- robot/session_manager_test.go
data race happening because we access a lock at the same time as we're deep equaling the session struct.
can reliably repro locally if I update the loop to run every 1ms and >30k times
simple fix is to remove the access (e.g. stop the background loop that session manager runs) by closing session manager before checking the equality
> RSDK-6951 - Test Datarace: go.viam.com/rdk/robot.TestSessionManager

- components/base/client_test.go
- components/base/kinematicbase/differentialDrive_test.go
- pointcloud/pointcloud_utils_test.go
- referenceframe/frame_system_test.go
- referenceframe/frame_test.go
- referenceframe/transformable_test.go
- referenceframe/urdf/geometry_test.go
- referenceframe/worldstate.go
- referenceframe/worldstate_test.go
- robot/framesystem/framesystem.go
- services/motion/client_test.go
- services/motion/server_test.go
- services/navigation/builtin/builtin_test.go
- spatialmath/box.go
- spatialmath/box_test.go
- spatialmath/capsule.go
- spatialmath/geometry.go
- spatialmath/geometry_test.go
- spatialmath/point.go
- spatialmath/point_test.go
- spatialmath/sphere.go
- spatialmath/sphere_test.go
- vision/object_test.go
- vision/segmentation/radius_clustering_test.go
- vision/segmentation/segments_test.go
This PR cuts the `AlmostEqual` and `String` methods from the `Geometry` interface to make it easier for implementers of this interface to add a new `Geometry`
> RSDK-367 prune extraneous methods from `Geometry` interface

- module/modmanager/manager.go
- module/modmanager/manager_test.go
the current behavior will restart modules if it crashes (like if a sigterm gets sent to it) even if server is in shutdown - this prevents process from restarting and also does not log that RDK will attempt to restart it
logs after changes (if in shutdown):
```
2024-03-25T21:20:34.386Z        ERROR   robot_server    modmanager/manager.go:841       Module has unexpectedly exited.{"module":"AcmeModule","exit_code":0}
2024-03-25T21:20:34.386Z        INFO    robot_server    modmanager/manager.go:927       Will not attempt to restart crashed module  {"module":"AcmeModule","reason":"context canceled"}
```
if not in shutdown:
```
2024-03-25T21:18:15.111Z        ERROR   robot_server    modmanager/manager.go:841       Module has unexpectedly exited. {"module":"AcmeModule","exit_code":0} …
```
> RSDK-7049 - Do not restart module if in shutdown

- cli/data.go
Previously it was impossible to export large files. Now, we use the URI from the metadata to download if we received an error that it was too large. 
Can try the following command in `Data/ML Dev` in staging
`viam data export --org-ids=f87b919c-63b2-4d32-b676-0b55393938d7 --data-type=binary --mime-types=application/octet-stream --destination=large_file_export` which should result in an error
`go run cli/viam/main.go data export --org-ids=f87b919c-63b2-4d32-b676-0b55393938d7 --data-type=binary --mime-types=application/octet-stream --destination=large_file_export` off of this branch, which should successfully download everything
> DATA-2433 - Add HTTP request to download binary

- web/frontend/package-lock.json
- web/frontend/package.json
- web/frontend/src/components/slam/index.svelte
- web/frontend/src/types/overrides.ts
Ticket: https://viam.atlassian.net/browse/RSDK-7061
Done:
* Set the `mappingMode` based on the mapping mode returned from `slamClient.getProperties()`
Tested:
* With latest App + cartographer & fake slam
* With this PR: https://github.com/viamrobotics/app/pull/4112
* With modules as they're going to be implemented by the end of this project
Related PR:
* https://github.com/viamrobotics/app/pull/4112
* Removes `overrides.mappingDetails.mode`; will be merged once RDK is released
> RSDK-7061 - Pull the mapping mode out of Properties

- robot/packages/cloud_package_manager.go
- fsync files after unpacking from tar
- we've seen files get truncated when someone yanks a power cord after provisioning a device
- look into fsyncing symlinks + directories
> APP-4406 add fsync in unpackFile

- robot/client/client.go
[DOCS-2044](https://viam.atlassian.net/browse/DOCS-2044
)
The docs team will use this PR as an example on how to move the existing Go code examples in docs.viam to the SDK. The goal is that the repo would be the source of truth for SDK API documentation.  
[DOCS-2044]: https://viam.atlassian.net/browse/DOCS-2044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-2044] Add code example to robot.TransformPose

- cli/app.go
- cli/auth_test.go
- cli/client.go
- cli/client_test.go
- cli/module_build_test.go
- testutils/inject/app_service_client.go
RSDK-7022
Adds `--count` flag to `viam machine logs` and `viam machine part logs` to fetch more than 100 logs (defaults to 100, maxes out at 10000). Adds tests for `--count`.
> RSDK-7022 Add count option to CLI log commands

- vision/objectdetection/color_detector.go
- vision/objectdetection/color_detector_test.go
The color detector can't detect black, white, or grayscale colors, so explicitly make that clear by making colors with saturation of 0 an error.
> rsdk-7157: change text on errors for clarity, and add new error

- services/motion/builtin/builtin_test.go
- services/motion/builtin/move_request.go
- services/motion/builtin/state/state.go
- services/motion/errors.go
- services/navigation/builtin/builtin.go
- services/navigation/builtin/builtin_test.go
This PR fixes the bug where motion returns an error when we are close to the next goal waypoint and the builtin nav service enters an infinite loop of trying to navigate to it anyway.
> RSDK-7077 fix bug in builtin nav service when moving to a sufficiently close waypoint

- protoutils/sensor.go
- protoutils/sensor_test.go
See comment in the code for the explanation, and see the ticket for how we tracked that down.
> [APP-3853] Remove non-ASCII characters from sensor-reading errors

- components/base/wheeled/wheeled_base.go
Default geometries apparently never worked on hardware bases.
> RSDK-7213 Default geometry fix for wheeled bases

- components/camera/camera.go
- components/camera/camera_test.go
- components/camera/client.go
- components/camera/replaypcd/replaypcd.go
- components/camera/replaypcd/replaypcd_test.go
- components/camera/rtppassthrough/rtppassthrough.go
- components/camera/rtppassthrough/stream_subscription.go
- components/camera/rtppassthrough/stream_subscription_test.go
- components/camera/videosource/webcam.go
- module/module.go
- robot/web/web_c.go
- testutils/inject/camera.go
[Ticket](https://viam.atlassian.net/browse/RSDK-7223)
Fixes build issue introduced in: https://github.com/viamrobotics/rdk/pull/3723
Moves RTP Passthrough features into submodule of camera so that building the viam CLI doesn't fail due to the camera package pulling in unneeded C deps as a side effect of module depending on the rtp passthrough interface.
I also renamed some types to shorten names & make it clearer that these features are about RTP passthrough. 
Cameras supporting RTP passthrough will need to implement the `camera/rtppassthrough.Source` interface and no longer need to implement the `VideoCodecStreamSource` method. 
Tested for compatibility with old modules & passthrough modules with:
```json
{
"modules": [
{
"name": "rtsp-nick",
"executable_path": …
```
> [RSDK-7223] move-camera-rtp-passthrough-to-own-package

- etc/setup.sh
- in etc/setup.sh, bump our go from 1.20 -> 1.21
- force-link go@1.21 at the end of the setup process (canon's unpinned `go` is giving 1.22)
- emit loud warning when running on focal (old ubuntu). another approach here would be to proceed, but exclude tensorflowlite (which is broken on focal)
- remove license finder in Brewfile + pi_OS? (which also means skipping ruby install). We use this in CI, but may not need it in most local dev setups
(`go version` at the end is the key line -- previously would have been 1.22.x)
```bash
$ docker run -it --rm -v $PWD:/rdk ubuntu:latest
root@b105f1bcb227:/# cd /rdk/
root@b105f1bcb227:/rdk# apt update && apt install -qy git make vim sudo
root@b105f1bcb227:/rdk# etc/setup.sh 
...
Dev environment setup is complete!
Don't forget to restart your shell, or …
```
> RSDK-6989 setup.sh maintenance

- robot/web/graphviz_c.go
- robot/web/web_c.go
- move `handleVisualizeResourceGraph` from web_c.go to new graphviz_c.go
- this change should not change any behavior
- but it will make incoming changes from the droid-x264 branch easier to merge, this: https://github.com/abe-winter/rdk/pull/4. droid-x264 uses more media functions, so it consumes most of web_c.go, but there is no android build for graphviz so it needs to be flagged separately
> factor out graphviz dependency from web_c

- components/base/sensorcontrolled/velocities.go
- components/motor/gpio/motor_encoder_test.go
oops forgot this in the original change and didn't catch it
> RSDK-7259: sensor controlled base discrete movement commands don't stop when expected

- web/frontend/package-lock.json
- web/frontend/package.json
- web/frontend/src/api/do-command.ts
- web/frontend/src/components/do-command/get-client-by-type.ts
- web/frontend/src/components/do-command/index.svelte
This is a hack to make the DoCommand card work for sensors and cameras, which is currently blocking a customer.
- Show a notification when there is not a client
- Use the `SensorClient` for sensors
- Use the `CameraClient` for cameras
- Bump package version
Code review should work here. @zaporter-work and I can verify together offline.
> RSDK-6810: Hack to add DoCommand for sensors and cameras

- services/datamanager/builtin/builtin.go
- services/datamanager/data_manager.go
- temp.json
This PR fixes a bug that exists in the builtin data service that occurs if a user specifies a default path to save files in the capture configuration.  It is fixed by changing a pointer to a `DataConfigMethod` to an instance of the struct itself.  When this happens the deep copy happening in the `Link` function works as intended (where before it did not) allowing the `builtin` struct to modify its internal representation of `DataConfigMethods` without it affecting the raw json that is compared during equality check.
Its worth pointing out here that anyone attempting to write an `AssociatedConfig` needs to write the deep copy method correctly when linking and that there might be a structural improvement that could be made by removing `Link` from the interface and handling the deep copy …
> RSDK-7271 - fix spurious reconfiguration bug in builtin data service

- components/board/digital_interrupts.go
- components/board/fake/board.go
- components/board/genericlinux/board.go
- components/board/genericlinux/digital_interrupts.go
- components/board/numato/board.go
- components/board/pi/impl/board.go
- components/board/pinwrappers/analog_smoother_test.go
- components/board/pinwrappers/analogs.go
- components/board/pinwrappers/digital_interrupts.go
- components/board/pinwrappers/digital_interrupts_test.go
- robot/impl/resource_manager_test.go
This PR:
- Moves the entire file containing Reconfigurable Analog Readers and AnalogSmoothers to the new pinwrappers package.
- Moves the lines creating basic digital interrupts from `board/digitalinterrupts.go` to the `digital_interrupts.go` file in the pinwrappers package.
- changes any usage of these wrappers the board drivers to the new package.
A few things to note: 
- The only actual board that uses the Analog smoother with a physically builtin analog reader is the numato board.
- generic linux use reconfigurable digital interrupts, so does the pi.
-  generic linux and the pi use the smooth analog reader when configured with an the MCP3008 chip.
- I'm not sure certain methods in the BasicDigitalInterrupt interface are actually being used anywhere.
Further code cleanup can be done, …
> Create pinwrappers package

- robot/impl/discovery_test.go
- robot/impl/local_robot_test.go
- robot/impl/resource_manager_modular_test.go
- robot/impl/resource_manager_test.go
- robot/impl/robot_reconfigure_test.go
- robot/impl/utils.go
- robot/impltest/local_robot.go
Adds a test helper version of [robotimpl.New](https://pkg.go.dev/go.viam.com/rdk/robot/impl#New), which creates a local robot and automatically closes itself, and also fails tests on any failure. This fairly small helper ends up eliminating a lot of boilerplate code.
In addition, this PR also converts `defer` calls in test helpers to use [T.Cleanup](https://pkg.go.dev/testing#T.Cleanup) instead.
> RSDK-6925 better helpers for resource manager tests

- components/movementsensor/accuracy.go
- components/movementsensor/adxl345/adxl345.go
- components/movementsensor/client_test.go
- components/movementsensor/dualgps/dualgps.go
- components/movementsensor/fake/movementsensor.go
- components/movementsensor/imuvectornav/imu.go
- components/movementsensor/movementsensor.go
- components/movementsensor/mpu6050/mpu6050.go
- components/movementsensor/replay/replay.go
- components/movementsensor/server.go
- components/movementsensor/server_test.go
- components/movementsensor/wheeledodometry/wheeledodometry.go
Since the server functions return pointer to accuracies, this is totally legal:
```go
func (ms *ms) Accuracy(ctx context.Context, extra map[string]interface{}) (*Accuracy, error)
return nil, nil
```
Which was causing the server to panic because of a nil pointer dereference:
```
2024-04-15T10:11:57.049-0400	ERROR	robot_server	rpc/server.go:318	panicked while calling unary server method	{"error": "rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference", "errorVerbose": "rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference
go.viam.com/rdk/components/movementsensor.accuracyToProtoResponse
\t/Users/randhidayah/viam/rdk/components/movementsensor/accuracy.go:62 …
```
> Defend against nil, nil returns in modular Movement Sensors. 

- module/modmanager/manager.go
- robot/impl/local_robot.go
- robot/impl/resource_manager.go
- utils/ticker.go
RDK now warns on slow resource startup/reconfiguration
`2024-04-15T21:05:02.960Z        WARN    robot_server    utils/ticker.go:22      Waiting for resource to complete (re)configuration      {"resource":"rdk:component:encoder/encoder2","time elapsed":2.000306042}
2024-04-15T21:05:05.961Z        WARN    robot_server    utils/ticker.go:22      Waiting for resource to complete (re)configuration      {"resource":"rdk:component:encoder/encoder2","time elapsed":5.000861625}`
> RSDK-6934 - Add ticker for slow resource (re)configuration

- .github/workflows/staticbuild.yml
- packaging.make
Use a sortable key for latest viam-server build so we can enable users to configure latest as release channel in Viam Agent config.
[APP-4566](https://viam.atlassian.net/browse/APP-4566)
[APP-4566]: https://viam.atlassian.net/browse/APP-4566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APP-4566] Tag 'latest' release with build timestamp

- cli/app.go
- cli/module_build.go
- add `--group-logs` param to ModuleBuildLogsAction
- when present, this flag adds a `::group::` wrapper to each platform in the logs output
- should match expected format in [their docs here](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines)
Currently, when multiple platforms are present in this output, it's difficult to read the logs. When one of them fails, it's difficult to know which.
```log
::group::{✅ linux/amd64}
Info: Logs for "linux/amd64"
Info: viam version
...
Total size uploaded: 1.7 KiB
::endgroup::
```
> APP-4665 collapse cloud-build logs

- components/board/board.go
- components/board/client.go
- components/board/fake/board.go
- components/board/genericlinux/board.go
- components/board/mcp3008helper/mcp3008.go
- components/board/numato/board.go
- components/board/pi/impl/analogs.go
- components/board/pi/impl/board.go
- components/board/pinwrappers/analog_smoother_test.go
- components/board/pinwrappers/analogs.go
- testutils/inject/analog.go
Removes the Close function from the analog interface, changes implementation of the raspberry pi to directly use the analog smoother rather than store it as a board.Analog in its struct.
Note: I have only implemented the `Write` method on the interface in the analog struct in board.go. This function does not yet go through the server or client in th main board file, which was ticketed separately. That will need to go over the wire using the `WriteAnalog` rpc.
> [RSDK-7335] Remove Close() from and Add Write() to  Analog interface in board 

- components/arm/fake/fake.go
Naomi noticed the fake arm does not show up on the RC card when configured with nothing. This is expected since omitting both a kinematics file and a model name builds a zero-degrees-of-freedom arm (i.e., no joints—there's nothing to control).
To keep the behaviour as is but surface what's happening to a user, I added a viam-server-side info log. The arm is there—you can get it from the resource graph in client code and use the arm APIs. 
Verified adding a model path or name works as expected, you get button for joints equal to the degrees of freedom specified by the kinematics model or model name of that arm.
An alternative is creating a 1-dof arm by default.
This is what shows up now:
> [APP-4529] fake arm shows nothing on rc card

- services/datamanager/builtin/builtin.go
- services/datamanager/builtin/sync_test.go
Hey yall, this PR is to add the necessary fields/goroutines to poll the filesystem at a regular interval. 
**Implementation details**
There is no real difference between the implementation here and the tech spec (yay). I added a cancel function and waitgroup to the service struct. These fields are intialized in reconfigure and any access to them is guarded by a nil check (pls point out if I missed a spot). Each time reconfigure is called, we cancel the context and wait for the currently executing thread to finish. 
If capture is enabled, we create a new context and wait group and kickoff the go routine. For now, this routine just prints once every 30 seconds if debug is enabled. 
If capture is disabled, we dont start the thread and nil out the cancel func and wait group.
In close, we …
> DATA-2483 Add infrastructure for thread to poll filesystem

- components/arm/xarm/xarm.go
- components/arm/xarm/xarm_test.go
- components/board/hat/pca9685/pca9685.go
- components/camera/videosource/webcam.go
An ask from fleet to change the following attributes:
- webcam "device_path" -> required
- xarm "speed", "host", "acceleration" -> optional. Did a little cleanup here too so that we 
a) don't change the config from app in Validation (an anti pattern)
b) add some schema clauses for defaults. We don't use these tags directly. These are checked in Reconfiguration and set for the driver that actually interfaces with hardware.
- pca -> "i2c_bus" required.
TODO
@mcous this won't be reflected in app until it pulls in the next rdk right? What's a quick and dirty way to verify that r2d2 adheres to these changes? Particularly interested in the json schema now breaking anything.
> Change xarm, pca, and webcam attribute requirements.

- .github/workflows/macos.yml
- pin macos.yml macos runner version
- macos-12 https://github.com/viamrobotics/rdk/actions/runs/8792719380/job/24129397979
- macos-13 https://github.com/viamrobotics/rdk/actions/runs/8792969817/job/24130089706
Our macos-latest jobs went from 12 -> 14 and started failing. We should investigate but for now I'm pinning the image to get builds green.
The failure:
```
In file included from ../../../go/pkg/mod/github.com/mattn/go-tflite@v1.0.4/tflite.go:5:
./tflite.go.h:8:10: fatal error: 'tensorflow/lite/c/c_api.h' file not found
#include <tensorflow/lite/c/c_api.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
[Passing job (old)](https://github.com/viamrobotics/rdk/actions/runs/8790733687/job/24124159229)
```
Image: macos-12
Version: 20240412.2
Included Software: …
```
> RSDK-7383 pin macos in CI

- components/base/kinematicbase/ptgKinematics.go
- components/base/kinematicbase/ptgKinematics_test.go
Prior PR missed updating the way ErrorState is calculated.
Tests did not catch because the test was also calculating the old way.
> RSDK-7210 Fix kinematic base ErrorState

- .github/workflows/test.yml
15-minute timeout for e2e job
Good runs for this are quick, but bad runs take hours
Quick runs:
- https://github.com/viamrobotics/rdk/actions/runs/8807475062/job/24174617621 3m
- https://github.com/viamrobotics/rdk/actions/runs/8805676593/job/24168779288 7:30
- https://github.com/viamrobotics/rdk/actions/runs/8759676217/job/24043586383 9:30
Slow runs (canceled after 1+ hours):
- https://github.com/viamrobotics/rdk/actions/runs/8817911494/job/24205474457 56m
- https://github.com/viamrobotics/rdk/actions/runs/8756235104/job/24032213572 5h
Even the good runs are fairly variable -- we should look into this. For now adding a 15 minute timeout so the endless ones get canceled and unblock the next run on main.
> add timeout for e2e job

- robot/impl/local_robot_test.go
DISCLAIMER: I don't fully understand this code -- I just saw a lot of notifs in team-devops and this flaked for me. If you would rather fix this your own way, we can close this or I can change this to just skip the test. [The ticket](https://viam.atlassian.net/browse/RSDK-7284) is assigned to maxim, but he is on vacation for another week 
The test was only checking that "Module successfully restarted" occured, but not that the manager had all of the resources updated.  I think DoCommand will fail until then
See modmanager/ newOnUnexpectedExitHandler:
```go
func (mgr *Manager) newOnUnexpectedExitHandler(mod *module) func(exitCode int) bool {
return func(exitCode int) bool {
mod.inRecoveryLock.Lock()
defer mod.inRecoveryLock.Unlock()
if mod.inStartup.Load() {
return false
} …
```
> RSDK-7284 - Fix TestModularResourceReconfigurationCount flake

- components/input/client.go
- components/input/client_test.go
added a bunch more locking, but I think the new lock points make sense
added a new test that definitely races if the changes were not in
> RSDK-6947 - Test Datarace: go.viam.com/rdk/components/input.TestClient

- web/frontend/package-lock.json
- web/frontend/package.json
- web/frontend/src/components/arm/index.svelte
Similar to the last one, these props can be undefined and need to be guarded against.
> Arm jointPosition patch fix

- components/movementsensor/imuwit/imu.go
- components/movementsensor/imuwit/imuhwt905.go
We've had a pattern of creating an `activeBackgroundWorkers` group to track our goroutines, with a context that gets canceled within `Close()`, followed by waiting for the workers to shut down. In my 20% time, I've abstracted this pattern out to a separate struct (see #3597; thanks @dgottlieb for the feedback on that!), and in this PR I'm using it in the IMU Wit code. 
It might be simplest to review the two commits separately: the second one just changes a bunch of whitespace to make the linter happy.
Similar PRs will be coming for the other places where we use this pattern...
> use StoppableWorkers in the IMU Wit components

- services/datamanager/datasync/sync.go
We use a exponential backoff algorithm, multiplying the previous time by 2 until min(maxRetryInterval, nextWait). So after 1 hour, we will retry sync at 2, 4, 8, 16, 24 hrs.
> DATA-2565 - Retry sync for up to a day

- components/board/digital_interrupts.go
- components/board/fake/board.go
- components/board/genericlinux/digital_interrupts.go
- components/board/pi/impl/board.go
- components/board/pi/impl/digital_interrupts.go
- components/board/pi/impl/digital_interrupts_test.go
- components/board/pinwrappers/digital_interrupts.go
- components/board/pinwrappers/digital_interrupts_test.go
- components/encoder/incremental/incremental_encoder.go
- components/encoder/incremental/incremental_test.go
- components/encoder/single/single_encoder_test.go
- components/input/gpio/gpio_test.go
- components/movementsensor/adxl345/adxl345_test.go
- robot/impl/robot_reconfigure_test.go
- testutils/inject/digital_interrupt.go
Removing tick for the interface and making it a helper function.
> RSDK-7363 Remove tick from digital interrupt interface

- cli/packages.go
ToDetailURL is [only used by ML training](https://github.com/search?q=repo%3Aviamrobotics%2Frdk%20todetailurl&type=code), so updated the code there. 
The [other package upload receives the URL from the server](https://github.com/viamrobotics/rdk/blob/1c27a46539b7598ed891c0063d2a9f2e98a2c3fc/cli/module_registry.go#L360-L403), which converts the input package type into the one used by the URL.
**Testing**
`go run cli/viam/main.go training-script upload --org-id=f87b919c-63b2-4d32-b676-0b55393938d7 --path=/Users/alexa.greenberg@viam.com/Downloads/trainingscript-0.1.tar.gz --name=alexas-example-script`
yields:
`Version successfully uploaded! you can view your changes online here: https://app.viam.dev/ml-training/f87b919c-63b2-4d32-b676-0b55393938d7/alexas-example-script`
Which can be viewed …
> [DATA-2591] Fix URL returned by CLI command to upload ML training script

- components/board/pinwrappers/analogs.go
Thanks to @cheukt for some of the investigation on this!
If you configure an analog reader but don't have the hardware set up, before this PR you get into a tight retry loop, and can log errors thousands of times per second. Now, you only log the errors as fast as you were supposed to read the analog.
This PR has an alternate implementation, where we try to read the analogs as quickly as before but shut down the entire goroutine if we get 100 errors in a row. I tentatively prefer this version instead (so it starts working if you plug in the right hardware, even if you don't then reconfigure your board), but am open to either approach.
> [RSDK-6243] read analogs at expected rate even with errors

- config/reader.go
- config/reader_test.go
In https://github.com/viamrobotics/rdk/pull/3620 @maximpertsov shrunk the requirement for parsing the cached config to just care about the tls cert and private key. This allows us to safely add fields to the cloud config without creating incompatibility with previous cached configs (a big & dangerous footgun)
However, this PR was only targeting a  `SignalingInsecure == false` environment (where TLS is required). When we have a local app and local rdk, we have `SignalingInsecure==true` and should not block on an empty tls object.
Add a check against the cached `SignalingInsecure` before failing validation in `tls.readCache`
```golang
func readCertificateDataFromCloudGRPC(ctx context.Context,
signalingInsecure bool,
cloudConfigFromDisk *Cloud,
logger logging.Logger,
) (tlsConfig, error) { …
```
> APP-3954 - Respect SignalingInsecure when reading TLS info

- components/board/client.go
- components/board/client_test.go
fixes an issue for modular boards where interrupt and analog names would be readed to the client names list, causing the status stream to grow exponentially.
Intended to be a quick fix as other work is scheduled for modifying the names list. 
Other board implementations appear to already solve this issue, such as [genericlinux](https://github.com/viamrobotics/rdk/blob/6ab84fbccd6cc2e99a781c02b50bb71739035f21/components/board/genericlinux/board.go#L413-L416) looking to see if the interrupt already exists
ticket: https://viam.atlassian.net/browse/RSDK-7437
> [RSDK-7437] check if a pin is already in the names list

- services/navigation/builtin/builtin_test.go
This flake was caused by this test checking the length of the waypoints in the nav service after it was set to `waypoint_mode`.  This has been a latent race condition that has existed as long as the test has, but only recently flaked due to a speedup introduced in surfacing the relevant error in motion/builtin.  Checking the length of the waypoint list before starting the motion removes the race and deflakes the test
> RSDK-7326 fix flaky test in builtin navigation service

- cli/app.go
- cli/client.go
- cli/client_test.go
- go.mod
- robot/server/server_test.go
- services/shell/builtin/builtin.go
- services/shell/client.go
- services/shell/copy.go
- services/shell/copy_local.go
- services/shell/copy_local_test.go
- services/shell/copy_rpc.go
- services/shell/copy_rpc_test.go
- services/shell/copy_test.go
- services/shell/server.go
- services/shell/shell.go
- services/shell/testutils/utils.go
- services/shell/testutils/utils_test.go
This adds bidirectional file copy support (think SCP) for the shell service. Tested this across machines far away for a 100MB transfer. This doesn't have visual file progress support like scp does.
Usage:
Copying to: `viam robot part cp --organization "First's Org" --location "First Location" --robot "r1" --part "r1-main" -r -p ~/Downloads/bar2 machine:~/foo`
Copying from `viam robot part cp --organization "First's Org" --location "First Location" --robot "r1" --part "r1-main" -r -p machine:~/Downloads/bar2 ~/foo`
n.b.: I went through the efforts of playing with `scp -S` under the hood where you can pass your own ssh compliant program to it and it handles all the protocol for you. It would be way less code to write (no proto additions) if we did it that way but it's convoluted in that the …
> shell service: add bidi file copy support

- components/movementsensor/gpsrtkserial/gpsrtkserial.go
Problem here is that we were seeing gap in position reporting when reconnecting to NTRIP caster. Removing the mu.Lock() from movementsensor functions helped speed up the process. 
I also reverted getstream function back what it used to be. In the old function we only block when getting rc and setting g.ntripClient.Stream to rc, which enables us getting nmea messages during reconnection. Removing the mutex from all the movementsensor functions doesn't cause any race condition since there are mutex lockes in the same functions in cached data. 
**This needs to be tested again in Long Island one more time before merging.**
Tested against NYGC in Long Island.
> Rsdk-7332: slow position reporting

- .github/workflows/full-static.yml
- .github/workflows/main.yml
- .github/workflows/stable.yml
- call the new full-static.yml from 'main' and 'stable' workflows
These full-static binaries are more portable than our existing static build, at the cost of fewer features.
- inside main.yml https://github.com/viamrobotics/rdk/actions/runs/8930990933
- example with channel and version https://github.com/viamrobotics/rdk/actions/runs/8930977917
> RSDK-7370 upload full-static from main and stable

- robot/web/web_notc.go
- remove unused import
This broke in a recent commit, but the `no_cgo` tagged build isn't exercised in PRs so it didn't show up until the PR was merged.
To-do later: add a (fast) version of the full-static build in PRs to protect against this.
> unbreak no_cgo build

- utils/stoppable_workers.go
It turns out several places set up background workers in multiple spots that can only be determined at runtime. So, this PR adds a way to put additional workers into the `StoppableWorkers` after the original ones are created.
I haven't tried this out on real hardware, but the compiler and linter are both happy, and I don't see anything obvious I could have broken that they wouldn't have caught.
> Add AddWorkers function to StoppableWorkers

- robot/server/server.go
- robot/session_manager.go
I was hoping to do more during the 20% Happy Hour, but this is as far as I got this time.
- In `server.go`, I was surprised that `activeBackgroundWorkers` was never used, and by extension `cancel` and `cancelCtx` weren't either! So, I removed them.
- In `session_manager.go`, I added a `StoppableWorker`  for the pattern it's intended to replace.
No changes to behavior are intended. Everything compiles and the linter is happy, but I haven't tried things more thoroughly than that.
> Use StoppableWorkers in some of the robot/ directory

- components/arm/client_test.go
- components/arm/server.go
- components/gripper/client_test.go
- components/gripper/server.go
- testutils/inject/arm.go
- testutils/inject/gripper.go
not sure if there's a reason these were different, but arm and gripper were always returning unimplemented error when calling `Geometries` from the sdk, but this fixed it
> RSDK-7512: arm and gripper geometries always returns unimplemented error

- .github/workflows/macos.yml
- Don't cache homebrew folders for slow builds
This caching never in fact worked, but a flag change broke our tflite import, masking this failure. (Fix for the flag change is here https://github.com/viamrobotics/rdk/pull/3903).
- :heavy_check_mark: https://github.com/viamrobotics/rdk/actions/runs/8972984931/job/24642172488
> revert macos homebrew cache

- robot/impl/local_robot.go
- robot/impl/resource_manager.go
- robot/impl/robot_reconfigure_test.go
* Simplifies TestRemoteRobotsGold by creating a smaller config instead of using a file
* Adds clarifying comments around TestRemoteRobotsGold and some other updated tests
* Remove triggerConfig calls from tests (ran it a few times, doesn't seem to change failure rate/time). triggerConfig can make reconfiguration go faster, but only if the remote robot has already re/connected by that point. Calling it immediately does not speed up reconnection and would not improve speed.
> Remove triggerConfig from remote robot tests and add documentation

- components/motor/motor.go
- components/servo/servo.go
I used "myServoComponent" and "myMotorComponent" as the names because the Code Sample boilerplate code appends "Component" to the ends of component names.
> DOCS-2085: Add motor and servo example code snippets

- module/modmanager/manager_test.go
Fixes this flake: https://github.com/viamrobotics/rdk/actions/runs/8988839369/job/24690566713#step:8:61327
> bump-rtppassthrough-test-timeout

- module/modmanager/manager.go
- module/modmanager/manager_test.go
We were logging after the test cleaned up, in this case in the OnUnexpectedHandler
* Added a setup/clean up function for mod manager in tests - made a copy of the mod map before modmanager.Close() because otherwise we wouldn't know which modules were in existence. Waited for the module in recovery lock after Close() instead of before so that modmanager could cancel any contexts related to module recovery which should speed up the Lock() and also prevent deadlocks
* Exit earlier in the attemptRestart loop, just an optimization
> RSDK-6804 - Test Datarace: go.viam.com/rdk/module/modmanager.TestDebugModule

- services/datamanager/datasync/sync.go
We have a bug where certain threads can get stuck in an extremely long wait for exponential backoff. This is mostly a problem we encounter with machines that go offline for long periods of time. This fixes that.
~Also, I changed the sleep logic to use `sleep()` instead of `ticker` as, based on reading [docs](https://gobyexample.com/tickers) it seems like this was a funny way of doing a changing sleep. But I'm a fool and should not be trusted on anything related to Go.~
**EDIT: Not changing anything about the ticker! Lessons learned: Always listen to @tahiyasalam!**
**Testing**
I set the number of threads to be 1 and the time interval to be 10 seconds (and added a print statement when it tries to upload).  I then, let it run and in the middle, turned off my wifi. Here are the logs
Notice …
> retry offline errors every thirty seconds

- components/board/numato/board.go
for the numato boards we use a go utils serial search function to find the serial path, but it is limited to 4 numato boards. This allows the user to optionally supply the serial path in the config so we can support all numato versions. non breaking change since the driver will use the serial search if the user doesn't supply path.
> RSDK-7300 Make numato support all serial models 

- module/modmanager/manager_test.go
- module/module.go
[Ticket](https://viam.atlassian.net/browse/RSDK-7521)
Ideally I'd rather this limit be enforced in viam-server but unfortunately there is no object in viam server that has currently does reference counting of how many active tracks there are on a given peer connection. 
As a result, it was most expedient to do this reference counting in the module. 
Note: If we add webrtc support to modules in languages other than golang, we will need to either fix the limitation in our WebRTC implementation or enforce the same limit in other languages.
I also found that the test `TestRTPPassthrough` had unnecessary setup & verbose variable names that harmed readability so I refactored that test.
> RSDK-7521 - Enforce temp WebRTC track limit in module.AddStream

- module/modmanager/manager_test.go
This [commit](https://github.com/viamrobotics/rdk/commit/2609b3d91d) changed log message content. `TestTwoModulesRestart` depended on those log lines to know when an assertion was valid.
> RSDK-7541: Have TestTwoModuleRestart wait for log message that implies its follow-up assertions have been met.

- components/board/board.go
- components/board/client.go
- components/board/client_test.go
- components/board/fake/board.go
- components/board/genericlinux/board.go
- components/board/hat/pca9685/pca9685.go
- components/board/numato/board.go
- components/board/pi/impl/board.go
- components/board/server.go
- components/board/server_test.go
- testutils/inject/board.go
Everything compiles and the linter is happy, but that's as far as I've tested; I don't have an analog writer to try this out with. Olivia, maybe I could borrow one from you?
> [RSDK-7322] Move analog writers from Board interface to Analog interface

- services/datamanager/builtin/builtin.go
- services/datamanager/builtin/file_deletion.go
- services/datamanager/builtin/file_deletion_test.go
Hey yall, this PR is to make the value of N for file deletion configurable via raw JSON. If no value is set, N is the default value of 5, otherwise it's what in the config.
Example service config:
```json
{
"name": "data_manager-1",
"type": "data_manager",
"sync_disabled": false,
"delete_every_nth": 5,
"sync_interval_mins": 60,
"capture_dir": "",
"tags": [],
"additional_sync_paths": []
}
}
```
I've tested this works on a pi 
I can see logs matching when I change the value for N. I also checked there are not random reconfigures happening as a result of this addition.
> DATA-2484 Make N configurable via JSON

- config/config.go
- robot/packages/cloud_package_manager.go
Removes the cleanup logic for previously renaming .data -> data in https://github.com/viamrobotics/rdk/pull/3608
>  APP-4066: Remove legacy .data dir cleanup logic

- services/motion/builtin/builtin_test.go
For some tests, we are mocking up transient obstacle avoidance and so wish to return a different value from an injected function the first time it is called.
As we are doing this several times over for multiple tests, we track the values in a map, where each tests can flip a bool corresponding to its own name to determine whether it has already run.
However, the map was unprotected, so we have multiple tests reading/writing to the same map simultaneously, even if it was guaranteed there would be no collision as each test only queried its own key.
This PR adds a mutex to the map.
> RSDK-7583 Fix test race condition

- components/motor/gpio/basic.go
- components/motor/gpio/setup.go
- make all pins omitempty to silence config errors on app
- change A/B/PWM warning message to make it clear that some A/B motor drivers also require PWM
> APP-4577: incorrect error message about gpio motor pins

- components/board/pi5/data.go
This fixes rover issue of trying to set pwm pin high.
> RSDK-7597 Allow pins to be either PWM or GPIO on pi5 boards

- logging/net_appender.go
- logging/net_appender_test.go
* The main cause seems to be that the background worker and us calling sync at the same time. So cancelled the background worker.
* I've been getting failures on 10k runs sometimes even after this fix, but less reliably and also seems like a network blip mostly (usually fails in `TestNetLoggerSyncFailureAndRetry` and the error is deadline exceeded), so opting to just push this in and see if the other failure will actually show up and may be easier to debug within CI. It was hard to debug the new issue because of the overwhelming amount of logs
> RSDK-7598 - Fix logger tests

- .gitignore
- data/collector.go
- data/collector_test.go
https://github.com/viamrobotics/rdk/commit/2845abe484258d45b20879a755fb9039d764ae72 is a strawman proposal for fixing the `TestCtxCancelledNotLogged...AfterClose` test. The PR here is more to communicate than be exactly what I think we should merge. The other commit in this PR that reverts the prior commit was just from the state my branch happened to be in when I was investigating. It's inclusion here is not a preference one way or the other.
My "fix" being proposed here is the smallest code change I know of that preserves existing behaviors[1] at the cost of introducing more state tracking. This state tracking is an intrinsic consequence of the number of goroutines data collection spins up.
[1] The existing behaviors I am intentionally preserving. I don't think all are particularly …
> RSDK-7487: Guarantee context cancel errors are not logged after a data collector is `Close`d.

- components/base/kinematicbase/execution.go
- components/base/kinematicbase/ptgKinematics_test.go
It was noted that course-correcting bases could sometimes veer wildly off the path.
It was determined that the goal poses being course corrected for could be incorrect in the case where their parent arc was one which had already been course-corrected.
> RSDK-6700 Bugfix for course correction

- components/movementsensor/wheeledodometry/wheeledodometry.go
- components/movementsensor/wheeledodometry/wheeledodometry_test.go
Not tried on real hardware yet; need to do that soon.
- At the top of `trackPosition` we'd check if `o.originCoord` was nil. However, `trackPosition` was only ever called immediately after setting `o.originCoord` to a non-nil value. So, I took that out. 
- Then, `trackPosition` did nothing but spawn a goroutine. I refactored so the call to `trackPosition` spawned the goroutine and `trackPosition` itself is just the code that runs in the routine. This meant unindenting the entirety of `trackPosition` a level, leading to a much bigger diff than it should really be. *I'd review this while ignoring whitespace changes.*
- Once we've replaced the `activeBackgroundWorkers` pattern with a `StoppableWorkers` struct, we no longer import go.viam.com/utils, so don't need to use a nonstandard name …
> use StoppableWorkers in wheeledodometry

- components/board/genericlinux/analogs.go
- components/board/genericlinux/board.go
- components/board/genericlinux/gpio.go
- `createGpioPin` is a method on the `Board` struct: put it in the file that defines `Board`. I was trying to do a different refactoring, and totally missed that this function existed!
- `wrappedAnalogReader` is a nontrivial struct: put it in its own file.
No changes to behavior are intended.
> Move some of the genericlinux code around

- services/motion/builtin/move_on_map_test.go
- services/motion/localizer.go
- services/motion/localizer_test.go
- services/navigation/builtin/builtin.go
- spatialmath/pose.go
The navigation service was not accounting for any rotation of a camera with regard to the base when placing obstacles.
This PR corrects that and will correctly orient obstacles with regard to the base.
> RSDK-6700 Nav service is not properly placing transient obstacles

- components/base/kinematicbase/ptgKinematics.go
Previous PR to fix a flaky test missed an update to `ErrorState()` which caused panics when completing plans.
> RSDK-7670 Fix errorstate when plan is complete

- robot/impl/local_robot.go
- robot/impl/resource_manager.go
- robot/impl/resource_manager_test.go
- robot/impl/robot_reconfigure_test.go
Add a parity test that asserts sync and async reconfigure flows produce the same resource state. 
We [previously discussed](https://github.com/viamrobotics/rdk/pull/3707#discussion_r1600236702) making this part of [the PR that introduced async reconfiguration](https://github.com/viamrobotics/rdk/pull/3707) but were concerned that this test might be a pain to maintain due to it's fuzzy nature and opted to use it as a one-time smoke test. However, after further discussion IRL, we think it's important to have as a long-term fixture.
> RSDK-6925 Add parity test for sync/async reconfigure flows

- module/version_reconfigure_test.go
Change test to filter+count a different error log - the current one can appear more than once occasionally.
We changed the log line we filter for (941aebecf294df655d3c086e8e2e8f51b6ef291c) since the tests were originally introduced (2bd2860d2722a8fe80aa0db27d8df07540328866).
The current error log is in the resource manager (in `completeConfig`): https://github.com/viamrobotics/rdk/blob/4be931a11870a197c13b5844027551ccaec00809/robot/impl/resource_manager.go#L613-L616, and the original is in the mod manager: https://github.com/viamrobotics/rdk/blob/4be931a11870a197c13b5844027551ccaec00809/module/modmanager/manager.go#L699
While rare, the current log line can conceivably appear more than once in this test if the `completeConfig` ticker goes off and triggers another reconfiguration. However, …
> RSDK-7674 - Fix flake: TestValidationFailureDuringReconfiguration

- services/datamanager/builtin/builtin.go
- services/datamanager/builtin/file_deletion.go
hey yall, this PR is to change the error log for file system stats to a warning log. While making this change, I added another check to swallow a file not existing from getting renamed as otherwise, we can exit out of the file system checking thread unnecessarily, leading to files not being deleted when they should be.
> DATA-2651 Change error to warning log

- robot/client/client_test.go
- robot/impl/local_robot_test.go
- robot/impl/resource_manager_test.go
- robot/impl/robot_framesystem_test.go
- robot/impl/robot_reconfigure_test.go
- robot/server/server_test.go
- services/sensors/builtin/builtin_test.go
- services/sensors/server_test.go
- testutils/resource_utils.go
QoL testing improvements identified while investigating [this flaky test](https://viam.atlassian.net/browse/RSDK-7706).
* Add a `VerifySameResourceNames` test utility function and use it in places where we verbosely convert to set + assert resembles.
* Note for reviewers - I tried my best to do this change programmatically via regex-replace, but the format of some sections varied too much and needed to be changed "by hand", so please double-check if I made a silly mistake.
* Under the hood, assert same resources by comparing sorted slices instead of converting to sets - this makes failure diffs a bit more a little more human readable.
> Test debugging QoL: compare sorted resource names instead of unordered sets

- components/motor/gpio/controlled_test.go
- components/motor/gpio/encoded.go
- components/motor/gpio/encoded_test.go
I found a race between `WaitForSuccess`'s `position` and `goForInternals` `position` that I'd like to address. But this makes the tests pass (they were failing - not racing - before).
I'll need to restructure some of the motor logic more to have less helpers and call the encoder position directly - we will be able to get rid of `direction` and possibly `m.TicksPerRotation` in the control logic. In a separate pr.
> [RSDK-6777][RSDK-7256][RSDK-7255] Make tests for goForMath and GoFor pass.

- config/config.go
- config/config_test.go
- config/data/config_with_web_profile.json
- config/diff.go
- config/diff_test.go
- config/proto_conversions.go
- config/proto_conversions_test.go
- web/server/entrypoint.go
Proto update here https://github.com/viamrobotics/api/pull/497
> [RSDK-7562]  Add enablewebprofile to robot config

- module/modmanager/manager.go
- module/modmanager/manager_test.go
[RSDK-7785](https://viam.atlassian.net/browse/RSDK-7785)
Only calls `removeOrphanedResources` for a crashed module if there were actually orphaned resources (`len(orphanedResourceNames) > 0`). Modifies tests accordingly. 
Calling `removeOrphanedResources` when no resources have actually been orphaned is not _terrible_, but it does cause an extra weak dependents update [here](https://github.com/viamrobotics/rdk/blob/main/robot/impl/local_robot.go#L561). Extra weak dependents update means extra, unnecessary `Reconfigure`s of resources like the data manager service, making us more prone to bugs like [DATA-2664](https://viam.atlassian.net/browse/DATA-2664).
cc @vijayvuyyuru 
[RSDK-7785]: https://viam.atlassian.net/browse/RSDK-7785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> RSDK-7785 Do not call removeOrphanedResources with no orphans

- services/datamanager/builtin/builtin.go
Hey yall, inside of datamanager's reconfigure, there is a check designed to only cancel the syncer if a relevant value has changed. There was a small bug where it would naively compare the service value to the value from the config struct(introduced by me sorry). However if this value was unset (which it is the majority of the time), it would be comparing the service threads to 0 (the default value if the field is unset). As a result, we would cancel and reconfigure the syncer unncessarily. This was discovered as part of @benjirewis's investigation into a customer issue where sync would not occur until a service level restart. 
**Testing**
This was tested by adding logging to reconfigure and verifying the log line was only printed when the actual number of sync threads was changed, not …
> DATA-2665 Change max thread check to handle empty value from config

- components/board/client.go
- components/movementsensor/server.go
- components/movementsensor/server_test.go
- protoutils/messages.go
Adding a check for a nil to avoid a panic if a modular movementsensor returns nil for position or orientation.
> RSDK-7743 Add checks for nil in movementsensor position and orientation

- components/base/sensorcontrolled/movestraight.go
- components/base/sensorcontrolled/sensorcontrolled_test.go
- components/base/sensorcontrolled/spin.go
https://viam.atlassian.net/browse/RSDK-6986
tested on a benchtop and in the grid area using a viam rover both with and without a position endpoint. Both cases used odometry for the velocity movement sensor, and odometry was used for the position endpoint for those tests.
> [RSDK-6986] add velocity only sensorcontrolled MoveStraight

- cli/auth.go
- cli/auth_test.go
- cli/client.go
- cli/client_test.go
- cli/config.go
- export `Config` struct and `ConfigFromCache` loader
- add `Config.DialOptions()` method in place of old piecewise dial opts creation
Make logged-in token usable by additional tools
This works:
```sh
go run ./cli/viam/ org list
```
> APP-5114 export CLI config parsing + dialing

- components/arm/client.go
- components/arm/server.go
- components/arm/server_test.go
`empty-arm` in fake components module now shows up correctly on the RC card
> RSDK-7797 Guard against nils in arm client and server 

- logging/net_appender.go
- logging/net_appender_test.go
- web/server/entrypoint.go
- the `NewNetAppender` constructor now has an optional `conn` param which allows it to share a ClientConn
Conserve and share resources used at runtime, esp as we duplicate this for viam-agent. Agent's Manager object already keeps a long-lived connection [here](https://github.com/viamrobotics/agent/blob/8848c83f11c02655ccb1ec8ac5f7fad0b406df29/manager.go#L383), no need to add another.
> RSDK-7786 optional shared ClientConn param in NetAppender

- components/encoder/fake/encoder.go
- components/motor/fake/motor.go
- components/motor/fake/motor_test.go
@biotinker was trying to use the fake motor and fake encoder to set up a wheeled odometer for testing in the nav stack. Casting the position in the encoder struct to an integer and Setting the Position in the fake encoder to an integer was accruing massive errors. This pr does away with unnecessary conversions.
Example output before change
```
encoder.go:107: 2024-06-05T15:22:11.679-0400	INFO		fake/encoder.go:107	position 0
motor.go:209: 2024-06-05T15:22:11.680-0400	DEBUG		fake/motor.go:209	Motor SetPower 0.102533
encoder.go:131: 2024-06-05T15:22:11.780-0400	INFO		fake/encoder.go:131	speed 1025.3337999999999, update rate 100, position 1
encoder.go:131: 2024-06-05T15:22:11.881-0400	INFO		fake/encoder.go:131	speed 1025.3337999999999, update rate 100, position 2
encoder.go:131: …
```
> Change fake encoder's position calculations to use floats

- components/base/sensorcontrolled/sensorcontrolled_test.go
- components/base/sensorcontrolled/spin.go
updates the sensorcontrolled Spin to work using only angular velocity. 
Behavior was comparable to using an orientation movement sensor when using a viam rover(the spin undershoots by ~5-10 degrees). 
tested on the benchtop and on carpet, with all permutations of desired angle/angular velocity directions
ticket: https://viam.atlassian.net/browse/RSDK-7789
> [RSDK-7789] add angular velocity only Spin to sensorcontrolled base

- services/datamanager/builtin/capture_test.go
- services/datamanager/builtin/file_deletion_test.go
I hand tested this by changing the number of files we needed to see before moving on. This is the sample output:
```
capture_test.go:392: 2024-05-21T16:29:45.356-0400	INFO		builtin/capture_test.go:392	waitForCaptureFilesToEqualNFiles diagnostics after 10 seconds of waiting	{"numFiles":4,"expectedFiles":5}
capture_test.go:394: 2024-05-21T16:29:45.357-0400	INFO		builtin/capture_test.go:394	File information	{"idx":0,"name":"2024-05-21T16_29_35.343210622-04_00.capture","size":203}
capture_test.go:394: 2024-05-21T16:29:45.357-0400	INFO		builtin/capture_test.go:394	File information	{"idx":1,"name":"2024-05-21T16_29_35.34433745-04_00.capture","size":111}
capture_test.go:394: 2024-05-21T16:29:45.357-0400	INFO		builtin/capture_test.go:394	File information …
```
> RSDK-7703: Grab more diagnostics in TestFilePolling files on disk.

- robot/client/client.go
- robot/impl/local_robot.go
- web/server/entrypoint_test.go
[RSDK-7829](https://viam.atlassian.net/browse/RSDK-7829): `TestShutdown()` failure in `entrypoint_test.go`
* This test was previously flaky because the client would send a `ShutdownRequest` and the `ShutdownResponse` was not guaranteed to make it back as the robot and server shutdown, potentially throwing a variety grpc errors.
* To fix this, `Shutdown()` returns `nil` if it recieves `nil` or a grpc error with one of the following codes: `Unavailable`, `Internal`, or `Unknown`. 
* These were decided based on the potential circumstances that may occur at shutdown described by the [grpc error code docs](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)
* This is unavoidable; we cannot guarantee a non-error response will be returned, and depending on shutdown timing and the state of …
> RSDK-7829: Make shutdown error handling more robust

- .github/workflows/docker.yml
- .github/workflows/test.yml
- test new runners with docker.yml arm jobs + `test32` job
Test new infra
- successful docker.yml run [here](https://github.com/viamrobotics/rdk/actions/runs/9405587339)
> move overnight + test32 jobs

- .github/workflows/docker.yml
- .github/workflows/test.yml
Revert 6a16992c -- mkdir denied.
Error was:
```
FAIL	go.viam.com/rdk/vision/objectdetection	0.287s
2024-06-07T23:32:10.678Z	FATAL	ext/verify.go:49	error opening artifact	{"error": "mkdir /rdk/.artifact/cache: permission denied"}
FAIL	go.viam.com/rdk/vision/segmentation	0.405s
2024-06-07T23:32:15.148Z	FATAL	ext/verify.go:49	error opening artifact	{"error": "mkdir /rdk/.artifact/cache: permission denied"}
FAIL	go.viam.com/rdk/web/server	0.391s
```
> revert CI runner change

- robot/client/client_test.go
- robot/impl/local_robot_test.go
- robot/impl/resource_manager_test.go
- robot/impl/robot_reconfigure_test.go
- robot/robot_test.go
- services/baseremotecontrol/builtin/builtin_test.go
- testutils/resource_utils.go
- testutils/slices.go
Follow-up to https://github.com/viamrobotics/rdk/pull/3996 - add a generic testing functionality that verifies is two slices of comparable elements have the same elements without considering order. This ends up removing a lot of boilerplate from resource tests.
> RSDK-2670 Testing QOL: add generic unordered list comparison

- logging/net_appender.go
- logging/net_appender_test.go
- when NetAppender is given a shared connection, don't try to close it
- add `remoteLogWriterGRPC.clientIsShared` field to support this behavior
In #4039 we added the ability to give NetAppender a shared connection. That (predictably, in retrospect) breaks cleanup because it's essentially a weak ref.
Specifically, this prevents 'unchecked error' / 'the client connection is closing' errors on shutdown when NetAppender is used in viam-agent.
Could add a `newRemoteLogWriterGRPC` constructor to encapsulate this logic, rather than doing it in NewNetAppender? But remoteLogWriterGRPC is internal so I'm fine leaving it as-is for now
> don't double-close when NetAppender uses shared connection

- config/module.go
- config/module_test.go
- module/concurrent_reconfigure_test.go
- module/modmanager/manager.go
- module/version_reconfigure_test.go
- robot/packages/cloud_package_manager.go
- robot/packages/cloud_package_manager_test.go
- robot/packages/utils.go
- utils/file.go
- utils/file_test.go
- EvaluateExePath changes:
- **main change**: support meta.json inside tarball
- error when ExePath isn't an abs path. Currently relative paths are undefined behavior (they will be relative to working directory), this turns them into an error. ( :warning: reviewers, check me on this)
- move SafeJoinDir to common utils + use it in a few places
- (incidental) parseJSONPath helper
- Currently local tarballs require a meta.json file *next to* the tarball. This is 1) awkward and hard to explain to people, and 2) makes it hard to use these. For example, what if you want two local tarballs in the same directory? They end up sharing a meta.json, which may be a non-starter.
- Embedded meta.json makes it easier to copy local tarballs around, which benefits android + remote reloading …
> RSDK-7831 support meta.json inside tarball

- module/module_interceptors_test.go
RSDK-7869: Test Goroutine leak due to not closing robot at end of test
* Closes robot at end of test
> RSDK-7869: Close robot at end of TestModuleClientTimeoutInterceptor

- robot/client/client.go
slight change to behavior, but I think logs for successes should be fairly silent, especially if this is a library users will be interacting with. 
If shutting down successfully is something they want to log, they can, but we shouldn't force it on them in the Info level.
also changed one of the logs to break out of the switch so we're not repeating the log, happy to change back though
> Change shutdown success line to Debug

- robot/framesystem/framesystem.go
Too much logging space was being taken up by empty tables.  Now when there is a reconfigure and nothing in the frame system service, we will get a log message such as 
```    framesystem.go:190: 2024-06-12T10:17:57.588-0400    DEBUG           framesystem/framesystem.go:190  reconfigured robot frame system: empty frame system```
> make frame system reconfiguration quieter when it is empty

- components/motor/gpio/encoded.go
- components/motor/gpio/mathutils.go
https://viam.atlassian.net/browse/RSDK-7739
small pr to help clean up encoded motor. This one changes encoded motor to read from the encoder directly, along with a few other smaller changes
> [RSDK-7739] remove unexported position function from encoded motor

- services/datamanager/builtin/builtin.go
I was able to reproduce the hang with a unittest that is attached in patch form to [DATA-2664](https://viam.atlassian.net/browse/DATA-2664). Unfortunately that leverages a [timely sleep](https://github.com/viamrobotics/rdk/blob/538896b370593c3b24071be5a7a88665d762c033/services/datamanager/builtin/builtin.go#L651-L652) to open a hole for the deadlock to form.
[DATA-2664]: https://viam.atlassian.net/browse/DATA-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DATA-2664: Unlock the datamanagement lock prior to waiting for background sync workers to drain.

- components/motor/gpio/controlled.go
- components/motor/gpio/encoded.go
- components/motor/roboclaw/roboclaw.go
https://viam.atlassian.net/browse/RSDK-7890
turns out only 3 drivers were missing this logic, so thats nice
> [RSDK-7890] ensure all motor drivers ignore rpm sign in GoTo

- testutils/robottestutils/robot_utils.go
- web/server/entrypoint_test.go
RSDK-7881: Refactor Shutdown to use actual robot client
* This PR refactors the `Shutdown()` integration test to use the actual robot client so that we don't have to maintain two different sets of expected errors between the test and the actual client.
> RSDK-7881: Refactor Shutdown to use actual robot client

- .artifact/tree.json
- services/vision/mlvision/ml_model.go
- services/vision/mlvision/ml_model_test.go
This will skip over blank lines in label files so that label strings do not accidentally get assigned the empty string
> RSDK-7106: Ignore blank lines in label files

- module/modmanager/manager.go
- robot/impl/local_robot.go
- robot/impl/local_robot_test.go
RSDK-7034: RDK panics when renaming a local module
* This bug occurs because when a module is renamed, it is a part of `conf.Added.Modules`, so when calling `updateResources()` during reconfiguration, components with the same API end up being registered twice (since it is not truly a newly added module) causing a panic. 
* In order to fix this, we remove resources marked for removal first before attempting to update resources.
* Before, we attempted to update resources then remove resources marked for removal.
* Log output on module rename now: 
src="https://github.com/viamrobotics/rdk/assets/93689852/5fece4b7-5b5c-4c69-9c34-8dd44b0a0935">
> RSDK-7034: Fix Panic when Renaming Modules

- logging/logging.go
- robot/impl/resource_manager_test.go
Output: https://gist.github.com/dgottlieb/9586d819b17313e6af00b78af79d2834
with an accidental debug line of:
```
Outputting logs. All: 52
```
> RSDK-7917: Only output `TestReconfigureParity` logs on failure.

- services/datamanager/builtin/builtin.go
- services/datamanager/builtin/file_deletion_test.go
- services/datamanager/builtin/sync_test.go
- services/datamanager/datasync/noop_sync.go
- services/datamanager/datasync/sync.go
hey yall, this PR is to change how go funcs are handled by sync and datamangement. 
**Implementation**
The big change here is now when we call .sync from builtin, it ONLY sends a filepath on a channel. It does nothing else. Sync has a global channel that all paths are sent to. On sync initialization it makes go funcs that pull from that channel. The number of go funcs is equal to the configured max sync threads. 
The big change is that we've decoupled sync from the datamanger loosely speaking. On reconfigure or close, the context in sync is cancelled, the threads exit after syncing their current file, and are recreated correctly. 
**Testing**
this is where I will need yalls help @n0nick @tahiyasalam . I have not tested how the changes in builtin.go affect scheduled sync or on large dirs. …
> DATA-2703 Fix oom

- services/motion/builtin/builtin_utils_test.go
- services/motion/builtin/move_request.go
- services/slam/fake/slam.go
- services/slam/fake/slam_test.go
- services/slam/slam.go
https://viam.atlassian.net/browse/RSDK-7847
had a user that ran into some issues when trying to use SLAM, and one of them was that they were trying to use motion while in mapping mode. 
While normally that shouldn't be a huge issue, since cartographer can take a pretty long time to send maps while in mapping mode it ends up being a poor user experience when using motion on mid/large sized maps. 
this pr adds a check for motion to only use localization mode, but I want to make sure I'm not breaking anything else by doing this change. I could also special case this check to only validate the mode with cartographer by looking at the internal state file if that makes things easier.
> [RSDK-7847] only allow motion to use slam in localization mode

- web/server/entrypoint.go
processConfig uses incoming config for debug and enableWebprofile while reconfiguring the robot
> Fix processConfig not updating debug or enableWebprofile 

- module/modmanager/manager_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-7666)
Using the in memory logger doesn't trigger go test to panic if it logs after the test terminates due to pion bugs.
> RSDK-7666 - fix log after test termination flake

- go.mod
- grpc/shared_conn.go
- grpc/shared_conn_test.go
- module/module.go
- services/sensors/client.go
- services/sensors/server.go
- services/sensors/server_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-7923)
Original intent when we added WebRTC connection support between a module & a viam-server is to support sending webrtc track data from the module to the viam-server. We assumed the loopback address would always be used. Testing found that frequently one or the other peer bind to a non loopback interface. This change makes it so that the viam-server & module will both only allow candidates from the other which are on the loopback interface.
Manual Testing:
> RSDK-7923 - fix WebRTC connections between a viam-server and a module can involve non loopback interfaces

- services/datamanager/datasync/sync.go
Useful feedback when changing the sync configuration.
> Change max_sync_threads from debug log to info log

- resource/name.go
- resource/name_test.go
- robot/web/web.go
- robot/web/web_c.go
- robot/web/web_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-7403)
This splits out the additions of some resource functions / methods for handling SDP names (which are self contained) from https://github.com/viamrobotics/rdk/pull/3957
Needed to DRY up the linked PR
> RSDK-7403 - add sdp methods to resource

- web/frontend/src/components/vision/index.svelte
Instead of requesting as many classifications as possible, just request the top 100. We decided on this change offline.
> Vision RC card: reduce max requested classifications to 100

- Makefile
- tools/tools.go
Forgot to import the `stringer` package and set `PATH` correctly.
Follow-up to https://github.com/viamrobotics/rdk/pull/4075, which introduced a code generation step to stringify enums via the [stringer tool](https://pkg.go.dev/golang.org/x/tools/cmd/stringer).
* Ran `make generate-go` in canon shell on amd64 and arm64 containers.
> Fix generate-go command

- .github/workflows/releasecandidate.yml
- .github/workflows/trigger-networking-tests.yml
* **RSDK-7885:** Run Networking Tests on release Candidate
* See [this pr](https://github.com/viamrobotics/sdk-integration-tests/pull/35)
* On RC build and upload success, sends an event to sdk-integration-test repo which triggers Networking Tests workflow for rc builds
* Running this command will trigger Networking Tests in the `sdk-integration-tests` repo:
```shell
gh api \       
-X POST \
-H "Accept: application/vnd.github+json" \
/repos/viamrobotics/sdk-integration-tests/dispatches \
-f event_type=new_rc_branch
```
> RSDK-7885: Send Event to Run Networking Tests on Release Candidate

- components/motor/gpio/encoded_test.go
ticket: https://viam.atlassian.net/browse/RSDK-7937
before the fix, the `"encoded motor test SetPower interrupts GoFor"` would fail ~1 in 1000 runs due to a motor power being set by GoFor after the context was canceled (via `Cancelrunning` and` makeAdjustmentsDone()`). 
when I got the context to be canceled, the injected motor was still handling the setpower call. Adding a check to the injected motor to see if the context was canceled fixed this. 
after the fix, I could not repro in 40k runs
testing command `/opt/homebrew/bin/go test -timeout 100s -count 1000 -run ^TestEncodedMotor$/^encoded_motor_test_SetPower_interrupts_GoFor$ go.viam.com/rdk/components/motor/gpio`
> [RSDK-7937] update injected motor to check for context canceled

- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/testmodule/main.go
The RDK server hangs and cannot process requests while it tries to load a module with a fatal bug (e.g. syntax error, immediate panic). This PR tries to detect if a module cannot start due to such an error and aborts loading to unblock the RDK.
* See https://github.com/viamrobotics/rdk/pull/4090#issuecomment-2180710730
> RSDK-7721: Fix bad module startup hang

- resource/graph_node.go
Change log levels to only warn if resource nodes transition to a new unexpected state. Self-transitions are a common and possibly not a problem, so log those at the debug level to cut down on noise.
> Reduce logging: downgrade resource state transition logs to DEBUG

- .github/workflows/releasecandidate.yml
- .github/workflows/trigger-networking-tests.yml
* **RSDK-7885:** Run Networking Tests on release Candidate
* See these PRs:
*  [This PR](https://github.com/viamrobotics/sdk-integration-tests/pull/35)  modifies `Networking Tests` workflow to be able to be triggered by `new-rc-branch` events sent by remote repositories
* [This PR](https://github.com/viamrobotics/rdk/pull/4083) creates a new workflow in the RDK which sends a `new-rc-branch` event to the `sdk-integration-tests` repo which triggers the `Networking Tests`
* This final PR makes a workflow-call from the RC workflow to the `trigger-network-tests` workflow triggering `Networking Tests` in the  `sdk-integration-tests` repo
You can manually run the "Trigger Networking Tests in sdk-integration-tests" workflow from the Actions tab and see that `Networking Tests` will be triggered in …
> RSDK-7885: Call networking tests trigger workflow in rc workflow

- .github/workflows/releasecandidate.yml
- .github/workflows/trigger-networking-tests.yml
[This PR](https://github.com/viamrobotics/rdk/pull/4115) added a job to trigger networking tests after building a new rc version. Somehow missed this Actions error:
```
[Invalid workflow file: .github/workflows/releasecandidate.yml#L74](https://github.com/viamrobotics/rdk/actions/runs/9617360229/workflow)
invalid value workflow reference: no version specified
``` 
which is due to using `./trigger-networking-tests.yml` as the job path instead of `./.github/workflows/trigger-networking-tests.yml`
> RSDK 7885: Fix Job path Syntax

- components/board/genericlinux/board.go
- components/board/genericlinux/board_test.go
- components/board/genericlinux/gpio.go
Not tested on hardware yet, will do that Monday.
The biggest change is that each GPIO pin has its own way to track goroutines, rather than reusing the board's one. I think this is a good move: it helps each struct be more self-contained and easier to reason about.
The second-biggest change is that every time we stop a software PWM loop, we call `StoppableWorkers.Stop()`, which means that next time we want to start it up again, we need to create a new one. Again, I think this is a good move, but that's why this isn't a 10-line PR.
> Use StoppableWorkers in genericlinux

- components/movementsensor/gpsutils/cachedData.go
- components/movementsensor/gpsutils/i2c_data_reader.go
Without this change, between a third and half of the NMEA sentences received over I2C had checksum errors. With this change, I haven't seen any! 
It turns out that sometimes, the chip will set the most significant bit of a byte it sends us. However, we expect all the data to be ASCII (which never sets the most significant bit), so we'd ignore those characters, and then we'd get NMEA sentences that are 1 character too short, and whose checksum doesn't match. Every example I looked at, if you just ignore the most significant bit of the problem byte (but keep the other 7 bits!), everything else lines up perfectly. So, that's the change I made.
Tried on piworld with a gps-nmea component.
> [RSDK-7081] Fewer checksum errors in I2C NMEA parsing

- config/proto_conversions.go
- config/proto_conversions_test.go
- module/testmodule/main.go
- robot/impl/resource_manager_modular_test.go
**[RSDK-7942:](https://viam.atlassian.net/browse/RSDK-7942)** Reconfiguring cloud robot's services' log levels does not propagate
* This bug occurs because the `ServiceConfig` message does not have a `LogConfiguration` field, so when converting proto objects to an actual config, the logging configuration is never properly set on a reconfiguration. [This PR](https://github.com/viamrobotics/api/pull/519) adds adds a `LogConfiguration` field to the `ServiceConfig` message so that data is actually captured and can be used to propagate log level changes. 
* This PR modifies `ServiceConfigFromProto` such that it attempts to read the log configuration level for the service from the proto configuration object and sets it in the service's actual config (just like`ComponentConfigFromProto`).
* Also …
> RSDK-7942: Include LogConfiguration field to ServiceConfig proto conversions

- logging/net_appender.go
- logging/net_appender_test.go
- web/server/entrypoint.go
- add `NetAppender.SetConn` method which can replace the underlying connection after the NetAppender has been instantiated
- add `sharedConn` bool which prevents NetAppender from creating its own connection
- ~add shutdownIters param so agent can shut down more quickly when offline~
This is a follow-up to adding NetAppender to viam-agent.
We want to:
- share viam-agent's existing grpc connection with the logger (this already happens)
- wait for that connection, but instantiate the NetAppender at the top of `main()` so it is copied to subloggers
- capture log messages from before the connection is available
`SetConn` lets us do the 2nd + 3rd bullet.
1. I've changed the NetAppender constructor. will this break compatibility with anything outside RDK? should I create a second constructor …
> APP-5330 NetAppender.SetConn and sharedConn

- web/frontend/src/components/vision/index.svelte
The vision service card doesn't support classifications. This adds a banner saying that it's not supported while we are working on the new vision service card.
> Add disclaimer about classifications in the vision service card

- services/datamanager/builtin/file_deletion.go
- services/datamanager/datasync/sync.go
Logging the files that were successfully deleted would help debug potential file corruption or sync issues.
> added some logging

- robot/impl/local_robot.go
there are too many, reducing to only log if changes detected or if it was triggered by a remote
> Reduce config ticker logs

- .github/workflows/releasecandidate.yml
- .github/workflows/trigger-networking-tests.yml
RSDK-7999: Fix RC Integration Tests download url
* Networking Tests triggered by new RC will currently always fail because it is not downloading a valid URL for an RC build, since their build names also include a version and rc number. 
* This PR adds in parameters for `version` and `rc_number` to `trigger-networking-tests.yml` which are passed within the curl to trigger Networking Tests.
* [This PR](https://github.com/viamrobotics/sdk-integration-tests/pull/38) modifies the Networking Tests workflow to handle these inputs and download the RC building with the correct URL
* On RC Build workflow, a new job is added to extract versioning from the branch tag and passes those parameters into the `run-sdk-integration-networking-tests` job, completing the automation flow. 
* Tested regex to …
> RSDK-7999: Parameterize RC Build & Networking Tests trigger job on RC version and number

- components/board/board.go
- components/board/digital_interrupts.go
- components/board/gpio_pin.go
Add code samples to Board API GO methods, for:
- `Board` API itself
- `Analog` API
- `GPIOPin` API
- `DigitalInterrupt` API
Code samples sourced from live docs.viam.com reference page: https://docs.viam.com/components/board/#api
> DOCS-2089: Add board API code samples

- logging/level.go
- logging/logging_test.go
[Jira Ticket](https://viam.atlassian.net/browse/RSDK-7933)
fixed an issue where the string input might be `warning` instead of `warn`.
> RSDK-7933: fix logging bugs

- cli/client_test.go
- logging/logging.go
- module/modmanager/manager_test.go
- robot/impl/resource_manager_test.go
Fix a flaky test failure related to [logging after a test completes](https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/testing/testing.go;l=1674-1679) by using a `MemLogger`, which suppresses logs unless a test fails for other reasons. This particular log is written [by a goroutine in the pion webrtc library that we cannot wait on](https://github.com/pion/webrtc/blob/a868a14ec8196a58bf064e33ba00dd3e259c36e8/datachannel.go#L330).
* Change `NewInMemoryLogger` to return a `MemLogger` that automatically outputs on test failures.
* Update CLI test helpers to automatically close robots created for testing.
Reproduce the data race with the following patch to https://github.com/viamrobotics/goutils and ensure that the change this PR resolves the data race.
```diff
diff --git …
```
> RSDK-7803 fix pion log after test "data race" (log goleak)

- components/movementsensor/gpsrtkserial/gpsrtkserial.go
- components/movementsensor/gpsrtkserial/gpsrtkserial_test.go
This is hopefully super easy to review commit-by-commit. 
It turns out that the `rtkSerial` struct had `lastposition` and `lastcompassheading` fields in it that were never set in production, while the `cachedData` struct had similarly named fields that were set instead. The fields _were_ set only during tests, and although I think I've got the tests working correctly, that part could use extra scrutiny.
No behavioral changes are intended; I'm just removing dead code.
> Remove unused fields

- components/encoder/single/single_encoder.go
Also, make `start()` a private function, so you can't get into trouble by someone building one of these structs and calling `.Start()` on it multiple times.
Not tried on actual hardware yet, will do that next week.
> Use StoppableWorkers in the single-line encoder

- robot/client/client.go
- robot/client/client_test.go
[RSDK-6811](https://viam.atlassian.net/browse/RSDK-6811): return foreign resource when client registration doesnt exist
- we now return foreign resources as resource clients for unregistered API's, so that modular resources may have arbitrary dependencies and still configure.
[RSDK-6811]: https://viam.atlassian.net/browse/RSDK-6811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-6811: return foreign resource when client registration doesnt exist

- cli/module_registry.go
Remove temp directory (not just contents) after starting a fake module manager as part of the `viam module update-models` command.
> Delete temp directory after running CLI command

- cli/auth.go
- cli/client.go
- cli/config.go
errors are now more like
`Error: Failed to parse cached config. Please log in again.`
If cached config fails to parse for any reason, cache gets removed.
The current logic already logs users out if their token is expired, just made the message clearer
These changes do hide the actual error in a few cases, but I think it'll make the experience more smooth since it's clearer what the next action should be
> APP-5082 - Better errors when token expires

- config/logging_level.go
- web/cmd/directremotecontrol/main.go
- web/cmd/droid/droid.go
- web/cmd/server/main.go
- web/server/entrypoint.go
[RSDK-8095](https://viam.atlassian.net/browse/RSDK-8095): rename robot_server loggers to rdk
- Renamed all instances of loggers with name `robot_server` to `rdk`
[RSDK-8095]: https://viam.atlassian.net/browse/RSDK-8095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-8095: rename robot_server loggers to rdk

- .github/workflows/staticbuild.yml
- set flag to use node16 in antique builds
actions/checkout suddenly started using node20 which added a GLIBC 2.28 dependency (see https://github.com/actions/checkout/issues/1809).
This is fine for us in most places, but our compatibility build is intentionally on an old linux that has old GLIBC.
Here, works:
https://github.com/viamrobotics/rdk/actions/runs/9845816473/job/27182189699
At some point node16 will be removed and we'll need to find a new option, probably overwriting the runner's node20 dist on start.
> RSDK-8116 allow node16 in antique

- .github/workflows/trigger-networking-tests.yml
* In the job run, you can observe that the RC version parameters were accepted just fine, but the variables `github.event.inputs.version` and `github.event.inputs.rc_number` did not populate correctly. 
* Since inputs were explicitly defined at the header of the workflow, they should be accessed using `inputs.<variable-name>` to be interpolated properly. https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/
> Use correct GH Actions Input Syntax for Networking Tests Trigger Job

- cli/app.go
- cli/ml_training.go
This allows us to specify the URL for a training script on upload. Corresponding app PR [here](https://github.com/viamrobotics/app/pull/5209)
If you use the following two commands, we can see the URL is successfully added to the registry item.
- `go run cli/viam/main.go --base-url=https://pr-5209-appmain-bplesliplq-uc.a.run.app/ login`
- `go run cli/viam/main.go training-script upload --org-id=83a4ce23-c0a5-4104-9e72-6148451fb0d7 --path=cli/module.tar.gz --script-name=test-upload-with-url --url=app.viam.com`
> DATA-2692 - Allow URL specification on upload

- cli/app.go
- cli/data.go
- cli/dataset.go
This new CLI commands allows a user to create a dataset file, where the file is formatted in the same way that's expected by the custom training script interface. This will allow a user to locally test parsing a dataset file and ensuring that their model compiles when writing training scripts. 
I manually tested a variety of scenarios and then used the dataset file as input to a training script. I tested with base command
`go run cli/viam/main.go dataset download --destination=test-download --dataset-id=6515b637a420eb685e988e84`
- with include-jsonl set to true, false, and unspecified which downloads the data as well the dataset, just the data, and just the data, respectively
- with parallel downloads set to 50, 100, and unspecified which works as implied
> DATA-2677 - Allow user to create dataset file from exported data for local testing of custom training scripts

- services/datamanager/builtin/builtin.go
- services/datamanager/builtin/capture_test.go
- services/datamanager/builtin/file_deletion_test.go
- services/datamanager/builtin/sync_test.go
- services/datamanager/datasync/sync.go
Bandaid fix for: https://viam.atlassian.net/browse/DATA-2728?focusedCommentId=31943
1. Change datamanager to call Close() on itself if Reconfigure returns an error
2. Change datasync to config changes to be processed after Reconfigure so that datamanger can boot successfully if viam-server starts while offline
I tested this with a custom sensor I wrote that records the number of times Readings has been called & the current time when the Readings method was called. This allowed me to confirm that data capture captured data at the configured interval (once a second) and that no sensor readings were dropped.
1. Booted a Pi with a viam-server built from this PR with an internet connection & the config below. Collected data for a few minutes. Unplugged pi from internet. Let run for a few …
> [DATA-2728] close datamanger if reconfigure fails and tolerate booting offline

- services/motion/builtin/builtin.go
The initial low angular velocity meant that turning radii were too large to easily course correct
> Update default rotational velocity in motion

- config/config.go
- config/log_config.go
- config/log_config_test.go
[RSDK-8087](https://viam.atlassian.net/browse/RSDK-8087): add utils for updating logger registry
`log_config.go`: 
- Stores the type for LogPatternConfig
- UpdateLoggerRegistry function, that returns a new registry map with any updates after reading in the new log config.
`log_config_test.go`:
- test valid pattern match strings
- test registry updates are as we expect
`config.go`:
- added LogPatternConfig as a field to each config struct
Note: Did not take into account the log configuration for resources, and did not use these utils meaningfully yet. Will do so in a subsequent PR.
[RSDK-8087]: https://viam.atlassian.net/browse/RSDK-8087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-8087: add utils for updating logger registry

- control/pid.go
I think there's probably a better place for this in the motor/sensor-controlled base setup code, but I can't immediately find it. We're relying on this log to surface the calculated gains. It's an okay stop-gap for the immediate future that we can remove when we store the gains in the controlled components' states.
> Add info log instruction to add pid gains manually after completing a control loop tuning

- components/movementsensor/gpsnmea/component.go
- components/movementsensor/gpsrtk/gpsrtk.go
- components/movementsensor/gpsutils/cachedData.go
- components/movementsensor/gpsutils/nmeaParser.go
Turns out we were using `sats_in_view `wrong. `sats_in_use` is used to calculate position and measure fix type. `sats_in_view` is the number of satellites visible to the receiver and it may or may not use it for positioning. 
I added some comments in the code to clarify the difference between the two and surfacing `sats_in_use` in sensor reading which is what we need to determine the fix type
> Rsdk-8155: adding sats in use to sensor reading

- components/movementsensor/gpsrtk/gpsrtk.go
- components/movementsensor/gpsrtk/pmtk.go
- components/movementsensor/gpsrtk/serial.go
- components/movementsensor/gpsutils/cachedData.go
- components/movementsensor/gpsutils/nmeaParser.go
- components/movementsensor/gpsutils/ntrip.go
- components/movementsensor/gpsutils/vrs.go
was quicker to make a new branch instead of fixing merge conflicts. previous pr was [here](https://github.com/viamrobotics/rdk/pull/4105) 
this PR  adds support for VRS for a gps rtk that is configured for i2c. This was done by adding the GGA message to cached data. In addition, this pr adds a `io.TeeReader` when connecting to a VRS, which allows the gps to get a rtk fix. 
other parts of the code include some small amounts of cleanup and making a function for a chunk of code that was used in multiple spots(`g.getStream`)
tickets: 
vrs with i2c https://viam.atlassian.net/browse/RSDK-5768
low fix with vrs https://viam.atlassian.net/browse/RSDK-8035
> [RSDK-5768][RSDK-8035] enable gpsrtk with pmtk to use vrs and write correction data to the gps when using vrs

- config/log_config.go
- config/log_config_test.go
When matching a dynamic regex to a logger name, we want to make sure that the full logger name matches the pattern, not just a subsection of it.
> ensure an exact pattern match for loggers

- components/movementsensor/gpsrtk/gpsrtk.go
- components/movementsensor/gpsrtk/pmtk.go
- components/movementsensor/gpsrtk/serial.go
The slow part of constructing a component was connecting to the NTRIP caster. So, I moved that to the start of the background goroutine, rather than the constructor. Now, the constructer is nice and fast again.
Tried on john-pi: both the serial and I2C components start up in less than a second! 
While I was at it, I renamed `closePort()` to `closeCorrectionWriter()`, which I thought was a clearer name. That part is unrelated to the rest, and I can undo that again if you prefer.
Justification for why it's okay to move `connectToNTRIP()` to the goroutine:
- `connectToNTRIP()` initializes `g.reader`. That field is only used in `receiveAndWriteCorrectionData()`, which comes later in the goroutine. It is not used elsewhere, so initializing it after we're done constructing the component is …
> [RSDK-8145] Speed up RTK construction

- web/frontend/src/components/remote-control-cards.svelte
- web/frontend/src/main-lib.ts
This exposes some props to allow us to do an incremental rollout of the new control tab.
- Do these props and this pattern make sense? Think about using this using `isInternalEnv` in App
- Check that the if statements are correct (it would be so bad if I accidentally turned off cards for a particular subtype)
> APP-5484: add props to disable cards for subtypes

- grpc/shared_conn.go
- grpc/shared_conn_test.go
- logging/impl.go
- logging/logger_manager.go
- logging/logger_manager_test.go
- logging/logging.go
- module/module.go
- web/cmd/directremotecontrol/main.go
- web/cmd/droid/droid.go
- web/cmd/server/main.go
RSDK-8088: Build registry of loggers in RDK
* This PR creates a `loggerRegistry` type and global variable which maintains a bidirectional map between logger names and loggers, as well as functions to register logger, retrieve them (either by the log object itself or name), and update their log levels. 
* All RDK loggers that get created now get registered into this data structure.
* Also converts loggers in `shared_conn.go` that don't need to be zap loggers into RDK loggers, and renames loggers created on robot start up to `entrypoint` so as to not have a name collision with the `rdk` logger actually responsible for robot processes. 
* A simple test suite for various `loggerRegistry` methods and functionality.
> RSDK-8088: Create Logger Registry

- robot/impl/resource_manager.go
- robot/impl/resource_manager_test.go
RSDK-6256: Robot Leaks Connection to Remote
* Certain robot configurations can cause remote connections to leak due to the same remote being added twice causing two clients to be created despite one resource, thus one connection gets leaked.
* Also having a single remote robot configured and switching the remote between two robots up at different addresses will cause a connection to leak each time the address is changed.
* This leak is due to the fact that new robot clients are allocated every time a remote is configured, without checking if the old client exists and closing it.
* This PR checks the remote resource node for a client, and if it exists, closing it before creating a new one so the connection does not leak.
* A test `TestRemoteConnClosedOnReconfigure` for checking that remote …
> RSDK-6256: Robot Leaks Connection to Remotes

- robot/impl/local_robot_test.go
otherwise we were getting
```
logger.go:130: 2024-07-15T12:18:51.959-0400 ERROR   rpc/server.go:320       panicked while calling unary server method      {"error": "rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference", "errorVerbose": "rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference\ngo.viam.com/utils/rpc.NewServer.func1\n\t/Users/cheukt/go/pkg/mod/go.viam.com/utils@v0.1.84/rpc/server.go:320\ngo.viam.com/utils/rpc.NewServer.WithRecoveryHandler.func10.1\n\t/Users/cheukt/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/options.go:33\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom\n\t/Users/cheukt/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1 …
```
> Fix debug arm panic

- components/encoder/single/single_encoder.go
Thanks to @seanavery for noticing the problem! This is a follow-up to https://github.com/viamrobotics/rdk/pull/4147 Changes include:
- Every time we lock the mutex, do so at the very top of the function and then defer unlocking it immediately, instead of manually unlocking it later. This ensures that the functions that lock the mutex are atomic. 
- Lock the mutex on all public functions. This ensures that we can't get bogus readings by calling some public function at the same time that we're, say, reconfiguring the component.
- Don't call `Close()` from within `Reconfigure()`, to avoid deadlocks now that both are locking the mutex no matter what. All we really needed from `Close()` was stopping the `StoppableWorkers`, and that's easy enough to copy over.
- We were calling …
> Avoid race conditions in single-line encoder

- components/movementsensor/fake/movementsensor.go
- components/movementsensor/gpsnmea/component.go
- components/movementsensor/gpsnmea/gpsnmea.go
- components/movementsensor/gpsrtk/gpsrtk.go
- components/movementsensor/gpsutils/cachedData.go
- components/movementsensor/gpsutils/cachedData_test.go
1. Added a const values for the `commonReadings` map in `gpsutils`
2. Created `GetCommonReadings` function. This includes `satsInView,` `fixQuality` and `satsInUse.` 
3. Removed `ReadSatsInUse` function
> Rsdk-8170: Create commonReading for GPS 

- components/board/beaglebone/data.go
- components/board/customlinux/board.go
- components/board/genericlinux/gpio.go
- components/board/orangepi/data.go
- components/board/pi5/data.go
Setting 0 or 100% duty cycle as gpio output on pwm pins. Adds an error if calling getGPIO on one of these pins. Tested on the pi5 and beaglebone, works great!
> RSDK-8247 Implement gpio output as PWM in generic linux

- components/movementsensor/gpsnmea/component.go
- components/movementsensor/gpsnmea/gpsnmea.go
- components/movementsensor/gpsnmea/pmtkI2C.go
- components/movementsensor/gpsnmea/pmtkI2C_nonlinux.go
- components/movementsensor/gpsnmea/serial.go
This is a follow-up from https://github.com/viamrobotics/rdk/pull/4201. The `NmeaMovementSensor` interface was a closeable `MovementSensor`, except that `MovementSensor` is already closeable. So, remove the redundant interface.
Tried on piworld: works like normal.
> [RSDK_8225] remove redundant interface NmeaMovementSensor

- config/config.go
- config/proto_conversions.go
- config/proto_conversions_test.go
- config/reader.go
- config/reader_test.go
- logging/impl.go
- logging/log_config.go
- logging/log_config_test.go
- logging/logger_manager.go
- logging/logger_manager_test.go
- logging/logging.go
This change creates exported wrapper functions on the logger manager instance methods. This allows us to utilize these instance methods outside the logging package. After talking offline, it was decided that keeping the logger manager private but having publicly exposed functions that operate on the manager is the best approach. As a side note, I left the instance methods as is since they are used for testing.
**UPDATE**:
Now closes [this](https://viam.atlassian.net/browse/RSDK-8087) ticket. 
- Moved `log_config.go` and corresponding tests into the logging package. This reduces the likelihood of cyclic dependencies arising between the `logging` and `config` packages and localized the `UpdateRegistry` function near the registry code.
- `LoggerPatternConfig` now lives inside the `logging` …
> RSDK-8087: add wrappers over registry methods + resolve cyclic dependencies 

- components/movementsensor/gpsrtk/gpsrtk.go
- components/movementsensor/gpsutils/ntrip.go
I strongly recommend reviewing this commit-by-commit! A lot of this is refactoring, and only a small amount is actually changing behavior. 
The original plan for this ticket was that, once we get into the for loop in the background goroutine, we can reconnect to the caster, so before we get to the for loop, we should also reconnect to the caster if something goes wrong, rather than just logging that we're giving up on the caster entirely and exiting the goroutine. 
However, after the refactorings, it became very clear that, if reconnecting to the caster fails within the for loop, we do the exact same thing of giving up entirely and exiting, but we've been doing so _silently,_ which is why no one thought this was a thing! John, Susmita, and I have discussed, and decided that this is …
> [RSDK-8260] Be more explicit if we permanently give up on the NTRIP caster

- components/board/orangepi/data.go
Tested a handful of gpio pins on a local build with success.
> RSDK-8270: Add orangepi 2w pin mappings

- components/board/genericlinux/board.go
- components/board/genericlinux/board_test.go
- components/board/genericlinux/gpio.go
Thanks to @oliviamiller for helping debug this with me! 
Tried on an Orin Nano: I'm no longer able to deadlock the pins! (though admittedly it's possible I just haven't tried hard enough, and I should continue trying to deadlock them. but it used to be way easier to deadlock!)
The idea here is that we only start up the background goroutine to do software PWM once per pin at the very beginning, and that background goroutine mostly sits around waiting to be told to start doing things. It gets stopped only once, when the pin is `Close`d.
There are 2 new fields in the struct:
- `enableSoftwarePWM` is a bool, that should only be read or written when the mutex is locked. Set it to false to tell the software PWM goroutine to go back to waiting, and set it to true to tell that goroutine to …
> [RSDK-8345] prevent deadlock in software PWM loop

- motionplan/planManager.go
- motionplan/rrt.go
This managed to go unnoticed until now because we still broke the path up into small sub-waypoints, allowing rrt star to mostly approximate a linear path...except when it didn't.
This also fixes RSDK-8352 as a drive-by
> RSDK-8367 Fix bug preventing use of cbirrt when topological constraints are enabled

- .github/actionlint.yml
- .github/workflows/appimage.yml
- .github/workflows/docker.yml
- .github/workflows/motion-benchmarks.yml
- .github/workflows/motion-tests.yml
- .github/workflows/staticbuild.yml
- .github/workflows/test.yml
Switching runners to avoid long queues
Also, simplify our large-runner names to just "small" and "large" varients, rather than individual cpu counts.
> Switch runners to github.

- components/movementsensor/gpsrtk/gpsrtk.go
- components/movementsensor/gpsrtk/pmtk.go
- components/movementsensor/gpsrtk/serial.go
This gets rid of the race condition discussed in `Close()`. Everything still compiles and the linter is happy, but I haven't tried this out on actual hardware yet. Will do that Monday...
The biggest change in here is that `cancelCtx` is now a local variable only available within the background goroutine, so I've passed it as an argument to several helper functions that didn't need an argument before.
> Use StoppableWorkers in the GPS RTK component

- motionplan/ik/metrics.go
- spatialmath/pose.go
- spatialmath/pose_test.go
This fixes two issues with linear constraints. One, `ik.OrientDist` should have been an absolute value. Two, pose interpolation needed to ensure both orientations were in the same hemisphere.
> RSDK-8390 pose interpolation between orientations can take the long way around

- components/board/genericlinux/board.go
Oof, this was a silly mistake! Thanks to @susmitaSanyal for sticking to her guns and pushing on this. We missed it before because _renaming_ a pre-existing interrupt to a different name worked totally fine: it was only creating a _brand new_ interrupt named something other than its pin name that was a problem.
Tried on the Harun (rpi5) rover: without this PR, the board cannot configure itself because it `cannot create digital interrupt on unknown pin re`, and with this PR, the board configures and the board/motors/encoders/base work properly.
> [RSDK-8261] initialize new interrupts using the correct name

- web/frontend/package-lock.json
- web/frontend/package.json
- web/frontend/src/lib/components/collapse.svelte
This adds IDs to each RC card. By doing this, all cards (new and old) will have fragments we can link to, so we can show all resources in the sidebar in App.
> APP-5488: add IDs to rc cards

- components/motor/gpio/encoded.go
https://viam.atlassian.net/browse/RSDK-8358
if the user sets the RPM of an encoded motor to be too low, they are going to have a bad time. adding more logs when this occurs to try to make this clear
> [RSDK-8358] add error log for low speeds for encoded motors

- components/board/mcp3008helper/mcp3008.go
- components/board/pinwrappers/analog_smoother.go
Thanks to @mariapatni for her patience while we figured this out! The problem wasn't actually to do with reconfiguring a digital interrupt: on the raspberry pi, if you initialize a new analog reader while using arbitrary GPIO pins as the Chip Select for the SPI device, it deadlocked during reconfiguration!
- when initializing a `SmoothAnalogReader`, don't read from the device immediately (see below for why that's a problem). Instead, just start the background goroutine that will read from it when yo're supposed to. If you ask for values out of it before the goroutine has read anything, you get an error saying that we haven't read anything yet.
- the `lastData` field was not thread safe, so it's now an `atomic.Pointer` instead of a raw value.
Tried on a raspberry pi (with …
> [RSDK-7209] fix deadlock in analog reader initialization

- components/movementsensor/gpsnmea/pmtkI2C.go
- components/movementsensor/gpsnmea/serial.go
- components/movementsensor/gpsrtk/pmtk.go
- components/movementsensor/gpsrtk/serial.go
- components/movementsensor/gpsutils/i2c_data_reader.go
- components/movementsensor/gpsutils/serial_data_reader.go
I recommend reviewing this while suppressing whitespace changes; otherwise the diff is way bigger than it should be (60ish lines of code merely became less indented).
- `start()` in both the `PmtkI2cDataReader` and `SerialDataReader` classes has been renamed `backgroundWorker`, and no longer spawns a background goroutine (it's just the implementation of the code that should run in the background). 
- `gpsutils.NewI2cDataReader` takes in a context. Should `gpsutils.NewSerialDataReader` take in a context it doesn't use, just to keep consistency? I'm unsure.
- The background goroutines in both data readers check their context while trying to put data into the output channel. This greatly simplifies the implementation of `Close()`, because you don't need to read from the …
> Use StoppableWorkers in the GPS DataReaders

- components/camera/collectors.go
Hey yall, this PR is to change the default mime type from `image/vnd.viam.rgba` to `image/jpeg`. Based on queries in the binaryDB, JPEG is the most popular format for binary data and should be the default.
> DATA-2505 Implement default mimetype (change to JPEG)

- config/reader_test.go
- logging/log_config_test.go
- logging/logger_registry.go
- logging/logger_registry_test.go
- web/server/entrypoint.go
Issue: Suppose we had a registered logger named `a.b.c` that we configured to have the level `WARN`. Then, we removed this configuration option and reconfigured. The `a.b.c` logger will still be set to `WARN` despite not specifying this.
Solution: Any loggers that no longer have a configuration are reset back to `INFO`. Also, logger changes are applied only once, so there is no undefined behavior of logs during reconfiguration.
> reset logger level when config isnt present

- components/movementsensor/adxl345/adxl345.go
We don't actually use interruptChannels anywhere, so removing
> Remove unused field in adxl struct

- cli/module_reload.go
- clear `version` field when you run `viam module reload` and the module is already installed on the robot from registry
The backend refuses to serve type=local modules with a `version` field, causing this error in RDK:
```log
2024-08-06T18:20:13.260Z	ERROR	rdk	config/config.go:135	module config error; starting robot without module	{"name":"viam_python-example-module_from_reload","error":"Error validating. Path: \"modules.0\" Error: the version field is not permitted on local modules"}
```
Tested cases:
1. empty config, `viam module reload` creates a new module
2. config has module installed from registry, `viam module reload` overrides it successfully
> APP-5844 clear version in `module reload` when type=registry

- module/runtime.go
I've seen this pattern copied and pasted in module after module. Let's just make it a helper function, and then when you write a new module, your main function is a one-liner (or two-liner, if you have lots of models). 
Everything compiles and I'm fairly confident I've copied and pasted this correctly, but I haven't tried it out in detail yet. I want a second opinion before I go to the effort: is this worthwhile? Should I put it somewhere else instead? Should I get a third opinion?
If you think this is useful, I'll try it out and make sure it works as expected.
Examples of modules whose `main()` could be replaced by a call to this function: [1](https://github.com/mariapatni/pinctrl/blob/main/main.go) [2](https://github.com/viam-modules/viam-ultrasonic/blob/main/main.go) …
> make a standardized Main function for writing modules

- cli/module_build.go
- services/shell/server.go
- wrap EACCES with PermissionDenied in CopyFilesToMachine
- in CLI `viam module reload` command, show an instructional warning when the copy command returns PermissionDenied
In remote reloading, when we upload a tarball to the destination RDK, the shell copy files endpoint takes an absolute path. That's fine, except when RDK is not running as root; in that case we need to know the remote user. This manifests as a permission denied error (see red error line in screenshot).
In #4139, the remote reloading PR, we added a `--home` flag so the user can override this. Today's PR prints instructions to use the home flag when you hit the permission denied error.
The ideal solve here is to support `$VIAM_HOME`, `~`, or relative paths in the file copy service. (There's a chance relative paths …
> show instructions in `viam module reload` when the user hits the non-root destination issue

- cli/module_registry.go
- cli/utils.go
- cli/utils_test.go
- when validating a tarball, make sure the binary matches the desired platform (e.g. linux/arm64 vs linux/amd64). Warn if not
We've seen people upload binaries of the wrong architecture when first doing cross-platform work; this makes that situation slightly louder, to save debugging time
- I made it a warning rather than an error because I'm not sure how complete / correct the parser is. It's designed to fail silently unless the system is reasonably sure something is wrong.
- This is silent if someone is using a run.sh
- This is silent for 32-bit arm
(The yellow warning line is new).
> check OS + architecture of binary in `validateModuleFile`

- grpc/dial.go
- robot/client/client.go
Get the version from `robot.Version`: `viam_client:[go;dev-unknown;v0.1.330]` (`dev-unknown` is because there's local changes and will be the default.)
Tested by manually changing the `TAG_VERSION` in Makefile: `viam_client:[go;v1.2.3;v0.1.330]`
> RSDK-8307: get and send go sdk versions

- go.mod
- go.sum
Specifically, https://github.com/benbjohnson/clock/pull/54 addresses the manifestation we saw and https://github.com/benbjohnson/clock/pull/58 supposedly found a couple more spots a mutex was missed.
> RSDK-8149: Upgrade mock clock library to resolve its data race.

- motionplan/constraint.go
- motionplan/plannerOptions.go
Because arms, like bases, are wrapped in solverFrames, the solverFrame fills the interface in the type check for planner options, giving arms the wrong resolution.
Here we add a length check to confirm that PTG options are appropriate.
Additionally, we add a minimum number of steps to check between configurations, as having this acts as an additional safeguard against issues where large joint swings over small physical distances (+/- 360) were not being properly checked.
> RSDK-8536 Fix PTG frame check, and add a minimum step check count

- cli/app.go
- cli/client.go
Ticket: https://viam.atlassian.net/browse/RSDK-8437
Needed because the SolEng team needed to restart a part that was offline but the app ui doesn’t want to show a restart button for offline robots. See: https://viam.atlassian.net/browse/RSDK-8436 
Assigning to me because I did the initial impl to unblock the SolEng team.
However, if you don’t like this idea or this ticket (or think it needs scoping), feel free to say so and I will close the PR and the ticket.
Output:
```
➜  cli git:(main) ✗ viam robot part restart --machine e4713ae5-013a-43fe-800e-ff7959a8e3a0 --part 804a4a26-3b28-4f1b-9a7c-5cccc949aa32
Info: Request to restart part sent successfully
```
> RSDK-8437 - Viam robot part restart cli command

- components/motor/tmcstepper/stepper_motor_tmc.go
- components/motor/tmcstepper/stepper_motor_tmc_test.go
Surprise: although sending a packet on an SPI bus is already atomic (as enforced by the Linux kernel), reading a value from a TMC5072 stepper motor is _not_ atomic, because it requires sending multiple packets on the bus! and that means that we need an _extra_ mutex across all TMC5072 components, making sure that only one of them communicates with the chip at a time.
Specifically, you can only read the value you interacted with in the previous command. So, to read a value you send a read command and get back arbitrary data, and then you send the read command a second time, and get back the value you care about. but if, in between those two, another component sent some other command, your second read has something else in it! So, we add in a global mutex that all the TMC5072's can use, to …
> [RSDK-8526] Make communicating with the TMC5072 atomic

- services/vision/collector.go
Arush added a collector the vision service (info [here](https://docs.google.com/document/d/1HvqAnnIjKNyLn0y0DnskJQ4tF-PgaI7ywJAq6V356ig/edit)) to allow one to simultaneously capture images and annotations (labels, bounding boxes).
This is adding in the logic for the filter readings.
https://viam.atlassian.net/browse/DATA-2823
> DATA-2823 - Add logic in CaptureAllFromCamera to exclude readings from being captured

- components/board/client.go
- components/board/interrupt_stream.go
I recommend reviewing this commit-by-commit. 
My original plan was to move this to using a `StoppableWorkers`, so that we definitely shut down the background goroutine when we call `closeStream()` (right now, it cancels the context and returns without waiting for the goroutine to actually stop). However, this is trickier than I realized: the context that is canceled is _not_ descended from the background context: it's passed in as an argument and might be canceled by something else! So, this PR is some preliminary cleanup without using a `StoppableWorkers` yet.
No changes to behavior are intended. I haven't tried this out yet; will do that Mondayish.
> Tweaks to the interruptStream

- examples/customresources/demos/complexmodule/module.go
- examples/customresources/demos/multiplemodules/gizmomodule/gizmomodule.go
- examples/customresources/demos/multiplemodules/summationmodule/summationmodule.go
- examples/customresources/demos/rtppassthrough/myrtppassthrough.go
- examples/customresources/demos/simplemodule/module.go
All examples compile and the ones with makefiles run, but I haven't tried things out further than that (I haven't figured out how to send requests and get responses back). The intention here is that I've made a `ModularMain()` function (see https://github.com/viamrobotics/rdk/pull/4256) to avoid copying and pasting so much boilerplate when running modules, and we should encourage users to use it instead of copying and pasting boilerplate, too. 
Have I tagged the right people for this PR? Feel free to untag yourself if I've got this wrong.
How thoroughly would you like me to test this? Given that the code compiles and all the ones with a makefile run, I suspect I've done this right (if I have a bug, I'd expect it not to compile in the first place), but I'm willing to try it out more …
> use ModularMain in the example modules

- services/datamanager/builtin/file_deletion.go
- utils/diskusage/disk_usage.go
[Ticket](https://viam.atlassian.net/browse/DATA-2672)
This PR applies self-contained changes needed to refactor builtin data manage to be easier to unit test.
Here is the PR which is the final state:
https://github.com/viamrobotics/rdk/pull/4161
1. Changes diskusage.NewDiskUsage to be named diskusage.Statfs (the actual syscall used) and return an error if the sys call fails rather than swallowing it (as the current implementation does)
2. Change it to return a struct rather than a pointer to a struct with methods that need to be called to get the underlying values. This will make it easier to test how data manager behaves under different file system conditions without needing to set up those conditions in tests.
3. Delete all unused portions of the diskusage package 
4. Update callers and …
> [DATA-2672] simplify diskusage

- components/movementsensor/gpsnmea/pmtkI2C_test.go
- resource/config.go
Here's an example of the new error message:
```
2024-08-20T22:11:20.668Z	ERROR	rdk.resource_manager.rdk:component:board/b	resource/graph_node.go:288	resource build error: incorrect config type: NativeConfig expected genericlinux.Config but got *genericlinux.Config. Make sure the config type registered to the resource matches the one passed into NativeConfig	{"resource":"rdk:component:board/b","model":"rdk:builtin:pi5"}
```
> [RSDK-7731] more verbose error message when NativeConfig has an unexpected type passed in

- data/registry.go
- data/registry_test.go
- go.mod
- services/datamanager/builtin/builtin.go
[Ticket](https://viam.atlassian.net/browse/DATA-2672)
This PR refactors the data.registry.go 
Here is the PR which is the final state:
https://github.com/viamrobotics/rdk/pull/4161
1. Change data.CollectorLookup to return a `CollectorConstructor` rather than pointer to one (everywhere we used it we had to de-reference the pointer which defeats the point)
2. Remove the unused data.RegisteredCollectors
> [DATA-2672] refactor data registry

- rimage/transform/parallel_projection.go
`make full-static` passes on canon rdk-arm64
> parallel projection is OK to include in static builds

- .artifact/tree.json
- services/vision/mlvision/classifier.go
- services/vision/mlvision/detector.go
- services/vision/mlvision/ml_model.go
- services/vision/mlvision/ml_model_test.go
This allows a non-breaking alternative for loading label files. 
The vision service now has an optional field called "label_path" which will over-write the labels from the meta data from the ml model (if they were present).
@acmorrow FYI
> RSDK-4575: Add optional label path to vision service

- components/base/sensorcontrolled/sensorcontrolled.go
- components/base/sensorcontrolled/sensorcontrolled_test.go
- components/base/sensorcontrolled/velocities.go
https://viam.atlassian.net/browse/RSDK-8562
last week we realized that some controllers we use have poor performance at low velocities. Adjusting the control loop frequency is another way we can improve controller behavior. 
default frequency, set velocity 50 mm/s
high frequency, same PID
> [RSDK-8562] make control freq configurable

- cli/app.go
- cli/ml_training.go
This returns all the logs for a given training job id.
Tested with: `go run cli/viam/main.go train logs --job-id=66cce7012df448bf1e4b6b5d`
> Data-2818: Get training logs

- .artifact/tree.json
- services/vision/mlvision/classifier.go
- services/vision/mlvision/ml_model.go
- services/vision/mlvision/ml_model_mock_test.go
- services/vision/mlvision/ml_model_test.go
In order to eventually remove tflite-cpu from RDK, all tests that depend on tflite-cpu will need to be removed.
This PR replaces all tflite models used in the "mlvision" tests with mocked out versions that copy what the input and output tensors were for the tests. 
It also changes the text of some errors to be more descriptive
> RSDK-8629: mock out all tflite model services in vision service tests

- components/base/sensorcontrolled/movestraight.go
- components/base/sensorcontrolled/spin.go
- components/base/wheeled/wheeled_base.go
When running sensor_controlled base, I ran into the following error 
```
8/28/2024, 3:19:00 PM error rdk.resource_manager.rdk:component:base/sensor-controlled sensorcontrolled/movestraight.go:105 context canceled 
``` 
I didn't have any idea to why this error was occurring. After talking with @JohnN193 I understand that when we switch away from the UI this error is surfaced. There are also possibility of some other reason why the context was cancelled, which is why it is surfaced. 
- changed the error to a warning
- Added comments around the why we may wanna ignore it. 
- resurfaced the  warning in wheeled base.
> Making sense of the error

- components/movementsensor/imuvectornav/imu.go
This all compiles, but I don't know how to test it out on real hardware. I'm willing to do that if you think it's important, but my hope is the change is simple enough that we can skip it.
I don't think this PR actually fixes any bugs or race conditions: the old code looked right to me. but I also think the new version is simpler to reason about.
Github suggests that @dgottlieb should review this; if you disagree, feel free to remove yourself and add someone else.
> use StoppableWorkers in vectornav/imu

- components/movementsensor/imuvectornav/imu.go
The RDK `StoppableWorkers` no longer exists; we should use the goutils version.
> Use correct `StoppableWorkers` in imu code

- .gitignore
I use [this tool](https://direnv.net) sometimes to load per-project environment variables. Add to `.gitignore` for convenience.
> Ignore direnv

- go.mod
- bump go.mod min to 1.21.13
- netip vuln https://pkg.go.dev/vuln/GO-2024-2887
> bump min golang

- utils/value.go
- use testing.Testing() inside utils.Testing(), deprecate our wrapper
This is in the standard library now
> deprecate unneeded utils.Testing

- components/arm/arm.go
- components/base/base.go
- components/board/board.go
- components/camera/camera.go
- components/encoder/encoder.go
- components/gantry/gantry.go
- components/generic/generic.go
- components/gripper/gripper.go
* Links to main component docs from arm --> gripper
* Does the same in examples section everywhere except for generic bc no examples
> DOCS-2498: Link to main component documentation on RDK docs site

- components/gantry/singleaxis/singleaxis.go
- components/gantry/singleaxis/singleaxis_test.go
- remove error margin to allow gantry to move to 0
- return more logs and errors for frontend
> RSDK-8699: Cannot go to gantry position 0.0, only 0.2+.

- web/server/entrypoint.go
in cloud logs
```
9/9/2024, 3:47:21 PM info rdk impl/local_robot.go:1265 (Re)configuring robot
9/9/2024, 3:47:20 PM info rdk server/entrypoint.go:71 Viam RDK built from source; version unknown
```
in local logs
```
2024-09-09T19:47:20.974Z        INFO    rdk     config/logging_level.go:38      Log level initialized: info
2024-09-09T19:47:20.975Z        INFO    rdk     server/entrypoint.go:71 Viam RDK built from source; version unknown
2024-09-09T19:47:21.487Z        INFO    rdk     impl/local_robot.go:1265        (Re)configuring robot
```
if version flag (stdout)
```
2024-09-09T19:48:53.021Z        INFO    rdk     config/logging_level.go:38      Log level initialized: info
2024-09-09T19:48:53.022Z        INFO    rdk     server/entrypoint.go:71 Viam RDK built from source; version unknown …
```
> RSDK-8722 - Log RDK version to cloud

- robot/impl/local_robot.go
- robot/impl/local_robot_test.go
- testutils/resource_utils.go
Stop holding `resourceGraphLock` while fetching machine status from local robot, since this prevents users from seeing resources statuses while a robot is (re)configuring.
> RSDK-8701 Show configuring state through MachineStatus endpoint

- services/navigation/builtin/builtin.go
Explanation of the runtime error:
the nil pointer dereference happens when we called `paths, err := s.ns.Paths(ctx, nil)` (https://github.com/viamrobotics/rdk/blob/main/services/navigation/builtin/builtin_test.go#L1029)
Specifically, we query the `rawExecutionWaypoint` with `rawExecutionWaypoint := svc.activeExecutionWaypoint.Load()`  (https://github.com/viamrobotics/rdk/blob/main/services/navigation/builtin/builtin.go#L841).
The test expects the `rawExecutionWaypoint` to be nil or the `emptyExecutionWayPoint`, but it is not.
We then proceed further in the function and encounter the nil pointer dereference.
------------------------------------------------------------------------------------------
What **should** be happening:
Within `moveToWaypoint` we swap the `activeExecutionWaypoint` …
> RSDK-8372 - Test RuntimeError: go.viam.com/rdk/services/navigation/builtin.TestStartWaypoint/Reach_waypoints_successfully

- services/baseremotecontrol/base_remote_control.go
- services/datamanager/data_manager.go
- services/generic/generic.go
- services/mlmodel/mlmodel.go
- services/motion/motion.go
- services/navigation/navigation.go
- services/slam/slam.go
- services/vision/vision.go
* adds links back for all documented services besides frame system which afaik doesn't have API user could access
* adds at beginning and around method examples
> DOCS-2498: Add links back to main docs for services

- components/gantry/collectors.go
- components/gantry/collectors_test.go
Our API contract specifies mm units for [Positions](https://github.com/viamrobotics/api/blob/cba5f1e67aad798b42134a1a748199a2faef6bc7/proto/viam/component/gantry/v1/gantry.proto#L79) and [Lengths](https://github.com/viamrobotics/api/blob/cba5f1e67aad798b42134a1a748199a2faef6bc7/proto/viam/component/gantry/v1/gantry.proto#L112), so I was getting my data collected in units of micrometres:
In general, I try not to transform any data being returned in our responses above the driver level. We are the only ones who have to adhere to our behavioural contract for the components/service rpc returns and ensure they adhere to the correct units; if someone wants to implement their gantry model driver in inches, for example, have at it.
Caveats:
> Do not scale gantry collector returns from `Lengths` and `Positions` 

- components/camera/camera.go
- components/camera/videosourcewrappers.go
This pr simply moves code around so that the structs implementing videosources are all in one file.
> Move more of the videosource code to the videosourcewrappers file

- components/gantry/singleaxis/singleaxis.go
- components/gantry/singleaxis/singleaxis_test.go
Switch to using SetRPM instead of GoFor with revolutions == 0 (removed behavior) when homing and moving away from a limit switch.
> RSDK-8838: Use SetRPM in gantry homing routine

- components/arm/xarm/xarm.go
Add to the xArm's DoCommand. 
This DoCommand is used within the wine pouring demo.
This allows us to set a higher acceleration and speed for when we want to de-pour.
A higher speed and acceleration prevents the wine from dribbling out of the bottle on the de-pour.
This is being added so that people other than me can run the demo here in nyc.
> RSDK-8840 - Add set speed and acceleration function to xArm doCommand

- components/gantry/singleaxis/singleaxis.go
when checking if the gantry hit a limit switch during homing, we were also checking if it hit the other limit switch that we didn't expect, and returned an error so the user knows their limit switches aren't configured correctly. this caused an out of range error when there was only 1 limit switch since there isn't a second limit switch to check but we were assuming there was.
I thought there'd be a software test to check this but all the functions, specifically `GPIOPinByName` are injected so it failed when we told it to and passed when we told it to. looking for suggestions of a good way to add a test for this even now that it's fixed
> RSDK-8836: Gantry Can't Home with Limit Switches

- module/modmanager/manager.go
- robot/robot.go
- robot/web/web.go
added some docs around how the foreign service handler works, let me know if there are other parts that are confusing and could use more color
> RSDK-8832 - add docs around foreign service handler

- go.mod
- go.sum
- testutils/resource_utils.go
Pulled out of https://github.com/viamrobotics/rdk/pull/4273 - provides a more concise diff of resources when the test utility `VerifySameResources` fails. The current (verbose) diff is still included in the failure output.
```
robot_reconfigure_remote_test.go:143: Expected: '[]resource.Name{resource.Name{API:resource.API{Type:resource.APIType{Namespace:resource.APINamespace("rdk"), Name:"component"}, SubtypeName:"arm"}, Remote:"", Name:"arm1"}, resource.Name{API:resource.API{Type:resource.APIType{Namespace:resource.APINamespace("rdk"), Name:"component"}, SubtypeName:"arm"}, Remote:"foo", Name:"remoteArm"}, resource.Name{API:resource.API{Type:resource.APIType{Namespace:resource.APINamespace("rdk"), Name:"service"}, SubtypeName:"motion"}, Remote:"", Name:"builtin"}, …
```
> Clearer resource diff in tests for VerifySameResources

- .github/workflows/docker.yml
- components/motor/gpio/encoded.go
Make it a bit less alarming and opt to warn users that we're going a slow motor speeds.
Tell users them what rpm the motor is going at compared to what they requested. 
Reset the zerorpm tracker so it doesn't continuously spam after the first time this condition is hit. cc @npentrel.
> [RSDK-8849] Change low rpm error to warning and limit zeroRpm tracker to make logs less noisy

- resource/graph_node.go
- robot/impl/local_robot_test.go
viam-server can have multiple successive config failures very quickly, which leads to some very long error messages
> RSDK-8736: Only keep last error instead of joining

- config/config.go
- config/config_test.go
- robot/impl/local_robot_test.go
- robot/web/web.go
- robot/web/web_test.go
This PR phases out support for legacy robot API keys by taking out most of the code that explicitly parses for them via a "key" field in the API key handler config. Some code still remains to account for a "keys" field. This is redundant, but it's required for backwards compatibility - also the only remaining artifact of legacy keys. Also in this PR is the reconfiguration of various tests in order to account for the change in App slightly affecting the structure of the API key auth config.
Testing: local testing suites pass and my dummy local robot as able to connect manually.
> [APP 2911]  Step Towards Removal of Legacy Robot API Keys

- web/frontend/package-lock.json
- web/frontend/package.json
I finally got tired of seeing the dependabot PRs in my inbox. I took matters into my own hands.
```
git cherry-pick 32d5bb1bd381ab148e0fa41bd4bfaaf7b4406342
git commit --amend --author="Ethan Look-Potts <ethan.look@viam.com>" --no-edit 
git cherry-pick ab0d41b03d76cdb386971f2090d8a5db4f167bbc
git commit --amend --author="Ethan Look-Potts <ethan.look@viam.com>" --no-edit 
```
CLA was being finicky - might not have been necessary to amend the author.
Closing these:
- #4373 
- #4385
> Bump dependencies in /web/frontend

- components/camera/videosource/webcam.go
- components/camera/videosource/webcam_e2e_test.go
- components/camera/videosource/webcam_test.go
- Added `frame_rate` to monitoredWebCam properties 
- Added a test in webcam_test.go to check that `frame_rate` was assigned properly
> RSDK-8858 Add frame_rate to webcam driver

- components/base/sensorcontrolled/sensorcontrolled_test.go
- control/constant.go
- control/derivative.go
- control/encoder_speed.go
- control/endpoint.go
- control/filters.go
- control/gain.go
- control/sum.go
after further investigation the issue was in the `Next()` function of various blocks. I added a lock to each, but I'm wondering if this will cause issues. @JohnN193 do you remember why we haven't done this yet? I did a quick test with tuning and behavior of controlled components with these changes and didn't see any issues
> RSDK-8824: Test Datarace: go.viam.com/rdk/components/base/sensorcontrolled.TestSensorBaseWithVelocitiesSensor

- robot/packages/utils.go
I split this into two commits:
* The [logging logic](https://github.com/viamrobotics/rdk/pull/4402/commits/46ce76f4431a636dfa60de2fd28fdb9dc32c8deb) `packageIsSynced`
* [Migrating from](https://github.com/viamrobotics/rdk/pull/4402/commits/ee69673c954ab4f4e74f3dd5b2b4c0b7e91614b8) `pkg/errors.Wrapf` to stdlib `fmt.Errorf("...%w", err)`
Old log:
```
2024-09-24T13:16:10.175-0400	DEBUG	packages/utils.go:312	unchecked error	{"error": "cannot find /home/dgottlieb/.viam/packages/data/module/4593c406-dda4-40ff-9ea2-e5eb2fbe4ac4-nicksensor-0_0_1-linux-amd64.status.json: open /home/dgottlieb/.viam/packages/data/module/4593c406-dda4-40ff-9ea2-e5eb2fbe4ac4-nicksensor-0_0_1-linux-amd64.status.json: no such file or directory", "errorVerbose": "open …
```
> RSDK-8883: Have package downloading better interpret file does not exist errors.

- components/gantry/singleaxis/singleaxis.go
- components/gantry/singleaxis/singleaxis_test.go
use move away to make sure limit switch it cleared before homing to the next limit switch
more info from ticket description:
Currently during the gantry homing process, the gantry will move to limit switch 0, and then limit switch 1. During this process, it is constantly checking if it has hit the limit switch it is looking for, but it is also constantly checking if it has hit the wrong limit switch, meaning if it was expecting to hit limit switch 0 next and it hits limit switch 1, or if it expects to hit limit switch 1 next and hits limit switch 0. If this happens, the homing sequence errors and stops. 
This causes a problem with slower gantries because there’s a case in which the first limit switch could be hit, and then the gantry starts moving in the opposite direction trying to find …
> RSDK-8878: gantry shouldn't look for the second limit switch until it has cleared the first limit switch

- cli/dataset.go
If a user tries to export a dataset that doesn't exist, we now return an error.
Manually tested:
`go run cli/viam/main.go dataset export --destination mydataset1 --dataset-id bccf8f8f-e3c4-4f72-ab9a-fc547757f352`
> RSDK-8773: Return error if invalid dataset ID during export

- web/server/entrypoint.go
RSDK-8900
Confirmed this change means `rdk.networking` logs appear in app.
> RSDK-8900 Do not use networking logger for net appender

- cli/module.schema.json
- cli/module_registry.go
- Add `build.darwin_deps` field to meta.json
Cloud build currently has a 20 minute homebrew step. Most modules don't need most of these libraries though. This change lets people iterate more quickly around hosted mac builds.
> APP-6543 configurable dependencies for faster mac build

- resource/graph_node.go
- resource/resource_graph.go
- robot/impl/local_robot.go
- robot/impl/resource_manager.go
- robot/impl/resource_manager_test.go
- robot/impl/robot_framesystem_test.go
- robot/impl/robot_reconfigure_remote_test.go
- robot/impl/utils.go
* Keep offline remote resources in `ResourceNames`
* Add an internal `unreachable` field to graph_nodes, so that existing tests have a way to assert on the subset of resources are still online
> RSDK-7903 Keep unhealthy remotes in ResourceNames

- services/datamanager/builtin/builtin.go
If you configure data sync without any collectors, you get logs in data sync that complain about the capture directory not existing.
This is b/c data manager currently only creates the capture directory if you have a collector, but data sync expects the capture directory to always exist. 
This mitigates the problem my having data manager builtin attempt to create the top-level capture director if it doesn't already exist.
> Create capture directory in data manager builtin

- services/datamanager/builtin/sync/sync.go
Turns out this log is a bit too noisy when your robot is not syncing data
> downgrade-sync-path-log-to-debug

- robot/impl/local_robot_test.go
- robot/impl/robot_framesystem_test.go
- robot/impl/robot_reconfigure_remote_test.go
- robot/impl/robot_reconfigure_test.go
- robot/impl/robot_reconfigure_weak_dependencies_test.go
- services/sensors/builtin/builtin.go
- web/server/entrypoint_test.go
The sensors service API is [deprecated](https://github.com/viamrobotics/api/blob/main/proto/viam/service/sensors/v1/sensors.proto). We still, however, add a default sensors service resource to every viam-server out there. This pr removes it as a default service.
> Make sensors service not configured on default

- .github/workflows/npm-bump-version.yml
With a new weekly release cadence, the TypeScript SDK is moving away from publishing release candidates. Instead, the TS SDK gets a draft release on Monday, goes through automated integration testing, and then is released. 
This PR updates the remote control RC workflow to grab the latest release for the TS SDK, which should be released earlier in the day. (Basically it just changes the comment to say "grab the latest or next version" instead of "RC version")
> [RSDK-7589] Update remote control version bump workflow

- module/modmanager/manager.go
- resource/name.go
- resource/name_test.go
- resource/resource_graph.go
goes from 
```
2024-10-09T21:11:08.342Z        ERROR   rdk.resource_manager    resource/resource_graph.go:599     cannot resolve dependency for resource due to multiple matching names      {"name":"rdk:component:power_sensor/power_sensor1","conflicts":[{"API":"rdk:component:movement_sensor","Remote":"","Name":"movement_sensor1"},{"API":"rdk:component:movement_sensor","Remote":"robot1","Name":"movement_sensor1"}]}
```
to
```
2024-10-09T21:39:10.399Z        ERROR   rdk.resource_manager    resource/resource_graph.go:599     cannot resolve dependency for resource due to multiple matching names      {"name":"rdk:component:power_sensor/power_sensor1","conflicts":["rdk:component:movement_sensor/robot1:movement_sensor1","rdk:component:movement_sensor/movement_sensor1"]}
```
> Clearer error for dependency conflicts

- .github/workflows/pullrequest-trusted.yml
- .github/workflows/test.yml
- use a virtualenv to unbreak the jsonschema test
- guessing ubuntu 22 -> 24 added 'don't break global python warning' but this is failing now on main
:heavy_check_mark: https://github.com/viamrobotics/rdk/actions/runs/11276793733/job/31361443053
> fix meta.json schema test

- cli/module_generate/templates/.github/workflows/deploy.yml
- add `token` field to deploy.yml to match build-action README
So this uses the new private repo support.
> APP-6588 private repo support in generated modules

- components/audioinput/microphone/microphone.go
Instead of using the default constraints (which were for video), microphone now uses audioConstraints. I was finally able to figure out how to test this by printing out the `malgo.DeviceInfo device.ID` and using that ID as the audio_path in app. 
-I tested the audio_input locally on darwin/arm64 (mac) by creating a microphone component and using the Macbook Air microphone as the audio stream. 
-I tested the audio_input locally on canon (for linux/arm64 and linux/amd64) by creating a microphone component and using the "Built-in Audio Analog Stereo Air" on the framework (aka framework microphone) microphone as the audio stream.
> RSDK-1848: Don’t use video constraints for microphone

- module/modmanager/manager.go
- module/modmanager/manager_test.go
Try viam is run with an untrusted environment, which means no modules. However, we are modularizing all the builtin components. We need a way to run specific modules only in untrusted environments.
Right now, I'm only whitelisting the raspberry pi, but I'm welcome to suggesting to make this not as brittle.
Tested with a `viam:odrive` module and a `viam:raspberry-pi` module, this only allows the pi resource to be built, though I do think the logging on what is going on could be clearer.
I have not added more whitelisted modules because we have a scope doc discussing their names right now.
Robot logs showing the pi being added in an untrusted environment, but not the drive:
```sh
archytas@archytas:~ $ sudo ./viam-server -untrusted-env -config /etc/viam.json 
2024-10-08T22:35:43.535Z	INFO …
```
> [RSDK-8950] Allow Try Viam to use specific viam modules

- components/motor/motor.go
- components/motor/ulnstepper/28byj-48.go
- components/motor/ulnstepper/28byj-48_test.go
Addressed in this PR:
- allow SetPower Calls to move backwards.
- allow SetRPM calls with rpms above the max rpm to move with the maxrpm, and add a warning saying we're moving at the maxrpm
- isMoving returns a correct state of the motor false when stopped, true when moving
- ResetZero position does not falsely report that the motor is moving after resetting the position.
Manual testing:
- control page execution of SetPower +ve/-ve, observed motor going forwards when expected and backwards when expected. 0 power did not move the motor.
- control page execution of SetRPM +ve/-ve, observed motor going forward when expected. 0 rpm did not move the motor, magnitudes of rpm > maxrpm did move the motor with the added warning. 
- control page GoFor with combo of -ve/+ve rpm and -ve and +ve …
> [RSDK-8486] Fix 28byj-48 control issues

- web/server/entrypoint.go
- Logs were not propogating to App when they occurred in the config retreiver
- Changing the logger name allows logs to be picked up by the net appender
> Change logger name to ensure logs are picked up by the net appender

- cli/client.go
See offline discussion: I'm guessing CLI users are timing out with 3 seconds.
> Bump timeout for CLI base URL validity check

- services/baseremotecontrol/builtin/builtin.go
- services/baseremotecontrol/builtin/builtin_test.go
While working with a Discord community member to configure the base remote control service to use joystick controls instead of the default D-pad (arrows) controls, I noticed a spelling discrepancy between the RDK code and the documentation. The latter specifies "joyStickControl" as the expected value for that control mode, however the RDK checks for "joystickControl" (even though the const variable is `joyStickControl`). This small spelling difference is confusing to debug, especially when there is no validation for that configuration attribute. 
I've submitted a PR to the docs (https://github.com/viamrobotics/docs/pull/3596) to update the spelling to match the RDK as the more immediate fix. This PR adds helpful validation of the control_mode attribute to ensure it matches one of the …
> fix(services/baseremotecontrol): validate control_mode config attribute

- cli/app.go
- cli/data.go
- cli/dataset.go
The previous implementation used authFlow.httpClient, which sets a 30
seconds timeout - not enough for large binary file downloads.
Also, simplify export CLI code slightly by passing the response body
reader as-is instead of an unnecessary ReadAll step.
> DATA-3040: Allow specifying timeout for large file downloads

- cli/module_registry.go
- config/module.go
- config/proto_conversions.go
- config/proto_conversions_test.go
this does not handle reading the JSON config from disk, might have to shadow the data structure like some other configData structs.
With this PR, app will be able to pass through the first_run_timeout correctly
> RSDK-8881, RSDK-9074 - add first_run to CLI update module action, proto conversions for first_run_timeout

- logging/proto_conversions.go
- robot/server/server.go
Manually handles log fields in `robot/server/server.go#Log` that are encoded as error types and contain an error object (or nil) in their `Interface` field. #4478 added a fix for Golang modules that ensures error fields are encoded as string types during proto conversion. Old Golang modules without that fix will still encode errors as error types, so we should have a similar change server-side to remain backward compatible. 
Tested with a version of `simplemodule` built before #4478 that tries to log an error field. RDK panics without the change in this PR:
```
panic: interface conversion: map[string]interface {} is not error: missing method Error
go.uber.org/zap/zapcore.Field.AddTo({{0x140009035b0, 0x3}, 0x1a, 0x0, {0x0, 0x0}, {0x10531b5e0, 0x14000b41980}}, {0x105815840, 0x14000b0e500}) …
```
> RSDK-9097 Accept malformed gRPC error log fields

- logging/logger.go
- module/modmanager/manager.go
Emit logs of stdio/stderr messages from setup phase command as they come instead of only at the end. ~Combined output is re-logged after the command completes.~ EDIT: [not anymore](https://github.com/viamrobotics/rdk/pull/4475#discussion_r1809701738)
Also fix bug where script logs were not being posted to app.viam
Example run with a setup phase that contains a mongo pull command:
```
2024-10-23T17:17:15.667Z        INFO    rdk.modmanager.first_run        modmanager/manager.go:1098      executing first run script        {"module":"5784b2a8-d84f-473b-9be5-9a2abe7e8752_my_setup_phase","path":"/home/mp/.viam/packages/data/module/5784b2a8-d84f-473b-9be5-9a2abe7e8752-my_setup_phase-0_0_13-linux-amd64/first_run.sh"}
2024-10-23T17:17:16.165Z        INFO    rdk.modmanager.first_run …
```
> RSDK-9091,RSDK-9088 Emit logs as they come from setup phase command

- robot/web/stream/server.go
- robot/web/web_c.go
Getting started on dynamic resolution epic. This is just a first-step PR to make sure I have a good handle on the relevant code & tests.
- Simplifies stream server initialization.
- No longer special case for noop stream server.
- Removes passing in streams to stream server constructor `webstream.NewServer`.
- Unifies logic for adding new streams between reconfigures and initialization.
- No longer have separate stream flows for `initStreamServer` vs `Reconfigure`.
- Simplified `addNewStreams` helper.
- Added `createStream` helper for commonalities between audio & video stream initialization.
- webcam live stream ✅ 
- linux ✅ 
- darwin ✅ 
- reconfigure ✅ 
- fake cam live stream ✅ 
- GetImage ✅ 
- passthrough ✅ 
- reconfigure ✅ 
- audio stream ✅
- reconfigure ✅ 
- viamrtsp ✅ 
- passthrough …
> [RSDK-9072] - Simplify stream inits

- examples/customresources/demos/complexmodule/module.go
- examples/customresources/demos/multiplemodules/gizmomodule/gizmomodule.go
- examples/customresources/demos/multiplemodules/summationmodule/summationmodule.go
- examples/customresources/demos/rtppassthrough/myrtppassthrough.go
- examples/customresources/demos/simplemodule/module.go
- examples/customresources/models/mygizmo/mygizmo.go
- module/module.go
- module/multiversionmodule/module.go
- module/runtime.go
- module/testmodule/main.go
- module/testmodule2/main.go
we want to force a breakage so that users will not use the wrong logger when making a Go module.
logs now look like
```
10/23/2024, 3:23:27 PM error acme:component:gizmo/gizmo1 mygizmo/mygizmo.go:61 hello err from the other side log_ts 2024-10-23T19:23:27.697Z
```
on app
when it used to be
```
10/23/2024, 3:23:27 PM error {moduleName}.acme:component:gizmo/gizmo1 mygizmo/mygizmo.go:61 hello err from the other side log_ts 2024-10-23T19:23:27.697Z
```
I think it's generally fine to no longer have the moduleName tacked on to the beginning of the logger name.
this is a breaking change but all the user needs to do is to get rid of the logger/module name from their function calls
cc: @benjirewis
> RSDK-9117 - Remove logger from NewModuleFromArgs, and moduleName from ModularMain

- components/gripper/gripper.go
- components/input/input.go
* add FromRobot to gripper and input controller
* clean up wonky code sample in input controller
* checked gantry through input controller
> DOCS-2950: Make changes from QA to gripper, input controller 

- robot/web/web.go
- robot/web/web_c.go
Currently, we have logic that forces the `PreferWebRTC` web option if audio/video streams are present in the stream server. This is overkill because [we prefer WebRTC by default](https://github.com/viamrobotics/rdk/blob/main/web/server/entrypoint.go#L45) from our command line argument handling.
This PR removes the streamServer wrapper struct and all web options coupling to the stream server.
> RSDK-9115 - Remove web options handling from stream server

- robot/web/web_notc.go
I did not remove options from the `web_notc` path in the previous [PR](https://github.com/viamrobotics/rdk/pull/4488). This is causing CI to fail, see [here](https://github.com/viamrobotics/rdk/actions/runs/11557035823/job/32167240371).
> RSDK-9115 - Hotfix - Remove options arg from web_notc init stream server stub

- robot/impl/local_robot.go
- robot/impl/local_robot_test.go
- The readings function is now more careful about reconfiguring when a sensor issue is discovered.
- We now do not reconfigure in the following cases
- if a non bool value is found
- if a maintenance key is not found
- if a maintenance key value is not the correct type
- Added a missing error log
> Maintenance Window - Block Reconfigure on all errors when reading a sensor

- components/camera/fake/camera.go
- components/camera/fake/camera_test.go
In order to test dynamic resolution endpoints, it is helpful to configure fake cameras with and without intrinsic parameters.  In the process of adding this I noticed some seemingly outdated code blocks and tests we can remove.
- Adds `Model` attribute to fake camera.
- Toggles `IntrinsicParams` and `DistortionParams` for the camera.
- Defaults to false.
- Removes seemingly stale width & height handling for params in `fakeModel` helper.
- No longer need to handle 16:9 aspect ratio adjustments.
- We now validate and set default sizes in the constructor.
- Removes tests that are not using the fake cam methods.
```
type Config struct {
Width          int   `json:"width,omitempty"`
Height         int   `json:"height,omitempty"`
Animated       bool  `json:"animated,omitempty"`
RTPPassthrough …
```
> RSDK-9188 - Add fake cam attr to toggle intrinsic & distortion props

- robot/impl/local_robot.go
Update reconfiguration loop to only run first_run script for new and modified modules, instead of all modules in received config. This caused the noop "first run already ran log" to be logged each time we receive a new config if any modules have an associated first run script.
> RSDK-9181 Log "first run already ran" once

- config/module.go
- config/module_test.go
- module/modmanager/manager.go
Move the majority of first run logic to `config/module`. Address some issues from the initial implementation of [the setup phase](https://github.com/viamrobotics/rdk/pull/4457).
> RSDK-9067 Refactor first run

- config/module.go
Fix-up for https://github.com/viamrobotics/rdk/pull/4511 - the doc string for `FirstRunTimeout` is incorrect. The value _must_ be a positive value or it will not be used.
> RSDK-9060: Fix docstring for FirstRunTimeout

- .github/workflows/appimage.yml
- .github/workflows/droid.yml
- .github/workflows/macos.yml
- .github/workflows/motion-benchmarks.yml
- .github/workflows/test.yml
The [breaking changes](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) documentation is poorly written:
> (1) On self hosted runners, additional [firewall rules](https://github.com/actions/toolkit/tree/main/packages/artifact#breaking-changes) may be required.
>
> (2) Uploading to the same named Artifact multiple times.
>
> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.
>
> (3) Limit of Artifacts for an individual job. Each job in a workflow run now has a limit of 500 artifacts.
>
> (4) With v4.4 and later, hidden files are excluded by …
> RSDK-9218: Move upload-artifacts to v4.

- robot/packages/utils.go
Refactor and add documentation around package file cleanup logic.
Convert `multierr.XXX` -> `errors.Join`
https://github.com/viamrobotics/rdk/pull/4457#discussion_r1807159318
> RSDK-9090 clarify package cleanup

- components/motor/gpio/basic.go
- components/motor/gpio/basic_test.go
in controlled motor, when stop is called, `updateControlBlock` is called, with the maxVel parameter being `cm.real.maxRPM*cm.ticksPerRotation/60`. maxVel cannot be 0 in this function, but `cm.real.maxRPM` didn't have a default value so sometimes it was causing maxVel to be 0 and error when stop was called on the controlled motor
> RSDK-9136: issues when stopping motor with controls

- components/encoder/single/single_encoder.go
- components/motor/gpio/controlled.go
- components/motor/gpio/encoded.go
- components/motor/gpio/encoded_test.go
- components/motor/gpio/setup.go
I'm not sure I think this is any better than the way it was before. I considered the method Olivia suggested by converting the `DoCommand` interface into a motor object, but it couldn't be `motor.Motor`, it would have to be specifically `gpio.Motor` because the interface doesn't implement all the API functions. And imo `gpio.Motor` in `DoCommand` is no better than `single.Encoder` in `setup.go` as it was before. Open to ideas tho, because I don't love this implementation. 
Basically, my goal here was to avoid casting to any specific model types of either motor or encoder. I did have to cast to the `DirectionAware` type, but that seemed better since it's specific to single encoder.
> RSDK-9037: Add AttachDirectionalAwareness to DoCommand

- config/platform.go
- add `readDarwinTags` which supplies `os_version` platform tag. (on linux systems we already get this from `/etc/os-release`)
- incidental: make the 5-second timer apply to the entire read tags function, rather than just the readGPUTags function
Macos version targeting for binaries.
On a device with:
```
$ sw_vers --productVersion
14.6.1
```
RDK logged:
```
{"tags":"os_version:14"}
```
> APP-6696 include `os_version` tag on GOOS=darwin

- components/motor/gpio/basic.go
- robot/impl/local_robot.go
The context was getting canceled before the pins could be set correctly in order to stop the motor. by using a background context, `Stop()` and `setPWM()` can return while `turnOff` is still setting the pins. Could this also be done with `SelectContextOrWait`? 
I also updated the error return from local_robot.go because it buried the error from `StopAll` in order to see what was actually happening.
> RSDK-8926: Rover canary motor test fail because failure to set pins

- app/viam_client.go
- app/viam_client_test.go
[Jira ticket](https://viam.atlassian.net/browse/RSDK-9194)
Changes:
- added new directory `app/`
- introduced a `ViamClient` struct
- made a function `CreateViamClient`, which takes in api key for credentials
- add unit tests for url and api key formatting
Testing:
- called a proto dataClient and tested with an existing machine
- unit tests
> RSDK-9194: streamline app connection

- cli/data.go
This PR fixes a bug in our ConfigureDatabaseUser flow in the CLI itself. We try to fetch the existing DB user from mongo and if we error, we return and exit. This is done as part of the confirmation of a password change code. However, this causes an edge case to fail. If we do not have an ADF instance and want to trigger creation of one via `viam data database configure --org-id 94380e5a-0df2-4ae8-9b5f-53eaaf507f02 --password *******`, we attempt to look up the existing DB user which doesn't exist. We then return an error to the user saying we can't find their instance. This PR changes this so that if the ADF instance doesn't exist, we skip the confirmation routine.
> DATA-3385 Fix ConfigureDatabaseUser flow

- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/testmodule/main.go
[RSDK-9315](https://viam.atlassian.net/browse/RSDK-9315)
Let it be known that in the current janky discovery world, `DiscoveryFunc` and `DiscoverComponents` are not 1:1. "Modular discovery," which is basically a `DiscoveryFunc` served via the `DiscoverComponents` method, should _not_ contain any crap like subtype, api etc. because it is serving one model only, even though it uses the `DiscoverComponents` method to go over the wire. This is partially what went wrong with the serialization in the first place.
The other part of went wrong was that we should not be returning raw pb. Let's use `asMap` to get rid of the proto wrappings.
[RSDK-9315]: https://viam.atlassian.net/browse/RSDK-9315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [RSDK-9315]   Fix modular discovery response

- components/camera/transformpipeline/mods.go
- components/camera/transformpipeline/mods_test.go
Right now, you have to give absolute pixel values to do a crop with the transform camera.
This update allows you to do both -- if you put in values between 0 and 1 for the crop, then it will interpret the crop as using relative proportions of the image
Also, a new attribute called `overlay_crop_box` allows you to not actually carry out the crop, but just overlay the cropping box on the original image. This is a way to visualize where the crop would be applied.
@randhid just FYI since it's touching cameras
> add relative crop to transform camera and overlay crop box

- gostream/webrtc_track.go
- robot/web/stream/server.go
- robot/web/stream/state/state.go
- robot/web/stream/state/state_test.go
- robot/web/stream/stream_test.go
[RSDK-8982](https://viam.atlassian.net/browse/RSDK-8982), [RSDK-9167](https://viam.atlassian.net/browse/RSDK-9167) [RSDK-8979](https://viam.atlassian.net/browse/RSDK-8979)
This PR adds the `SetStreamOptions` endpoint to the stream server. 
- Validates the requests and performs a hot swap on the video source with a `NewResizeVideoSource`.
- If Resolution is provided, we dispatch a `Resize` msg to the `streamState` handler.
- If in Passthrough mode, the state transitions to gostream.
- Prevents attempting to use passthrough during `Increment` and `Decrement` calls.
- If Resolution is not provided, we dispatch a `Reset` msg to the `streamState` handler.
- Attempts to restart passthrough if available.
- In order to unify RTP `Sequence Number` handling between GoStream and Passthrough paths we …
> [RSDK-8982, RSDK-9167, RSDK-8979] - Add SetStreamOptions to stream server

- .github/workflows/staticbuild.yml
- in antique build, symlink `/__e/node20/node` to the container's node 16 intallation
- incidental: add `no-upload` bool to workflow_dispatch for the static build workflow (to support my testing today)
The actions nodejs install (`/__e/node20/node`) now requires GLIBC 2_28 and we have 2_27; antique builds are failing as a result, example [here](https://github.com/viamrobotics/rdk/actions/runs/12038915350/job/33566401901#step:3:18). Context: the antique container intentionally links against old GLIBC for broad compatibility.
https://github.com/viamrobotics/rdk/actions/runs/12039219859
> override nodejs to unbreak antique builds

- cli/module_generate/_templates/go/tmpl-main.go
It got out of sync as a result of https://github.com/viamrobotics/rdk/commit/517e861b2bc11b01f184067935f73c1e238bd8d2
tested locally
cc: @michaellee1019
> RSDK-9368 - Remove log arg in module generation code

- app/data_client.go
- app/data_client_test.go
Changes:
- rename some structs for clarity
- add optional parameter structs
- add comments clarifying what happens if a parameter is left empty
Note as to why I didn't put all optional parameters in structs: 
At first, I thought I should be putting the optional `filter` parameters for some of the methods in its own `<method>Options` struct. Thinking over it some more, I realized these functions could be seen as ones where the user is purposely leaving this parameter `nil`. This is in line with my discussions with Benji when we first introduced optional parameter structs. It also seemed more straightforward, especially with more clarifying comments.
> RSDK-9338: add optional parameters in data client

- components/camera/client.go
- data/collector.go
- module/modmanager/manager.go
[RSDK-9314](https://viam.atlassian.net/browse/RSDK-9314)
[RSDK-9314]: https://viam.atlassian.net/browse/RSDK-9314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
That point cloud method is the only usage of the helper.
> [RSDK-9314]   Fully deprecate data.GetExtraFromContext

- Makefile
- services/datamanager/builtin/disk_summary_logger.go
- services/datamanager/builtin/disk_summary_logger_posix.go
- services/datamanager/builtin/disk_summary_logger_windows.go
- services/datamanager/builtin/sync/file_deletion.go
- services/datamanager/builtin/sync/file_deletion_posix.go
- services/datamanager/builtin/sync/file_deletion_windows.go
- web/server/entrypoint_windows.go
- datamanager + entrypoint build tag changes to allow RDK to build with GOOS=windows
- `make windows` target in makefile
Keeping our options open for windows support. WSL is a better route for us for now (because of systemd support), but there are potential benefits to running un-sandboxed so I rehabbed this. Note that [unix sockets dropped in 2017](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/).
- the process starts on windows without WSL
- the device turns green in webapp
- still figuring out module connectivity. Status: Working on updates. 29% complete. Don't turn off your computer.
> APP-7128 windows build

- cli/module_generate/_templates/go/models/tmpl-module.go
- cli/module_generate/scripts/tmpl-module
[Jira ticket](https://viam.atlassian.net/browse/RSDK-9266)
Changes:
- add more clarifying details of what to put in config struct
- add example config struct
- describe what `Validate()` does
- explain what `path` parameter is
Tested by running the module generator locally
> RSDK-9266: improve comments in golang module templates

- app/app_client_test.go
- cli/app.go
- cli/client.go
- cli/client_test.go
This PR adds functionality to get / set a support email at the org level from the CLI. This is used for white-labelled billing. 
@benjirewis @stuqdog I just want to make sure there is nothing I am missing here with test coverage + CLI additions. Thank you for the 👀 on this PR! 
Manual Testing Against Staging:
> APP-6819: Adding the CLI command to get/set support-email

- components/arm/arm.go
This will allow the example be pulled into the correct place in the docs
> Fix MoveThroughJointPositions example label

- app/app_client.go
- app/app_client_test.go
- cli/app.go
- cli/client.go
- cli/client_test.go
- testutils/inject/app_service_client.go
The new command from the scope:
```
viam organization billing-service get-config --org-id=<org-id>
```
Manual Testing:
> APP-6846: Adding the GetBillingConfig CLI endpoint

- module/modmanager/manager.go
- module/modmanager/manager_test.go
- Module specific logs will now use the module logger instead of the mod manager logger
> RSDK-9292 - change module specific logs to use the module logger

- pointcloud/basic_octree_test.go
- pointcloud/pointcloud_utils.go
- pointcloud/pointcloud_utils_test.go
We already have the [ReadPCDToBasicOctree](https://github.com/viamrobotics/rdk/blob/main/pointcloud/pointcloud_file.go#L536) method. However in order to use it on a pointcloud.PointCloud object, a user first needs to convert it into a PCD file and only then are they able to use the mentioned method. This is not an optimal route.
The goal of this PR is to add a function which removes the step of converting a pointcloud into a file.
> Add method which converts a pointcloud into an octree.

- app/app_client.go
- app/app_client_test.go
- app/billing_client_test.go
- app/common.go
- app/data_client.go
- app/data_client_test.go
- app/mltraining_client.go
- app/mltraining_client_test.go
- app/viam_client.go
- app/viam_client_test.go
This PR mainly focuses on basic cleanup for app wrappers. Naming and return types were standardized to follow the rest of the app wrappers. Note that these changes do not necessarily mean that something was done wrong previously.
Changes:
- return pointers where pointers are returned from proto
- name response shadow types `<Method>Response`
- convert `anypb.Any` types to Go standard types
- call `MQL` function with queries
- remove pointers from types that are already references
- return errors where applicable
- check for errors in tests
- return proto type for Google Status object
> RSDK-9441 clean up app wrappers

- module/module_unix.go
I'm doing something funny with this module I'm writing where I need to execute the binary as the root user.  If I then run viam-server as a non-root user I got a vague message talking about sock ownership.  This seems like a less than ideal user experience, that we can make better by more explicitly answering the burning questions that must be on their mind relating to who owns the socks. 
The new error can be seen below
> help users better understand who really owns the socks

- components/camera/camera_test.go
- components/camera/client_test.go
- components/camera/fake/camera_test.go
- components/camera/fake/image_file_test.go
- components/camera/ffmpeg/ffmpeg_test.go
- robot/client/client_test.go
- robot/impl/local_robot_test.go
- testutils/inject/camera.go
[RSDK-9512](https://viam.atlassian.net/browse/RSDK-9512)
[RSDK-9512]: https://viam.atlassian.net/browse/RSDK-9512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Non-breaking change we can do before removing Stream 
Can't remove injected StreamFunc since we use it for transform pipeline tests
> [RSDK-9512]   Remove Stream and ReadImage tests

- app/app_client.go
- app/app_client_test.go
- cli/app.go
- cli/client.go
- cli/client_test.go
- testutils/inject/app_service_client.go
APP-6996: Implement OrganizationGetLogo 
dont have org with logo set but heres an example of it without:
```
go run cli/viam/main.go organization logo get  --org-id  a757fe30-5648-4c5b-ab74-4ecd6bf06e4c
Info: Using "https://app.viam.dev" as base URL value
No logo set for organization "a757fe30-5648-4c5b-ab74-4ecd6bf06e4c"
```
> APP-6996: Implement OrganizationGetLogo

- services/motion/builtin/builtin.go
- services/motion/builtin/builtin_test.go
There currently exists a bug in the DoPlan option in motion/builtin's DoCommand function where when you pass a WorldState it is not properly deserialized.  This is due to the protobuf struct making use of oneofs.  This PR switches the library used for serialization and deserializing of the MoveReq to the [the protojson package](https://pkg.go.dev/google.golang.org/protobuf@v1.35.1/encoding/protojson) which solves this problem by properly using the struct tags in the protobuf
> improve DoCommand in motion/builtin to properly support WorldStates

- robot/web/stream/camera/camera.go
- robot/web/stream/camera/camera_test.go
[RSDK-9513](https://viam.atlassian.net/browse/RSDK-9513)
[RSDK-9513]: https://viam.atlassian.net/browse/RSDK-9513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Add helper necessary to convert a `camera.Camera` into a `Stream`-having struct for streaming in the server.
> [RSDK-9513]   Add VideoSourceFromCamera helper in stream camera utils

- app/data_client.go
- app/data_client_test.go
- testutils/inject/data_service_client.go
This PR fixes the git mess that happened here:
https://github.com/viamrobotics/rdk/pull/4597
> DATA-3445 Implement Go SDK for ExportTabularData API

- .github/workflows/motion-tests.yml
See documentation here: https://www.baeldung.com/ops/git-double-vs-triple-dot
Basically, this prevents the diff from being applied bidirectionally, only triggering the extended tests on the actual PR that changes motion, rather than any PRs coming in after a motion PR has been merged that did not rebase on main
> RSDK-8471 Add three-dot diff to git diff

- components/camera/transformpipeline/classifier.go
- components/camera/transformpipeline/composed.go
- components/camera/transformpipeline/depth_edges.go
- components/camera/transformpipeline/detector.go
- components/camera/transformpipeline/mods.go
- components/camera/transformpipeline/pipeline.go
- components/camera/transformpipeline/preprocessing.go
- components/camera/transformpipeline/segmenter.go
- components/camera/transformpipeline/undistort.go
- components/camera/videosourcewrappers.go
This fixes a bug where transform cameras cannot reconfigure hitting the below error
This was caused by the transform pipeline refactor in https://github.com/viamrobotics/rdk/pull/4487/files#diff-7901d35a5a488937d314d3f6be687673f43b08fbf5b904b74caf8f6a55713abc
```
12/16/2024, 3:40:31 PM error rdk server/entrypoint.go:200 Fatal error running server, exiting now: webcam already closed; webcam already closed; webcam already closed; webcam already closed
12/16/2024, 3:40:31 PM error rdk server/entrypoint.go:220 error serving web error webcam already closed; webcam already closed; webcam already closed; webcam already closed
```
> RSDK 9552: Transforms shouldn't have to close anything

- components/powersensor/client_test.go
- components/powersensor/server.go
- components/powersensor/server_test.go
- components/sensor/client_test.go
- components/sensor/server.go
- components/sensor/server_test.go
- protoutils/sensor.go
went through power sensor, sensor, and servo server code to see what had the possibility to be returned as nil, and added checks to return errors in that case. also added tests for each nil failure. there were no changes for servo.
added necessary tests to client test file to ensure that the server changes resulted in the same returned error, so the checks didn't need to be added in the client files as well.
work for other components are in other PRs (https://github.com/viamrobotics/rdk/pull/4618 & https://github.com/viamrobotics/rdk/pull/4620)
> (powersensor/sensor) Guard against nil responses in rdk client/servers

- components/gripper/client_test.go
- components/gripper/server.go
- components/gripper/server_test.go
- components/input/client.go
- components/input/client_test.go
- components/input/server.go
- components/input/server_test.go
went through encoder, gripper, input controller, motor, and posetracker server code to see what had the possibility to be returned as nil, and added checks to return errors in that case. also added tests for each nil failure. there were no changes for encoder, motor, or pose tracker.
added necessary tests to client test file to ensure that the server changes resulted in the same returned error, so the checks didn't need to be added in the client files as well.
still need to do this for the other components, but want to break up the work into smaller PRs (https://github.com/viamrobotics/rdk/pull/4618 & https://github.com/viamrobotics/rdk/pull/4621)
> RDSK-9311: (gripper/input-controller) Guard against nil responses in rdk client/servers

- components/camera/collectors.go
- components/camera/server.go
- motionplan/errors.go
- motionplan/motionPlanner.go
- motionplan/motionPlanner_test.go
- pointcloud/pointcloud_utils.go
- robot/server/server.go
- services/motion/builtin/builtin.go
- services/motion/builtin/builtin_test.go
Currently, passing motion options in the MoveRequest does not work.  This PR fixes this so they are correctly transmitted.  
In addition, I did a little bit of refactoring to make it easier to convert a pointcloud into bytes.  This is related to the above objective because we are interested in passing in pointclouds through the MoveReq Options field.
> allow passing MoveReq options in motion/builtin.Do

- app/data_client.go
- app/data_client_test.go
After discussing with SDK team, changing `ExportTabularData` to return the full response as a slice instead of streaming the responses. This will better align with the other SDKs and will also be more user-friendly.
> DATA-3445 Update ExportTabularData to return a slice

- gostream/webrtc_track.go
This fixes a livestream bug that was causing two concurrent webrtc streams to fail.
- Test two concurrent gostream livestream feeds ✅ 
- Test passthrough ✅ 
- Test dynamic resolution resize ✅ 
https://github.com/user-attachments/assets/99f9df41-7b98-48cf-bd74-8e3cb1e86484
https://github.com/user-attachments/assets/5ffd7f87-4eaf-47b6-acd8-95e03db737a3
https://github.com/user-attachments/assets/25445f52-f6a9-4e34-a2f1-06898bbdca9d
> [RSDK-9574] - Do not bump sequence number for each track

- gostream/stream.go
I hand tested this with some "panic once" code:
```
+                               var bounds image.Rectangle
+                               var boundsError any = nil
+                               func() {
+                                       defer func() {
+                                               if paniced := recover(); paniced != nil {
+                                                       boundsError = paniced
+                                               }
+                                       }()
+
+                                       bounds = framePair.Media.Bounds()
+                                       global.Do(func() {
+                                               panic("dan paniced")
+                                       })
+ …
```
> RSDK-9602: Prevent lazyEncodedImage.Bounds from getting gostream into a panic loop.

- cli/client.go
- cli/client_test.go
https://viam.atlassian.net/browse/APP-7307
> [APP-7307]: Remove logo file path manipulation in CLI for OrganizationSetLogo.

- components/board/board.go
- components/board/client.go
- components/board/client_test.go
- components/board/fake/board.go
- components/board/genericlinux/board.go
- components/board/genericlinux/board_test.go
- components/board/interrupt_stream.go
- testutils/inject/board.go
We can now do this cleanup chore since `Status` and `StatusStream` are completely unused and the reason for these rpcs to exist is now gone.
Tested with Viam server running on a mac with a few fake modular boards.
Will probably wait to merge until SDK work is complete.
> Remove non rpc interface methods `AnalogNames` and `DigitalInterruptNames` from board

- cli/app.go
- cli/auth.go
Adds a slightly less verbose `no-browser` alias to the `disable-web-browser` flag, and changes default behavior such that a command won't fail when a browser can't be opened, but rather inform the user that the browser failed to open and that they can still visit the provided URL to log in.
Tested manually.
Without flag, artificially injected error at browser open attempt:
With flag:
> RSDK-9295 - refactor disable-web-browser name and behavior

- cli/app.go
- cli/module_build.go
- Add the `--platforms` field to the `module build start` CLI command (it was already in the API)
User request, simpler iteration when someone is debugging a build.
1. If someone passes a version field, i.e. tries to do a release, this allows them to release for only one platform, or for a platform not mentioned in meta.json. I think that's okay; user is boss in this case
2. this doesn't support granular tagging yet
> APP-7335 add --platforms to `viam module build start`

- cli/module_generate/scripts/generate_stubs.go
- cli/module_generate/scripts/generate_stubs_test.go
[Ticket](https://viam.atlassian.net/browse/RSDK-9370) found a bug where pointer param types weren't attributing to the resource subtype.
Return and param types were treated differently and separately, so even though return types were attributing pointer types correctly, params were not. Now, types are being formatted the same in both returns and types. Instead of a switch statement, a for loop that contains prefix types (`"*", "[]*", "[]", "chan "`) was introduced for scalability and readability.
Testing:
- unit test for `formatType`
- locally with `arm`, `board`, and `camera` components and `vision service`. Not sure if there's other resources with more kinds of types that should be tested.
arm component:
board component:
vision service:
> RSDK-9370: change param prefix check in module generation

- cli/module_generate/_templates/go/tmpl-main.go
This is a follow-up to https://github.com/viamrobotics/rdk/pull/4455.
Nearly all modules can really have a 1-line `main` function, rather than all the boilerplate that gets generated in the current version.
Tried locally: running `./main module generate` can make a new codebase whose `main.go` looks like this:
```go
package main
import (
"branch-module-one-space/models"
"go.viam.com/rdk/module"
"go.viam.com/rdk/resource"
"go.viam.com/rdk/components/audioinput"
)
func main() {
// ModularMain can take multiple APIModel arguments, if your module implements multiple models.
module.ModularMain(resource.APIModel{ audioinput.API, models.BranchModelOnespace})
}
```
Running `make` not only successfully compiles everything, but `main.go` gets cleaned up like this (note the reordering of the …
> Generate less boilerplate code when making a new Go module

- components/camera/camera.go
- components/camera/client.go
- components/camera/client_test.go
- rimage/lazy_encoded.go
- rimage/lazy_encoded_test.go
https://viam.atlassian.net/browse/RSDK-9660
This fixes a bug in which the `vision.CaptureAllFromCamera` data collector receives an `*rimage.LazyEncodedImage` with a mime_type of empty string. This condition happens when a builtin vision service uses a remote or modular camera to get it's image. This causes those images to show up under the `files` tab in app.viam.com rather than the data tab when they are synced to the cloud.
1. Change camera.DecodeImageFromCamera to always return a lazy image (for lower resource usage)
2. Change camera.client.Image to return the mime_type of the camera.GetImageResponse when the camera.Image caller doesn't specify a mime_type. This is needed so that vision services (which frequently don't specify a mime_type in their call to camera.client.Image) to still …
> [RSDK-9660] - fix-camera-image-returning-no-mime-type

- data/capture_file.go
- reverse order of file.Close and os.Rename
On windows, which has stricter file sharing restrictions, the old way produced:
> 1/6/2025, 7:41:15 PM error rdk.resource_manager.rdk:service:data_manager/data_manager-1.capture data/collector.go:106 failed to flush collector error rename .viam\capture\rdk_component_sensor\***.prog .viam\capture\rdk_component_sensor\***.capture: The process cannot access the file because it is being used by another process.
Is flush called concurrently with writes? i.e. have I introduced a write-after-close error? (assign me reading if reviewers don't know the answer)
> APP-7128 close-before-move fix for windows

- module/modmanager/manager.go
the connection from the viam-server to the module still has the 4mb limit. this raises the limit to 32mb
tested on an example module by returning a very large response
> RSDK-9666 - Increase module resource client max receive message size limit

- .gitignore
- components/motor/gpiostepper/gpiostepper.go
In trying to clean up this code, I discovered the following:
- We don't need separate stop functions.
- There's a possible deadlock with SetPower if we call it before close.
I'm going to go ahead and refactor the stepper motor code next - it's not great as is.
> Move lock down in gpiostepper SetPower

- cli/app.go
- cli/client.go
- cli/client_test.go
- testutils/inject/app_service_client.go
add create oauth app command to the cli. usage text screenshot:
> APP-6997: Implement CreateOAuthApp CLI

- robot/impl/robot_framesystem_test.go
can't repro locally, but what I'm theorizing is that the cancel happening at the same time the mDNS lookup is happening on the background reconfig routine is what is causing the issue. maybe one of the recent changes made this more likely? In any case, want to merge this in first so that dev is not blocked while we fix it properly
> RSDK-9668 - Mitigate mDNS race

- robot/web/stream/server.go
- robot/web/stream/stream_test.go
Although we can resize to odd resolutions this breaks our h264 encoder pipeline. Prevent odd resolutions by rounding down to nearest even.
Manually tested we no longer return odd resolutions and resize streams are working.
> [RSDK-9702] - Do not return odd resolutions from GetStreamOptions Response

- robot/impl/local_robot.go
My changes collided with @cheukt's a bit: `newWithResources` now calls `reconfigure` instead of `Reconfigure`, so the `r.initializing.Store(true)` does not happen, and the robot does not actually start in an initializing state when `config.Initial == true`.
To some extent, this proves how fragile the code I added is... But, at least the test I wrote will break if anyone moves things around.
(cc @dgottlieb but small so just got Cheuk as RLGTM)
> RSDK-9440 Store initializing value at end of reconfigure not Reconfigure

- examples/customresources/models/mydiscovery/mydiscovery.go
- module/module.go
- module/module_test.go
- services/discovery/fake/fake.go
- services/discovery/fake/fake_test.go
- services/discovery/register/register.go
- services/register/all.go
https://viam.atlassian.net/browse/RSDK-9655
in order to get around the tagger/proto reflection issue we saw when using the discovery service with modules, we are now skipping the reflection step for discovery apis, and relying on the builtin fake discovery service to register the proto definition. 
tested with a module that implements a discover service and some client code
> [RSDK-9655] skip reflection for discovery service and add fake discovery

- module/modmanager/manager_test.go
> RSDK-9728 Do not assert on old client for TCP mod manager test

- module/modmanager/manager_test.go
RDSK-9356
1ms timeout, as @dgottlieb diagnosed, was sometimes not enough time to actually let the first run script start, so we got did not get the expected error. Bumping to 100ms should definitely be enough time for the script to start while still not being a high enough value to allow `module/testmodule/first_run.sh` to complete (as it calls `sleep 1` internally.)
> RSDK-9356 Bump timeout slightly for TestFirstRun/with_timeout

- cli/client.go
- cli/client_test.go
- cli/module_build.go
- cli/module_reload_test.go
RSDK-8217
Allows passing in loggers to CLI actions that establish connections to machines with `client.New`. Passes in test loggers to those actions during testing.
This will not necessarily _ensure_ we're outputting debug client logs from future tests that end up calling `client.New`, but, from what I can tell, that's not super trivial to ensure, and my guess is this ticket was mostly to make sure we can see debug logs from the shell service tests.
> RSDK-8217 Add client logs to CLI tests

- robot/packages/cloud_package_manager.go
- robot/packages/utils.go
- robot/web/web.go
- utils/env.go
note all of these are behind goos==windows guards:
- in `installPackage`, delete rename destination before renaming (to prevent permission error)
- homedir hack to satisfy abs path checks
- temporarily flag off cloudManager.Cleanup
Initial support for registry modules on windows. Some of these require follow-ups (in particularly `cloudManager.Cleanup`).
> APP-7377 registry modules on windows

- components/encoder/encoder.go
- components/gantry/gantry.go
- components/gripper/gripper.go
- components/input/input.go
- components/motor/motor.go
* add method backlinks encoder-motor
> DOCS-3353: Add backlinks part 2

- vision/objectdetection/connected_components_detector.go
We don't support segmentation through our vision APIs yet but theres not a reason our library functions cant start to support this use case.  I have an application I'm working on that requires this and it is not possible with existing vision support. This PR refactors the underlying algorithm we use for our detections to return clusters of pixels along with their bounding boxes.  
I tested this functionality works by running a test that I don't think has a place in RDK but calls this function with the values in the config below
```
objectdetection.ColorDetectorConfig{
SegmentSize:       20, 
HueTolerance:      .9,
SaturationCutoff:  .9,
ValueCutoff:       .9,
DetectColorString: "#FF660",
}
```
and applies them to this image
to get a mask of just the orange parts
> refactor connected components algorithm to also support segmentation use case

- cli/client.go
[ticket](https://viam.atlassian.net/browse/APP-7459)
This PR fixes the bug of appending to an empty array when converting enabled grants to the proto values
> APP-7459 Fix Enabled grants parsing issue in CreateOAuthApplication CLI

- components/camera/camera.go
- components/camera/replaypcd/replaypcd_test.go
- components/camera/server.go
- components/camera/videosourcewrappers.go
- robot/web/stream/server.go
- robot/web/stream/state/state.go
- testutils/inject/camera.go
Making https://github.com/viamrobotics/rdk/pull/4691/files smaller so we can focus on actual changes.
> [RSDK-9458] Remove 'Stream' from Camera interface I - cosmetic + test changes

- .github/workflows/test-module-generation.yml
- cli/app.go
- cli/module_generate.go
- cli/module_generate/modulegen/inputs.go
Provides improved help text in terms of the `usage` invocation, as well as clarifying the role/usage of the `language`, `model-name`, `name`, `public-namespace`, and `resource-subtype` flags.
Additionally, removes `resource-type` as a flag we pay attention to/care about. While still supported for backwards compatibility, it is invisible and ignored. This flag is a gotcha since each subtype only has one valid type (except generic, but we can carve out a specific case for that), and a user shouldn't reasonably be expected to understand the component/service distinction that is primarily internal.
Tested by creating modules using both old and new code and diffing them to ensure no changes in behavior.
Old help text:
```
NAME:
viam module generate - generate a new modular resource via prompts …
```
> RSDK-9726 - improve modulegen help text and deprecate resource-type flag

- config/module.go
- config/module_test.go
- module/modmanager/manager.go
Search for a registry module's meta.json file in the top level of the module _and_ in the parent directory of its executable entry point.
Running the robot linked in the [Jira ticket](https://viam.atlassian.net/browse/RSDK-9498) no longer outputs the WARN log listed. `first_run.sh` is successfully sourced and executed, and a `dist.first_run_succeeded` file is created.
**Note:** This has only been tested with a registry module, _not_ a local module.
> [RSDK-9498] Search for meta.json File in Top Level of Online Module

- .github/CODEOWNERS
- cli/CONTRIBUTING.md
- cli/STYLEGUIDE.md
Add style guide and contributing guide to the CLI.
> RSDK-9285 - add style guide and contribution guide

- config/reader.go
- internal/cloud/service.go
- logging/net_appender.go
Bumps config read timeout, cloud service connection timeout, and net logging timeout to 1 minute when behind SOCKS proxy. Previous values were causing timeouts when using the SOCKS proxy.
> Further bump timeouts when behind SOCKS proxy

- services/vision/vision.go
* use DecodeImageFromCamera instead of Stream/Next
> DOCS-3196: Update vision docs for camera interface update

- .github/workflows/test.yml
- cli/app.go
- cli/module_generate.go
The current state of the CLI is, for all* commands except for `viam module generate`, to error out pretty much immediately if the user is not logged in, with a "please run `viam login`" message. `viam module generate`, however, will do much of the work happily even if not logged in (e.g., it will run all the user prompting and take in inputs), and then only at the last moment will it try to log in. The behavior after login is inconsistent, however. While I have had no problems with the job successfully logging in and completing, @felixreichenbach, @stevebriskin, and @npentrel have all had issues where the job then failed and had to be rerun. This is a frustrating case because there is non-trivial time and work done in the steps leading up to that failure (e.g., filling out all the user …
> RSDK-9452 - require logged in status for module generation

- services/datamanager/builtin/sync/connectivity.go
- on windows only, in `isOffline`, temporarily increase the timeout, and add a second attempt
- (incidental) close the temporary connection
I'm not sure if a specific test machine is on a slow network, or if this is an OS-specific issue, but this is a hack to make this check more forgiving until RSDK-8344 lands.
> special-case datamanager sync.isOffline on windows

- cli/module_generate.go
- cli/module_generate/_templates/README.md
- cli/module_generate/modulegen/inputs.go
- cli/module_generate_test.go
- cli/module_registry.go
Generates a base README.md for modules created with `viam module generate`. The template is inspired by our [docs](https://docs.viam.com/operate/get-started/other-hardware/#upload-your-module) readme example. Meta.json is updated to have a relative link to the model level documentation of the readme. I adjusted the template with this feature in mind, attempting to reduce repetitive sentences "to configure a component/service go to..." and "This is a model that implements the ... API" so that the docs embedded in the app are to the point.
Tested the generator locally:
`go run cli/viam/main.go module generate`
Selected: "my-module-4", "test" namespace, Python, Arm Component, "my-model-4", Use CloudBuild, Register with Viam.
Generated markdown:
```markdown
TODO: Provide a description of the …
```
> APP-7171: Add README.md to module generate CLI

- components/generic/generic.go
- components/gripper/gripper.go
Added gripper  as it was missing.
Added generic to fit the pattern.
> Add generic and gripper `FromDependencies` methods

- robot/web/stream/server.go
- robot/web/stream/state/state.go
This PR adds a check before refreshing a video source to see if it is in resized mode. If the streamState is resized, we re-apply the resize transformation before swapping.
- fake camera
- maintains resize state through reconfigures ✅ 
- toggle animated flag ✅ 
- webcam
- maintains resize state through reconfigures ✅ 
- can change video_path ✅ 
- viamrtsp
- maintains resize state through reconfigures ✅ 
- can change rtsp url ✅
> [RSDK-9703] - Maintain dynamic resolution preference through reconfigures

- cli/module_generate/scripts/generate_stubs.py
Changes:
- generated module resources will now include async functions from `ComponentBase` or `ServiceBase`
Arm Component:
Vision Service:
> RSDK-9778: add resource base stubs to python modules

- components/button/button.go
- components/button/button_test.go
- components/button/client.go
- components/button/client_test.go
- components/button/fake/button.go
- components/button/fake/button_test.go
- components/button/register/register.go
- components/button/server.go
- components/button/server_test.go
- components/button/verify_main_test.go
- components/register/all.go
- testutils/inject/button.go
This adds the button client and server, and registers a button fake model.
Here's a button component properly configured in app:
1. https://github.com/viamrobotics/api/pull/619
2. #4740
3. #4741 
I used Cursor quite a bit here:
- Bump `go.viam.com/api` version
- Add `Button` SDK helpers
- Add client and tests
- Add server and tests
- Add inject testutil
- Add fake button implementation and register it
- This implementation just logs a message when pushed
- Code review
- Try a config with the button fake - does it work as expected?
> APP-7497: Add Button client, server, and fake model

- components/register/all.go
- components/switch/client.go
- components/switch/client_test.go
- components/switch/fake/switch.go
- components/switch/fake/switch_test.go
- components/switch/register/register.go
- components/switch/server.go
- components/switch/server_test.go
- components/switch/switch.go
- components/switch/switch_test.go
- testutils/inject/switch.go
This adds the switch client and server, and registers switch 2-way, 3-way, and 10-way fake models.
Here are switch components properly configured in app:
1. https://github.com/viamrobotics/api/pull/619
2. #4740
3. #4741
I used Cursor quite a bit here:
- Add `Switch` SDK helpers
- Add client and tests
- Add server and tests
- Add inject testutil
- Add fake switch implementations and register them
- Code review
- Try a config with the switch fakes - does they work as expected?
> APP-7497: Add Switch client, server, and fake models

- config/reader.go
- grpc/app_conn.go
- logging/net_appender.go
- web/server/entrypoint.go
- web/server/restart_checker.go
This PR accomplishes two main things:
1) creates a new type to implement the  [`rpc.ClientConn`](https://github.com/viamrobotics/goutils/blob/main/rpc/dialer.go#L65) interface that we'll use as our one global connection to app in [unifying](https://viam.atlassian.net/browse/RSDK-8291) the many that already exist.
2) uses said global connection to replace (or unify, rather) the two separate connections currently created in our `NetAppender` and `RestartChecker`.
The global connection works as follows. It's first instantiated - and thus made available to the entire RDK server - when the NetAppender is created in [web/server/entrypoint.go](https://github.com/viamrobotics/rdk/blob/main/web/server/entrypoint.go#L194). This could change in coming PR's as more connections are roped into this …
> [RSDK-8292] Create Single App Connection and Use for Net Appender and Restart Checker

- packaging.make
- in `make static-release-win`, change output path from `windows-BUILD_CHANNEL-uname.exe` to `BUILD_CHANNEL-windows-uname` (no exe)
Previous attempt wasn't working with the discovery regex.
Working and non-working patterns in prod:
- non-working: `viam-server-windows-v0.60.1-x86_64.exe`
- working: `viam-server-v0.60.1-windows-x86_64`
I ran this locally and got:
```sh
$ ls etc/packaging/static/deploy
viam-server-local-windows-x86_64
```
> APP-7356 alter windows release filename to work with discovery

- web/server/entrypoint.go
- web/server/restart_checker.go
After [unifying](https://github.com/viamrobotics/rdk/pull/4746) the connections to App used by RDK's net appender and restart checker, we realized that the lifecycle of the connection they now share should not be managed by either of them. The net appender already does not manage it (i.e., it never tries to close it), but the restart checker _does_ try to close the connection. This PR stops the restart checker from closing it and instead closes the connection when the server exits - once we know it [the connection] isn't getting used anymore. This oversight became apparent through the logs below. The net appender was incorrectly logging messages in its queue because the restart checker was closing the connection required for the logging to succeed.
`2025-01-30T15:03:54.717Z        INFO …
> [RSDK-9869] Globally Manage Lifecycle of Shared Connection to App

- grpc/interceptors.go
- module/modmanager/manager.go
- module/module.go
- module/testmodule/main.go
- robot/client/client.go
- robot/client/client_options.go
- robot/impl/local_robot_test.go
- robot/web/web.go
Pass a VIAM_MODULE_NAME env variable to module processes.
> RSDK-9818: Annotate gRPC requests from modules to the viam-server with module names.

- robot/web/stream/backoff.go
- robot/web/stream/stream_c.go
- robot/web/stream/stream_notc.go
- robot/web/web.go
- robot/web/web_c.go
- robot/web/web_notc.go
The webstream package is now always imported. Split up webstream package into C and not-C pieces to accommodate this.
> RSDK-9878: Move webService into web.go.

- ftdc/cmd/parser.go
- ftdc/sys/net.go
- robot/impl/local_robot.go
This continues to add more usages to the prometheus procfs library. The new usages read from 3 files:
- `/proc/net/dev` (this powers the numbers in `ifconfig`)
- `/proc/net/tcp` (i.e: grpc to app)
- `/proc/net/udp` (i.e: webrtc)
How the graph looks before the `parser.go` changes:
How the graph looks after the `parser.go` changes:
> RSDK-9885: Add network stats to ftdc.

- cli/module_generate/scripts/generate_stubs.py
The `|` character was only introduced in Python 3.10. Using `Union` instead so that 3.9 can be supported
> RSDK-9744: support module generation in python 3.9

- cli/auth.go
Stop erroring when unable to refresh token in login action.
~~Not tested; I believe this only arises after someone has been logged in for more than 24 hours such that a new login action is required, and then tries to run `viam login` without running an intervening command that causes a logout first. However, the change is fairly straightforward so I think it's probably fine. If people want testing to confirm, I can do so tomorrow (Tuesday, February 4th, 2025).~~
Tested locally, it works.
> RSDK-9882 - stop erroring out when unable to refresh token on login

- cli/module_generate.go
We weren't requiring namespaces when calling `module generate` with an Org ID, which allowed models to be: `:module:component`. In the `meta.json`, the model triplet would show up to be `xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx:module:component`.
Changes:
- Fix the order so that the generated `meta.json` has the updated information.
- Require a namespace for the organization
> RSDK-9910: require namespace for module generation

- components/camera/videosource/webcam.go
[RSDK-6861](https://viam.atlassian.net/browse/RSDK-6861)
See the +diffed comment for a good description of what's going on here.
Tested with the problematic camera listed in Jira (Logitech C90 Pro). It now selects a 640x480 res by default instead of the tiny one from before.
[RSDK-6861]: https://viam.atlassian.net/browse/RSDK-6861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [RSDK-6861] - For webcams, default to standard resolution if available

- cli/data.go
- cli/data_test.go
If user wants to upload an arbitrary file with a filepath that contains a `/.viam/capture/` in the middle, ie Users/gloriacai/.viam/capture/123,  it would download as data/Users/gloriacai123. This PR fixes this missing backslash issue and removes the preceding directories for the /.viam/capture/ case.
Testing:
- added some testcases with nested ./viam/capture directories
- uploaded a file with filepath Users/gloriacai/.viam/capture/123, ran `go run cli/viam/main.go data export binary --destination="." --start=2025-02-06T14:00:00Z` and checked that the file downloaded directly inside the data folder.
> DATA-3698: fix weird file path behavior with export

- ml/api.go
- ml/classifications.go
- ml/ml.go
- services/mlmodel/client.go
- services/mlmodel/mlmodel_test.go
- services/mlmodel/server.go
- services/vision/mlvision/classifier.go
- services/vision/mlvision/detector.go
- services/vision/mlvision/ml_model.go
In app, for the Cloud ML model service, we will need to have code that basically looks at flat tensors and then parses the relevant classifications from them. This is essentially duplicated in the vision service, since that it almost exactly what we do. 
Please cross-reference this PR for a WIP of what we're trying to accomplish: https://github.com/viamrobotics/app/pull/7458 
I am mainly looking for feedback on whether:
a) this refactoring makes sense
b) if this where all the code should live
c) if you want me to add any more tests to make sure I didn't break anything 
I used the EfficientNet-ImageNet2012 model that's in production and configured a vision service locally using the changes in RDK (above) and compared against stable RDK (below)
> DATA-3461 - Refactoring code for classifications 

- cli/app.go
- cli/data.go
- Renames `dataset data remove` to `dataset data remove ids` 
- Creates new command `dataset data remove filter`
Manually tested:
`viam dataset data add ids --dataset-id=67a512205da1bc26ca01cd5a --location-id=nihu6z0k8c --org-id=0fbe951e-d4c6-427f-985f-784b7b85842c --file-ids=rXu0LkivJtEZojTkmO86xdy5Ft3QovKQfYo17a6EsCNhgCPngHGgab9zj6jCpwLK,9kw4DyE5qxYai0c86xzXXyQNnpN2K26FKT3UzM68WdwmhB4zNValb4bSKkvl7b5V`
`viam dataset data remove filter --dataset-id=67a512205da1bc26ca01cd5a --location-ids=nihu6z0k8c --start=2023-01-01T05:00:00.000Z --end=2024-10-01T04:00:00.000Z --tags=blue_star`
- Both commands correctly add and remove images from dataset
> DATA-3399: Dataset Data Remove Functions

- cli/app.go
- cli/flags.go
- cli/flags_test.go
Updates the `String` method of `AliasStringFlag` to hide aliases, and ensures that `AliasStringFlag` is used consistently for `organization`, `location`, `machine`, and `part`.
Note: I opted to update `AliasStringFlag` rather than creating a new `InvisibleAliasStringFlag` type. My reasoning was 1) avoiding excessive type proliferation is a good thing, and 2) the only places `AliasStringFlag` was being used was for org/location/machine/part, so after this PR it wasn't actually being used anywhere. However, if in the future we have a string flag that is required and has aliases that we _don't_ want to hide in the help text, we may have to revisit. Happy to discuss the decision here if there's any pushback.
Tested locally to confirm the new help text, and to confirm that despite not …
> RSDK-9884 - support invisible aliases

- robot/server/server.go
Still need to talk with @abe-winter about why this might be necessary, and double check that everything still actually works (tests still seem to pass.)
> RSDK-9972 Update server tunnel to connect to 127.0.0.1 instead of localhost

- packaging.make
In the `static-release-win` makefile target, correct the filename pattern of the manifest json.
The json filename has to agree with the `subsystemParsedName.objectPath` function in the backend job that consumes this.
This is confusing because the filename pattern of the executable is different from the name pattern of the json file, but it's compatible with the logic we have. I could alternatively patch this on the backend, but I'm slightly concerned about creating incompatibility with previous deploys, so I went with this approach.
> correct manifest filename in `static-release-win` target

- cli/app.go
In the CLI docstring for `viam module build upload`, replace `os_codename` with `codename`.
To agree with the actual tag key [here](https://github.com/viamrobotics/rdk/blob/5e0a4e281881823b39dba3683deb70704235af95/config/platform.go#L135):
```go
tags = appendPairIfNonempty(tags, "codename", osRelease["VERSION_CODENAME"])
```
> rename os_codename to codename in docstring

- cli/auth.go
maybe there's a better way to figure out which auth method we're using, but I saw this pattern in a few other places so thought this is fine for now
tested connecting with robot parts with both an api key (both robot-scoped and org-scoped) login and a regular app.viam login
cc: @njooma
> RSDK-10006 - Fix dials to robot when using api key authentication

- components/arm/server.go
This fixes a bug that surfaced when trying to get an arm module in c++ that returns the "unimplemented" string to return geometries.  Now instead of a naive check we check for the existence of the word anywhere in the error.
> make geometry construction from kinematics work with  modules written with non-go SDKs

- app/data_client.go
- app/data_client_test.go
- testutils/inject/data_service_client.go
Hey folks, we are deprecating this API, so I'm starting to remove references of it from RDK and app.
> Remove TagsByFilter in preparation of deprecating API

- components/posetracker/client.go
- components/posetracker/client_test.go
- components/posetracker/pose_tracker.go
- components/posetracker/server_test.go
- testutils/inject/pose_tracker.go
This code hasn't been touched in a couple years because its not a super popular component.  This PR does two things:
- change the return type of the `Poses` method to be compatible with more recent motion/frame system code
- removes the `Readings` function from the interface.  It is not supported in the proto definition of the component and now that the `Sensor` service has been removed there is nothing that can even call this anymore using our module based paradigm
> clean up the PoseTracker interface

- gostream/swapper.go
See [ticket](https://viam.atlassian.net/browse/RSDK-9664) for Dan's detailed explanation of deadlock case. This PR simply removes holding the read lock during `init` calls to avoid the case where a swap is hit during initialization. 
Added Dan's patch to sleep for a second in `init` to repro the deadlock. See how the tests are now passing in CI.
> [RSDK-9664] - Fix deadlock in hotSwappableMediaSource

- ftdc/ftdc.go
in some machines, the current limits means ~8hrs of data, this aims to get the limit closer to 1 week of data (200mbs should is 20x of 10mb, which is the current limit)
> RSDK-10057 - up limits on FTDC local storage

- cli/auth.go
- cli/client.go
- cli/data.go
- cli/dataset.go
- cli/ml_training.go
- cli/module_build.go
- cli/module_generate.go
- cli/module_registry.go
- cli/packages.go
`ensureLoggedIn` has turned into a gotcha where everyone adding a new CLI command is responsible for calling it themselves or else risking trying to run actions without being logged in. This feature creates a single canonical call site when a viam client is first created (except when running a login action) so that no one has to think about this anymore!
Tested locally after logging out. For non-login actions (e.g. `viam organizations list` and `viam module generate`), being logged out resulted in an error. for `viam login`, the normal login process proceeded as normal.
> RSDK-9758 - refactor ensureLoggedIn call sites

- gostream/codec/x264/encoder.go
- gostream/codec/x264/encoder_test.go
- gostream/codec/x264/utils.go
- robot/web/stream/server.go
This PR gives a more accurate bitrate estimation to our libx264 pipeline based on resolution and framerate. The idea here is that smaller streams will use less bandwidth and we will get better quality out of larger streams.
- Removes hardcoded 3.2 Mbps bitrate.
- Adds look up for framerate from Properties and if it is not found default to 30. 
- Calculates bitrate using a reasonable 0.15 bits per pixel ratio.
- Adds minimum bitrate to avoid buffering issues with small frame sizes.
- Adds a maximum bitrate that is safely over 20fps 4k stream size.
Examples bitrates:
```
640p at 30 fps: 640*480*30*0.15 - > 1.382400 Mbps
1080p at 30fps : 1920*1080*30*0.15 -> 9.331200 Mbps
4k at 20fps: 3840*2160*20*0.15 -> 24.883200 Mbps
```
- add unit test for bitrate calculation ✅ 
- webcam
- picks up …
> [RSDK-6469]  Set x264 bitrate based on resolution and fps

- config/proto_conversions.go
- config/proto_conversions_test.go
- resource/name.go
allows for all types of malformed names to pass on MaintenanceConfigToProto, issue was that any errors were preventing configs from returning from the config endpoint
this will allow for some janky resource names on both sides of the conversion (ToProto and FromProto), but the hope is that validation will take care of it
> RSDK-10112 - Fix maintenance config to proto

- .github/workflows/staticbuild.yml
- .gitignore
- Makefile
- etc/dev-version.sh
- packaging.make
Previously we'd been building "latest" as timestamp (20250304121314) style "versions." This switches to using a semantic version compatible format with a "dev" prerelease tag. It also embeds that version properly in builds.
This will be picked up by upcoming changes in App, along with similar work for Agent.
> [RSDK-7007] Update CI to build semver "dev" versions for latest

- cli/client.go
- cli/config.go
Adds better warnings on out-of-date CLI. The logic flow is as such:
- Determine the local version and the latest version.
-- if both can be determined and the local version is older than the latest version, emit warning and return
-- if both can be determined and the local version is _not_ older than the latest version, then emit no warning and return
- if local version and/or latest version can't be determined, then determine when the binary was built.
-- if we can't determine when the binary was built, return
-- if we _can_ determine when the binary was built, emit a warning if it's more than a week old
Tested locally by artificially amending the version tag and build window (from one week to one second), confirmed the cases worked as described.
> RSDK-10041 - better warnings on out-of-date CLI

- cli/module_generate.go
- cli/module_generate/_templates/go/.gitignore
- cli/module_generate/_templates/go/cmd/cli/tmpl-main.go
- cli/module_generate/_templates/go/tmpl-Makefile
- cli/module_generate/_templates/go/tmpl-module.go
- cli/module_generate/scripts/tmpl-module
I just went with the reviewer suggestions, no idea if these are right
> 20250301 go template tweaks

- cli/profile.go
Makes sure that when `viam profile update` is called, we actually store an updated config.
Tested locally, was able to create a poorly formatted profile, then run `viam profile update` on it, then successfully use it.
> RSDK-9978 - fix profile updating

- robot/client/client.go
- robot/client/client_options.go
Adds `initialDialAttempts` to robot client options, to indicate the number of attempts when initially dialing.
I opted not to include a timeout, under the thinking that adding a timeout to a context is the more idiomatic way to work with timeouts in go (and is already respected by the `dial` func in goutils).
> RSDK-6155 - add initialDialAttempts to robot client options

- cli/module_build.go
- cli/module_reload.go
- cli/module_reload_test.go
[Ticket](https://viam.atlassian.net/browse/APP-7537)
When developing a registry module, users often want to temporarily point a part to the local version of the module that has the changes they're making on it. The `viam module reload` command currently does this by overwriting the `execution_path` setting in the config. However, this is a destructive change, so when they user wants to switch the part back to using the registry version of the module, they have to look back at its history and figure out what the config used to be and either revert or paste that old setting back in.
With this PR we're instead going to write this local dev path to a new field called `reload_path` and set `reload_enabled` to true. We've already made changes in the app backend to reference these fields when …
> APP-7537: Update `viam module reload` to set "reload_path" instead of overwriting "execution_path"

- robot/server/server.go
- tunnel/tunnel.go
- web/server/entrypoint_test.go
RSDK-9852
RSDK-9763
Actually honors valued specified in `traffic_tunnel_endpoints`. Adds E2E test for tunneling.
cc @abe-winter  + @njooma
> Honor `traffic_tunnel_endpoints` and test tunneling E2E

- components/camera/camera.go
- components/camera/transformpipeline/mods_test.go
- components/camera/transformpipeline/pipeline.go
- components/camera/transformpipeline/pipeline_test.go
- rimage/depth_map_raw.go
- rimage/image_file.go
- rimage/lazy_encoded.go
- rimage/lazy_encoded_test.go
- robot/web/stream/camera/camera.go
- robot/web/stream/camera/camera_test.go
- robot/web/stream/server.go
Essential changes
- Change signature of camerautils `VideoSourceFromCamera` to return an error in order to report the lazy encoding failure to the stream server safely
- Made the decode and decodeConfig methods on lazy encoded images public so we can call them and check for errors instead of doing it in the `image.Image` methods `Bounds` `At` and `ColorModel` methods which give no ways to return errors and forces a panic when decoding fails. 
- Added notes to use these util methods and check for errors before using `image.Image` methods.
This is no longer a breaking change because it is an additive change to the `LazyEncodedImage` struct.
It is an alternative to un-Golang-ly directly recovering from panics.
Tested with machine config with Rand's malformed camera that returns bad lazy …
> [RSDK-10100, RSDK-10111] - Add utils to lazy encoded image to decode and return errors instead of panic-ing always

- cli/auth.go
Trying to debug why sometimes we get refresh errors, but the existing code was replacing the refresh error with a different error (or nil) from `getGlobalArgs`. Because that function is only used for setting a debug flag and shouldn't break the rest of the code, I updated the code to basically ignore that error. 
Hopefully we can get improved error messaging when this refresh issue happens now.
> [RSDK-10205] Ignore the error of getGlobalArgs

- cli/client.go
- cli/client_test.go
RSDK-9865
Adds an E2E CLI test for tunneling that is almost identical to the one that will be introduced in https://github.com/viamrobotics/rdk/pull/4839. 
We want to ensure that CLI tunneling and programmatic tunneling (manually utilizing `RobotClient.Tunnel`) work, so while the tests are repetitive, they are likely both necessary, and I was not feeling up to somehow consolidating their common code 😆.
> RSDK-9865 Add E2E CLI test for tunneling

- module/log.go
RSDK-10245
Uses `VIAM_MODULE_NAME` as the logger name for loggers created through `NewLoggerFromArgs` if passed in `moduleName` is `""`.
Golang modular resource logs that used to look like:
```
2025-03-12T19:20:59.145Z	INFO	rdk:component:generic/counter1	simplemodule/module.go:37	Creating a new counter component!	{"log_ts":"2025-03-12T19:20:59.144Z"}
```
now look like:
```
2025-03-12T19:21:52.640Z	INFO	SimpleModule.rdk:component:generic/counter1	simplemodule/module.go:37	Creating a new counter component!	{"log_ts":"2025-03-12T19:21:52.640Z"}
```
> RSDK-10245 Use VIAM_MODULE_NAME as logger name for golang module loggers

- etc/dev-version.sh
One liner to fix the sorting of versions so that -rc is sorted as BEFORE the stable version.
> [APP-7829] Fix tag sorting when -rc involved

- cli/client_test.go
- web/server/entrypoint_test.go
@cheukt would be nice to skip these for now. Don't know if I'll have time to fix before going OOO, and they are causing failures on the main branch (only with 32-bit.) Can diagnose further once I get back.
> RSDK-10246 Skip E2E tunnel tests on 32 bit arch for now

- ftdc/sys/net.go
RSDK-10247
I _think_ `netStatser.fs.NetUDPSummary()` can return `nil` and cause a npe in some circumstances (after robot close maybe?) Guarded the one actual dereference (the calls above don't cause issue.)
I saw this stack trace from a new test I was writing:
```
goroutine 236 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:26 +0x67
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:18 +0x1d
go.viam.com/utils.PanicCapturingGoWithCallback.func1.1()
/home/testbot/go/pkg/mod/go.viam.com/utils@v0.1.132/runtime.go:146 +0x65
panic({0x35e85a0?, 0x53a1280?})
/usr/local/go/src/runtime/panic.go:785 +0x132
go.viam.com/rdk/ftdc/sys.(*netStatser).Stats(0xc000cb8678)
/host/ftdc/sys/net.go:70 +0x23c
go.viam.com/rdk/ftdc.(*FTDC).constructDatum(0xc000396600) …
```
> RSDK-10247 Guard FTDC net dereference

- config/reader.go
- config/reader_ext_test.go
did a dumb thing and was making a copy (since we're passing by value) before modifying, so we end up losing the modifications
> RSDK-10227 - Propagate env vars for local modules

- cli/client_test.go
- robot/client/client.go
- tunnel/tunnel.go
- web/server/entrypoint_test.go
RSDK-10246
- Unskips `TestTunnelE2E` and `TestTunnelE2ECLI`
- "Fixes" ordering for those tests (cancels context at "correct" time)
- Swallows more errors in `filterError` for tunneling code
Tests passed ~200 times on blinky with this change where they used to fail about 1 every 20 times.
cc @dgottlieb
> RSDK-10246 Fix `TestTunnelE2E*` tests

- components/camera/fake/image_file.go
- components/camera/register/register_cgo_android.go
- services/register/all.go
- services/register/all_cgo_droid.go
- add back some components and services in no_cgo mode
Needed on a no_cgo platform (and C dependency cleanup work has made this easy).
> in no_cgo mode, flag on image_file camera and vision services

- cli/client_test.go
- web/server/entrypoint_test.go
Disable 2 e2e tunnel tests
Temporarily disabling flaky tests pending fix
> temporarily disable e2e tunnel tests

- app/viam_client.go
- app/viam_client_test.go
Adds support for building an app client from env vars, to be used within modular resources.
Blocked on release of https://github.com/viamrobotics/rdk/pull/4853
> RSDK-10211 - create app client from env vars

- motionplan/collision.go
- motionplan/planManager.go
Include origin frame geoms in collision spec in case where specified frame is a Transform rather than an RDK component.
> RSDK-10319 fix collision spec for origin frames.

- cli/client.go
- cli/client_test.go
maybe merge next week to allow for the rollout of config changes first.
example output
```
❯ viam machine part tunnel --part XXXX --destination-port 1010 --local-port 8888
Error: Tunneling to destination port 1010 not allowed.
```
> RSDK-10257 - Early return if tunnel destination port not allowed

- config/config.go
- robot/packages/cloud_package_manager.go
* Update PackageConfig.SanitizedName() to use strings.ReplaceAll(p.Package, "/", "-") as PackageConfig.Package is always set as "{org_id}/{package_name}", this had the unintended consequence of causing packages modules to be installed in a different directory structure than in Unix which caused CloudPackageManager to fail to cleanup packages in Windows.
https://viam.atlassian.net/browse/APP-7918
> Update CloudPackageManager to cleanup in Windows

- cli/module_registry.go
- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/server.go
- robot/impl/local_robot.go
- robot/impl/resource_manager.go
- utils/env.go
- add cleanWindowsUDS function to clean unix socket paths on windows hosts, so they're compatible w/ the grpc library
- still respect VIAM_TCP_SOCKETS env var, but don't force-activate it on goos=windows
The `url.Parse` call in the (3rd-party) grpc library, [here](https://github.com/grpc/grpc-go/blob/v1.71.0/clientconn.go#L1720-L1727), as well as its direct caller, become unhappy in various ways when given windows-looking filesystem paths. This PR works around that by formatting the paths in a way it likes.
To see this fail in the small, do:
```golang
urls := []string{
"unix://C:\\hello\\whatever.sock",
"unix://\\hello\\whatever.sock",
"unix://C:/hello/whatever.sock",
"unix:///hello/whatever.sock",
}
for i, raw := range urls {
if u, err := url.Parse(raw); err != nil {
println("err", i, …
```
> APP-7464 support unix sockets on windows OS

- cli/app.go
- cli/client.go
Update the CLI and API to match the UI change by setting the default log time filter to 12 hours instead of 1 day.
**See ticket [here](https://viam.atlassian.net/browse/APP-7845)**
- https://github.com/viamrobotics/rdk/pull/4857
```
viam machines logs -machine="mac" --organization="Joseph's Org" --location="First Location" 
```
```
viam machines logs -machine="mac" --organization="Joseph's Org" --location="First Location" --start="2025-03-31T00:00:00Z"
```
```
go run cli/viam/main.go machines logs -machine="mac" --organization="Joseph's Org" --location="First Location"
```
```
go run cli/viam/main.go machines logs -machine="mac" --organization="Joseph's Org" --location="First Location" --start="2025-03-30T11:00:00Z"
```
> [APP-7694] Change logs default to twelve hours

- services/vision/colordetector/color_detector.go
- services/vision/colordetector/color_detector_test.go
- services/vision/detectionstosegments/detections_to_3dsegments.go
- services/vision/detectionstosegments/detections_to_3dsegments_test.go
- services/vision/fake/vision.go
- services/vision/mlvision/ml_model.go
- services/vision/mlvision/ml_model_test.go
- services/vision/obstaclesdepth/obstacles_depth.go
- services/vision/obstaclesdepth/obstacles_depth_test.go
- services/vision/obstaclesdistance/obstacles_distance.go
- services/vision/obstaclesdistance/obstacles_distance_test.go
- services/vision/obstaclespointcloud/obstacles_pointcloud.go
- services/vision/obstaclespointcloud/obstacles_pointcloud_test.go
- services/vision/vision.go
- services/vision/vision_test.go
- vision/objectdetection/color_detector.go
- vision/segmentation/detections_to_objects.go
- vision/segmentation/er_ccl_clustering.go
- Also tested locally and everything works fine
- I would imagine that this would require a docs change  
- as of this writing, verdict is still out on if this is a breaking change or not
> [RSDK-10350] - Add a `default-camera` attribute to vizModel

- components/camera/transformpipeline/mods.go
- services/vision/client.go
- services/vision/client_test.go
- services/vision/collectors_test.go
- services/vision/detectionstosegments/detections_to_3dsegments_test.go
- services/vision/fake/vision.go
- services/vision/mlvision/detector.go
- services/vision/server.go
- services/vision/server_test.go
- services/vision/vision_test.go
- vision/objectdetection/connected_components_detector.go
- vision/objectdetection/detector.go
- vision/objectdetection/detector_test.go
- vision/objectdetection/postprocessor_test.go
Here we're adding normalized bounding boxes to RDK by incorporating it into our idea of a "Detection".  I've edited the Detection constructor to take in the image bounds so the calculations can happen. See scope: (https://docs.google.com/document/d/1cezhhCrPOi6ANjo7laOZ_CBzvZxi7Ea4zx3qgrolwks/edit?tab=t.0#heading=h.tcicyojyqi6c) 
I've also included a "no img bounds" constructor.  Server and client side code were updated and tests were updated as well to include/test the new changes.
> RSDK-10142 - Add relative (normalized) bounding boxes to RDK

- services/motion/builtin/builtin.go
Tested and confirmed we still get logs to the specified file, while also no longer having the assorted issues we have also been encountering when using non-builtin motion services.
> RSDK-10376 Fix motion service file logging

- gostream/stream.go
Simply moving from 30fps to 20fps livestream poller.
Tested that we see appropriate reduction in CPU utilization.
- Small frame size (352x240) goes from 40% to 30% on a Jetson Orin Nano.
> [RSDK-9079] - Move to 20fps livestream default

- robot/web/stream/backoff.go
- robot/web/stream/server.go
Currently, we are not setting the Cooldown backoff option. This means our backoff log throttle for livestreams has not been functional.
Tested with a fake camera with bursty error returns. The Image endpoint returns an error in the 8-10 second range with following logic:
```
elapsed := int(time.Since(c.startTime).Seconds()) % 10
if elapsed >= 8 && elapsed < 10 {
return nil, nil, errors.New("fake camera read error")
}
```
Upstream behavior without cooldown (essentially no backoff)
- We get 10s of errors per minute, however, the errors are swallowed up decently well from the logger. See [here](https://github.com/viamrobotics/rdk/blob/main/logging/impl.go#L276).
- No actual backoff, we continue to query Image endpoint even if the same error is returned multiple times in a row. …
> [RSDK-7085] - Set cooldown option for streaming err backoff

- cli/module_generate.go
Actually sets a default for the meta.json markdown description, to the `README.md` when you run `viam module generate`
> APP-8007 Set default for module readme link

- robot/web/options/options.go
- robot/web/web.go
- web/server/entrypoint.go
tested the ts sdk vanilla end to end and it does work without internet
run rdk with `go run web/cmd/server/main.go -config <CONFIG> -no-tls`
however, the example has to be updated slightly
```
machine = await VIAM.createRobotClient({
host: HOST,
credentials: {
type: 'api-key',
payload: API_KEY,
authEntity: API_KEY_ID,
},
signalingAddress: `http://${HOST}.local:8080`,
reconnectAbortSignal,
});
```
cc: @stuqdog @ale7714
> RSDK-10410 - Add No TLS option

- config/reader.go
- add `r.Close` call before `clearCache`
There are various scenarios where the cached json config gets corrupted, so we have a `clearCache` function in config/reader.go which deletes the cache after a json parse failure. This allows RDK to recover after a restart (if online).
On windows, the current setup gives a 'process cannot access the file because it is being used by another process' at debug level (from unchecked error function) inside clearCache.
This PR closes the file before deleting it.
Please review the double-close pattern readFromCache + confirm that this is safe / best practice
> APP-8020 fix clearCache on windows

- motionplan/rrt.go
This PR changes the default planner iterations for rrt* to 1500 instead of 3000.
> Change default iterations to 1500

- cli/module_generate.go
- cli/module_registry.go
Automatically looks for the top-level README.md if no `markdown_link` is included in `meta.json` and logs warnings if no README is found
> APP-8012 reading module markdown from root level README if not included in meta json

- .github/workflows/test.yml
- add `windows` job to test.yml
Coverage on windows
> run a subset of the test suite on windows in test.yml

- module/modmanager/manager.go
- module/modmanager/manager_test.go
Abe and I found a situation where if two modules point to the same ExePath, the module will be loaded twice and neither will work. This validation check will error on adding the 2nd module from the config when the ExePath exists.
For example this config is currently an issue:
```
{
"type": "registry",
"name": "michaellee1019_gpio-flicker_from_reload",
"module_id": "michaellee1019:gpio-flicker",
"version": "latest-with-prerelease",
"reload_path": "/root/.viam/packages-local/michaellee1019_gpio-flicker_from_reload-bin-module.tar.gz",
"reload_enabled": true
},
{
"type": "local",
"name": "michaellee1019_gpio-flicker_from_reload-local",
"executable_path": "/root/.viam/packages-local/michaellee1019_gpio-flicker_from_reload-bin-module.tar.gz"
}
```
Tested on a machine in my personal org …
> APP-7995: Don't allow two module configs to point to same ExePath

- utils/env.go
- utils/env_posix.go
- utils/env_windows.go
- On windows systems older than build 17063, default VIAM_TCP_SOCKETS to true
- (but if a value is given for VIAM_TCP_SOCKETS, it will be respected)
AF_UNIX socket type was only added 8 years ago https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
Confirmed via logs that this does the right thing on a recent version of windows:
> 4/25/2025, 3:44:32 PM info rdk.modmanager.awinter_stopper.StdOut   pexec/managed_process.go:297   \_ 2025-04-25T19:44:32.574Z INFO awinter_stopper client/client.go:437 successfully (re)connected to remote at address {"address":"unix:///Users/admin/AppData/Local/Temp/viam-module-3635204454/parent.sock"} 
^ the address is a socket as expected
> RSDK-10104 default to tcp sockets on old windows versions

- logging/appender.go
- logging/proto_conversions.go
- logging/proto_conversions_test.go
The server was crashing when modules sent logs containing certain types. This seems to be because zap enforces some invariants on `zap.Field` instances that we break when serializing them to protobuf. This PR:
1) Adds code to sanitize incoming log fields so they can be printed.
2) Adds a recover just above where we convert those fields into json to be printed so if we break zap again in the future we at least won't crash the entire server.
> APP-8080: Fixing RDK crash when processing logs with certain data types

- motionplan/motionPlanner.go
In the case where validity checking of IK solutions takes longer than the actual generation of those solutions, the channel used to communicate solutions can fill up.
In these cases, in the case of a failed context, the individual solvers will wait on trying to write to the passed solver channel, causing an indefinite deadlock.
The quickest solution is to explicitly clear the channel in these cases. Additionally, as we do not want our IK workers to be idle, we should increase the size of our solution buffer.
> RSDK-10603 Fix deadlock

- cli/app.go
- config/module.go
- robot/packages/local_package_manager.go
- utils/env.go
- utils/file.go
- utils/file_test.go
- ~when hot reloading from CLI, default `--home` to `~` instead of `/root`~ -> nope, postponing this, see below
- add `ExpandHomeDir` util with unit test
- use ExpandHomeDir in module EvaluateExePath, module validate, and the package manager's local file copy helper
Without this, there are ~5 potential values for `--home` in hot reloading, depending on OS and how viam is running (agent vs local mode).
We originally made this user-configurable bc it was simpler, but the hot reloading feature has spread to more users and more platforms so we are beefing it up.
Did a hot reload on my system, it worked
After one stable release cycle, make `~` the default `--home` in the CLI reload command
> APP-7945 support tilde in hot reloading

- cli/module_generate/scripts/generate_stubs.go
- cli/module_generate_test.go
The old system called github servers to download client code and generate stubs. The new system embeds a current version of the client code. Addresses [RSDK-10606](https://viam.atlassian.net/browse/RSDK-10606)
[RSDK-10606]: https://viam.atlassian.net/browse/RSDK-10606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [RSDK-10606] Allow for offline testing of go stubs generation

- .github/workflows/appimage.yml
- remove double `pip install` of appimage build on 32 bit appimage job
32 bit appimage builds started failing on main. (Example [here](https://github.com/viamrobotics/rdk/actions/runs/14759716922/job/41438555379)).
This has been broken since I originally wrote it (`pip install appimage-builder git+appimage-builder` pattern is installing it twice + leaving ambiguous which version ends up in charge). Not sure why it started failing suddenly, best guess is pip upgrades in the setup-python action. Could potentially confirm this by testing a range of pip versions.
- do we still need the appimage for 32-bit, or could we just have the static build?
- should we make 32-bit a no_cgo build rather than setting up a docker cross environment?
> fix failing step in 32-bit appimage build

- robot/client/client.go
- robot/impl/local_robot.go
- robot/impl/local_robot_test.go
- robot/impl/resource_manager.go
- robot/impl/resource_manager_test.go
- robot/impl/robot_reconfigure_test.go
- robot/robot.go
- testutils/inject/robot.go
This PR removes the process manager from the RDK and effectively deprecates processes. Whenever a config is changed and there is processes in the config, an error message will appear in the logs.
Regarding usage of processes. I did an audit of usage as part of the scope and have also talked with SEs internally. There are a few internal projects running processes that will need a new solution. Otherwise we are ok to deprecate.
> Deprecate processes in viam-server

- .github/workflows/cli.yml
- .github/workflows/pullrequest-trusted.yml
- add a 'pr' release_type to cli.yml which doesn't upload to GCP
- call cli.yml from pullrequest-trusted.yml
To protect against breaking the CLI in PRs
> run cli.yml in PRs to protect against breakage

- app/data_client.go
- app/data_client_test.go
TabularDataSourceTypeUnspecified is never an intended behavior - if data
source options were unspecified, should send an empty DataSource field
(and App will apply default behavior).
> DATA-4091 Avoid sending TabularDataSourceTypeUnspecified

- web/server/entrypoint.go
- web/server/network_check.go
- web/server/network_check_types.go
Network check logs were not actually making it up to app.viam.com. There were two issues: the net appender was not on the logger used for network checks, and the usage of `w` stopped the logs from being readable once they made it up to app. Starts the network check goroutine later and stringifies `[]*STUNResponse` instead of just logging them with `w`.
> RSDK-10633 Send network check logs to app

- cli/module_registry.go
I wanted to write a test for this, but I also wanted not to add any binary files (including .tar.gz files) into the repo, and couldn't figure out how to square that circle. This function is not currently tested, so I'm not decreasing the test coverage very much.
Instead, I built the CLI both with and without this change, and tried uploading a Windows module: this version succeeded (see [version 0.1.0-rc1000](https://app.viam.com/module/viam/tflite_cpu)), whereas the `main` branch failed with an `Error validating module: the archive does not contain a file at the desired entrypoint`.
> [RSDK-10646] Allow uploading a module via CLI if the windows build's meta.json doesn't have a .exe in the entrypoint

- components/arm/collectors.go
- components/board/collectors.go
- components/camera/collectors.go
- components/encoder/collectors.go
- components/gantry/collectors.go
- components/motor/collectors.go
- components/movementsensor/collectors.go
- components/powersensor/collectors.go
- components/sensor/collectors.go
- components/servo/collectors.go
- data/collector.go
- services/slam/collectors.go
- services/vision/collectors.go
This PR logs FailedToReadErrs at the warning level rather than the error level. It accomplishes this by creating a custom error type for FailedToReadErr.
I configured a part with data capture on NextPointCloud on a webcam. Webcams don't support NextPointCloud natively, so this returns an error.
Part config:
```json
{
{
"name": "cam",
"type": "camera",
"model": "webcam",
"video_path": "FDF90FEB-59E5-4FCF-AABD-DA03C4E19BFB"
},
"service_configs": [
{
"type": "data_manager",
"capture_methods": [
{
"method": "NextPointCloud",
"capture_frequency_hz": 1,
"disabled": false,
"additional_params": {}
}
]
}
}
]
}
],
"services": [
{
"name": "dmsvc",
"type": "data_manager",
"sync_disabled": false, …
```
> DATA-4090 - Log FailedToReadErrs at warning level rather than error

- module/modmanager/manager.go
- module/modmanager/manager_test.go
This changes the behavior of the TCP sockets code to "randomly" grab a port from the OS, close it, and then pass that to the module as its intended port. Linux randomizes port assignments when done this way, and windows (the main intended user of this) doesn't put ports back in the pool for ~4 minutes, so plenty of time for a module to start up, and thus any collision chance should be extremely minimal.
> [APP-7240] Acquire faux-random port on behalf of child module

- cli/module_registry.go
I'm not sure why the current URL loses the anchor point during the redirect. Regardless, it is kinder to link users directly to the module section instead of dropping them at the top of a very long page and hoping they ctrl+f their way to success.
> Update link to module documentation to correctly anchor to module section

- referenceframe/frame_system.go
- robot/impl/local_robot.go
In testing for a demo, I discovered that a camera resource I need to exist in the FrameSystem was not appearing when the camera was disconnected.  It occurred to me that there is no reason it can't be added even if its down, because all the required info exists in the robot config rather than needing to be returned from the resource itself.  This little change fixes this and should make the framesystem build more completely as a result.
Tested by running a robot with and without a camera resource.  Framesystem builds succesfully regardless of state
> Allow non-`ModelFramer` resource subtypes to expose their frames even if they are not built

- cli/app.go
Change the default `--home` value from `/root` to `~`.
Follow-up to #4931; that PR supports tilde on the server, this one forces it on the client.
> in CLI reload command, default homedir to `~`

- services/motion/builtin/validation_test.go
We've had a couple instances of this test being flaky.  Culprit was instantiating a map and passing it into two functions that run in parallel and both read from it.  This code should fix this.
> RSDK-10696 fix data race in test

- gostream/media.go
- gostream/query.go
Mediadevices's camera driver's init function, defined in camera_PLATFORM.go, runs C code within it's init() function that tries to discover webcams but doesn't always work on all platforms, sometimes causing the OS process to crash:
https://github.com/pion/mediadevices/blob/v0.6.4/pkg/driver/camera/camera_linux.go
https://github.com/pion/mediadevices/blob/v0.6.4/pkg/driver/camera/camera_darwin.go
https://github.com/pion/mediadevices/blob/v0.6.4/pkg/driver/camera/camera_windows.go
Currently, any module that has a transitive dependency on the RDK camera interface also depends on gostream, and as a consequence, will execute the media devices camera driver's init function on os process startup.
This is completely unnecessary as the only reason why gostream depended on mediadevices is to …
> remove-gostream-dep-on-mediadevices

- utils/ticker.go
- web/server/entrypoint.go
```
2025-05-14T21:45:05.065Z        WARN    rdk.resource_manager    utils/ticker.go:22      Waiting for resource to complete (re)configuration      {"resource":"rdk-internal:service:frame_system/builtin","time elapsed":"2.000356s"}
2025-05-14T21:45:10.066Z        WARN    rdk.resource_manager    utils/ticker.go:22      Waiting for resource to complete (re)configuration      {"resource":"rdk:service:motion/builtin","time elapsed":"2.000263667s"}
2025-05-14T21:45:10.066Z        WARN    rdk.resource_manager    utils/ticker.go:22      Waiting for resource to complete (re)configuration      {"resource":"rdk-internal:service:packagemanager/deferred-manager","time elapsed":"2.000353875s"}
----
2025-05-14T21:54:30.182Z        INFO    rdk     impl/local_robot.go:1454        Robot (re)configured …
```
> RSDK-10682 - Some extra logs around startup

- web/server/entrypoint.go
we did not clear the packages config when creating the minimal config, so we were still downloading packages on the initial startup phase
cc: @stevebriskin
> RSDK-10740 - Download packages after server startup

- robot/packages/local_package_manager.go
- robot/packages/utils.go
- call `ExpandHomeDir` in localManager.SyncOne
The `viam module reload` command was failing here with a no such path error on the second attempt. (i.e. you reload, it works, you make changes, and reload again).
> Error: Rpc error: code = Unknown desc = while restarting module id=----, name=: stat ~/.viam/packages-local/----_from_reload-dist-archive.tar.gz: no such file or directory
> APP-8298 expand homedir in reloading

- motionplan/constraint.go
Its possible to construct valid protobuf structs that cause this to error at the moment, as @JessamyT discovered.  This PR should patch this from being able to happen.
> RSDK-10695 fix nil pointer dereference when orientation tolerance is unspecified

- services/vision/mlvision/detector.go
- services/vision/mlvision/ml_model_mock_test.go
- services/vision/mlvision/ml_model_test.go
Hey, so this fix comes from a bug Nick ran into.  Basically if someone uses a custom mlmodel module with a set input size different from the original image, we mess up the bounding box.  Like, any absolute bbox coordinates that were read in were "normalized" using the original image and not the resized one.  I think we've been so far getting lucky either with proportional bbox tensors or mlmodels that have [1 -1 -1 3] (variable) size input. 
Here we just fix it by checking if we resized the image and using the appropriate image dims for normalization.  
Tested via Python SDK with Nick's funky ncnn-ml module (0.1.1-rc1) and with our classic EffDet mlmodel setup.  Nick's module used to not work now it does! And EffDet didn't break!
> RSDK-10765 - Let mlvision resize to mlmodel's input size

- motionplan/constraint.go
- motionplan/motionPlanner.go
- motionplan/planManager.go
This is a follow-on from a recent PR that fixes a case that was not caught during testing where the end effector begins in collision with a pointcloud. Currently this is simply an error as motionplan expects all point clouds to be associated with SLAM maps.  This PR changes the scope of where this check is made, moving it to the planager, which has knowledge of whether the motionplan is using TP space or not.
> whitelist starting collisions with pointclouds for non-SLAM applications

- services/motion/builtin/builtin.go
- services/motion/builtin/builtin_test.go
This would be useful to users who want to configure this parameter across every call they make to the motion service
> add a config parameter to motion/builtin that sets a default number of threads to use

- cli/app.go
- cli/client.go
- cli/client_test.go
Does what the title says. Internally the new command is reusing the file copy code with presets for the path and flags.
>  RSDK-9648: Add viam CLI command to grab all captured FTDC data

- .github/workflows/test.yml
- Move windows tests from windows-2019 to windows-2022 runner
Github is [deprecating the windows-2019 runner](https://github.com/actions/runner-images/issues/12045).
- :heavy_check_mark: successful CI run [here](https://github.com/viamrobotics/rdk/actions/runs/15424790628/job/43408898257)
This doesn't affect the windows RDK build, which happens on an ubuntu runner [here](https://github.com/viamrobotics/rdk/blob/main/.github/workflows/staticbuild.yml#L37-L40) using the `make windows` cross-compilation target.
> APP-8440 upgrade runner for windows tests

- cli/app.go
- cli/data.go
- cli/dataset.go
Allowing export/download of images from Viam Cloud from the CLI.
This PR includes:
- addition of --binary data-ids string slice flag to the data export binary command in the cli
- modifications to downloadBinary() to take in a variate string slice id instead of a single id
- modifications to dataExportBinaryAction() to call downloadBinary() directly when flag --binary-data-ids is provided
Tested using a mock machine with dummy images. Checked that the correct files were downloaded and correct function was called whenever the binary data flag was set even if other flags are provided. Functional for a single binary id as well as multiple comma separated binary ids are provided.
> RSDK-10679: Download images from Viam Cloud by Binary Data ID using Viam CLI

- cli/module_build.go
- wrap the os.Open failure in hot reloading
I've seen multiple users get to this step in reloading and not know that they need to look at meta.json to resolve
> in hot reload, clearer error when no file is at build.path

- cli/client.go
- cli/client_test.go
When somebody runs `viam organization auth-service oauth-app read` we only print the oauth config information. We should also print the client name.
> APP-8183: Print client name for oauth app read command

- robot/client/client.go
If a client specifies `WithNetworkStats()` option, there are `latencyPingNum` gRPC `GetOperations` requests that are sent to server. The average time, in milliseconds, is measured and logged back to the client. If the average latency exceeds `latencyWarningThresholdMs`, the client gets an addition warning log line.
> RSDK-10508 Client-side latency measurements

- cli/module_generate.go
- in the golang case in module_generate.go, change meta.json `build.path` from `bin/module.tar.gz` to `module.tar.gz`
The go makefile template [here](https://github.com/viamrobotics/rdk/blob/main/cli/module_generate/_templates/go/tmpl-Makefile#L31) generates this in the module root
> fix build.path for golang generated modules

- examples/customresources/demos/optionaldepsmodule/module.go
- module/module.go
- robot/impl/local_robot.go
- robot/impl/optional_dependencies_test.go
RSDK-10762
Adds a test for _modular_ optional dependency cycles that ensures modular resources can optionally depend upon each other _without_ any `Reconfigure` methods (using `AlwaysRebuild`).
> RSDK-10762 Add test for modular optional dependency cycles

- cli/module_generate/_templates/go/tmpl-Makefile
Per discussion in https://github.com/viam-modules/mlmodel-tflite/pull/35, https://github.com/viamrobotics/rdk/pull/4969, and on Slack, Windows is smart enough to know that if you try executing `foo` and the only file present is `foo.exe`, that's the one to use. So, no need to rewrite meta.json to add the `.exe` suffix on Windows.
This also makes the code less surprising: if I modify meta.json myself and then build without committing, I don't expect that to discard my changes! :flushed: 
I'm tagging Julie on this PR, but that might be wrong. Julie, feel free to reassign if you don't want to review.
> module template: no need to modify meta.json when building on Windows

- cli/module_generate.go
Instead of printing `Module successfully generated at my-module`, this will now print `Module successfully generated at /Users/njooma/my-module`
> [RSDK-10480] Log full module path upon success

- motionplan/motionPlanner.go
- motionplan/planManager.go
- motionplan/plannerOptions.go
- motionplan/planning_algorithms.go
- motionplan/tpSpaceRRT_test.go
First of many PRs to clean up `PlanRequest` and `plannerOptions`.
This particular PR is the start of trying to remove function pointers from these structs wherever possible (due to them not being serializable or explicit)
> [RSDK-10933] use PlanningAlgorithm enum in favor of function pointer

- config/logging_level.go
- web/server/entrypoint.go
[RDSK-10723](https://viam.atlassian.net/browse/RSDK-10723)
For now, leave a `TODO` comment and `Warn` about inability to modify module logger levels through the `"debug"` or `"log"` field for now.
I won't close the ticket, but until we do this work, let's at least log what _won't_ work.
cc @bkaravan
> RSDK-10723 Warn about inability to modify module logger levels for now

- components/camera/camera.go
- components/camera/client.go
- components/camera/client_test.go
- components/camera/replaypcd/replaypcd.go
- components/camera/server.go
- components/camera/videosource/webcam.go
- components/camera/videosourcewrappers.go
- testutils/inject/camera.go
Add geometries to camera. Not sure who should be a reviewer on this, feel free to remove yourself.
@raybjork included you since you were on the original email
@randhid included you because you recently edited these files
> Add geometries to camera

- pointcloud/basic_octree.go
Function was incorrectly using the default when an explicit one was set
> Use the passed in confidenceThreshold

- motionplan/check.go
- motionplan/motionPlanner.go
- motionplan/motionPlanner_test.go
- motionplan/planManager.go
- motionplan/plannerOptions.go
- motionplan/tpSpaceRRT.go
- motionplan/tpSpaceRRT_test.go
- motionplan/utils.go
Another incremental step on refactoring `PlanRequest` and `planningOptions`. This one targets the infrastructure around motion chains. In this PR, we consolidate the logic around motion chains to a single struct instance (`motionChains`). The intention is that all chain processing occurs in a single constructor function and information about the chains comes from instance methods on the struct.
This will eventually make writing the simplified constructor for `planningOptions` easier.
> [RSDK-10933] refactor motion chains structure

- components/button/fake/button.go
A pretty silly change...
Now that we dedupe identical logs that happen in succession, testing with a fake button is difficult as its `Push` log messages get suppressed. Adding a timestamp to the log to stop the logger from deduping.
> Log fake button press with time to avoid log deduping

- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/modmanager/module.go
- robot/client/client.go
- robot/impl/local_robot_test.go
- robot/impl/resource_manager.go
actual fix was just one line, but renamed some functions and added a "Success" log for when resources get configured/reconfigured successfully
> RSDK-11150 - Reregister models after crash recovery

- motionplan/cBiRRT.go
- motionplan/cBiRRT_test.go
- motionplan/check.go
- motionplan/constraint.go
- motionplan/constraint_handler.go
- motionplan/constraint_test.go
- motionplan/motionPlanner.go
- motionplan/motionPlanner_test.go
- motionplan/planManager.go
- motionplan/plannerOptions.go
- motionplan/planning_algorithms.go
- motionplan/rrtStarConnect.go
- motionplan/stubs_nocgo.go
- motionplan/tpSpaceRRT.go
- motionplan/tpSpaceRRT_test.go
- services/motion/builtin/builtin.go
- services/motion/builtin/move_on_globe_test.go
- services/motion/builtin/move_on_map_test.go
- services/motion/builtin/validation_test.go
- services/navigation/builtin/builtin_test.go
Continuing on the path to make `plannerOptions` and `PathRequest` serializable, we now move `ConstraintHandler` to the `planner` struct.
> [RSDK-10933] Move ConstraintHandler from plannerOptions to planner

- .github/workflows/cli.yml
- in the CLI build, pin the runner instead of using latest
When the default runner changed from 22 to 24, the cloud build base image started throwing GLIBC errors when it tried to run the CLI binary.
> pin runner for CLI builds

- .github/workflows/cli.yml
- Makefile
- force CGO_ENABLED=0 in the cli target in Makefile
- revert https://github.com/viamrobotics/rdk/pull/5110 (my previous, wrong fix for this)
The extra dependencies in bedf954b caused the cli build to silently switch to CGo for the build. (You can test this for yourself by doing CLI builds from that commit + the previous commit, then doing `ldd` on both).
This created a GLIBC dependency which broke cloud build. Cloud build is on an older ubuntu image intentionally to create broadly compatible binaries.
> require non-cgo build for CLI

- data/capture_file.go
- services/datamanager/builtin/builtin.go
- services/datamanager/builtin/builtin_test.go
- services/datamanager/builtin/config.go
- services/datamanager/builtin/config_test.go
- services/datamanager/builtin/shared/default_capture_directory.go
- services/datamanager/builtin/sync/config.go
- services/datamanager/builtin/sync/sync.go
This PR updates datamanager to use a variable that netcode provides to determine the location of the `.viam/capture` directory, while syncing from both the old and the new locations in order to not lose any data when machines update viam server.
Also needed to update `CaptureFilePathWithReplacedReservedChars` so that it wasn't replacing the colon after a Windows drive with an underscore.
Manually tested on a Windows machine and was able to sync data from both capture directory locations ✅
> DATA-4241 Fix capture directory

- app/data_client.go
- app/data_client_test.go
- cli/app.go
This PR adds the enable backfill argument for CreateDataPipeline to both the Go SDK and the CLI
> DATA-4220: Update Go SDK + CLI to have enable backfill argument for CreateDataPipeline

- config/proto_conversions.go
One of the two PRs for [this](https://viam.atlassian.net/browse/RSDK-11208) ticket. Most of the changes are in app, but there was a small bug in rdk that was never propagating the value of `disableParitalStart` from the proto message to the internal config struct.
> RSDK-11208 Propagate DisablePartialStart to the config struct

- module/modmanager/manager.go
- module/modmanager/manager_test.go
This PR will allow any viam namespace modules to run on Try rovers. Specifically this fixes the case where the webcamera discovery service cannot be used, but will also fix future cases where we want to allow additional viam supported modules in Try.
> APP-8851: Allow all viam supported modules in untrusted environments

- motionplan/check.go
- motionplan/constraint.go
- motionplan/constraint_handler.go
- motionplan/constraint_test.go
- motionplan/motionPlanner.go
- motionplan/motionPlanner_test.go
- motionplan/planManager.go
- motionplan/tpSpaceRRT_test.go
Logs right now are noisy because a Global logger is being used.  This does the more correct thing of passing the logger down several levels so that it ultimately inherits the logger from motion-builtin
> pass a logger to collision constraint functions for better logging

- pointcloud/basic_octree.go
points don't have a collides with octree check, so we were erroring and need to flip the geometries.
> Returning points of the collision between two octrees was impossible

- motionplan/armplanning/motionPlanner.go
- motionplan/armplanning/motionPlanner_test.go
Fixing a small bug here.  Adding test cases to help us protect against this in the future
> allow passing nil plannerOptions in a PlanRequest

- Makefile
- README.md
- examples/customresources/demos/complexmodule/Makefile
- examples/customresources/demos/multiplemodules/Makefile
- examples/customresources/demos/optionaldepsmodule/Makefile
- examples/customresources/demos/remoteserver/Makefile
- examples/customresources/demos/remoteserver/server_test.go
- examples/customresources/demos/simplemodule/Makefile
- change `go build web/cmd/server/main.go` to `go build ./web/cmd/server` throughout codebase
The `main.go` style excludes `main_nocgo.go`, the new file where the services registration lives. The `./web/cmd/server` style is a package build which is subtly different in go + includes all files in the package. (it also has some vcs metadata automation that would be useful if we wanted)
> fix missing motion service in `make server-static` builds

- robot/impl/local_robot.go
grpc.Dial() with a unix socket seem to break windows machines. This is a quick patch to only allow jobmanager on non-windows OS, as well as an additional guard against a nil panic. 
We might be able to enable jobManager on windows by always routing to TCP sockets, but this needs more investigation.
> Fix: disable JobManager on windows

- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/modmanager/module.go
- robot/impl/local_robot.go
- robot/jobmanager/jobmanager.go
- utils/env.go
Re-Enabling Job manager on Windows has two major changes: 
- Job manager's failure to start will no longer crash the whole server. Rather, an error message will be logged instead.
- Job manager will leverage the existing `CleanWindowsSocketsPath` helper to adjust the unix socket address to work appropriately on windows.
> RSDK-11485 Re-Enable Job manager on Windows

- robot/web/web.go
tests were spewing these errors but we also shouldn't be trying to remove a file in TCP mode
> RSDK-11217 - Stop trying to remove addr if in TCP mode

- cli/module_generate.go
If a user is unauthenticated/we get an error with auth and tries generating a module, show this prompt to the user:
If they select "Do not continue", they will get the usual error:
If they select continue, they will get prompted for the rest of the information per usual, except the last option (register module) will be disabled:
Cc @dgottlieb since you ran into this issue recently
> [RSDK-11339] Allow for unauthenticated local module generation

- config/diff.go
- web/server/entrypoint.go
The warning was logged too often because the `LogEqual` field of Diff struct is set to false even when `log` fields are the same, but some of the components or services have changed (in an effort to propagate their own loggers and applied patterns from `log`). I have added an extra field to keep track of the equality of the `log` field specifically, which helps to only output the warning only when the `log` field was actually changed.
> RSDK-11454 "log" Warnings only on "log" field changes

- cli/app.go
- cli/module_local_viam_apps_setup.go
https://viam.atlassian.net/browse/APP-9074
Extend the `viam module local-app-testing` CLI command to support multi-machine Viam apps.
We use the `--machine-id` CLI argument to determine if we should run the local testing for a single machine Viam app setup or a multi-machine one.
For the multi-machine setup we extract the access token from the CLI context and return it as a cookie as the Viam app server does.
```
viam module local-app-testing -h
NAME:
viam module local-app-testing - Test your viam application locally. This will stand up a local proxy at http://localhost:8012 to simulate the Viam app server. If testing a single-machhine app you MUST provide the machine-id parameter, omit it to test a multi-machine app.
USAGE:
viam module local-app-testing --app-url=<app-url> …
```
> Support multi-machine Viam apps in "viam module local-app-testing"

- web/server/entrypoint.go
Adds `time_elapsed` field to the slow shutdown warning log that ticks every 20s. 
New log Looks like this locally:
```
2025-08-19T16:05:53.129Z	WARN	rdk	server/entrypoint.go:492	Waiting for clean shutdown	{"time_elapsed":"10.001088209s"}
```
And like this on app:
```
8/19/2025, 12:05:53 PM warn rdk   server/entrypoint.go:492   Waiting for clean shutdown   time_elapsed 10.001088209s
```
[This log](https://github.com/viamrobotics/rdk/blob/053ae5c1c6dde3c834dd3802afd15feb3dca8a86/web/server/entrypoint.go#L491-L491) is missing time elapsed, so it both gets deduped and is lacking key information.
> RSDK-11680 Include time elapsed in slow shutdown log for machine

- cli/app.go
- cli/module_build.go
- cli/module_build_test.go
- cli/module_generate/_templates/python/build.sh
- cli/module_registry.go
- cli/module_reload.go
- cli/module_reload_test.go
- cli/packages.go
Testing:
1. `viam module reload` without cloudbuild has no regression
2. `viam module reload --cloud-build` when no `reload` version exists successfully builds and reloads
3. `viam module reload --cloud-build` when a previous `reload` version already exists also successfully builds and reloads
4. `viam module reload --cloud-build` works across platforms
5. `viam module reload --cloud-build` to machine A causes no change to machine B that is running the same module.
> RSDK-11488 - module reload cli improvements

- config/config.go
- config/proto_conversions.go
- config/proto_conversions_test.go
- Add `Prefix` field to `Remote` and `remoteData` structs in `config/config.go`
- Add Prefix handling to `MarshalJSON` and `UnmarshalJSON` functions in `config/config.go`
- Add Prefix handling to `RemoteConfigToProto` and `RemoteConfigFromProto` functions in `config/proto_conversions.go`
- Add `Prefix` field to `testRemote`, add Prefix handling to `validateRemote` function and `TestRemoteConfigToProto` test in `config/proto_conversions_test.go`
> [APP-8840] Add support for adding prefix to remote config

- .github/workflows/macos.yml
- .github/workflows/pullrequest-trusted.yml
This change update the github actions config for the MacOS runner to point to the `main` branch.
> Updating github actions config for MacOS runner to point to main

- config/module.go
- config/module_test.go
- module/modmanager/manager.go
- module/modmanager/manager_test.go
- module/modmanager/module.go
[APP-8439](https://viam.atlassian.net/browse/APP-8439?actionerId=615b581da7071000698f89c8&sourceType=assign) Ensure VIAM_MODULE_ROOT is set when getting module environment
* Modifies module manager's `getFullEnvironment` helper to check and set `VIAM_MODULE_ROOT` for local modules.
* Local non-tarball root is set to the module's exe path in it's config
* Local tarball root is set to the local package directory where it gets unpacked.
* `TestModManagerFunctions` has a section that tests that environment variables get set correctly for registry and local modules. I extended this section by testing that the env var `VIAM_MODULE_ROOT` gets set correctly for both local non-tarball and tarball modules. 
[APP-8439]: https://viam.atlassian.net/browse/APP-8439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> [APP-8439] Ensure VIAM_MODULE_ROOT is set for local modules

- grpc/app_conn.go
RSDK-11947
We currently run DNS network checks after the global app connection fails to establish [synchronously](https://github.com/viamrobotics/rdk/blob/ccfebbd44639d21e714816f20819284e737e0b22/grpc/app_conn.go#L76-L76). That means that if we’re truly offline, establishing the global app connection will take 2 minutes to fail, which will stop viam-agent from beginning the process of reactivating whatever connection it needs to for at least 2 minutes. We should run those checks asynchronously.
> RSDK-11947 Run DNS network checks asynchronously upon app connection failure

- app/viam_client_test.go
- grpc/app_conn.go
- grpc/conn.go
- grpc/shared_conn.go
- services/datamanager/builtin/builtin.go
- services/datamanager/builtin/builtin_sync_test.go
- services/datamanager/builtin/builtin_test.go
- services/datamanager/builtin/noop_client_conn_with_connectivity_test.go
- services/datamanager/builtin/sync/connectivity.go
- services/datamanager/builtin/sync/sync.go
mostly moved the connectivity interface out of data manager, tested and works
doesn't require https://github.com/viamrobotics/goutils/pull/482, we should merge this in before the next release then after the release is cut, merge https://github.com/viamrobotics/goutils/pull/482 and release that. since this PR removes the dependency on GetState as part of the ClientConn interface, we will be able to do that without breaking anyone at any point
> RSDK-11955 - Facilitate revert of goutils ClientConn interface change

- logging/net_appender.go
- logging/net_appender_test.go
This attempts to fix an issue the sanding team ran into where trying to ship logs containing invalid UTF-8 completely halted log shipping. The core problem is that `NetAppender` is written with the assumption that any errors sending logs are caused by network issues that will eventually resolve, but this was an issue with the data being sent so would never resolve on its own. This change fixes the specific issue we observed where log messages contain invalid UTF-8 by detecting such issues, sanitizing all the messages in the failed batch, then retrying.
There's potentially a bigger change we could make to have failed log batches "decay" over time and eventually be dropped from the queue entirely, but I opted not to implement that for now since the failure we did observe is fairly easy to …
> RSDK-11975: Sanitize logs before serializing to proto

- etc/dev-version.sh
dev versions will go from `v0.93.1-dev.9` to `v0.93.1-dev.9-gd23fe503c`
Needs this [PR](https://github.com/viamrobotics/app/pull/9809) to be merged for the releases to properly be picked up
> Update dev-version release to include a short hash

- services/vision/collectors.go
- services/vision/collectors_test.go
Currently, the test card on the vision service displays all bounding boxes / classifications, regardless of confidence. However, when using captureAllFromCamera, only annotations with confidence > 0.5 are saved by default. This is confusing to the user, who expects that all annotations that are displayed in the test card should be saved. This PR changes the default min_confidence value to 0.
> CaptureAll Default Confidence Threshold

- motionplan/armplanning/cBiRRT.go
- motionplan/armplanning/cmd-plan/cmd-plan.go
- motionplan/armplanning/errors.go
- motionplan/armplanning/errors_test.go
- motionplan/constraint2.go
```
We've found richer IK solution errors to be useful when there are frame system 
configuration errors. Resulting in goal poses that cannot be satisfied as the
goal frame is embedded inside a geometry that may not collide.
The interactive cmd-plan mode can be used for rerunning renderings or rendering
failed ik solutions.
```
The demo is [using an uncommitted](https://github.com/viam-labs/motion-tools/pull/134) version of the motion tools. Which addresses `DrawWorldState` missing meshes/pointclouds. And because performance is poor, I added some downscaling (that I sped up even further for this demo). Pointclouds are being more thoroughly addressed by the actual tools team, so expect improvements soon.
The demo is the example from where the framesystem config had the compliance/sandpaper …
> Return richer IK solution errors. Add an interactive cmd-plan mode

- cli/dataset.go
Tested locally, whilst logged in to staging, using the following command:
`go run cli/viam/main.go dataset export --include-jsonl=true --dataset-id=6515b637a420eb685e988e84 --destination=.`
> DATA-4662 - Export all capture metadata fields in dataset file

- referenceframe/model.go
- referenceframe/model_json_test.go
- referenceframe/model_test.go
Limits were being written out to JSON properly. But not reflected in the deserialized obejct.
> Fix `SimpleModel` json roundtripping

- motionplan/armplanning/real_test.go
Definition of a pirouette:
A pirouette is when joint 0 of a given arm does a [121 - 390] degree rotation along with some rotation on joint 1 to reach a pose `p` when instead a smaller rotation would suffice for satisfying  pose `p`.
Note: the range [121 - 390] was determined experimentally.
Test setup:
1. Define a set of joint positions.
2. Get the kinematic model of the arm and perform forward kinematics to determine the pose each of element of (1) corresponds to.
3. Construct a request which specifies which pose we would like to navigate to while also specifying the current joint positions of where the arm currently is.
4. Execute the request and get a trajectory.
5. Query the trajectory to see what the change in joint 0 is.
6. Query the set of joint positions defined in step (1) to see …
> RSDK-11997 - Add pirouette tests in motion planning

- etc/dev-version.sh
Now the dev version will be formatted as v1.2.3-dev.9-099c853aa instead of v1.2.3-dev.9-g099c853aa.
> Remove g prefix from commit hash

- module/testmodule/expected_meta.json
- module/testmodule/first_run_meta.json
- module/testmodule/main.go
- robot/impl/robot_framesystem_test.go
Adds a small "integration" test for the feature added in RSDK-9430/https://github.com/viamrobotics/rdk/pull/5146. 
The test passes, and I haven't yet reproed the issue described by RSDK-12124, but it would be good to have a more full test either way.
> RSDK-12124 Add integration test for framesystem modular dependency

- spatialmath/mesh.go
- spatialmath/mesh_test.go
I intend to use it in the sanding code, as part of https://viam.atlassian.net/browse/RSDK-11539
While I was at it, I saw that the proto-conversion code wasn't tested, so I added a test. I had expected the test to fail and then to need to fix it, but it seems like it passes after all: the list of triangles is immutable, so we can precompute the byte representation on initialization and never worry about it changing later.
> make Mesh-to-PLY conversion public

- module/modmanager/manager.go
- module/module.go
- module/testmodule/main.go
- robot/impl/robot_framesystem_test.go
RSDK-12124
Adds `{framesystem.PublicServiceName: framesystem.Service}` to the dependencies passed into Golang modular resource reconfiguration. Expands the existing integration test to ensure that that happens. Also logs a warning but allows passing `$framesystem`, `framesystem`, and `rdk-internal:service:frame_system/$framesystem` as implicit required/optional dependencies (returns from `Validate`) to avoid borking users build if they happen to do the wrong thing.
> RSDK-12124 Pass a framesystem client as a dependency in reconfigure in addition to constructor
